### ISSUE TITLE
quick question on using ts-estree instead of acorn

### ISSUE THREAD

**Issue by jeremy-coleman** [typescript-eslint/typescript-eslint#1003]
I would like your thoughts on replacing acorn in a tool like browserify or rollup with ts-estree -  pros/cons?

**Comment by bradzacher** [comment]
What's the use case?
Is it purely to add "out-of-the-box" support for parsing typescript?

**Comment by jeremy-coleman** [comment]
that is a secondary goal, initially im just looking to reduce complexity and dependencies. I also really don't see the point in parsing source files with acorn when 99.9% of the time it's going to be parsed again by either typescript or babel

**Comment by jeremy-coleman** [comment]
this is just a personal pet project btw, no downstream consequences from experimenting lol

**Comment by bradzacher** [comment]
yeah that's a known problem with many build chains - i.e. webpack wastes a lot of time converting back and forth from AST representation A to raw code string to AST representation B....

side note - that's why instagram is bundled using metro  - https://github.com/facebook/metro
IIRC it keeps the source as a babel AST throughout the build process, which saves a huge amount of time

---

The problem that you've got is that each plugin for your build tool will be expecting either a specific AST format, or a raw code string.
It'd be a fair bit of work retooling all of the plugins to work with a single AST representation.

If you're going to all that effort, then question I'd be asking instead would be "why use a TS-ESTree AST instead of just the TS AST?" (i.e. save a conversion step).
I don't think that the ESTree AST is necessarily nicer to work with, esp when there are libs like `tsutils` to help wrangle the TS AST.

The tools probably won't need type information, so you probably don't want to run ts-estree in full type aware mode (i.e. the mode when providing a `project`) - doing that means you pay the hefty cost of analysing types.

So you'd probably want to be running ts-estree in its pure compiler mode (i.e. it uses ts to parse, then converts the ts AST to the TS-ESTree AST). At which point it'd be slower than acorn, because of the conversion step.

Yeah the more I look at it, the more I think it's not a great idea to use ts-estree in a build chain, unless you really like / need the TS-ESTree AST.

**Comment by jeremy-coleman** [comment]
Cool, thanks for your thoughts. I also concluded ts is the best end choice, but being able to drop in an acorn replacement 1:1 with a ts backed ast would make converting everything immensely easier (basically just fork this repo , get a ref to the intermediate ast and start deleting things). I already tried implementing browserify in ts ast, but was too difficult trying to map all the deps to ts at once. Type info definately isnt needed for bundling, plus i just fundamentally think type checking and transpiling should definitively be separate concerns.

**Comment by bradzacher** [comment]
if you don't pass the project to ts-estree, then it'll just do a basic (isolated modules mode) ts parse and convert the AST to the TS-ESTree representation.
About as quick as you can get without writing a bespoke parser to parse TS code to TS-ESTree without the intermediary representation (i.e. there's nothing to delete that'll save you a meaningful amount of time).

**Comment by bradzacher** [comment]
(closing this for housekeeping reasons as there's no issue, we can continue discussing though)
