### ISSUE TITLE
Bug: Changelog of package 'typescript-eslint' misses relevant changes

### ISSUE THREAD

**Issue by benutzer193** [typescript-eslint/typescript-eslint#10141]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

typescript-eslint

### Example

Check the [Changelog file](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-eslint/CHANGELOG.md).

### Expected Result

The Changelog contains all relevant changes of the packages contained in the package 'typescript-eslint'.

### Actual Result

Often only a version bump is logged.

### Versions

n/a

**Comment by bradzacher** [comment]
The files are auto-generated by nx - we don't have control over their contents.

We've been planning on removing the changelog files because we list all our change notes (sometimes hand curated) in our github releases. We don't really love having the rules because they're a pain for us to manually update as opposed to the GH releases.

There's also the changelog file in the repo root which lists everything.
