### ISSUE TITLE
Configs: all files includes by recommended config

### ISSUE THREAD

**Issue by MillerSvt** [typescript-eslint/typescript-eslint#10168]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

All files includes by recommended config. For example @typescript-eslint/ban-ts-comment tries to lint html files, and fails with error: 

```
TypeError: Cannot read properties of undefined (reading 'at')
Occurred while linting /Users/s.v.zaytsev/IdeaProjects/chat-fusion-front/libs/shared/ui-containers/src/lib/error/error.component.html:1
Rule: "@typescript-eslint/ban-ts-comment"
    at Program (/Users/s.v.zaytsev/IdeaProjects/chat-fusion-front/node_modules/@typescript-eslint/eslint-plugin/dist/rules/ban-ts-comment.js:118:50)
```

I suggest add filter only *.ts (and related) files to that config.

**Comment by bradzacher** [comment]
We don't use `*.ts` because there are more file extensions that support TS code than just that.
It's up to you the user to use [`files` (for flat configs)](https://eslint.org/docs/latest/use/configure/configuration-files#specifying-files-and-ignores) or [`overrides` (for legacy configs)](https://eslint.org/docs/v8.x/use/configure/configuration-files#configuration-based-on-glob-patterns) t to limit the config to just the files you want to apply it to.

**Comment by MillerSvt** [comment]
How to limit files for existing recommended configs?

**Comment by bradzacher** [comment]
Check out the above links for examples of how to use the config options with shared configs.
