### ISSUE TITLE
Using `/` as config name separator.

### ISSUE THREAD

**Issue by ntnyq** [typescript-eslint/typescript-eslint#10181]
ESLint officially recommended using / as the config name separator.

Refs:

[ESLint docs - configuration-naming-conventions](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions)

In https://github.com/typescript-eslint/typescript-eslint/pull/10094, config names are joined with `__`. 

Maybe we should change it to `/`.

**Comment by bradzacher** [comment]
Part of me thinks that `__` is better than `/` for our "generated" name because it avoids clashes and makes it clearer that the name was joined by us automatically.

**Comment by auvred** [comment]
I thought about using `/` when I was working on #10094, but I decided to stick with `__`. Because `/` refers to scopes for shared configurations/plugins, and `tseslint.config` is just an utility function that applies some common options to a several extended configs. It doesn't actually configure anything. So I'm +1 on using `__` here.

**Comment by JoshuaKGoldberg** [comment]
Looks like we have consensus on `__`. I'm in favor of making it more clearly generated. Thanks all!
