### ISSUE TITLE
Performance degradation in 8.1.0: @typescript-eslint/no-unsafe-return with high-cardinality unions

### ISSUE THREAD

**Issue by AaronMoat** [typescript-eslint/typescript-eslint#10196]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I haven't exactly narrowed down _why_ yet, but there appears to be a performance degradation in patterns like this:

```typescript
type Alpha2Code =
  | "AF"
  ...
  | "XK";

type LanguageCode =
  | "aa"
  ...
  | "zu";

type Locale = `${LanguageCode}-${Alpha2Code}`;

export function getDefaultLocale() {
  return 'en-AU' as Locale;
}
```

In the example reproduction, it takes about 73 seconds on my machine. 

Note that `tsc` takes 0.7s.

### Reproduction Repository Link

https://github.com/AaronMoat/typescript-eslint-perf

### Repro Steps

1) clone the repo
2) `yarn install`
3) `yarn lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript-eslint`     | `8.11.0` |
| `TypeScript`                           | `5.6.3` |
| `ESLint`                               | `9.13.0` |
| `node`                                 | `v20.17.0` |

**Comment by bradzacher** [comment]
A few things you need to do:

First - you've filed an issue saying there's been a perf regression... But you've provided no point of comparison. You say it's gotten slower... But by how much? Is it slower with the exact same config? Or did your config change? You need to provide more information!

Next - you've provided a reproduction with all of the recommended rules turned on. That's a massive blast radius for performance and so any meaningful comparisons will be very difficult. You need to slim down the config so that it includes the **_minimum_** config to reproduce the issue.

Help us to help you by providing a minimal repro with all the information.

**Comment by AaronMoat** [comment]
Ah interesting; digging further, the issue is not reproducible in 8.0.1 but is reproducible in 8.1.0, so it's not the v8 upgrade.

**Comment by AaronMoat** [comment]
Looks like https://github.com/typescript-eslint/typescript-eslint/pull/8693/; most of the time is spent in `tsutils.isThenableType`. I don't have nearly enough context to understand if there's feasible fixes, though.

**Comment by tezf** [comment]
I spent some time looking at this with @AaronMoat and think we were able to narrow down the cause. Issue isn't currently taking PRs so I'll just link to the commit. 

https://github.com/typescript-eslint/typescript-eslint/compare/main...tezf:typescript-eslint:fix-accidental-n-2-iterations

**Comment by bradzacher** [comment]
that fix certainly looks reasonable.
feel free to raise a PR so we can see how the CI goes on it.
