### ISSUE TITLE
Rule proposal: Enforce JSX Presence in `.tsx` Files (`no-tsx-without-jsx`)

### ISSUE THREAD

**Issue by HesamSe** [typescript-eslint/typescript-eslint#10190]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I would like to propose a new rule for `@typescript-eslint/eslint-plugin` that enforces the presence of JSX elements in files with a `.tsx` extension. This rule would help maintain consistency and clarity in TypeScript projects using React or other JSX-based libraries.

**Problem Statement**: Currently, it’s possible to create .tsx files without any JSX elements. This can lead to:

* **Confusion**: Developers might use the .tsx extension unnecessarily for files that do not contain any JSX, potentially causing confusion about the file's intended purpose.
* **Consistency Issues**: Keeping `.ts` and `.tsx` file distinctions clear ensures that the purpose of each file is easily understood by other developers working on the project.

**Proposed Rule**: `no-tsx-without-jsx`
* This rule would throw an error if a file with the `.tsx` extension does not contain any JSX elements.
* The rule would suggest renaming the file to a `.ts` extension if JSX is absent.

### Fail Cases

```TypeScript
// sample.tsx

const sample = 'hello world';
```

### Pass Cases

```TypeScript
// sample.tsx

const sample = <div>hello world</div>;
```

### Additional Info

I developed this rule in my repository. You can check that at https://github.com/HesamSe/eslint-plugin-recommended/blob/main/src/rules/noTsxWithoutJsx.ts

**Comment by Josh-Cena** [comment]
Specific handling of JSX is out of scope for our plugin, and you probably want to enforce the same for .js/.jsx. Why not propose it to eslint-plugin-react first?

**Comment by bradzacher** [comment]
I'd agree - there is generally no issue with using tsx without JSX. In fact it can actually be good because using the tsx extension will ban the old angle bracket assertion syntax.

In reality there is no need to add precedence to one over the other except for conventions you enforce within your own codebase.

I'd agree with Josh - this seems like a good fit for `eslint-plugin-react` (or its fork). But even if they don't accept it - it is not a fit for our project as it's not a general thing the broader TS ecosystem expects or asks for.

---

For context - I can see some value to this. For example at my company we tweak infra setup (build pipeline and codegen) if the file is a tsx file, and so it makes sense for us to enforce the difference (we have a lint rule that does exactly this!).
But in the general sense - the distinction is meaningless.

**Comment by HesamSe** [comment]
@Josh-Cena @bradzacher 
Thank you both of you. You are right. Proposing it in `eslint-plugin-react` is a better idea. I thought handling Typescript part of this rule was within the scope of your plugin.
