### ISSUE TITLE
Bug: @typescript-eslint/no-unused-expressions Multiple assignments when using comma still breaks the rule.

### ISSUE THREAD

**Issue by IamFastre** [typescript-eslint/typescript-eslint#10195]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [x] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.6.3&fileType=.ts&code=JYOwLgpgTgZghgYwgAgBoE1kG8CwAoZZADwC5kQBXAWwCNoBufQgTzMtofwF998xmADigAiwKBARhgAexAAVCETDIAvMgDkAGwgww65AB8NUYAHMAFnsMaKA-UfUATaQHcQ6xnnwJZAZ2WOYhJSsgpKqhrauvpwvsii4pIy8opgnt5%2BAUFJsmQYEbgExGQADAA0TMisyOXc6XjAMMgAFIGJISnhKt02dgCUlW3ByQB0RBHlyEM5ICPMEQCMnhCaviiNLdMdYcrdauomFnoDRVuj42oAtAtlU9kdcxPLq%2BtNrffJO6o9Tq7uJ4QzrIxhNbkDZvMrkt8Cs1oMPsCLsgbnd2qNITVPEA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2uCUADgDYCuA5gJZKYAC8AnodGgMYBOlh8AtC8dXgB6AIbFikfAF0QAXyA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
interface XY {
  x: number;
  y: number;
}

type DirectionText = 'left' | 'right' | 'up' | 'down';

const directionText = 'left' as DirectionText;

const direction: XY = {
  x: 0,
  y: 0,
};

if (directionText === 'up')
  direction.x = 0, direction.y = 1;
else if (directionText === 'right')
  direction.x = -1, direction.y = 0;
else if (directionText === 'down')
  direction.x = 0, direction.y = -1;
else
  direction.x = 1, direction.y = 0;
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unused-expressions": "error"
  }
}
```

### Expected Result

No error should be fired 'cause the comma binary operation is of two assignments meant to make the code more compact.

### Actual Result

An unnecessary error was fired.

**Comment by kirkwaiblinger** [comment]
Hi @IamFastre!

This is an extension rule and the behavior you're demonstrating isn't TS-specific (see [the eslint playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXVudXNlZC1leHByZXNzaW9uczogW1wiZXJyb3JcIl0gKi9cblxuXG5pZiAoZGlyZWN0aW9uVGV4dCA9PT0gJ3VwJylcbiAgZGlyZWN0aW9uLnggPSAwLCBkaXJlY3Rpb24ueSA9IDE7XG5lbHNlIGlmIChkaXJlY3Rpb25UZXh0ID09PSAncmlnaHQnKVxuICBkaXJlY3Rpb24ueCA9IC0xLCBkaXJlY3Rpb24ueSA9IDA7XG5lbHNlIGlmIChkaXJlY3Rpb25UZXh0ID09PSAnZG93bicpXG4gIGRpcmVjdGlvbi54ID0gMCwgZGlyZWN0aW9uLnkgPSAtMTtcbmVsc2VcbiAgZGlyZWN0aW9uLnggPSAxLCBkaXJlY3Rpb24ueSA9IDA7XG4iLCJvcHRpb25zIjp7InJ1bGVzIjp7fSwibGFuZ3VhZ2VPcHRpb25zIjp7InNvdXJjZVR5cGUiOiJtb2R1bGUiLCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19)), so you'll need to [file an issue upstream with eslint](https://github.com/eslint/eslint.org/issues). If they accept and fix it, let us know, and we'll update our version of the rule accordingly, but otherwise we don't take on changes regarding core rule extensions unless they have to do with TS-specific behavior.
