### ISSUE TITLE
Website: Switch to flat config for website playground ESLint config

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#10239]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now, the playground uses the deprecated legacy ESLint config for the _eslintrc_ tab. We should switch it to flat config now that everything in typescript-eslint supports flat config (#7694).

### Affected URL(s)

https://typescript-eslint.io/play

### Additional Info

💖

**Comment by bradzacher** [comment]
To be fair -- "legacy config" is a bit of a stretch given I'm pretty sure the tab just accepts the list of rules and their config and accepts nothing else!

Keeping it json is nice cos it gives us free autocomplete for rule names and rule options. Otherwise we'd need to generate some form of TS types to do the same thing.

Theres also things to consider with respect to the execution of the flat config. If you make it look like a JS file then people would expect to be able to import any npm packages and have that work - which we couldn't really do.

I'm personally in favour of keeping it as JSON like it is and just renaming it to "eslint config"

**Comment by kirkwaiblinger** [comment]
> ...the tab just accepts the list of rules and their config and accepts nothing else!

It also accepts preset via adding an "extends" field! Which is a great feature that I use regularly 🙂 (not even entirely sure if this is an intentional feature but it's a good one regardless)

> Keeping it json is nice cos it gives us free autocomplete for rule names and rule options. Otherwise we'd need to generate some form of TS types to do the same thing.

> Theres also things to consider with respect to the execution of the flat config. If you make it look like a JS file then people would expect to be able to import any npm packages and have that work - which we couldn't really do.

I'm torn because I very much agree with these benefits of the current setup... And I note that eslint doesn't even attempt to surface flat config in [their playground](https://eslint.org/play/). As far as I can tell, they usually specify just specify inline configs rather than using the GUI config at all. Furthermore, the playground intentionally only operates on a single file, whereas the flat config contains necessary overhead related to project setup... which means, we might, for example, have to prepend typed linting setup to whatever the user provides? Or provide it by default inline? It's not clear how to solve this in a user-friendly way. 

Ultimately, I think it would be beneficial for the ecosystem for there to be a working flat config playground if it's feasible to solve these problems... Though I can also certainly be swayed that that's out of scope for the goals of our playground.

It's tough for me because we have special setup required for TS files, and especially for typed linting, that would be very helpful to be able to provide users full examples of. Perhaps we should solve this in a different way than the playground, though, for example, by publishing some sample repos? Thinking out loud a bit here.

**Comment by bradzacher** [comment]
Personally I also would say that truly using flat config is a security hole. Flat config is arbitrary JS that needs to be physically executed to resolve the config.

The playground automatically loads the config to show errors in the code tab.

This means you could write some nefarious code in the flat config tab and send the URL to someone and be able to execute that code on their machine before they can look at it.

So we'd need to add some system to allow a user to confirm running and even then it's difficult to justify allowing arbitrary JS execution like that...

So I'm personally -1 on actually supporting flat config files and instead in favour of keeping it as json. If we want we can update the schema so it matches the new flat config keys, if it's even applicable?

**Comment by bradzacher** [comment]
Also worth noting - link preservation. We have thousands of issues with playground links that we don't want to break.

Whatever we do we have to maintain backwards compatibility in some manner to ensure all of the old links work.

**Comment by JoshuaKGoldberg** [comment]
Yeah, agreed, it's fine as-is. 🙂
