### ISSUE TITLE
Docs: settings in Quick Start run in quirks mode currently which behave differently from the Legacy ESLint Setup

### ISSUE THREAD

**Issue by me1ting** [typescript-eslint/typescript-eslint#10264]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Modify the [Quick Start](https://typescript-eslint.io/getting-started/) settings to mimic the behavior of [Legacy ESLint Setup](https://typescript-eslint.io/getting-started/legacy-eslint-setup).

I spent an hour updating the ESLint configuration from legacy to flat format due to Quick Start's quirks mode settings

```js
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
  files: ["src/**/*.ts"],
  ignores: ["dist/**/*", "**/__tests__/**"],// does not work
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
);
```
or
```js
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
  files: ["src/**/*.ts"],
  ignores: ["dist/**/*", "**/__tests__/**"],// does not work
  },
);
```

The `ignores` setting in both files is ineffective. The correct configuration is:

```
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config({
  files: ["src/**/*.ts"],
  ignores: ["dist/**/*", "**/__tests__/**"],
  extends: [
    eslint.configs.recommended,
    ...tseslint.configs.recommended,
  ]
});
```

It's important to use [extends](https://typescript-eslint.io/packages/typescript-eslint#flat-config-extends) like it's done in Legacy ESLint Setup.The quirks mode settings confuses beginners like me.

Good quick start for beginners:
```
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config({
  extends: [
    eslint.configs.recommended,
    ...tseslint.configs.recommended,
  ],
});
```

### Affected URL(s)

https://typescript-eslint.io/getting-started/

**Comment by bradzacher** [comment]
Our quick start guide is there to get you from 0-linting as quick as possible.
It purposely does not touch on advanced topics like globally ignoring files.

Instead one should refer to the official ESLint docs on this topic which [is linked at the bottom of the getting started guide](https://typescript-eslint.io/getting-started/#documentation-resources). Specifically [this section explains how to globally ignore files](https://eslint.org/docs/latest/use/configure/configuration-files#globally-ignoring-files-with-ignores). Specifically:

> If ignores is used without any other keys in the configuration object, then the patterns act as global ignores.

---

One cannot blindly apply the legacy config guide to flat configs as they are different config systems each with their own behaviours and nuance -- which is why the two are separated into distinct guides.

**Comment by me1ting** [comment]
I understand what you said, you are right. The config system changes a lot. The [globally ignore files setting](https://eslint.org/docs/latest/use/configure/configuration-files#globally-ignoring-files-with-ignores) works for me.

Thank you.
