### ISSUE TITLE
[member-ordering] separating readonly members is not supported

### ISSUE THREAD

**Issue by mustafa-cosar** [typescript-eslint/typescript-eslint#1063]
Hi, I want to separate `readonly` members from others. For example;
```TS
export class Class
{
    public static readonly A_CONSTANT = 56;
    public static readonly STRING_CONSTANT = "string";

    public static CLASS_MEMBER = "can be modified";

    public readonly anInstanceMember: string;

    public modifiableInstanceMember: string;
}
```

I couldn't find an option for `readonly` members in the documentation (https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md)

**Repro**
N/A

```JSON
{
  "rules": {
    '@typescript-eslint/member-ordering': 'error',
  }
}
```
**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.3.2` |
| `@typescript-eslint/parser`        | `2.3.2` |
| `TypeScript`                       | `3.6.3` |
| `ESLint`                           | `6.5.1` |
| `node`                             | `8.14.1` |
| `npm`                              | `6.11.3` |

**Comment by ljwagerfield** [comment]
Is there any news on this? 

Would be an awesome feature :)

**Comment by luminela** [comment]
Are there any plans to add this? This would make ordering better in my opinion. I would love to keep **readonly** members at the top.

**Comment by bradzacher** [comment]
With any issue in opened in this project - it either has a visible progress in the form of an attached PR, or it has no progress.

We are a community run project. The **volunteer** maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues *will not progress* unless a member of the community steps up and **champions** it.

If this issue is important to you - consider being that champion.

If not - please just subscribe to the issue and wait patiently.
Commenting asking for status updates does not bump issue priority in any way and just serves to spam ***everyone*** subscribed to the issue.
