### ISSUE TITLE
[2.4.0][Watch][Linux] Out of file watchers errors

### ISSUE THREAD

**Issue by AviVahl** [typescript-eslint/typescript-eslint#1080]
**What code were you trying to parse?**
A sample monorepo, with an extremely low number of *source* files.
```
git clone https://github.com/wixplosives/sample-monorepo`
cd sample-monorepo
yarn
yarn lint
```

**What did you expect to happen?**
Lint to pass. No watching done what-so-ever, as I'm not in any watch mode of eslint.

**What actually happened?**
- out of file watchers errors on Linux: https://travis-ci.com/wixplosives/sample-monorepo/jobs/245642338
- eslint trying to watch files inside `node_modules`, which is explicitly ignored in `.eslintignore`. 

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.4.0` |
| `@typescript-eslint/parser` | `2.4.0` |
| `TypeScript`                           | `3.6.4` |
| `node`                                 | `12.12.0` |
| `npm`                                  | `6.11.3` |
| `yarn`                                  | `1.19.1` |

**Comment by raymondfeng** [comment]
We ran into the same issue. The workaround is to set `noWatch` in `eslintrc.js` as follows:
```js
{
  parserOptions: {
    noWatch: true,
  },
}
```

**Comment by AviVahl** [comment]
thanks for the workaround. will re-upgrade and set the flag for now.
I can't help but wonder why would the abstraction that remaps typescript ast to estree has to do *any* sort of watching ... :/

**Comment by bradzacher** [comment]
you can additionally use the environmental variable `PARSER_NO_WATCH=true` to work around this whilst we investigate.

Setting the flag in the config will disable it for your IDE as well, so I'd avoid it unless you have isolated configs.

**Comment by bradzacher** [comment]
> I can't help but wonder why would the abstraction that remaps typescript ast to estree has to do any sort of watching

See this for a fullish overview: https://github.com/typescript-eslint/typescript-eslint/issues/1079#issuecomment-541867845

**Comment by JounQin** [comment]
Can we detect CI automatically to disable this feature?

**Comment by bradzacher** [comment]
Nope, every CI system is vastly different, and we do not want to tie ourselves into detecting this, as it would be a maintenance nightmare.

This is a problem specifically with linux, which my pr #1088 will fix.

Linux has an abysmally low number of available file watchers by default. I had thought it would be fine, so I didn't add handling for it, but it turns out it's a case that will happen easily in the real world.

There are two workarounds for this:
1) use `PARSER_NO_WATCH=true` to disable file watching completely.
2) run `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` to increase the number of file watchers available on linux
    - ([command taken from chokidar docs](https://github.com/paulmillr/chokidar#install-troubleshooting))

Once we merge #1088, then this will not be an issue, as the exception will be handled.

**Comment by AviVahl** [comment]
It's not just how it handles stuff once it gets out of handles. There seems to be a separate issue, where the current implementation watches files it shouldn't.

It iterated into `node_modules` and picked up `.js` files. These aren't being linted nor they are part of the TypeScript program (considering the `tsconfig.json` of the `sample-monorepo` example).

We see it in the Linux machine, due to lower default number of max watches, but that number should be more than sufficient for the repo at hand.

**Comment by JounQin** [comment]
I personally think we can detect `process.env.CI` naively to skip watching which should be available  for most CI.

**Comment by MaximDevoir** [comment]
@JounQin This error is not exclusive to CI environments.

**Comment by JounQin** [comment]
I meant we could catch the error and detect CI at the same time. It is just redundant to watch changes on CI, isn't it?

**Comment by bradzacher** [comment]
It shouldn't be watching any files at all, though.
We don't do it on purpose, because we treat eslint's input as the source-of-truth for file contents, so file changes are irrelevant.
_If it is actually attaching watchers to files, then that is a bug._

I didn't see the watchers being attached to files, but I may be wrong, because either:
- I tested everything on MacOS, which could have a very different behaviour to Linux (when asked to watch a directory).
- I didn't properly inspect all of the files that had a watcher attached.

Both are possible - if you have evidence that it's watching files instead of folders, I'd love to know so I can investigate this, because as I mentioned - it's a bug.

---

We attach watchers to two sets of things:
- the tsconfig file(s) you give us, so that we can react to changes to `include`/`exclude`/`files`.
- the directories typescript tells us to care about, so we can tell typescript new files have been added to those directories.

The latter is a lot more far-reaching than you might think, because typescript asks us to watch folders in `node_modules`. It does this because it wants to know when the type definitions change, so it can update its representation.
We can add an exclusion to the folders within `node_modules`, but there are two problems with that:
1) you will have to reload your IDE whenever you install a new package, or else your IDE will report incorrect errors for rules that need type information. This is something we could live without, it's a bit of an edge case which could be an acceptable trade-off for making the watchers work better.
2) typescript will follow symlinks created by lerna (if there are type definitions there), and ask us to watch the symlinked folder, instead of the link itself. This is not able to be handled by a simple folder filter, as the symlinked path does not include `node_modules`. (i.e. in your example repo, it will ask us to watch `/sample-monorepo/packages/components` when linting the `app` package, instead of `/sample-monorepo/packages/app/node_modules/@sample/components`).

---

> I personally think we can detect process.env.CI naively to skip watching which should be available for most CI.

As @MaximDevoir mentioned, this is a bug on linux. The fact that it occurs on your CI is an implementation detail of the CI running on linux boxes. You could just as easily have a CI running on MacOS, or on Windows, and not have run into this issue at all

Additionally, adding in naive handling like you mentioned could also have side-effects for people's _local_ setups, as `CI` isn't exactly a unique environment variable.

#1088 will stop it erroring on all linux boxes, and you have the option of disabling watching completely for your CI box by using the `PARSER_NO_WATCH=true` environment variable.

**Comment by bradzacher** [comment]
> I meant we could catch the error and detect CI at the same time.

The error occurs after the watchers have been registered. Which means that we'd hit the error, and then have to do the work of removing the watchers, and then block future watchers from being rendered, if and only if we "detect that it's CI".

It's a very weird way to handle.

> It is just redundant to watch changes on CI, isn't it?

It is, it's also redundant to watch files from a CLI run that doesn't need watchers.
But we're in a weird place because of the platform we're building upon.

See https://github.com/typescript-eslint/typescript-eslint/issues/1091#issuecomment-542447852 for a longer explanation.

**Comment by JounQin** [comment]
I've changed to use `PARSER_NO_WATCH=true`, it does work. I'm just suggesting a `better` solution, maybe, as I sad it was redundant to enable watching on CI.

**Comment by JounQin** [comment]
Thx for your explain, but again, watching on CI is redundant and may course issues like this, [is-ci](https://www.npmjs.com/package/is-ci) may could help, or, the watching feature should not be enabled by default IMO.

**Comment by AviVahl** [comment]
I removed the `noWatch` flag, went to `node_modules`, found `tsconfig-parser.js`, and added:
`console.log(path, options)` right before the call to `chokidar.watch`.

Output It gave me:
```
[avi@localhost sample-monorepo]$ yarn lint
yarn run v1.19.1
$ eslint . --ext .js,.ts,.tsx -f codeframe
/home/avi/projects/sample-monorepo/tsconfig.json { interval: 2000 }
/home/avi/projects/sample-monorepo/node_modules { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/packages { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/tsconfig-paths-webpack-plugin { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo { depth: undefined, interval: 250 }
/home/avi/projects/sample-monorepo/html-webpack-plugin { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/mini-css-extract-plugin { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/tsconfig-paths { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/chalk { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/tapable { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/webpack { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/html-minifier { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/react { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/csstype { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/prop-types { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/react-dom { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/sanitize.css { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/express { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/compression { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/express-serve-static-core { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/serve-static { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/range-parser { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/mime { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/body-parser { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/connect { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/minimatch { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo/node_modules/@types { depth: 0, interval: 250 }
/home/avi/projects/sample-monorepo { depth: 0, interval: 250 }
Done in 3.57s.
[avi@localhost sample-monorepo]$ 
```
I then added the following to `node_modules/eslint/bin/eslint.js`:
```js
// right after the require('fs')
const originalWatch = fs.watch
fs.watch = (...args) => {
    const [p] = args;
    console.log('fs.watch', p)
    return originalWatch(...args)
}
```

The problematic call is:
`/home/avi/projects/sample-monorepo { depth: undefined, interval: 250 }`

It doesn't specify `depth` (due to typescript telling us to be recursive), and causes `chokidar` to watch *all* files in repo. Yes, not just `node_modules`, but even ones inside `.git`. :)

I can also see `chokidar` calls watch several times for the same paths, which is odd. No other abstraction is watching. I verified by reenabling the noWatch flag.

Since the current implementation uses `chokidar` with `fsevents` disabled, you might as well use `require('fs').watch` directly, managing which `FSWatchers` are open. Supporting the recursive flag only for directories shouldn't be too hard (`readdir` -> `stat` -> `isDirectory` -> do it for subdirs).

I should mention I use Node 12.12 on Fedora 30 locally.

**Comment by AviVahl** [comment]
full log with the logging. gets out of memory for some reason:
https://github.com/typescript-eslint/typescript-eslint/files/3731982/out.txt

**Comment by bradzacher** [comment]
#1088 was just merged, and that should stop it from crashing, at the very least. I also added some handling to reduce duplicate watchers.

I'll look into explicitly adding ignoring for some folders we know to ignore (like node_modules / .git) (and potentially add a configurable ignore list?).

I'll look into the cases when typescript specifically asks for an `undefined` recursive watcher, and see if I can just ignore those cases entirely.

**Comment by AviVahl** [comment]
Ignoring `node_modules` and `.git` sounds sensible.

"ignoring" those cases entirely is not an ideal approach. When a file is added inside a package's  `/src/components` or `/test/some-folder`, then that recursive watch request would be the one to have caught it.

`chokidar` was nice several node versions ago (when native `fs.watch` was trash). With `libuv` addressing many of its watch issues, it now feels `chokidar` is just an overhead where you have to account for its naive glob-like behavior.

**Comment by raymondfeng** [comment]
Can we honor .eslintignore?

**Comment by bradzacher** [comment]
> chokidar was nice several node versions ago (when native fs.watch was trash).

That's the thing I'm worried about, as we support node 8+, when did watching with `libuv` become the standard?
I notice that a lot of big things still use it (like vscode, which ships its own node version via electron, so it shouldn't be tied to version inconsistencies?).

---

Running with some debugging on our repo, this is the output:
```
unlimited depth watcher
path: /typescript-eslint/tsconfig.eslint.json

unlimited depth watcher
path: /typescript-eslint/node_modules

unlimited depth watcher
path: /typescript-eslint/tools

unlimited depth watcher
path: /typescript-eslint/node_modules/@types

unlimited depth watcher
path: /typescript-eslint/tests

unlimited depth watcher
path: /typescript-eslint/tools

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin-tslint/tsconfig.json

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree

unlimited depth watcher
path: /typescript-eslint/packages/parser

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin-tslint/src

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin-tslint/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree/dist/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree/dist/ts-estree/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin-tslint/tests

unlimited depth watcher
path: /typescript-eslint/packages/parser/dist/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/parser/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/parser/dist/scope/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/dist/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/dist/ts-eslint/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/dist/ts-eslint-scope/node_modules

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin-tslint/node_modules/@types

unlimited depth watcher
path: /typescript-eslint/packages/node_modules/@types

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin/tsconfig.json

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin/src

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin/node_modules

0 depth watcher
path: /typescript-eslint/packages/eslint-plugin

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin/typings

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin/tests

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin/tools

unlimited depth watcher
path: /typescript-eslint/packages/eslint-plugin/node_modules/@types

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/tsconfig.json

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/src

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/node_modules/@types

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/typings

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/tests

unlimited depth watcher
path: /typescript-eslint/packages/experimental-utils/tools

unlimited depth watcher
path: /typescript-eslint/packages/parser/tsconfig.json

unlimited depth watcher
path: /typescript-eslint/packages/parser/src

unlimited depth watcher
path: /typescript-eslint/packages/parser/tests

unlimited depth watcher
path: /typescript-eslint/packages/parser/node_modules/@types

unlimited depth watcher
path: /typescript-eslint/packages/parser/tools

unlimited depth watcher
path: /typescript-eslint/packages/shared-fixtures/tsconfig.json

unlimited depth watcher
path: /typescript-eslint/packages/shared-fixtures/node_modules/@types

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree/tsconfig.json

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree/src

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree/tests

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree/node_modules/@types

unlimited depth watcher
path: /typescript-eslint/packages/typescript-estree/tools
```

So it appears that typescript attaches the unlimited depth watchers most of the time, especially when the `includes` path is set to a folder, I.E. in our tsconfigs we have like `"include": ["src", "tests", "tools"]`.

**Comment by bradzacher** [comment]
> Can we honor .eslintignore?

In this case, no, because we cannot properly provide types for a project if we do not include require typescript files.

**Comment by AviVahl** [comment]
`vscode` might not be the best example, as it has *terrible* watch experience. It fails to pick up basic changes, like `node_modules` folder after `git clean -fdx; yarn`.

`fs.watch` gives a less-than-ideal developer experience, as it doesn't de-bounce events, which come in bulk for the same path. Some IDEs "save" operation results in `'rename'` event followed by several `'change'` ones. One has to *re-watch* paths upon `'rename'`, as the original `FSWatcher` will be irrelevant for the path.

So yeah, there are a few gotchas, but debouncing and re-watching gives a lightweight watching solution that works for all platforms (node 8+).

I've experimented quite a lot with the native API in https://github.com/wixplosives/file-services/blob/master/packages/node/src/watch-service.ts (has bugs, but a nice reference to a possible approach)

I wonder, why don't you use `ts.sys`'s own `watchFile`/`watchDirectory`, only providing a middle-ware for the arguments and return value? I mean, `tsc -w` has pretty good watching experience, and their implementation probably behaves best with the rest of typescript's API. They use `fs.watch`, and have polling as fallback.

**Comment by bradzacher** [comment]
> I wonder, why don't you use ts.sys's own watchFile/watchDirectory, only providing a middle-ware for the arguments and return value?

We need non-persistent watchers, or else the lint process will hang open. TS uses persistent watchers.

As per https://github.com/typescript-eslint/typescript-eslint/issues/1091#issuecomment-542447852, we are in a weird spot where we have to simultaneously support both the persistent experience required by IDEs, as well as the transient experience required by CLI runs, without the ability to discern between the two.

So we need the non-persistent watchers to attempt to get the best of both worlds.
Which is why we can't use FSEvents, because FSEvents does not correctly work when attached as a non-persistent watcher - it will emit an initial event, but not any change events.

**Comment by AviVahl** [comment]
Can't the vscode plugin specify it needs watch mode? might be able to use `parserOptions` for that.

https://github.com/microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L885
https://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by bradzacher** [comment]
The ESLint APIs have no concept of "watch", as it's designed to be stateless.

I had considered PRing an option into ESLint to help us here, but that ties us in to a minimum version of eslint (a lot of our users are stuck on v5).

I also considered PRing the eslint IDE plugin, but that ultimately sort of fixes one use case.
Then I have do the same for the plugins for intelliJ, webstorm, visual studio, sublime, vim, etc...
It's not really a maintainable solution to try and get every single eslint IDE plugin to special case our parser. Additionally it's also a pretty gnarly experience if we force users to pressure the plugin maintainers to add the special case.

Finally I considered PRing typescript to expose more internals so we can work around this problem without asynchronicity (or maybe without watches at all), but that would be worse, because it'd tie us to a minimum version of typescript, when a lot of our users are barely past v3.

So the million dollar question is: how can we make this work without any external changes?

**Comment by AviVahl** [comment]
I see. Thanks for taking the time to explain this.

Hmm... since eslint is synchronous, how about using process.nextTick() for program invalidation?

I did something similar in older versions of `@ts-tools/node`: https://github.com/AviVahl/ts-tools/blob/177581a70f12d1f445fddc6fa7e2fcbd08c18dba/packages/node/src/register-node-extension.ts#L44
(newer versions no longer do type checking or create a program, so exact commit is necessary)

**Comment by AviVahl** [comment]
I'll clarify myself a bit:
- first request comes in
- `createProgram` (not watching) & register as invalid upon next tick
- when running the `eslint` cli, next request comes in synchronously and reuses Program.
- next tick comes -> mark as invalid
- another lint request comes (in case of an IDE), revalidate program- parse config, stat every file, verify everything matches. If mismatch, create a new program reusing the old one.

The language service does something similar:
https://github.com/microsoft/TypeScript/blob/v3.6.4/src/services/services.ts#L1172

**Comment by bradzacher** [comment]
I've just landed #1106, and it will be deployed to the `canary` tag imminently.
This change reworks the invalidation approach so that it doesn't need file watchers at all.

I'd appreciate if you could take a moment to test the canary tag on your codebases, and let me know if anything isn't working as expected for your real-world codebase.

**Comment by AviVahl** [comment]
I tried `canary` (removed the now-irrelevant `"noWatch"` flag).

Running the `eslint` cli passes. I does gives me an unexpected warning:
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.8.0 >3.7.0-dev.0

YOUR TYPESCRIPT VERSION: 3.6.4

Please only submit bug reports when using the officially supported version.

=============
```
I went on checking the eslint extension in `vscode`.
- Live lint of existing files works well.
- Copying a file (ctrl+c, ctrl+v in the file tree) gives me the following error:
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: packages/server/src/index copy.tsx.
The file must be included in at least one of the projects provided.eslint
```
- Creating a new file also causes the above error.

Tested on [sample-monorepo](https://github.com/wixplosives/sample-monorepo) (see [branch](https://github.com/wixplosives/sample-monorepo/tree/typescript-eslint-canary)), using fedora@30, node@12.12, vscode@1.39.2.

**Comment by bradzacher** [comment]
Ahhh shoot. For the warning, that was my mistake - #1109 I'll get that in asap.

Did you reload your IDE after updating your package version?
I tried copy pasting files, renaming, and creating new files in the project and it was working fine in my VSCode.

**Comment by AviVahl** [comment]
I completely closed the IDE and restarted... I even tried disabling all extensions and re-enabling just `eslint`. Same issue.

My local `vscode` config has:
```
    "eslint.autoFixOnSave": true,
    "eslint.packageManager": "yarn",
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact"
    ],
```
I wonder, did you try my "sample-monorepo" example locally?
Any chance you could:
```
git clone git@github.com:wixplosives/sample-monorepo.git --branch typescript-eslint-canary
cd sample-monorepo
yarn
code .
```
and then try?

**Comment by bradzacher** [comment]
Hmmm I see the problem - TS has a different code path when you provide a tsconfig with no `include`.

**Comment by bradzacher** [comment]
I've raised #1110 to keep track of this, as I don't know if I'll be able to fix this case by the automated release on Monday.

**Comment by AviVahl** [comment]
Thank you for looking into this and the workaround. I'll comment further in the new issue.
