### ISSUE TITLE
[2.4.0][Watch] OUT OF MEMORY on node 10

### ISSUE THREAD

**Issue by Hotell** [typescript-eslint/typescript-eslint#1107]
maybe related to https://github.com/typescript-eslint/typescript-eslint/issues/1091 ? 

**What did you expect to happen?**

lint should work as before

**What actually happened?**

after bumping to 2.4.0 I got out of memory error ![image](https://user-images.githubusercontent.com/1223799/67147340-a956df80-f2c6-11e9-84bc-d5b35dccb63f.png)

not present with 2.3.3.

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `2.4.0` |
| `TypeScript`                | `3.6.4` |
| `ESLint`                    | `6.5.1` |
| `node`                      | `10.16.1` |
| `yarn`                       | `1.19` |

**Comment by bradzacher** [comment]
As you probably read on the other issues, I added some to add some weak file watching to attempt to support the IDE use case. TBH this code wasn't great, missed a lot of cases, and didn't work well across OSs.

I've just landed #1106, and it will be deployed to the `canary` tag imminently.
This change reworks the invalidation approach so that it doesn't need file watchers at all.

I'd appreciate if you could take a moment to test the canary tag on your codebase, and let me know if anything isn't working as expected for your real-world codebase.

**Comment by Hotell** [comment]
fixed in `2.4.1-alpha.9` 👍
