### ISSUE TITLE
Unify assertions AST with Babel

### ISSUE THREAD

**Issue by thorn0** [typescript-eslint/typescript-eslint#1158]
The Babel team named the node property `assertsModifier`, not `asserts`. Let's rename it while it's not too late, shall we?

https://github.com/babel/babel/pull/10543

**Comment by bradzacher** [comment]
Shouldn't it be the other way round?
We've had this merged and released for 2 weeks - babel merged theirs in 44 minutes ago.

**Comment by thorn0** [comment]
Probably, I read this in readme

> Some of the people involved in typescript-eslint are also involved in Babel and babel-eslint, and in this project we are working hard to align on the AST format for non-standard JavaScript syntax. This is an ongoing effort.

but didn't know how exactly this process works and which project is considered the source of truth.

**Comment by bradzacher** [comment]
Looking at that PR, nobody involved in this project was pulled in at all to eyeball, and none of the reviewers are involved here as well.

James has been involved in the babel side of things in the past but he's been pretty busy with real life stuff. We have a few other people who are collaborators on both projects, but then that relies them seeing the work in both repos (or being notified).

**Comment by existentialism** [comment]
@bradzacher sorry I missed this. re: alignment, feel free to ping me as things get ready to land here for TS, and we'll be sure /cc you and James on the Babel-side!

**Comment by thorn0** [comment]
@bradzacher And what is the process supposed to be for the existing differences? E.g. for `TSImportType`, Babel uses the `argument` property name, `typescript-eslint` uses `parameter`. How are these things going to be aligned?

**Comment by bradzacher** [comment]
> re: alignment

Definitely, I think it makes sense to add a collaborator list here so we can easily tag the relevant babel peeps when we are making / talking about the AST (and vice versa for babel when the TS AST is being worked on).

> And what is the process supposed to be for the existing differences

We don't have one!
We need to "sit down and talk" about these differences so that we can figure out what breaking changes are required where so that we can converge the two representations.

There's a bunch of stuff that I've been thinking about around this, because there's a lot of weirdness in the AST.

**Comment by nicolo-ribaudo** [comment]
We should definitely ping each other when designing new ASTs. We already have a #typescript room in our Slack channel, we might use it for any chat which doesn't fit well the GitHub issue format.

Regarding the AST differences, do you already know the complete set of them?

**Comment by bradzacher** [comment]
We have a basic alignment pipeline setup in this repo, but since james set it up, it has fallen a bit into disrepair.
Between not keeping it up to date with the latest version of babel, our teams not fully aligning on things (like babel having some props being optional when we always emit them), and some things differing, it's not showing a great state.

Here is a list of our fixtures where the two impls differ in some way.
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts

This test can definitely be improved (like ignoring times that we emit `prop: false` and babel emitting no prop), but it's at least a start.

Side note that we probably need to have a lot more cases added to our fixtures, I know there's a number of edge case gaps that we don't have proper testing for (eg https://github.com/typescript-eslint/typescript-eslint/pull/1100).
