### ISSUE TITLE
Add no-unused-expressions to recommended

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1194]
Added in https://github.com/typescript-eslint/typescript-eslint/pull/1175 by @Nizarius

Should be added to the `eslint-recommened` set.

**Comment by pandaLv** [comment]
Or have any way to add this rule to the eslint rule list? 

If a rule is not in recommended/fixable/requires type information, how can I use them?

**Comment by bradzacher** [comment]
The docs are your friend here

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-expressions.md

https://eslint.org/docs/user-guide/configuring#configuring-rules

**Comment by JerryLyu93** [comment]
THX for the docs. 

I was trying to follow the docs of eslint & typescript-eslint, but the linter just keeping throw the Error `Definition for rule '@typescript-eslint/no-unused-expressions' was not found`. 

So first I thought the reason was that I use `plugin:@typescript-eslint/recommended` and `@typescript-eslint/no-unused-expressions` is not recommended. But your reply shows the reason seems not true.

Then I found some issues like this Error. Most of them were version issues but the packages of `typescript-eslint` in my project seem were already up-to-date but it's not really. At last, I found the package `react-scripts` was depended on the 1.x `@typescript-eslint/eslint-plugin`. OMG monorepo always cause issues like this, and maybe I should notice not only package.json but also yarn.lock.

THX for your help again.
