### ISSUE TITLE
Getting the new parser into AST Explorer

### ISSUE THREAD

**Issue by platinumazure** [typescript-eslint/typescript-eslint#125]
[AST Explorer](https://astexplorer.net) has the latest typescript-eslint-parser (from the ESLint org) available for use, but we'll want to get the new parser out there.

Anyone know where to start?

Vaguely related question: Do we intend to set up a web demo somewhere?

(Might be off-topic as this is not strictly an issue in this repo-- apologies if that's the case)

**Comment by ikatyang** [comment]
FYI, fkling/astexplorer#377.

**Comment by j-f1** [comment]
Web demo would be cool.

**Comment by armano2** [comment]
You should check https://vuejs.github.io/eslint-plugin-vue/rules/

**Comment by bradzacher** [comment]
@armano2 has pointed out that eslint-plugin-vue has this setup for their repo, so we can look to leveraging(/stealing) their work to make interactive docs happen:

https://mysticatea.github.io/eslint-plugin-es/rules/no-json-superset.html
https://mysticatea.github.io/vue-eslint-editor/

Note that even with this codebase as a starting point - this is still a non-trivial amount of work due to the need for build tooling and such.

**Comment by mysticatea** [comment]
I think it's not a steal :D 

Also, https://mysticatea.github.io/vue-eslint-demo/ is an existing playground, which supports old `typescript-eslint-parser`. I think that it's not hard to fork that for this repository. I can work in this weekend.

**Comment by j-f1** [comment]
https://github.com/jvilk/BrowserFS

**Comment by JamesHenry** [comment]
Looks like the reason for the initial issue has been resolved, as AST explorer added `@typescript-eslint/parser` to its list

**Comment by JamesHenry** [comment]
A separate interactive playground is definitely a nice to have too :)
