### ISSUE TITLE
Exception when parsing JSDocFunctionType

### ISSUE THREAD

**Issue by bradzacher** [typescript-eslint/typescript-eslint#1301]
**What code were you trying to parse?**

```ts
var a: function(b): c;
```

**What actually happened?**

`Cannot set property 'typeAnnotation' of null`

I haven't debugged this at all, but I assume it's because the variable's type declaration is of kind `JSDocFunctionType`, which we do not have any handling for.

https://astexplorer.net/#/gist/a1a5bcad94191c0d730eb920ced2e24b/f10df5321aaf8ceef561d14ce57a0ab59eee0ac5

**Comment by armano2** [comment]
This syntax is invalid if used in code, typescript reports error code `8020`,

error happens when we are trying to convert `b` -> `Parameter`

typescript does not return correct ast node (there is no name) and parameter is created as null

https://github.com/typescript-eslint/typescript-eslint/blob/348d2f6b207acb9e18721cba53f0aa85908fa777/packages/typescript-estree/src/convert.ts#L1364-L1372

we should enable error code 8020

**Comment by armano2** [comment]
what do you think about throwing parse error when we encounter nodes from range `FirstJSDocNode` and `LastJSDocNode`? as this is going to to produce incorrect ast anyway (in unexpected ways).

**Comment by bradzacher** [comment]
I don't see why not - it's a TS error anyways.
