### ISSUE TITLE
[indent] add baseIndent for Vue SFC 

### ISSUE THREAD

**Issue by pleek91** [typescript-eslint/typescript-eslint#1325]
I was using [vue/script-indent ](https://eslint.vuejs.org/rules/script-indent.html#vue-script-indent)to handle the indentation of javascript in single file vue components. However after switching to typescript that rule no longer works and their documentation recommends switching to `@typescript-eslint/indent` for vue files that use `ts`. But what I've discovered is when using the typescript version it removes all of my script tag indentation converting this

```
<script lang="ts">
    @Component
    export default class Button extends Vue {}
</script>
```

to this

```
<script lang="ts">
@Component
export default class Button extends Vue {}
</script>
```

Is there a way around this? Or could `baseIndent` be added to the `indent` rule so I can specify that vue files have a `baseIndent` of `1`?

**Comment by bradzacher** [comment]
Having a nonzero indentation for your script tags is a personal stylistic preference.

There is no option in the rule. Happy to accept a PR to add one.

**Comment by pleek91** [comment]
Probably a little out of my wheelhouse but I'll take a look. Thanks

**Comment by RensBoeser** [comment]
I'm switching from TSlint to ESlint and I'm having the same problem with my Vue components. I'm guessing more and more people will encounter the same problem due to the deprication of TSlint.

**Comment by bradzacher** [comment]
This project is maintained by volunteers, and is run off the contributions of the community.
Happy to accept a PR to add an option.

**Comment by bradzacher** [comment]
Hi there 👋!

As you may have heard [ESLint core is deprecating its formatting rules](https://eslint.org/blog/2023/10/deprecating-formatting-rules/). We are likewise moving in the same direction and deprecating our formatting rules.

Deprecated rules will be removed in the next major version as their new home is the [eslint-stylistic](https://github.com/eslint-stylistic/eslint-stylistic) project.

If this issue is important to you please consider filling an issue over at eslint-stylistic which will be the new home for stylistic/formatting rules.

Thanks!
