### ISSUE TITLE
Wrong typescript version being used with yarn workspaces/monorepo (repro inside)

### ISSUE THREAD

**Issue by andreialecu** [typescript-eslint/typescript-eslint#1392]
I've set up a simple repro where there are two packages inside a packages/* directory, and their package.json are these:

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "jest --config jest.json"
  },
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "@types/jest": "^24.0.25",
    "@typescript-eslint/eslint-plugin": "^2.13.0",
    "@typescript-eslint/parser": "^2.13.0",
    "eslint": "^6.8.0",
    "jest": "^24.9.0",
    "ts-jest": "^24.2.0",
    "typescript": "^3.7.4"
  }
}
```
```json
{
  "name": "something-else",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "typescript": "3.5.3"
  }
}
```
For some reason yarn determines that typescript 3.5.3 gets to be put in the root workspace's node_modules and eslint uses that typescript version, resulting in problems inside packages such as this one:

![image](https://user-images.githubusercontent.com/697707/71588508-75036900-2b2a-11ea-8e95-796f9839afb3.png)

Repro at https://github.com/andreialecu/tsjestrepro/tree/eslint

If you update typescript in both the something-else and something-else2 packages in the repro, the error will be gone. Unfortunately, because of Angular, I'm stuck with older typescript versions in some packages.

I'm able to work around it by adding `nohoist` to `typescript-eslint` like this:

```json
{
  "private": true,
  "workspaces": {
    "packages": ["packages/*"],
    "nohoist": ["**/@typescript-eslint", "**/@typescript-eslint/**"]
  }
}
```

Should this be supported out of the box instead?

**Comment by bradzacher** [comment]
We can't do anything more than just requiring the module.
The node/npm ecosystem runs on the assumption that your dependencies are correct.

If yarn has set up a weird set of dependencies in your workspace, then you'll have to file an issue with them for support.

**Comment by andreialecu** [comment]
If you require typescript from within a script in the ‘test’ project, the version of typescript will be correct so this isn't a yarn issue.

Perhaps it's an issue with eslint instead but this is still an issue and the repro shows it.

At a minimum a note about this should be added to the documentation.

**Comment by bradzacher** [comment]
As far as yarn is concerned, all of the `@typescript-eslint` packages essentially have a peer dependency of `"typescript": "*"`.

When yarn goes about installing our packages within the `test` package, it first checks the requirements for our packages. As mentioned it sees _no strict version dependency_.
Because of this, yarn tries to be helpful, and hoists the installation to the root of the repo. This is seen as "safe" because yarn has already hoisted the `3.5` version of typescript from your other two packages, and no strict range means it should (and does) work fine with either version.

Then, when you run `yarn eslint` from within `test`:
- yarn picks up the `eslint` bin from the root level - as that's where it's been installed by yarn.
- eslint `require`s our parser from the root level, because that's where eslint was installed by yarn.
- our parser `require`s `typescript` from the root level, because that's where our parser was installed by yarn.
- parse is executed with the root level typescript version (3.5, not 3.7)

If you don't like how yarn has helpfully hoisted things, I'd suggest raising an issue with them, or else you've done the right thing by telling yarn not to hoist the packages.


At the end of the day, the problem you've got is you've got multiple TS versions installed across your workspace. This is almost always a bad idea. Multiple TS versions can cause chaos, because you may find during execution that two different versions are required at any given time. This is not only a problem for memory reasons, but also because typescript has many enums which are not "stable" between versions, which can cause subtle, hard to repro bugs.

Recommendation is always to use a single, standardised TS version across a given project.
