### ISSUE TITLE
[generic-type-naming] Support regex literal for config properties that accept regex string

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#143]
Would be nice to be able to use regex literals to not have to double-escape certain characters when using JS-based ESLint config.

### Before

```js
'@typescript-eslint/generic-type-naming': [
	'error',
	'^[A-Z][a-zA-Z\\d]+$'
],
```

### After

```js
'@typescript-eslint/generic-type-naming': [
	'error',
	/^[A-Z][a-zA-Z\d]+$/
],
```

It also means it becomes syntax highlighted and ESLint (through some built-in rules) can prevent some common mistakes when you lint the config itself.

This would require changes to the following rules:

- `@typescript-eslint/generic-type-naming`
- `@typescript-eslint/member-naming`
- `@typescript-eslint/no-unused-vars`

---

Related ESLint issue: https://github.com/eslint/eslint/issues/11318

**Comment by bradzacher** [comment]
Revisiting this.

It's not something we can handle ourselves.
The short and curlies of it is that eslint uses JSONSchema to define rule options, and JSONSchema does not support JS RegExp out of the box, (because it's a spec for validating JSON, not native JS objects).

Looking into it a bit.
Under the hood, eslint uses the `ajv` library to handle the JSONSchema validation. This library is pretty stupidly powerful, so they could add a bunch of helpful features if they wanted to stray from the spec, but from our end there's not a lot we could do due to not owning the stack.

If it's important to you, there's always the path of raising an [eslint rfc](https://github.com/eslint/rfcs). The eslint maintainers are generally pretty receptive to good ideas 😄

---

Side note.
While playing, I realised that you can actually use this pretty simple hack to use native RegExp in your JS config file:
```js
'@typescript-eslint/generic-type-naming': [
	'error',
	/^[A-Z][a-zA-Z\d]+$/.toString().slice(1, -1)
],
```
(note modifiers are not supported).

**Comment by sindresorhus** [comment]
> While playing, I realised that you can actually use this pretty simple hack to use native RegExp in your JS config file:

This would be better:

```js
/^[A-Z][a-zA-Z\d]+$/.source
```
