### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by achavhantexada** [typescript-eslint/typescript-eslint#1551]
**npx eslint sometypescript file.tsx --debug?**

```ts
N/A
```

**What did you expect to happen?**
Should perform the linting. 
**What actually happened?**
Error: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
**Versions**

| package                                   | version |
| ----------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.17.0` |
| `@typescript-eslint/parser`               | `2.9.0` |
| `TypeScript`                              | `3.7.2` |
| `ESLint`                                  | `v6.8.0` |
| `node`                                    | `10.18.1` |
| `npm`                                     | `6.13.4` |

Whenever Eslint encounters with .ts or .tsx files, it just stops working and in debug mode, and you can see the Javascript Out of Heap Memory errors. (checked in Vscode debug plugin and Command-line)

Anyhow I changed my tsconfig.json file and added "include" property to target only specified directories. 
It works amazingly and everything is normal now. 

So my concern is why Eslint is checking the whole project even I've specified the file path(This is an assumption since Eslint is throwing Out of Heap memory). 

I was not running ESlint on the whole project, but just one file.

I have seen a lot of other issues regarding Heap Memory, and to be honest, I don't want to twist my Node.js runtime. This is insane if an application is using this much Heap memory.

**Comment by bradzacher** [comment]
If you're linting with type information, we have to gather that type information.
There's only one way to gather this type information - via typescript.

Typescript needs to know what files are part of the project so it can parse and typecheck them all, and return the data structures for the type information.

ESLint doesn't tell us which files are being linted ahead of time, it only tells us (one file at a time) which files are being linted.

So the two tools are at-odds with one another. So we just tell typescript about the tsconfigs you've told us about, and let it gather all of the type information for those files. We cache the result, so that we don't waste time double parsing anything.

This works great for almost every use case, like running `eslint src`, or using an IDE with a plugin, because those use cases will need type information for every (or almost every) file in the project.

The one case that this doesn't work great for is when you specify a single, or a subset of files (`eslint src/foo/bar/myfile.ts` or `eslint src/foo/bar`) because typescript will over-parse. However this is a rarer use case, so we optimise for the 99% use case instead.

---

Not having an `include` property in your tsconfig will cause issues, because it's the same as doing `include: ["**/*"]`. It's a prevalent issue, and as such is explicitly called out in our FAQ:
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#wide-includes-in-your-tsconfig

You should probably take a look at all of our docs on linting which are in that folder.
The docs also include guides for setting up your project to be linted with our tooling.

---

The reason you're running into memory issues is probably because your project is probably setup something like this.
```
/
├── tsconfig.json
├── src/
│   └── **/*.ts[x]?
├── tests/
│   └── **/*.ts[x]?
└── build/
    └── **/*.js
```

So your tsconfig with no `include`, which is actually using the glob `**/*` will match `src`, `tests`, ***AND `build`***.
This obviously means that typescript will do around double the amount of work, parsing double the amount of files, and storing double the amount of type information.

For small projects, they will luckily fit within the size limit, so they won't even notice. They will have slow runtimes, but it won't crash.
For medium to large projects, it's very easy to hit the memory limit.

**Comment by achavhantexada** [comment]
Thanks for the information, it is really helpful for me and I can now understand what is the actual root cause for this error. @bradzacher
