### ISSUE TITLE
[require-await][question] sync implementation of an inherited async method

### ISSUE THREAD

**Issue by quezak** [typescript-eslint/typescript-eslint#1599]
**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/require-await": "error",
    "@typescript-eslint/promise-function-async": "error",
    "@typescript-eslint/return-await": ["error", "in-try-catch"]
  }
}
```

```TS
// Can be an interface or a base class
interface StuffProvider {
    // say normally this would call some external API to return a result
    getFeatures(): Promise<string[]>;
}

class TestProvider1 implements StuffProvider {
    // say we know this particular provider has no features, so we're returning `[]` right away
    // Error: Async method 'getFeatures' has no 'await' expression.
    async getFeatures(): Promise<string[]> {
        return [];
    }
}
```

**Expected Result**
No linter error on a sync implementation of an inherited async method.

Question: how?

Possible workarounds:
* disable the `require-await` for this line -- becomes ugly if this pattern repeats a few times
* `return Promise.resolve([])` -- looks ugly & _boilerplate'y_, since it works without it and in TS code you generally don't have to construct promises manually

I can't use `return await` or remove `async` because of arguments mentioned in [rule docs](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/require-await.md#rule-details).

But this time I also can't change the method to return a non-promise type, since the method signature must match interface/base class. Is this enough to make this rule ignore inherited methods? Or maybe add an option `{ "ignoreInheritedMethods": true }`?

**Actual Result**
I need to resort to workarounds to silence an error from the `require-await` rule.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.19.2` |
| `@typescript-eslint/parser`        | `2.19.2` |
| `TypeScript`                       | `3.7.2` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `11.9` |
| `npm`                              | `6.5` |

(but I don't use `npm`, only `yarn` ^)

**Comment by bradzacher** [comment]
An ignore option would not work. Ignore options lack context, and are a shotgun approach. This lacks nuance and easily causes a rule to false negative.

In this case you are intentionally stubbing out method implementations for a test. But what about in a real world case where you just forgot to await something? Or you called the wrong method? Etc. In those cases the lint rule _should_ fire, but would be suppressed by an option.

---

The rule exists to enforce that you are using the `async` keyword such that you aren't just using it for its side-effect of wrapping a non-promise return value in a promise.

If you're intentionally using the async keyword to wrap the return value in a promise, then that's what the eslint disable comments are for.

The great thing about disable comments is that they let you explicitly call out why you're working around a lint rule.

```ts
    // stubbing out the method so intentionally using async to wrap the array in a promise
    // eslint-disable-next-line @typescript-eslint/require-await
    async getFeatures(): Promise<string[]> {
        return [];
    }
```

> looks ugly & boilerplate'y, since it works without it and in TS code you generally don't have to construct promises manually

Similarly, explicitly wrapping the return value in a `Promise.resolve` is great documentation that you are intentionally not awaiting anything.

---

The other thing I'd like to mention is that if this is a pattern that happens regularly in your production code, then it's a definite code smell - why is an interface declaring a method that so many things just stub out?
In this case you should change your code to support your patterns you're coding, instead of changing the lint rule to support the code smell.

If it's only happening in test code, then it's something we don't generally look to support. Test code is often messy, and usually intentionally violates "best practices" defined by linters for good reasons.
