### ISSUE TITLE
[interface-name-prefix] Complains about IjQuery* interfaces

### ISSUE THREAD

**Issue by crystalfp** [typescript-eslint/typescript-eslint#1601]
**Repro**
If in the example below I uppercase the first "j" the warning disappears.

```JSON
{
  "rules": {
    "@typescript-eslint/interface-name-prefix": ["warn", {"prefixWithI": "always"}]
  }
}
```

```TS
interface IjQueryLayoutOptions {
	[key: string]: {
		[key: string]: unknown;
	};
}
```

**Expected Result**
No warning

**Actual Result**
Interface name must be prefixed with "I"

**Additional Info**
No exception from eslint

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.19.2` |
| `@typescript-eslint/parser`        | `2.19.2` |
| `TypeScript`                       | `3.7.5` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `12.15.0` |
| `npm`                              | `6.13.7` |

**Comment by bradzacher** [comment]
Two things.

1)
There is no way around this for this rule. The rule runs of a simple regex - `/^I[A-Z]/`.
There is no way to teach the rule that the `j` in `IjQuery` is intentionally lowercase because the name `jQuery` is capitalised in that non-standard way. 

2)
This rule has been deprecated, and will be removed in a future version.
You should switch to the `naming-convention` rule.
The `naming-convention` rule has options to let you use regex to ignore names and such.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md
