### ISSUE TITLE
[import/no-unresolved] How to tell eslint I'm just bringing types from @types module?

### ISSUE THREAD

**Issue by aecorredor** [typescript-eslint/typescript-eslint#1624]
**Repro**

Use the following code in a repo that only has `@types/aws-lambda` as a devDependency:

```js
import { APIGatewayProxyEvent, Context } from 'aws-lambda';
```

**Expected Result**
eslint understands that I'm only bringing in the types from `@types/aws-lambda` and not the actual `aws-lambda` module.

**Actual Result**
eslint complains with `import/no-unresolved` because it can't find `aws-lambda` in the dependencies.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `^2.18.0` |
| `@typescript-eslint/parser`        | `^2.18.0` |
| `TypeScript`                       | `^3.7.5` |
| `ESLint`                           | `^6.8.0` |
| `node`                             | `12.16.0` |
| `npm`                              | `6.13.4` |

**Comment by bradzacher** [comment]
A few things:
- this is a question you should be asking in the relevant plugin's github repo, `eslint-plugin-import`.
- you shouldn't bother using the `import/no-unresolved` rule, because it duplicates errors that typescript itself provides better.
- as per the eslint-plugin-import docs: https://www.npmjs.com/package/eslint-plugin-import#resolvers
  - https://www.npmjs.com/package/eslint-import-resolver-typescript

**Comment by aecorredor** [comment]
@bradzacher thanks for the quick and clear response. Everything makes sense. And sorry for asking this here, will keep it in mind for the future.
