### ISSUE TITLE
[no-empty-interface] Cannot extend type alias / incorrect fixit

### ISSUE THREAD

**Issue by Bouke** [typescript-eslint/typescript-eslint#1640]
**Repro**

```ts
interface MyBase {
  //...
}
interface MyType extends MyBase { }
interface MyType {
  // ...
}
```

**Expected Result**
No error.

**Actual Result**
`interface MyType extends MyBase`
> An interface declaring no members is equivalent to its supertype.

`--fix` will replace the interface definition:
```ts
interface MyBase {
  //...
}
type MyType = MyBase
interface MyType {
  // ...
}
```
Which is invalid typescript:
> Duplicate identifier 'MyType'.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `2.21.0` |
| `@typescript-eslint/parser`        | `2.21.0` |
| `TypeScript`                       | `3.8.2` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `13.0.1` |
| `yarn`                              | `1.19.1` |

**Comment by bradzacher** [comment]
happy to accept a PR to fix this.

question:
why are you using declaration merging like this in your codebase?

**Comment by pablobirukov** [comment]
Whole idea of deprecating `interface MyType extends MyBase { }` in favour of `type MyType = MyBase` seems to be buggy, as `type` is semantically different and can not be augmented.

@Bouke, you probably know that the option [`allowSingleExtends`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-empty-interface.md#options) is set to `true` will change the behaviour to [desired](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/tests/rules/no-empty-interface.test.ts#L33)

@bradzacher  As extension could happen in different file or package, it seems to me that the rule should behave as `allowSingleExtends` is always `true`.

**Comment by bradzacher** [comment]
I disagree, because I don't think declaration merging is something the majority of TS users consciously use, particularly not across file/package boundaries.

I'm inferring this based on the codebase I've seen, and the fact that there have been very, very few issues opened about rules not supporting it, despite the fact that none of our rules actively support it.

Declaration merging is definitely an advanced use case which, which brings with it many potential type safety holes (simple example below). So IMO it should be avoided in codebase where possible, unless it's explicitly required.

```ts
interface Console { methodThatDoesntExist(): void }

console.foo(); // compile-time safe, but errors at runtime
// unless ofc the declaration merged properties are guaranteed to exist at runtime.
```

If this is something you explicitly want to support in your codebase, then sure, turn the option on.
If it's not, then `type Foo = Bar` is equivalent to `interface Foo extends Bar {}`, and there's no need for the option to be on.

In the latter case as well, you can easily just use a disable comment if you run into a use case that you explicitly want it, then there is the added bonus of you adding documentation about why you are disabling the rule, making it clear that it's used for declaration merging.

**Comment by Bouke** [comment]
Your example doesn't generate any linting issues regardless of `allowSingleExtends`. If extending existing interfaces is an advanced case, shouldn't this also be an issue?

`type Foo = Bar` isn't equivalent to `interface Foo extends Bar {}` when `Foo` is imported from elsewhere. In the first case it might lead to duplicate identifiers and missing properties. Maybe this should be considered an advance case. However the suggestion from the linter is simply incorrect as it isn't equivalent.  Take for example the following:

```ts
interface Array<T> extends Ember.ArrayPrototypeExtensions<T> { }
[1].pushObject(...); // OK (implementation from ember)
```
vs
```ts
type Array<T> = Ember.ArrayPrototypeExtensions<T>; //  - error TS2300: Duplicate identifier 'Array'.
[1].pushObject(...); //  error TS2339: Property 'pushObject' does not exist on type 'Address[]'
```

PS in your example I'm assuming you meant `console.methodThatDoesntExist();`.

**Comment by mheavenor** [comment]
Related to @pablobirukov 's comment above... types and interfaces are not equivalent because the Typescript compiler treats them differently. In some cases, performance can be an order of magnitude worse (my typechecking stage using ForkTsCheckerWebpackPlugin went from a few seconds to 3 minutes!!!)

[Typescript documentation reference regarding prefering interfaces](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections)

**Comment by Josh-Cena** [comment]
What are we trying to fix here? This rule is not type-aware so we cannot know if there is declaration merging and whether this `interface` is safe to convert to `type`. I thought `allowSingleExtends` was to exactly allow this kind of declaration merging.

**Comment by bradzacher** [comment]
We can detect it in the same file - otherwise no - it's not possible to fix this.
I'm personally okay with just closing this as a known edge case we can't handle because the complexity of building that single file support vs the usecases it'll allow is not a good cost:value ratio.

This issue is now over 3 years old and has garnered 5 total participants - so it's not a widely encountered problem - I still stand strongly by my original statement:

> I don't think declaration merging is something the majority of TS users consciously use, particularly not across file/package boundaries
