### ISSUE TITLE
lint with type checking is too slow

### ISSUE THREAD

**Issue by memao** [typescript-eslint/typescript-eslint#1646]
We have a big monorepo with over 100 packages. Lint with tsconfig.json in the parserOption takes over 20 mins. I also tried build our project first then do eslint, but still didn't get any better. It feels to me that lint is re-doing build. 

Build already takes 10 mins for our project. I am wondering if there is an option to use the artifact from the build step, so lint become faster.

**Comment by bradzacher** [comment]
Have you had a look at our FAQ?
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#my-linting-feels-really-slow

---

> It feels to me that lint is re-doing build.

It essentially is. We talk to the typescript API, and it does a complete typecheck of the project to provide type information for the lint rules to consume.

> I am wondering if there is an option to use the artifact from the build step

What artifact?
And there are no options, no.

**Comment by memao** [comment]
@bradzacher I did read the FAQ. The include field in our tsconfig.eslint.json only includes folders and file types that we want to lint. The indent rule is commented out. Actually for experiment purposes, there is only one rule in the config file. We also don't use those two plugs in eslint. 

> We talk to the typescript API, and it does a complete typecheck of the project to provide type information for the lint rules to consume.

If we want to build and lint our project, is it going to do build twice and take almost twice the time? Is there a way to do build and lint together and only cost "one build time"?

**Comment by bradzacher** [comment]
> Is there a way to do build and lint together 

There is not, no.
You could parallelise it via lerna or some custom tooling. But we don't support anything.

Your project size is an outlier, most users don't often break 10 packages in a monorepo, let alone triple digits.
This is why there is little tooling or support for this; we as maintainers focus on the majority use case as we are volunteers, and have limited time.
We rely on the community to support their minority use cases. For example the vuejs community is fairly small, but they come out in force to help support the framework's quirks.

Larger projects often have to customise their tooling to deal with their scale anyways, so they just do extend that for linting as well. Unfortunately, it usually ends up customised to their specific (often proprietary) codebase, and working to generalise it is more effort than it's worth, so they never usually contribute back.

Would love a PR for some perf improvements or new tooling if you create some. But it's really hard for us to build anything, because as mentioned - large codebases are often proprietary, and thus nobody usually wants to share code with us.

At your scale you're going to have to invest some time in refactoring scripts and configs such that you can do isolated runs of each package instead of running.
