### ISSUE TITLE
Checker for ESLint rules already covered by TS

### ISSUE THREAD

**Issue by astorije** [typescript-eslint/typescript-eslint#1677]
The README of this repo says:

> This means that there will be cases where TypeScript actually solves a problem for us that we previously relied on ESLint for. These two solutions could have similar aims, but different results, or be incompatible in other ways. The best way to deal with situations like this is often to disable the relevant ESLint rule and go with the TypeScript Compiler.

In most cases, rules that are already covered by TypeScript itself can be easily identified. In practice, there are rules that are covered by TS but that can be overlooked.

https://github.com/prettier/eslint-config-prettier solves this by providing a CLI helper that checks configuration files for unnecessary rules that have manually been turned on. I think this would nicely complement the amazing list of rules that you provide.

**Comment by bradzacher** [comment]
The docs here a probably a bit unclear here, but this is already provided by our `eslint-recommended` config.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/configs/eslint-recommended.ts

Happy to accept a PR to clarify the docs here!

**Comment by astorije** [comment]
Hey @bradzacher, thanks for chiming in! Apologies if I was unclear in my initial issue, but I don't believe we are on the same page here 😅

I totally get the `eslint-recommended` config (in fact, I use it) and that would be something similar to the purpose of the `eslint-config-prettier` config.
However, they also provide a nifty CLI tool called `eslint-config-prettier-check` (see https://github.com/prettier/eslint-config-prettier/#cli-helper-tool) that checks if extra rules have been added on top of the recommended preset and can be removed.

For example, say our extensive ESLint configuration overrides `no-const-assign`. While `eslint-recommended` would do the correct job of turning it off, our erroneous configuration would supersede it and we'd never notice. Such a CLI could inform us of this and we could clean up our configuration file(s).

**Comment by bradzacher** [comment]
If someone wants to build and help maintain a tool, then it's something we can look at merging, but otherwise I don't really want to add another tool to the keychain, as we're very short on both contributor and maintainer cycles right now (there are few people that want to contribute to the project beyond the rule or option they need).

An example of what I mean - of their own accord, one of our contributors created the `tslint-to-eslint-config` tool, which helps people migrate to our tooling from tslint. They did this in their own namespace to begin with, and (with their blessing) we later brought the project within our namespace to help co-locate the ecosystem. However that contributor has retains control of the tool, and maintains it.

----

I think that there's definitely a lot of room within this space to improve the onboarding experience, but it's a rather low pri thing for me personally for a couple of reasons:
- onboarding happens (for most users) once, or at most a handful of times, meaning invested time only has so much "value".
- between our documentation and external articles / example repos, there's generally enough guidance for people to fumble their way through setup, and learn as they go.
- most importantly (for me at least) the shortage of time - as a core maintainer, I'd rather spend my time working on bugs/features too complex/too large a scope for external contributors.

But as mentioned, if a contributor wants to take up the mantle and build something to make the experience better or write docs to smooth the onboarding, I'd be very grateful!

**Comment by G-Rath** [comment]
> we're very short on both contributor and maintainer cycles right now (there are few people that want to contribute to the project beyond the rule or option they need)

While my bandwidth is pretty saturated right now, I'm keen to help & contribute when & where I can - Feel free to ping or assign issues to me as you like :)

(I've actually got a few rules half-done, but need to upskill on TypeScript internals to be able leverage the typechecking side properly 😬)

**Comment by bradzacher** [comment]
There's always plenty of issues to work through :)
Feel free to put up some prs in draft mode if you want some pointers and such.
