### ISSUE TITLE
Regression in 2.24.0: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by crfrolik** [typescript-eslint/typescript-eslint#1746]
**What code were you trying to parse?**

This seems to be an issue with barrel files, and was likely introduced by https://github.com/typescript-eslint/typescript-eslint/commit/133f622f38a286eac45288a9789d2ee529d5e582#diff-68b2b0b0d2d0ff1846b1114472008332R1606

```ts
export * from './app/foo';
```

**What did you expect to happen?**

No error.

**What actually happened?**

```
myrepo\src\public_api.ts
  0:0  error  Parsing error: Cannot read property 'name' of undefined
```

Running with `--debug` gives the following (clipped for brevity):

```
 eslint:file-enumerator Yield: public_api.ts +51ms
  eslint:cascading-config-array-factory Load config files for myrepo\src. +52ms
  eslint:cascading-config-array-factory Cache hit: myrepo\src. +6ms
  eslint:cli-engine Lint myrepo\src\public_api.ts +50ms
  eslint:linter Linting code for myrepo\src\public_api.ts (pass 1) +26ms
  eslint:linter Verify +8ms
  eslint:linter With ConfigArray: myrepo\src\public_api.ts +2ms
  eslint:linter Parsing error: Cannot read property 'name' of undefined
  eslint:linter TypeError: Cannot read property 'name' of undefined
    at Converter.convertNode (myrepo\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:1247:67)
    at Converter.converter (myrepo\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
    at Converter.convertChild (myrepo\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:147:21)
    at myrepo\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:203:32
    at Array.map (<anonymous>)
    at Converter.convertBodyExpressions (myrepo\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:202:14)
    at Converter.convertNode (myrepo\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:441:32)
    at Converter.converter (myrepo\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:72:29)
    at Converter.convertProgram (myrepo\node_modules\@typescript-eslint\typescript-estree\dist\convert.js:47:21)
    at Object.astConverter (myrepo\node_modules\@typescript-eslint\typescript-estree\dist\ast-converter.js:26:29) +9ms
```

**Versions**

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/typescript-estree` | `2.24.0` |
| `TypeScript`                           | `3.7.5` |
| `node`                                 | `13.9.0` |
| `npm`                                  | `yarn 1.22.1` |

**Comment by bradzacher** [comment]
I'm unable to repro this against master.

The line in the stack trace cannot cause this error, because it can only be hit if `node.exportClause` is not undefined.

https://github.com/typescript-eslint/typescript-eslint/blob/d12183883aa880810560ef7a2447d002f440ebc5/packages/typescript-estree/src/convert.ts#L1605-L1607

Could you please create a repro repo to help us investigate this?

**Comment by crfrolik** [comment]
Thanks for the response. I will work on trimming down my repo to a minimal example and get back to you.

**Comment by crfrolik** [comment]
It looks like `SyntaxKind.NamespaceExport` is undefined, which is causing the ` node.exportClause?.kind === SyntaxKind.NamespaceExport` expression to be truthy. Is this because I am using typescript 3.7 instead of 3.8?

**Comment by bradzacher** [comment]
interesting. I hadn't thought about that outcome.
that's definitely it. simple fix.

**Comment by bradzacher** [comment]
PR: #1751
Followup issue to make sure this doesn't happen again: #1752

**Comment by san4ezgig** [comment]
Could you please help, how to fix it without waiting new version? Upgrade to typescript 8.3.0 doesnt work

**Comment by jameschao** [comment]
My workaround was to downgrade to `2.23.0`.

**Comment by canpoyrazoglu** [comment]
In my case I'm using `create-react-app` which only includes `react-scripts` in this manner (and all the logic is handled by react-scripts), and I have no idea how to change version separately.

**Comment by ibc** [comment]
Just wondering, any ETA for a new version with the fix?

**Comment by bradzacher** [comment]
If you're stuck on ts 3.7, then downgrade to 2.23.0.
If you can upgrade to 3.8, then doing so will fix it.

I have a fix ready, but due to a glitch in azure, our per commit canary release is broken. So this will go out with our regular release schedule, listed on our readme.

**Comment by bradzacher** [comment]
@JamesHenry managed to fix the canary pipeline 🎉 

The fix for this is now released to the `canary` tag on npm.
Will be released to the main tag as per our regular release schedule.

**Comment by jmlew** [comment]
Any advice on how to downgrade when this is included with create-react-app? This is breaking all builds at the moment.

**Comment by bradzacher** [comment]
I don't know exactly how create-react-app does its dependency management, but you might just be able to install your own version of our packages?

Having a look at their eslint config, it has a peer dep on our packages, so you should just be able to bump the version yourself?

https://github.com/facebook/create-react-app/blob/6adb82a505eb06080dc11702a472f74131e95dc7/packages/eslint-config-react-app/package.json#L18-L19

Worst case, you can use a mechanism like yarn resolutions to force a certain version
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by jmlew** [comment]
Thanks. Confirming forcing version 2.23.0 manually as well as through Yarn resolutions for the following now works.

"resolutions": {
    "@typescript-eslint/eslint-plugin": "2.23.0",
    "@typescript-eslint/parser": "2.23.0",
    "@typescript-eslint/typescript-estree": "2.23.0"
  },

**Comment by mend3** [comment]
> Thanks. Confirming forcing version 2.23.0 manually as well as through Yarn resolutions for the following now works.
> 
> "resolutions": {
> "@typescript-eslint/eslint-plugin": "2.23.0",
> "@typescript-eslint/parser": "2.23.0",
> "@typescript-eslint/typescript-estree": "2.23.0"
> },

Confirmed that downgrading is now working, thanks!

`react: 16.12.0`
`npm: 6.13.4`

**Comment by canpoyrazoglu** [comment]
I've upgraded to TS 3.8 (even 3.9 nightly), no avail. Tried the resolutions, still no avail. I'm still getting the same error.

**Comment by netpoe** [comment]
> I've upgraded to TS 3.8 (even 3.9 nightly), no avail. Tried the resolutions, still no avail. I'm still getting the same error.

Same here, this happens when trying to import a dependency built with typescript in one of my components: 

```
../libraries/api/index.ts 1:7
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export type Maybe<T> = T | null;
```

my env: 

```
node v12.16.1
npm 6.13.4
yarn 1.22.4
typescript ^3.8.3
react: ^16.13.1
```

I also tried @mend3 resolutions 🤷‍♂ 

I'd apprecitate some signs of light here, an important project is stuck due to this.

**Comment by bradzacher** [comment]
> You may need an appropriate loader to handle this file type

@netpoe - this isn't an error related to our project. Loaders are a webpack concept, and we do not do anything with webpack. Nothing I can do to help here, sorry.

----

@canpoyrazoglu - hard to help without some more information. "The same error" is what error? What does your package.json look like? How are you using the tooling?
Help me to help you.

----

For anyone coming here - the fix is released on our `canary` tag on NPM.
So pin your dependency on the `canary` tag of our package.
You should be able to do this by simply updating the dependency in your package.json.
As mentioned before [yarn resolutions](classic.yarnpkg.com/en/docs/selective-version-resolutions) are a great way to do this, as they force a certain version, regardless of what dependencies of dependencies specify.

I don't know what your individual setups are, so I can't provide more concrete advice than that.

If you don't want to use our `canary` version, then pin your dependency on last week's version - 2.23.0, which is known good.


Make sure you restart vscode (or whatever IDE you are using) after you change your dependencies, as the IDE extensions _will not_ automatically switch to the new version.

### Otherwise it will be released to the latest tag on Monday morning, as per our standard release schedule.

https://github.com/typescript-eslint/typescript-eslint#package-versions
