### ISSUE TITLE
New rule: Avoid deprecated members

### ISSUE THREAD

**Issue by tom-sherman** [typescript-eslint/typescript-eslint#1927]
It's quite common, especially in the React typings, to have deprecated members as part of the API.

The tsd library has a great assertion for this: https://github.com/SamVerschueren/tsd/blob/master/source/lib/assertions/handlers/expect-deprecated.ts I would love if this could be transfered into a lint rule.

**Comment by bradzacher** [comment]
Please use a rule template next time. We set them up to help us keep the repo organised.

Have you tried https://github.com/gund/eslint-plugin-deprecation?
We try not to repeat work already done by the open source community.

**Comment by tom-sherman** [comment]
I'm not sure how I missed that when googling but it works perfectly, thanks for the tip!

**Comment by ecraig12345** [comment]
eslint-plugin-deprecation has some bugs and lacks feature parity with the TSLint deprecation rule, and the repo owner doesn't directly know about the plugin since it was forked from somewhere else, or have time to work on it (see https://github.com/gund/eslint-plugin-deprecation/issues/2). So it's *really* not "good enough" when migrating from TSLint.

Given those issues, is there any chance of reconsidering whether a deprecation rule could be included in typescript-eslint itself?

**Comment by bradzacher** [comment]
The reason that rule was added in a new repo instead of here was because it is essentially a direct port from an existing repo. We use a different licence (MIT licence vs their LGPL), and because IANAL; it was easier just put it there and link to it from our docs.

At the end of the day though - it's all just open source!
It being in this repo doesn't mean it'll be any better maintained.

The core maintainers here are all volunteers, so we rely upon the community to implement and drive the features and bug fixes that they want. Which is why we have a backlog of 203 issues right now.
I spend most of my time on community maintenance, and the remaining time I spend working on "big ticket" items that one-time contributors will struggle to complete.

My suggestion would be to submit a PR to that repo if it's something you rely on and need fixed sooner rather than later.

**Comment by ecraig12345** [comment]
I also noticed the LGPL license and had similar concerns. I'd be willing to submit a fix (and am actually trying to figure one out right now based on the old TSLint rule), but it's frustrating because I'm finding ESTree to have a very steep learning curve

**Comment by bradzacher** [comment]
I'm looking to write some documentation to help flatten the learning curve.

Its hard for me to do it by myself though as I'm knee deep in it all, so I don't know what's difficult to pick up.

If you could note down some of the problems and points you're running into, I can take them and flesh it out.

Feel free to ask me any questions here or on twitter.

**Comment by ecraig12345** [comment]
@bradzacher Thanks! After posting that comment I looked around a little and found https://astexplorer.net/ which uses acorn by default but can be switched to use the typescript-eslint parser. So that helps some.

**Comment by ecraig12345** [comment]
For anyone following, I have a PR out with a lot of fixes: https://github.com/gund/eslint-plugin-deprecation/pull/6
