### ISSUE TITLE
Detecting type of CallExpression

### ISSUE THREAD

**Issue by abhilashr1** [typescript-eslint/typescript-eslint#2037]
Hello, I am working on an eslint plugin to detect browser compatibility of expressions. There are a few plugins for the espree which detect static methods like `Object.assign({},{})` but not for instance methods like below, because it goes undetected because the linter does not know the type of the CallExpression. 
```ts
const someString = 'abc'; 
someString.trimStart();
```
I think this should not be a problem if the typescript-parser is used, since the type information can be detected. 

In my plugin, I use 
```ts
const service = ESLintUtils.getParserServices(context);
const checker = service.program.getTypeChecker();

 return {
      CallExpression: expr => {
              const node = service.esTreeNodeToTSNodeMap.get(expr)
              const nodeType = checker.getTypeAtLocation(node );
              const constrained = checker.getBaseConstraintOfType(nodeType);
              const type = constrained ?? nodeType;  
      }
...
}
```
but I still do not get the type information that I want. Ideally, the type information should be as a string like "Array", "String", .. Am I missing something?

**Comment by bradzacher** [comment]
You can explore TS's API types to see the types of things that are returned from their functions.
The API does not work with strings, because strings are vague and contextless.
Thus they return objects which can fully describe a type.

There are plenty of examples for rules that use type information in our project here, just look for rules with the 💭 icon in [the plugin readme](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules)

**Comment by abhilashr1** [comment]
I couldn't find anything that matched my use case, but thanks for sharing.
