### ISSUE TITLE
"It is advised not to mix package managers" warning. Can I use npm instead of yarn?

### ISSUE THREAD

**Issue by iwis** [typescript-eslint/typescript-eslint#2058]
I have installed Typescript using the `npm install typescript@3.7.5 --save-exact` command, and then I ran the `yarn add -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin` command.
I got the following warning:

> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

Can I use  the `npm install -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin` command instead of  `yarn add -D eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin` command as it is proposed in [How to use ESLint with TypeScript](https://khalilstemmler.com/blogs/typescript/eslint-for-typescript/) article?

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`      | 2.24.0 |
| `@typescript-eslint/parser`             |2.24.0|
| `@typescript-eslint/typescript-estree`  | 2.24.0 |
| `@typescript-eslint/experimental-utils` | 2.24.0 |
| `TypeScript`                            |3.7.5 |
| `node`                                  |12.10.0 |
| `npm`                                   | 6.10.3|

**Comment by iwis** [comment]
Sorry to report so many issues but I still have doubts how to use ESLint with TypeScript.

**Comment by bradzacher** [comment]
you can use any package manager you'd like.

Though as logged by yarn; switching between the two in the same project can and will lead to issues, so you should pick one and use just that one for your project.

We use `yarn` because it's what we're familiar with, and we have been using it for a while. But there's nothing that precludes you from using `npm`.

Some people also use package managers like `pnpm`. They should all work.
Each tool has positives and negatives, but most of the core experience is the same.

Just make sure you are consistent and use one or the other.

**Comment by iwis** [comment]
Thank you for the answer and all your support! It is clear for me.
