### ISSUE TITLE
[no-var-requires] Support non-top-level synchronous imports

### ISSUE THREAD

**Issue by fabiospampinato** [typescript-eslint/typescript-eslint#2141]
**Repro**

```TS
function foo () {
  const dep = require ( 'expensive-dep' );
  return dep.foo();
}
```

**Expected Result**

There's no ESM equivalent for non-top-level synchronous imports, and some dependencies are expensive to evaluate, so they should be only imported when they are needed. This is especially important for improving startup times.

As such I think there should be an option, possibly enabled by default, for allowing non-top-level synchronous imports like that.

**Actual Result**

Currently that triggers an error/warning.

**Comment by bradzacher** [comment]
How common is this throughout your codebase? I would assume that this is a rare thing, as opposed to a common thing.

Rare things that are not the usual are better left to the `eslint-disable` comments, so you can properly document why you're circumventing the lint rule.

If you add an option that allows it, then it means there's nothing stopping engineers doing it all the time.

At facebook we achieve this automatically for all imports with a build-time transform. I.e.
```js
const foo = require('foo');

function bar() {
  foo.bar();
}
// transforms to
function bar() {
  require('foo').bar();
}
```
That way you don't need to selectively choose to inline your requires, and you automatically optimise to remove dependencies that aren't used in certain cases.

**Comment by fabiospampinato** [comment]
Before addressing your points let me just say that ideally for my use case this lint rule should just be a little bit smarter, obviously, and although this is a bit of a rare occurrence overall, when considering only this single rule you can see that it doesn't seem to properly cover a big portion of the spectrum it is supposed to lint over.

> How common is this throughout your codebase? I would assume that this is a rare thing, as opposed to a common thing.

It's relatively rare for my use case, yes.

> Rare things that are not the usual are better left to the eslint-disable comments, so you can properly document why you're circumventing the lint rule.

The thing is this rule overall deals with inherently rare things (`require` calls), in modern codebases at least, so should the rule itself not exist? I'd argue if it exists it should attempt to cover the major use cases it lints over, and I think using `require` for deferring the synchronous import of a dependency seems about the only use case in modern codebases actually.

Additionally, but this is more my preferences than anything else, I actually have a rule that disallows eslint-disable comments, because the moment I start to use these comments everywhere to deal with rules shortcomings the linter kind of stops being only a lint-er but becomes a litter-er too, which I'd rather avoid.

> If you add an option that allows it, then it means there's nothing stopping engineers doing it all the time.

How about common sense? Like if the idea is that engineers might shoot themselves in the foot can't they do it already by disabling the rule entirely or something?

> At facebook we achieve this automatically for all imports with a build-time transform. I.e.

That might work for some cases but that approach has shortcomings too:

1. It can introduce bugs if the imported dependencies have side effects.
2. Now the code actually executes pretty differently at run time than how it is written, which could be confusing and a bit too magical for my likings.
3. I don't want to add babel to my compilation steps if at all possible.

**Comment by bradzacher** [comment]
> The thing is this rule overall deals with inherently rare things (require calls), in modern codebases at least, so should the rule itself not exist?

TBH this rule primarily exists as a teaching tool - to help stop people new to typescript from defaulting to the `require` syntax they're used to. Also as a migration tool to help ensure you remember to switch to `import` syntax as you migrate each file. As more and more pure JS codebases leverage babel for transpilation and migrate to the `import` syntax, this rule becomes less and less relevant.

I fully expect to be able to remove this rule at some point, once the JS ecosystem as sufficiently matured and has ubiquitous support for modules like TS does.

In the vast majority of TS codebases, this rule could definitely be _safely_ turned off and you would never see a regression. For example - we explicitly turn the rule off in this codebase:
https://github.com/typescript-eslint/typescript-eslint/blob/0e83d15781d56a852cf145a622b70ecf09addcc9/.eslintrc.js#L44
Because everyone that touches this codebase is proficient in TS (or are following the existing code style, which is all `import`s), and the only cases we have for `require`s are explicit and unavoidable:
https://github.com/typescript-eslint/typescript-eslint/blob/0e83d15781d56a852cf145a622b70ecf09addcc9/packages/parser/src/index.ts#L5-L6
Thus for us, the rule isn't required at all.

If you're in the same boat, then I think it's completely valid to turn off the rule entirely.  

> I actually have a rule that disallows eslint-disable comments

You should consider the [`eslint-comments/require-descriptions`](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/require-description.html) rule, to only allow disables that have comments on them. It requires ESLint v7 though.

Circumventing linting with a disable comment is something that is completely valid to do, but should be done sparingly and should be clearly explained whenever it's done.

> How about common sense? Like if the idea is that engineers might shoot themselves in the foot can't they do it already by disabling the rule entirely or something?

This is true, but this is lot easier to notice in a code review due to the large and obnoxious comment:

```ts
function foo() {
  // eslint-disable-next-line @typescript-eslint/no-var-requires: intentional inline require as this is an expensive dependency to pull in
  const mod = require('module');
  return mod.doSomething();
}
```

Without the comment, you're just relying on a reviewer to notice that the code is using `require` instead of `import`, which can be an easy thing to miss, esp in larger diffs.

Also one thing I've learned working at an org with thousands of engineers from all walks of life; common sense isn't common. Even the brightest of engineers can be complete idiots sometimes 😄 .

---

> It can introduce bugs if the imported dependencies have side effects.

IMO any module with an export should not have any side-effects as it creates refactoring nightmares and vectors for bugs. But you may have use-cases that make sense for it.

> Now the code actually executes pretty differently at run time than how it is written

Having worked with it for almost 2 years - you don't notice it. I didn't even know it was happening until I read an internal post about a really weird edge case with an erroneous top-level react hook that shouldn't have worked but worked because of the transform (this was "fixed" with a lint rule that reports top-level hooks; one that should have existed to help people learn hooks anyway).

> I don't want to add babel to my compilation steps if at all possible.

Understandable. Babel is a great tool for polyfilling etc. I don't know your use case so it's 100% valid to not want or need that (eg we don't use it here either).  
FB has a lot of custom babel plugins that do various simple optimisations on the codebase that most projects won't ever need.

**Comment by fabiospampinato** [comment]
> Thus for us, the rule isn't required at all.
> If you're in the same boat, then I think it's completely valid to turn off the rule entirely.

Good point, I may have gone a little overboard with these lint rules 🤔

> TBH this rule primarily exists as a teaching tool - to help stop people new to typescript from defaulting to the require syntax they're used to. Also as a migration tool to help ensure you remember to switch to import syntax as you migrate each file. As more and more pure JS codebases leverage babel for transpilation and migrate to the import syntax, this rule becomes less and less relevant.

Closing as adding support for what I'm asking for wouldn't be beneficial with this main use case in mind.
