### ISSUE TITLE
[dot-notation] Allow Square Bracket Notation if the Type Has an Indexer or the Any Type

### ISSUE THREAD

**Issue by ChrisGrohHS** [typescript-eslint/typescript-eslint#2205]
**Proposal**
Add settings to dot-notation to allow square bracket notation on types that have an indexer or the 'any' type. 

```json
{
  "rules": {
    "@typescript-eslint/dot-notation": ["error", { allowIndexerBracketNotation: true, allowAnyBracketNotation: true }]
  }
}
```

```ts
    interface MyInterface {
        name1: number;
        name2: number;
        [other: string]: number;
    }
    const foo: MyInterface;
    foo.name1 = 4;
    foo['bar'] = 5;

    const bar: any;
    bar['baz'] = 4;
```

**Comment by bradzacher** [comment]
why do you specifically want to use different notation between the two?

**Comment by ChrisGrohHS** [comment]
I prefer square bracket notation for conceptually indexing into a map/dictionary type rather than accessing a 'direct' property. 

Square bracket notation was required prior to TypeScript 2.2. You can find a lot of discussion in the link below. Many developers there seem to indicate wanting to require square bracket notation when accessing an indexer so it might be worth considering that as an option as well rather than my proposal to just allow either square bracket or dot notation. From that thread, you can also get a bit of additional checking against spelling issues on types that have both explicit properties and an indexer.

```ts
interface MyInterface
{
  doStuff():void;
  [index: string]: () => void;
}
let foo: MyInterface;
foo.doStufff();// No error
```

https://github.com/microsoft/TypeScript/issues/12596

**Comment by bradzacher** [comment]
> you can also get a bit of additional checking against spelling issues on types that have both explicit properties and an indexer

How so? These two `foo.doStufff` and `foo['doStufff']` both will not error in TS, and you get autocomplete for both of them:
![image](https://user-images.githubusercontent.com/7462525/84524014-17a14580-ac8e-11ea-9e3a-c57bb4653789.png) ![image](https://user-images.githubusercontent.com/7462525/84524023-1d972680-ac8e-11ea-80fe-3bf58d952d0c.png)

---

I disagree with this style pretty whole heartedly, because I think you should never be using array index notation to access using a string literal.

If you have a known name, then you know the property should exist, so it should be hoisted onto the interface definition.

I.e. instead of
```ts
interface Foo {
  bar: () => void;
  [key: string]: () => void;
}
declare const foo: Foo;

foo.bar();
foo['baz']();
```
do
```ts
interface Foo {
  bar: () => void;
  baz: () => void;
  [key: string]: () => void;
}
declare const foo: Foo;

foo.bar();
foo.baz();
```
if you expect the property might not exist, you can then also provide safer typings for this known property:
```ts
interface Foo {
  bar: () => void;
  baz?: () => void;
  [key: string]: (() => void) | undefined;
}
```

This makes it _much_ clearer to your consumers that they can pass in this property (via viewing the interface definition, or via autocomplete) whilst still maintaining full type safety.

Also note that this style of defining mapped types is also much safer,  as it enforces that you ensure the property exists before consuming it.

**Comment by ChrisGrohHS** [comment]
> two `foo.doStufff` and `foo['doStufff']` both will not error in TS, and you get autocomplete for both of them:

This was in the context of changing my original proposal to also have an option to require square bracket notation when using an indexer rather than just allow it. So foo.doStufff would raise a linter issue.

> If you have a known name, then you know the property should exist, so it should be hoisted onto the interface definition.

I might have a known value in my code while the interface is defined in a library. 

This proposal also allows consistent access to properties instead of having to mix square bracket indexers with dot notation. 

```ts
foo[dynamicKey]();
foo.key();
foo['dashed-key']();
```
vs
```ts
foo[dynamicKey]();
foo['key']();
foo['dashed-key']();
```

**Comment by bradzacher** [comment]
> This proposal also allows consistent access to properties instead of having to mix square bracket indexers with dot notation

Sure, for that specific object. But then your codebase becomes inconsistent and you can have inconsistencies within the same codeblock as you work with both object types and mapped types.

IMO is the bigger issue - this places a cognitive load on the engineer as they have to think about what style to use to reference a property so they can correctly satisfy the linter for no reason other than stylistic preference.  
This is the opposite of what a lint rule should do - lint rules are supposed to reduce cognitive load and make coding easier.

Ultimately there is no functional difference between the two - it doesn't matter if you know the keys ahead of time or not - it's still a plain old javascript object.

If you're looking to signal unsafety due to dynamic keys, then changing the value type of the mapped type to include `undefined` is much better, as you get actual TS errors and flow-control analysis of the types instead of just an empty syntactic check.

In the case of library types, then it's trivial to use a library like [`patch-package`](https://www.npmjs.com/package/patch-package) to change the types locally for your project.
