### ISSUE TITLE
Missing type information while linting

### ISSUE THREAD

**Issue by elitvinchuk** [typescript-eslint/typescript-eslint#2211]
Hello! First of all thank you for great work you're doing (and documentation you've provided 😉)!

We've ran into OOM issues while using TypeScript in monorepo. So I decided to get back to the manual once again and investigate it candidly. I've found the issue and workaround https://github.com/typescript-eslint/typescript-eslint/issues/1192 and created minimal example to make informed decision about whether or not "Linting with Type Information" is needed. 

![image](https://user-images.githubusercontent.com/1371092/84577495-600f4f00-adc5-11ea-9245-146cea03e087.png)

But unfortunately, I didn't find typed lint errors about assigning string to a number. The error highlight I get is from TS language service. So what is considered as type information? Given the language service is running in background in most modern IDEs, does it make sense to provide projects' tsconfigs to TypeScript ESLint parser?  Especially if we're running `tsc -b` on CI along with eslint. Or am I missing something?

Thank you!

**Repro**
This is [minimal repo](https://github.com/elitvinchuk/eslint-typescript) reproducing the issue.

```javascript
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    tsconfigRootDir: __dirname,
    project: ['./tsconfig.json'],
  },
  plugins: [
    '@typescript-eslint',
  ],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
  ],
};
```

```JSON
{
  "compilerOptions": {
    "esModuleInterop": true,
    "pretty": true,
    "strict": true,
    "target": "esnext",
    "noEmit": true
  },
  "include": [
    ".eslintrc.js",
    "src"
  ]
}
```

**Expected Result**
ESLint highlights "not assignable" errors. 

**Actual Result**
It doesn't

**Additional Info**
No exceptions

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `3.2.0` |
| `TypeScript`                | `3.9.5` |
| `ESLint`                    | `7.2.0` |
| `node`                      | `14.4.0` |
| `npm`                       | `6.14.4` |
|`yarn`|`1.22.4`|

**Comment by bradzacher** [comment]
You're misunderstanding what we do.

Our tooling does not reproduce the errors that typescript provides. That would be silly - typescript already provides those errors.  
Instead, our tooling exists to augment typescript's built in checks. We [provide lint rules](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules) which consume the type information to do improved static analysis of your codebase.

Type information is just a name for the data that is provided via typescript's compiler APIs. It's the data that typescript itself uses to do its built in checks on your codebase.

By providing us with your tsconfig, you're enabling us to use the typescript compiler API to analyse your code to generate the type information.

ESLint as it stands is a single file static analysis tool. It is very powerful, and can do really interesting analysis of code. But it's limited by the fact that it operates only on a single file. It's also limited by the fact that it doesn't understand typescript type annotations, so it cannot easily do things like infer the type of a variable, or the signature of a function. 

TypeScript, on the other hand, analyses your entire codebase, and it understands type annotations - but it has no framework for building out custom checks.

So by marrying TypeScript and ESLint together; 
- you benefit from the vast ecosystem that exists for ESLint
- you benefit from the architecture and infrastructure provided by ESLint for building rules that analyse files
- you can remove the drawbacks of ESLint because TypeScript can give you detailed information about the type of anything anywhere.

**Comment by elitvinchuk** [comment]
Hello @bradzacher ! 

Thank you so much for this detailed explanation. Even though I asked the wrong question (about propagating TS errors via ESLint, but meant more generic benefits of types in linting), you've managed to cover the real one :)

I've tested linting with and without type information based on [lint rules 💭](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules) and witnessed the difference. It's crear now, moreover it's total hindsight is 20/20 situation.

Thanks again, and wish you success on this mission ;)
