### ISSUE TITLE
Rule proposal: detect and warn about circular imports

### ISSUE THREAD

**Issue by avocadowastaken** [typescript-eslint/typescript-eslint#224]
Currently I'm using [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) with [eslint-import-resolver-typescript](https://github.com/alexgorbatchev/eslint-import-resolver-typescript), but it works really slow. 

And I was thinking that creation of dependency tree with TS project (that already passed to `@typescript-eslint/eslint-parser`) must be much faster than file system scanning.

See also: [tslint-no-circular-imports](https://github.com/bcherny/tslint-no-circular-imports).

**Comment by jtbandes** [comment]
I've been using [circular-dependency-plugin](https://github.com/aackerman/circular-dependency-plugin), but it's not compatible with `"importsNotUsedAsValues": "preserve"`. When this setting is enabled circular imports that are used as types only are treated as errors, but with the setting disabled they are not. And `import type` cycles are never treated as errors. If a lint rule is added for this I would hope it would have configuration options about whether or not to raise errors on type-only imports.

**Comment by krzysztof-grzybek** [comment]
@JoshuaKGoldberg To implement this feature, we need to preserve the state between linted files - it's needed to build the dependency graph between the modules. 
`create` function is called once per file, so we can't keep the state there, in the closure.
It seems that the only possible way of doing that is to keep the state object outside of the object passed to the `createRule` function. Please have a look at the pseudo code below.

Is this an acceptable way of doing that? I wonder if there's some case where we would start linting with stale state (with some records from previous linting).

```
const graph = new Map(); // state - keeps track of dependencies

export default createRule({
  name: 'no-circular-dependencies',
// ....
  create(context) {
    return {
      ImportDeclaration(node): void {
         graph .set('fileName', 'importPath'); 
    }
}
```

**Comment by bradzacher** [comment]
@krzysztof-grzybek Your comment is actually roughly how the [`import/no-cycle`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md) lint rule works.

Their lint uses the AST from the current file to determine its dependencies, then it does an out-of-band parse on each dependency to determine its dependencies, and so on.

However - we don't need to store any state because we have access to type information.

We can rely on the fact that TS has already analysed every file and knows the dependency graph of the project.
So instead of manually building it - we can just ask TS for the information.

This is the basis of this proposal - the `import/no-cycle` lint rule is slow because it has to parse dependencies itself but we could potentially be faster because TS has already got the information.

**Comment by ko22009** [comment]
up

**Comment by bradzacher** [comment]
@rubiesonthesky

```ts
// fileA.ts
import { b } from './b';

export const a = b;

//  fileB.ts
import { a } from './a';

export const b = a;
```

What's the result of a 3rd module doing `import { c }  from './b';`?

The tl;dr is that cycles in the dependency graph increase complexity greatly. It makes it hard to reason about code because you need to think about and understand the way in which the underlying ESM infra works.

And that's assuming your build tool / bundler transpilers your code in such a way that it works how ESM says it should.

Why take on that complexity when the vast, vast majority of cases could be refactors to remove the cycle? Moving a variable or a function to a new module can break the cycle and restore your dep graph to be an acyclic graph and reduce complexity.

**Comment by kirkwaiblinger** [comment]
@rubiesonthesky 

> * runtime error (this is something that is saw, but I’m not sure if the exact circumstances why and how)

1. ReferenceError will (probably) occur in Brad's example. (This is what has happened in my experience with webpack.)

1. You can also easily overflow the callstack
    ```ts
    // Assert.ts
    import { reportAssertion } from './Report.ts';

    export function assert(x) {
       if (!x) reportAssertion();
        throw new Error();
    }

    // ReportAssertion.ts
    import { assert} from './Assert.ts';

    export function reportAssertion() {
        try {
           throw new Error(); // suppose the network is not available or something
        } catch {
           // should have reported
           assert(false);
        }
    }

     // main.ts

    assert(false); // <-- (if reporting crash fails) Uncaught RangeError: Maximum call stack size exceeded
   ```
   You could also do this within a file with 
   ```ts
   function f() {
      g();
   }

   function g() {
       f();
   }
   
   f() // Uncaught RangeError: Maximum call stack size exceeded
   ```
   but it's a lot easier to write by accident across circularly imported, maybe even distantly related files

**Comment by bradzacher** [comment]
The real value IMO isn't 2-module cycles like you always see in examples. Those cases are always simple and often are easy to spot by hand.

The more interesting cases are when you've got a cycle where the path is 3 or more. I've seen cases where there are a dozen modules in the cycle - nearly impossible for a human to see.

**Comment by kirkwaiblinger** [comment]
The other example that comes to mind is 
```ts
// fileA.ts
import { something } from 'fileB.ts';
console.log('side effect that needs to happen first');

// fileB.ts
import { somethingElse } from './fileThatTransitivelyImportsFileA.ts';

console.log('side effect that needs to happen second');

// main.ts
// transitively import fileA or fileB

// order of console logs can be changed by addition or removal of files in cycle 
```

There is of course more than one code smell here, but... it happens in the wild.

**Comment by JoshuaKGoldberg** [comment]
Copying from https://github.com/typescript-eslint/typescript-eslint/pull/8965#issuecomment-2187923184: on the one hand, this rule would be _really_ useful, and it makes a lot of sense to have in our plugin. On the other hand, per https://github.com/typescript-eslint/typescript-eslint/issues/224#issuecomment-1116455239 & https://github.com/eslint/rfcs/pull/102, there isn't a straightforward way to set up the graph creation system in a way that's both performant and works well with the various ways ESLint might be run.

We've talked about this internally and think this rule would be better off in a separate plugin from typescript-eslint for now. It can be iterated on there more rapidly & not be bound by our project's limited flexibility & staffing. 

Closing this issue for now 😞. But, if someone does figure out how to overcome the performance limitations, please let us know! We'd be happy to reopen.
