### ISSUE TITLE
Parsing error: Cannot read property 'map' of undefined on import when a function has an array return type

### ISSUE THREAD

**Issue by mwiedmann** [typescript-eslint/typescript-eslint#2446]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```TS
// some export in a file1.ts, it doesn't matter what you export
export type Foo = number

// file2.ts, import from file1.ts and have an array return type on a function.
// The [sometype] return type seems to be the key to causing the issue.
import { Foo } from './test-import' // This line has error: "Parsing error: Cannot read property 'map' of undefined"

export function foo(id: Foo): [number] { // The [number] or any array return type seems to be the cause
  return [id]
}
```

**Expected Result**
I expected it not to fail.

**Actual Result**
Parsing error: Cannot read property 'map' of undefined

**Comment by bradzacher** [comment]
What version of our tooling are you using?

**Comment by mwiedmann** [comment]
"@typescript-eslint/eslint-plugin": "4.0.0",
 "@typescript-eslint/parser": "4.0.0",
"eslint": "7.7.0",
  "typescript": "4.0.2",

**Comment by bradzacher** [comment]
TS4.0 included a breaking change to their AST shape which we've properly handled since our `v3.3.0` release.
If you've got v4 of our packages installed and you're still seeing errors, likely you also have older version(s) of our tooling installed alongside the new versions.

See discussion in: https://github.com/typescript-eslint/typescript-eslint/issues/2260
Packages like `react-scripts` have their own dependency versions, which you will have to use resolutions to bypass.

**Comment by mwiedmann** [comment]
Yes. Confirmed that we did have an older version of the parser being pulled in by another package. Terribly sorry about this. Working fine now.

**Comment by SCWR** [comment]
"@typescript-eslint/eslint-plugin": "4.1.0",
"@typescript-eslint/parser": "4.1.0",
"eslint": "6.8.0",
"typescript": "4.0.2",

Hello, I am getting an error in eslint 6.8.0
Parsing error: Cannot read property 'map' of undefined
