### ISSUE TITLE
Rule proposal: Enforce `types` or `typings` field naming in package.json

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#248]
TypeScript supports using either a [`"types"` and `"typings"` field in package.json](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) (they are synonymous) to declare the path to the TypeScript type definitions. I would like to enforce one naming in my projects for consistency. I realize this is not related to a JS file, but it's very much related to TypeScript projects, so I'm hoping it will still be accepted.

**Comment by bradzacher** [comment]
Sounds reasonable, however the problems I see with it are:
1) our parser does not support json files:
```
typescript-eslint/packages/eslint-plugin/package.json
  2:8  error  Parsing error: ';' expected
```

2) you'd have to manually adjust your eslint setting to include json files i.e.
```
$ eslint src package.json --ext=".ts,.tsx,.json"
```

They are hurdles to overcome, but still doable.

**Comment by j-f1** [comment]
Could this be a better fit for something like [`npm-package-json-lint`](https://www.npmjs.com/package/npm-package-json-lint)?

**Comment by sindresorhus** [comment]
Alternatively, we could try to get this into TypeScript itself as an option in `tsconfig.json`, but that might be harder.

**Comment by sindresorhus** [comment]
> Could this be a better fit for something like [`npm-package-json-lint`](https://www.npmjs.com/package/npm-package-json-lint)?

It would also fit there, yes, but it's not a replacement. I and most people, I'm sure, are not willing to add yet another linter (and all of the baggage that entails) just for that.

**Comment by sindresorhus** [comment]
> 1. you'd have to manually adjust your eslint setting to include json files i.e.

The new ESLint config format will allow setting extension in the config itself: https://github.com/eslint/rfcs/pull/9/files#diff-4fab19e15273179c525fc49a689b73a5R475

**Comment by JoshuaKGoldberg** [comment]
You know, it's been three and a half years since this was posted, and there've only been two 👍s. Even with the new config format (which will take a while to be rolled out to a majority of users), adding this one package.json rule will add some complexity to our configs.

I'm going to go ahead and say this should be in [npm-package-json-lint](https://www.npmjs.com/package/npm-package-json-lint) or another plugin. If it gains significant popularity & use there, then we can consider adding it here.

Thanks for the discussion, all!
