### ISSUE TITLE
[@typescript-eslint/no-unnecessary-type-assertion] Puzzling fix in vue ts project

### ISSUE THREAD

**Issue by eightHundreds** [typescript-eslint/typescript-eslint#2591]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

https://github.com/eightHundreds/eslint-vue-ts--typescript-eslint-no-unnecessary-type-assertion-issue
1. git clone
2. npm i
3. npx eslint ./src/components/tmp.vue --fix

**Expected Result**

```
<script lang="ts">
/* eslint-disable class-methods-use-this */
export default class Cmp {
  get a() {
    const list: Array<string> = [];
    return list;
  }

  async mounted() {
    this.a as Array<string>;
  }
}
</script>
```

**Actual Result**
```
<script lang="ts">
/* eslint-disable class-methods-use-this */
export default class Cmp {
  get a() {
    const list: Array<string> = [];
    return list;
  }

  async mouna as Array<string>;
  }
}
</script>
```

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.2.0` |
| `@typescript-eslint/parser`        | `4.2.0` |
| `TypeScript`                       | `3.9.3` |
| `ESLint`                           | `7.9.0` |
| `node`                             | `10.14.2` |

**Comment by bradzacher** [comment]
You ticked the box saying you've upgraded to the latest version of our tooling, but you've listed v2.33.0 as your version. This version is 4 months old.............

**Comment by eightHundreds** [comment]
> You ticked the box saying you've upgraded to the latest version of our tooling, but you've listed v2.33.0 as your version. This version is 4 months old.............

I upgraded and the problem still exists

**Comment by bradzacher** [comment]
> I upgraded and the problem still exists

You should always try the  latest version before filing an issue to ensure that it hasn't been fixed. We release every week, so there's a chance the latest version has fixed an issue.

----

This is occurring because the lint rule uses the typescript nodes to do the fixes.

https://github.com/typescript-eslint/typescript-eslint/blob/39c45f360993f9689a8460dfe4735fc4ef2331fa/packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts#L242-L250

`vue-eslint-parser` alters the locations information for every node it produces within a `script` tag, but it doesn't know about the typescript nodes, so their range information is wrong. The fix is being applied as if there was no `script` tag.

Simple fix - happy to accept a PR.

**Comment by thomasmichaelwallace** [comment]
Happy to pick this up-
