### ISSUE TITLE
[no-unsafe-assignment] causes eslint to run very slowly

### ISSUE THREAD

**Issue by ukch** [typescript-eslint/typescript-eslint#2612]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

I am trying to convert from a tsconfig/tslint setup to the eslint equivalent, but where tslint used to be able to lint the whole codebase in about 2-3 seconds, eslint is currently taking about 19 seconds per individual file.

Running eslint on an individual file with `TIMING=1` yields this result:

```
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
@typescript-eslint/no-unsafe-assignment |  6302.518 |    97.7%
@typescript-eslint/no-unsafe-return     |    25.425 |     0.4%
@typescript-eslint/no-floating-promises |    22.079 |     0.3%
import/order                            |    14.589 |     0.2%
@typescript-eslint/no-misused-promises  |    10.006 |     0.2%
jsdoc/check-alignment                   |     8.062 |     0.1%
react/jsx-no-bind                       |     6.875 |     0.1%
jsdoc/check-indentation                 |     5.433 |     0.1%
react/no-direct-mutation-state          |     4.058 |     0.1%
react/no-deprecated                     |     3.991 |     0.1%
```

As you can see, the `no-unsafe-assignment` rule is about 400 times slower than the next slowest rule, and a lot slower than the equivalent rule in tslint (`no-unsafe-var`). As it is, I will have to disable this rule for the time being.

**Expected Result**

The generated eslint config to operate at approximately the same speed as the tslint equivalent

**Actual Result**

eslint is much slower. `no-unsafe-assignment` is causing 97% of the lag.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.2.0` |
| `@typescript-eslint/parser`        | `4.2.0` |
| `TypeScript`                       | `3.9.6` |
| `ESLint`                           | `6.8.0` |
| `node`                             | `13.4.0` |

**Comment by glen-84** [comment]
See https://github.com/eslint/eslint/issues/13695.

**Comment by bradzacher** [comment]
Typescript computes type information lazily. This means that the first rule to access type information will have a disproportionately higher runtime than other rules using the same information.

On top of that (as @glen-84 points out) eslint is kind of naive in its approach to timing, and it times bootstrapping and parsing times in the first rule run.

This makes it very difficult to accurately time individual lint rule performance.

Additionally each rule looks for different things. `no-unsafe-assignment` looks at all of your assignment expressions, property assignments, jsx attributes, and spreads. OTOH `no-unsafe-return` just looks at return statements and bodyless arrow functions.

The more things a rule inspects, the more type information it consumes and thus the slower it will be.

This can also be very dependent on your project itself. For example a react project is going to be hit hard by `no-unsafe-assignment` because all jsx attributes are checked, and there aren't many returns in comparisons.

Ths same goes for rules like `no-floating-promise`. If you have a lot of floating expressions, that rule is going to be slow, but if you don't have many it'll be speedy.

---

For most projects the parse time should very, very far outweigh the rule run times, so it's not something that's mentioned in any of the docs explicitly. There is a general note about performance in our getting started guide: https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#performance

---

As for solutions... There aren't any really.

The only way to speed a rule up is to audit a lint rule to try and short-circuit before it accesses type-information.

If someone wants to do that, then I'd be happy to accept a PR!!!
However, in most cases this sort of work would likely shave _maybe_ a few hundred milliseconds off the run. It's very low impact work compared to the amount of effort it would take.

As an aside. In the past I've toyed with shifting the workload to the parser instead, by modifying the parser and making it ask TS for the type information ahead of time. However this doesn't actually result in a perf win - first it only moves the workload around, and second it ultimately slows the lint run down because it will access more type-information than what is required by the rules.

Maybe there is a solution that I haven't thought of? If anyone is particularly good at performance and profiling - happy to chat!
