### ISSUE TITLE
Specify custom typescript with ParserOptions

### ISSUE THREAD

**Issue by yoyo930021** [typescript-eslint/typescript-eslint#2660]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

We need to set special typescript when sometimes.
Like #2127 , yarn PnP support, monorepo.

We can add a option like:
```javascript
module.exports = {
  root: true,
  parserOptions: {
    parser: '@typescript-eslint/parser',
    typescript: require('typescript'), // or `instance`
    project: './tsconfig.json',
    sourceType: 'module'
  },
  plugins: [
    '@typescript-eslint',
  ]
};
```

Many packages have same design.
https://github.com/TypeStrong/ts-loader#instance
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#typescript-options

I'm willing to implement this feature if the maintainer has no problem with it.

**Comment by bradzacher** [comment]
This won't work the way you think it will.

Plugins use tools, enums and utils from typescript (and libraries like our utils package or tsutils).

All of these pieces just import typescript. If there's any discrepancies between versions etc, it will cause undefined behaviour in the lint rules.

You would be much better off using something like an npm alias to use a completely different typescript package so that every piece of the lint run uses exactly the same package.

**Comment by yoyo930021** [comment]
You're right.
It seems difficult to use different TypeScript versions in monorepo.
