### ISSUE TITLE
[naming-convention] allow treating quoted properties differently

### ISSUE THREAD

**Issue by ab-pm** [typescript-eslint/typescript-eslint#2761]
This is essentially a duplicate of #1483, which unfortunately was closed without a complete solution.

We have a large code base that used the camelCase rule. We have the convention that whenever objects are used as key-value dictionaries not as records, properties would be quoted (string literal instead of identifier syntax). The camelCase rule would not complain about snake_case or PascalCase property names then. This is used in a lot of places (custom headers, database access layer, application-specific logic, external protocols, and more…) so that **whitelisting** allowed names **is not an option**.

Since we don't want to get rid of identifier linting completely, and cannot achieve the desired behavior with the naming-convention rule, we're currently blocked from upgrading typescript-eslint - very dissatisfying.

I'm not suggesting to just add a `ignoreStringKeys` option or even to enable it by default.
What is needed is **a new `selector`** to distinguish properties that are IdentifierNames from properties that are StringLiterals. For [completeness](https://tc39.es/ecma262/#prod-LiteralPropertyName), a third category might match properties that are NumericLiterals. I imagine this as an extension to `propertyDefinition` from https://github.com/typescript-eslint/typescript-eslint/issues/2244#issuecomment-649015119, which would become a group selector itself.
However, this could actually be a separate dimension for the matcher, like `modifiers` and `types`. While for my concrete use case the distinction is only necessary in object literals (not interface/class member declarations) and not (rarely, actually) for methods, it would provide more flexibility. What do you think?

**Comment by bradzacher** [comment]
Originally the problem with solving this was that it's actually a really, really, really difficult thing to catch 100% of the time because the rules for what is a valid "identifier" in JS is [very, very complicated](https://github.com/estools/esutils/blob/a825f91fd1d1e3a9fff84227cb06c011d8a0b9e8/lib/code.js#L39-L44).

However since then, we learned that (thankfully) TypeScript exposes its functions which let it do this check, and we have got a usage of it this in the plugin:
https://github.com/typescript-eslint/typescript-eslint/blob/98ab010fb7fca884984bb4200fd806ecee8071b6/packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts#L37-L53

---

### What solution would I accept for this rule?

I would be happy to accept a modifier for the `property` selector.
For example `requires-quotes` which denotes when the property name _must_ be quoted.

Why a modifier which detects required quotes vs a selector that matches any quoted name?

I don't agree that all quoted names should ever just be ignored.
That is not the way to enforce a naming convention because it means that people can _very_ easily create names that break your convention solely because they used quotes.

A modifier that only is applied when quotes are _required_ allows you to choose to ignore these property names specifically, because they're clearly written this way on purpose.
