### ISSUE TITLE
[consistent-type-imports] add option to autofix to a single type import

### ISSUE THREAD

**Issue by TwitchBronBron** [typescript-eslint/typescript-eslint#2769]
I'd like to propose a third option for the [consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/v4.4.1/packages/eslint-plugin/docs/rules/consistent-type-imports.md) rule's `prefer` property. It currently has two options for `prefer`: `type-imports` and `no-type-imports`. However, it would be very useful to have a third option: 
 - **type-imports-combine**: enforce all type-only imports to be `import type` _except_ when there's already a concrete import from that same file, in which case prefer to combine the imports into a single statement. 

Here's an example: 

*Logger.ts*
```typescript

export class Logger implements ILogger {
    log(message: string) {
        console.log(message);
    }
}
export interface ILogger {
    log(message: string);
}
```

*main.ts*
#### `prefer: 'type-imports'`
```typescript

import { Logger } from './Logger';
import type { ILogger} from './Logger';
import type { SomeInterface } from './SomeInterface';
```

#### `prefer: 'no-type-imports'`
```typescript
import { ILogger, Logger } from './Logger';
import { SomeInterface } from './SomeInterface';
```

#### `prefer: 'type-imports-combine'`
```typescript
import { type ILogger, Logger } from './Logger';
import type { SomeInterface } from './SomeInterface';
```

**Comment by bradzacher** [comment]
Happy to accept a PR

**Comment by olee** [comment]
Please please please do this!
Just enabled the rule for me as well just to find out it would split all the mixed import lines into multiple which makes this unusable for me.
Maybe I will also try to do a PR for this one, but I'm not sure I can do it.

**Comment by olee** [comment]
Ok I think I got it working - this should prevent the rule from triggering when there are mixed imports

**Comment by marcus-sa** [comment]
Any updates on this?

**Comment by bradzacher** [comment]
With any issue in opened in this project - it either has a visible progress in the form of an attached PR, or it has no progress.

We are a community run project. The **volunteer** maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues *will not progress* unless a member of the community steps up and **champions** it.

If this issue is important to you - consider being that champion.

If not - please just subscribe to the issue and wait patiently.
Commenting asking for status updates does not bump issue priority in any way and just serves to spam ***everyone*** subscribed to the issue.

**Comment by merrywhether** [comment]
With the release of TS 4.5, it seems like updating the auto-fixer to use inline type annotations (skipped in https://github.com/typescript-eslint/typescript-eslint/pull/4237 due to complexity) addresses the underlying issue here as you'd get:

```
import { type ILogger, Logger } from './Logger';
import { type SomeInterface } from './SomeInterface';
```

**Comment by bradzacher** [comment]
yup - with 4.5 we can now autofix to use inline types to combine the imports.
the fixer code is super complicated which is why I skipped it. There's a lot of branches in the fixer, and the code isn't the cleanest - so it's a non-trivial amount of work to build such an option.

It's worth noting that with support for 4.5's inline type qualifier in #4237 - we don't *explicitly* need fixer support in the rule. Instead a rule like [`import/no-duplicates`](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/no-duplicates.md) could be enhanced to merge imports as inline imports.

Eg the fix would be

```ts
// original
import { ILogger, Logger } from './Logger';

// @typescript-eslint/consistent-type-imports
import type { ILogger } from './Logger';
import { Logger } from './Logger';

// import/no-duplicates
import { type ILogger, Logger] from './Logger';
```

OFC it'd be great if we had support in our rule to cut-out the middleman.

**Comment by merrywhether** [comment]
Should there be a new issue to reflect that work and replace this one? I'm looking at the fixer logic now to see just how hard the augmentation would be.

**Comment by bradzacher** [comment]
no we can keep this one - i've update this issue to match.
it was almost correct already anyways!

**Comment by merrywhether** [comment]
Should it be 
```
import type { SomeInterface } from './SomeInterface';
```
like the description or
```
import { type SomeInterface } from './SomeInterface';
```

The second version is more accommodating to additional imports from the same source with fewer changes necessary?

**Comment by bradzacher** [comment]
IMO the former.
It's cleaner as it allows tools to ahead-of-time optimise the import away instead of having to interrogate all the imports to determine if it includes a type-aware import.

eg compilers can do
```diff
- import type { SomeInterface } from './SomeInterface';
```

instead of
```diff
// (1)
  import {
-   type SomeInterface
  } from './SomeInterface';
// (2)
- import {} from './SomeInterface';
```

This also aids with static analysis tools which might look for runtime references.

**Comment by ocket8888** [comment]
IMO, it depends on the imports themselves. Currently I have a rule enforcing no duplicate imports, which means I can't use the `consistent-type-imports` rule, because many packages have mixed types and values. For instance, if a package "src/foo" exports the type `Foo` and the value `Bar`, using `consistent-type-imports` would mean that any other module that wants to import both would need to import them like:
```typescript
import type { Foo } from "src/foo";
import { Bar } from "src/foo";
```
which duplicates imports. What I'd like to be able to do - independent of supporting inline `type` - is
```typescript
import { Foo, Bar } from "src/foo";
```
because it recognizes that at least one import is a value so it cannot be an `import type`.

But to get back on-topic, the rule should, IMO prefer
```typescript
import type { Foo } from "src/foo";
```
over 
```typescript
import { type Foo } from "src/foo";
```
because all imports are types, but should not raise an issue (optionally?) if one has
```typescript
import { Bar, type Foo } from "src/foo";
```
because at least one import is not a type.

**Comment by bradzacher** [comment]
> Currently I have a rule enforcing no duplicate imports, which means I can't use the consistent-type-imports rule, because many packages have mixed types and values

Why not? Why can't your duplicate import rule handle this and fix it appropriately?
Lint rules are purposely isolated and unaware of one another and aren't expected to output fixes that won't report in another rule.
For example - if a rule fixes a class method to a class property - it doesn't need to insert a `;` with the fix as it can assume the user will have a rule to fix that separately.

If you're using ESLint's core `no-duplicate-imports` rule, then you're going to be in for a bad time - you should look to a decent version like `import/no-duplicates` (#4238)

----

> Also, this probably isn't the appropriate place to mention this, but Angular uses type annotations for dependency injection, so even if FooService is only used as a type, it needs to be imported as a value for the compiler's sake, which consistent-type-imports doesn't (and probably can't) recognize.

This is supported - if you use type-aware linting.
If you don't use type-aware linting then our analysis tools can't determine if you've got all the directive options turned on or not.
But that is very off topic for this issue.

**Comment by ocket8888** [comment]
Oh, I didn't realize there was `@typescript-eslint/no-duplicate-imports` - that does appear to support mixed type and value imports. I still can't use it with `consistent-type-imports` though, because "`No suitable injection token for...`".

> If you don't use type-aware linting...

I'm fairly sure I am, my .eslintrc.json:
```json
{
	"root": true,
	"ignorePatterns": [
		"projects/**/*"
	],
	"overrides": [
		{
			"files": [
				"*.ts"
			],
			"parserOptions": {
				"project": [
					"tsconfig.json",
					"e2e/tsconfig.json"
				],
				"createDefaultProgram": true
			},
			"extends": [
				"plugin:@angular-eslint/ng-cli-compat",
				"plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
				"plugin:@angular-eslint/template/process-inline-templates"
			],
			"rules": [ "hundreds of rules" ],
		}
	]
}
```
I'm pretty sure the Angular configs being extended use/require `@typescript-eslint/parser` (otherwise I don't know what that's doing in my `devDependencies`) but it still can't tell that some types need to be imported as values.

**Comment by bradzacher** [comment]
again - that is off-topic, please file a new issue.

**Comment by shpakkdv** [comment]
Any updates?

Could you add the same option?

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-exports.md

**Comment by bradzacher** [comment]
With any issue in opened in this project - it either has a visible progress in the form of an attached PR, or it has no progress.

We are a community run project. The **volunteer** maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues *will not progress* unless a member of the community steps up and **champions** it.

If this issue is important to you - consider being that champion.

If not - please just subscribe to the issue and wait patiently.
Commenting asking for status updates does not bump issue priority in any way and just serves to spam ***everyone*** subscribed to the issue.

**Comment by bradzacher** [comment]
The `fixStyle: "inline-type-imports"` option was added in #5050 (v5.43.0).
https://typescript-eslint.io/rules/consistent-type-imports/#fixstyle
This will allow the rule to fix the imports to inline type specifiers.

This won't deduplicate your import declarations, however.

If you want then, then you can then use a rule like `import/no-duplicates` with the `prefer-inline: true` to collapse the imports (v2.27.0 of `eslint-plugin-import`):
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md#inline-type-imports

You can also use `import/consistent-type-specifier-style` to enforce the use of inline OR top-level imports in your codebase (v2.27.0 of `eslint-plugin-import`):
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/consistent-type-specifier-style.md
