### ISSUE TITLE
Docs request: how to disable type-aware linting for a specific file

### ISSUE THREAD

**Issue by Vinnl** [typescript-eslint/typescript-eslint#2794]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

In the docs on linting with type information, there's a section that specifically addresses [I get errors telling me "The file must be included in at least one of the projects provided"](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided).

The solution that is listed there that would apply to my project is:

>     Use ESLint's overrides configuration to configure the file to not be parsed with type information.

However, it is not clear what overrides to pass to disable parsing with type information. This is what I tried:

```JS
{
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
  ],
  "parserOptions": {
    "tsconfigRootDir": __dirname,
    "project": ["./tsconfig.json"],
  },
  // etc.
  "overrides": [
    {
      "files": ["file-without-type-aware-linting.js"],
      "parserOptions": {
        "project": undefined,
        "tsconfigRootDir": undefined,
      },
      "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:@typescript-eslint/recommended",
      ],
    },
  ],
}
```

**Expected Result**

To see what configuration values i need to set to disable type-aware linting.

**Actual Result**

Just trying out what I think is the oppose of the instructions to enable type-aware linting, which didn't work. I still get this error:

> Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
> The file does not match your project config: file-without-type-aware-linting.js.
> The file must be included in at least one of the projects provided

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.8.1` |
| `TypeScript`                | `4.1.2` |
| `ESLint`                    | `7.13.0` |
| `node`                      | `12.19.0` |

**Comment by bradzacher** [comment]
Disabling the type-aware parser isn't enough - you also need to disable all type-aware lint rules as well.
This is why people usually configure it the other way around - setup the base config to not be type-aware and then turn on the type-aware lint rules in an overrides.

Though your config will work if you use `null` instead of `undefined`.
ESLint works with the configs as if they were JSON, and `undefined` means "this property does not exist". So when merging `{ project: undefined }` into `{ project: "something" }`, ESLint will treat it the same as merging `{}` into `{ project: "something" }`, hence the parser isn't being turned off.

It's hard to provide exact docs for this as everyone's setups vary wildly. Some people use `overrides`, some people use nested config files, some people use different lint commands.
