### ISSUE TITLE
[return-await] rename to `no-return-await` to be consistent with other extensions

### ISSUE THREAD

**Issue by dimitropoulos** [typescript-eslint/typescript-eslint#2855]
I noticed that (with the exception of `camel-case` which was extended by `naming-convention`) the `return-await` rule is the only extension rule that doesn't have the same name as the corresponding eslint rule (which is `no-return await`).

If there's interest in fixing this for the next major release I'd be happy to fix it by renaming `@typescript-eslint/return-await` to `@typescript-eslint/no-return-await`.

- [ ] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.9.0` |
| `@typescript-eslint/parser`        | `4.9.0` |
| `TypeScript`                       | `X.Y.Z` |
| `ESLint`                           | `7.15.0` |
| `node`                             | `X.Y.Z` |

**Comment by bradzacher** [comment]
The base rule is called `no-return-await` because it simply bans returning an `await`.
The base rule can't handle enforcing you return an `await` because it doesn't have type information.

When the extension was implemented an intentional decision was made to drop the `no-`, because the extension rule specifically allows enforcing the inverse - _requiring_ an `await`ed return.

**Comment by dimitropoulos** [comment]
Ok, thanks.  I tried to find the discussion of that intentional decision and couldn't locate it.  Sorry for the noise, then.
