### ISSUE TITLE
question about publishing of docs folder

### ISSUE THREAD

**Issue by david-fong** [typescript-eslint/typescript-eslint#2914]
This is a question out of curiosity. I was doing a disk-usage scan of my local packages, and I noticed that in this package, the docs folder is explicitly included to be published in package.json, and that on my local disk, all the markdown files together take up ~600KB of space.

Are these files used by the plugin at runtime? Or are they purely for local reference? I noticed that `dist/util/createRule.js` has some code to link to _online_ documentation, but doing a naive grep of the package, I didn't find anything that seemed to reference the local markdown files.

I wonder... In the case that the docs folder is not used at runtime, would users of this package miss it if it were no longer published as part of the package? I myself prefer reading the documentation on github, since I'm so used to the browser. Removing the docs would cut the size of this package down by 20%.

Thank your time in reading and answering this! I appreciate it.

**Comment by bradzacher** [comment]
You're right in saying that we don't create any runtime links to the bundled markdown files. We'd prefer that a user sees the online files as they're properly rendered markdown.

For linting it's important that users always have access to documentation.
Without documentation - it's damn near impossible to configure anything without them.

There's potential for users to be offline whilst working on configuration etc, and being able to find the docs locally means that they can actually do this.

The links in the `eslint-plugin` readme are all relative - meaning that if someone opens the readme for the package - by including the docs folder, the links in the readme all work fine.

Right now the uncompressed package size is 2.1MB, but compressed, the size is 385kb.
Running an experiment - removing the docs folder changes that to 1.8MB uncompressed and 315kb compressed.

Because this project is only consumed at dev time (eg it's installed once per machine), and it's ultimately a small amount of bytes - I don't think there's enough to be gained by removing them from the bundle, but there's much to be lost by removing them..

**Comment by david-fong** [comment]
Thanks a bunch for the comprehensive explanation / evaluation, Brad! I appreciate it. It makes total sense to me.

Have a great day!
