### ISSUE TITLE
Error: Plugin "@typescript-eslint" was conflicted between "packages/website/.eslintrc.js » ./../../.eslintrc.js" and ".eslintrc.js".

### ISSUE THREAD

**Issue by mgcrea** [typescript-eslint/typescript-eslint#2921]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

Recently updated my dev deps and it looks like `@typescript-eslint` does not support being extended anymore.

I'm using a monorepo of `create-react-app`-based packages that all reference the root `.eslintrc.js` config. Used to work fine but now I get the following error:

```
[Error - 12:07:20 AM] Error: Plugin "@typescript-eslint" was conflicted between "packages/website/.eslintrc.js » ./../../.eslintrc.js" and ".eslintrc.js".
    at mergePlugins (/Users/foo/bar/node_modules/@eslint/eslintrc/lib/config-array/config-array.js:202:19)
    at createConfig (/Users/foo/bar/node_modules/@eslint/eslintrc/lib/config-array/config-array.js:305:9)
    at ConfigArray.extractConfig (/Users/foo/bar/node_modules/@eslint/eslintrc/lib/config-array/config-array.js:481:33)
    at CLIEngine.isPathIgnored (/Users/foo/bar/packages/website/node_modules/eslint/lib/cli-engine/cli-engine.js:973:18)
    at CLIEngine.executeOnText (/Users/foo/bar/packages/website/node_modules/eslint/lib/cli-engine/cli-engine.js:883:38)
    at /Users/olivier/.vscode/extensions/dbaeumer.vscode-eslint-2.1.14/server/out/eslintServer.js:1:22816
    at fe (/Users/olivier/.vscode/extensions/dbaeumer.vscode-eslint-2.1.14/server/out/eslintServer.js:1:28664)
    at /Users/olivier/.vscode/extensions/dbaeumer.vscode-eslint-2.1.14/server/out/eslintServer.js:1:22786
    at /Users/olivier/.vscode/extensions/dbaeumer.vscode-eslint-2.1.14/server/out/eslintServer.js:1:24043
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

root config

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  ignorePatterns: ['*.js'],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    'prettier',
    'prettier/@typescript-eslint',
    'prettier/react'
  ],
  plugins: ['@typescript-eslint', 'react', 'react-hooks', 'prettier'],
  rules: {
    'react/prop-types': 'off',
    'react/no-unescaped-entities': 'off',
    'react/display-name': 'off',
    '@typescript-eslint/triple-slash-reference': 'off',
    '@typescript-eslint/ban-types': [
      'error',
      {
        types: {
          '{}': false
        },
        extendDefaults: true
      }
    ],
    '@typescript-eslint/no-use-before-define': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/explicit-function-return-type': [
      'warn',
      {allowExpressions: true, allowTypedFunctionExpressions: true, allowHigherOrderFunctions: true}
    ],
    'prettier/prettier': 'error'
  },
  overrides: [
    {
      files: '*.{spec,test}.{js,ts,tsx}',
      env: {
        jest: true,
        jasmine: true
      }
    }
  ],
  settings: {
    react: {
      version: 'detect'
    }
  }
};
```

child config (eg. `packages/website`):

```js
module.exports = {
  extends: ['./../../.eslintrc.js'],
  parserOptions: {
    project: './tsconfig.json'
  }
};
```

Tried to comment ou the `parserOptions` block but it did not change anything.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.12.0` |
| `@typescript-eslint/parser`        | `4.12.0` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.17.0` |
| `node`                             | `14.15.3` |

**Comment by bradzacher** [comment]
As indicated by the stack trace - ESLint is unsure how to handle your repo's setup.
The reason it's doing this is because you've got multiple versions of `@typescript-eslint` installed, and your two different `.eslintrc`'s are essentially referencing different ones.

ESLint can tell this and hence it's throwing an error.

You need to normalize and flatten your repo setup so that you only have one copy of our tooling installed.

**Comment by domehead100** [comment]
I'm not sure what you mean @bradzacher.

This suddenly happened to me when in vscode the eslint extension popped up some dialog asking me to trust it and asking if I always wanted to trust it, to which I answered something like "Always".  After that, this error started appearing in vscode.

I've uninstalled and re-installed the extension to no avail.

My package json does not have "multiple versions of @typescript-eslint":
```json
 "@typescript-eslint/eslint-plugin": "^4.8.1",
 "@typescript-eslint/parser": "^4.8.1",
```
Maybe there is something in settings.json for vscode, but source control doesn't indicate that this changed.  I realize that whatever the problem is was probably caused by the eslint vscode plugin rather than @typescript-eslint, but I'm having a hard time understanding what the error message from eslint is complaining about or how to resolve it.

**Comment by bradzacher** [comment]
If you look at each line fo the stack trace - each line is from ESLint.
Investigating the ESLint codebase, for the string "conflicted" leads you to:

https://github.com/eslint/eslintrc/blob/a75bacd9a743a7bbcdb8c59e5d4f9de3dc8b0f20/lib/config-array/config-array.js#L162-L174

Which is thrown

https://github.com/eslint/eslintrc/blob/a75bacd9a743a7bbcdb8c59e5d4f9de3dc8b0f20/lib/config-array/config-array.js#L202-L211

The code itself is a bit vague, but combined with the error message, I can roughly translate it:

> Plugin "@typescript-eslint" was conflicted between "packages/website/.eslintrc.js » ./../../.eslintrc.js" and ".eslintrc.js".

Translates to:

> ESLint found that for your file there were several configs files that cascaded for it.
> ESLint found that the plugin "@typescript-eslint" was referenced from these two config files:
> - "packages/website/.eslintrc.js » ./../../.eslintrc.js", and
> - ".eslintrc.js"
> When we compared the import paths this plugin resolved against these configs, we found two different resolution paths for the plugin.
> Because we don't know which one is correct, and we don't want to import the wrong one - we're throwing an error.

**Comment by libin-code** [comment]
Hi, I hit the same problem and finally fixed it recently. I use the VSCode editor and installed the ESLint extension. This error is made by the ESLint extension because it's not sure which .eslintrc file should be used.

But the extension support a setting like `{ "pattern": "./packages/*/" }` can help it know which config file should be used in each directory. And that could fix the issue.

Hope that helps.

There are some details in the ESLint document below:

> [{ "pattern": glob pattern }] (@since 2.0.0): Allows to specify a pattern to detect the working directory. This is basically a short cut for listing every directory. If you have a mono repository with all your projects being below a packages folder you can use { "pattern": "./packages/*/" } to make all these folders working directories.
