### ISSUE TITLE
[no-unnecessary-condition] Option to ignore "both sides of the expression are literal" in if-else chains of enum cases

### ISSUE THREAD

**Issue by peterflynn** [typescript-eslint/typescript-eslint#2952]
- [x] I have tried restarting my IDE and the issue persists.
- [ ] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/no-unnecessary-condition": "error"
  }
}
```

```TS
enum Option {
    one, two, three
}

function test(value: Option) {
    if (value === Option.one) {
        // ...
    } else if (value === Option.two) {
        // ...
    } else if (value === Option.three) { // ERROR
        // ...
    }
}
```

**Expected Result**

Developers may prefer this style of exhaustively listing all the enum values, including the last one, for several reasons:

* It may be more future proof if additional enum values are added.
* It's less readable if the last case's enum value isn't spelled out. (You could write `} else /* value === Option.three */ {` but that is awkward, and easier to drift out of sync with the code).
* It's easier if you ever want to reorder the cases later.

I'm not sure if these problems go away if you were to use a `switch` statement where you can also enable "switch-exhaustiveness-check". But for style reasons, developers may prefer an if-else chain for simpler enums regardless.

**Actual Result**

Error "Unnecessary conditional, both sides of the expression are literal values" on the last `else if`.

This occurs because the type of `value` has been narrowed from its original `one|two|three` to simply `three`, making the final `if` technically redundant (a bare `else` would behave identically, unless more items are added to the enum).

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.1.0` |
| `@typescript-eslint/parser`        | `4.1.0` |
| `TypeScript`                       | `3.9.7` |
| `ESLint`                           | `7.12.1` |
| `node`                             | `12.18.3` |

**Comment by bradzacher** [comment]
`<opinion>`

In the case of enums - `switch`es are just straight up better.

if/else is ambiguous in its meaning, and is more verbose.
It's ambiguous in its meaning because `if (x === Enum.A) { ... }` is used regularly to check just a single case of an enum, whereas `switch (x) { case Enum.A: { ... }` is not.

So if a developer were to write an exhaustive if check on an enum, and then a new value were to be added, it's not simple to tell if, exactly, the intention was an exhaustive check or not.
Additionally it's possible to (and not uncommon to) mix-and-match types and conditions in an if:
```ts
if (x === Enum.A) {
} else if (y === OtherEnum.B) {
} ...
```

OTOH - a switch/case is much clearer because it sees much narrower usage in control-flow logic.
And because a switch/case is syntactically limited to be about a single variable, there is no ambiguity in the logic.
Because of the simplicity and lack of ambiguity, rules like (as you mention) [`switch-exhaustiveness-check`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md) can exist.

Worth noting that even for simple cases - there's not much difference in terms of character count between switch/case and if/else.
Eg - there is 134 characters in your example if/else, and only 145 in this equivalent switch/case:
```ts
switch (value) {
  case Option.one:
    // ...
    break;

  case Option.two:
    // ...
    break;

  case Option.three:
    // ...
    break;
}
```

Code is read many, many, many more times than it is written. **Always** optimise for readability and, more importantly, clarity of _intention_.

`</opinion>`

---

All that aside.

This is not an easy addition to code - there are a lot of cases to think through and check, which would make it rather expensive.

Whilst your example is pretty simple to validate as a human - for static analysis it becomes really difficult.

This stems from the fact that TypeScript tells us the value of a variable at any given time. It does not tell us its history, nor does it give us tools to view what it used to be.

So for the condition `} else if (value === Option.three) {`, as a human you can easily glance upward at the context just above, and easily tell that "`value` used to be of type `Option`, but it has since been narrowed down to just be `Option.three`".

However for type-aware static analysis, it can't see that. All it sees is "`value` is of type `Option.three`".
Which means in order for static analysis to determine that this condition is in fact "necessary" as per your proposal, it would have to back-track to some arbitrary point to figure out that `value` _used to be_ of type `Option`, and then we could inspect the control flow from then onwards.

There are numerous edge-cases etc which compound the complexity for what is seemingly a simple problem for a human to understand. (eg - if an `if/else` has multiple subject variables).

For that reason - I don't think this is a good addition to this rule - because doing it well is hard to impossible.

**Comment by bradzacher** [comment]
> I wonder if a decent mitigation might be adding an option to disable the warning when the "both sides" type is an enum value?

That can create some pretty big holes in what the rule checks. For example, it'll allow cases like these, all of which are clearly invalid code:

```ts
function test(condition: boolean, mode: Mode.two) {
  if (mode === Mode.two) {}

  if (condition) {
  } else if (mode === Mode.two) {}

  if (condition || mode === Mode.two) {}
}

function test2(condition: boolean, mode: Mode) {
  if (mode === Mode.one) { return; }

  // same checks as above, which should all be errors
}
```

Missing cases like this harms user trust - not just in this lint rule, but in the entire linting ecosystem. People lose trust that rules are covering cases correctly, and can start to second guess the advice rules are reporting. False positives are bad because noise is obviously bad, but false negatives are much worse because you don't know about them until they cause a problem.

A naive implementation which just prevents reporting on `===` when both sides are the same enum type invites a lot of unsafety into a rule about strictness - which I'm not comfortable adding for the above reason.

There are several strategies one might explore here to limit the scope of such an option, but as mentioned mentioned above - with static analysis and type information being essentially stateless, and if statements / logic expressions being ambiguous, building up and maintaining this state is quite a complex problem to solve.

---

> That 1-line if statement is definitely more compact than a switch block:

it is (39 characters - 2/5 of which is whitespace).
But as mentioned - code is read many more times than written - optimising for compactness/low character count is not a good strategy to code to.

but it's also reasonably ambiguous code - it's not entirely clear (without a comment) whether or not it's supposed to be exhaustive.

OTOH a switch with a default makes it explicit that it's intended to forever be non-exhaustive:
```ts
function test(mode: Mode) {
  switch (mode) {
    case Mode.one:
    case Mode.two:
      // ...
      break;

    default:
      break;
  }
}
```
