### ISSUE TITLE
[strict-boolean-expressions] add option to ignore common types, not only nullable

### ISSUE THREAD

**Issue by maksnester** [typescript-eslint/typescript-eslint#2977]
Hey guys, I really wanted to use `strict-boolean-expressions` to forbid falsy checks against numbers, but this case blocks me from using it.

```typescript
let array = [{ a: 1}, {a: 2}];
let arbitraryIndex = 100500;

// ESLint: Unexpected object value in conditional. The condition is always true.(@typescript-eslint/strict-boolean-expressions)
if (array[arbitraryIndex]) {
  // do something
}
```
I would like to have an option to allow not only checks against nullable objects, but also to disable object checks at all. 

I know that typescript in that case gives you an `object` type for `array[arbitraryIndex]` and it's not your fault, but just give us an option to disable those checks. The rule is super useful for numbers and I don't really need anything else from it.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.10.0` |
| `@typescript-eslint/parser`        | `4.10.0` |
| `TypeScript`                       | `4.1.3` |
| `ESLint`                           | `7.15.0` |
| `node`                             | `12.18.3` |

**Comment by bradzacher** [comment]
Nope! There's a TSConfig option to do this:
https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess

**Comment by maksnester** [comment]
Can't say that it solves anything for me. `noUncheckedIndexedAccess` has a consequence of converting literally any index access to `type | undefined` e.g. 

```typescript
function screamLines(strs: string[]) {
    // this will have issues
    for (let i = 0; i < strs.length; i++) {
        console.log(strs[i].toUpperCase());
        //          ~~~~~~~
        // error! Object is possibly 'undefined'.
    }
}
```

And I don't want to clutter code with `!` when I'm sure that index exists as in the example above. I would still prefer to avoid `noUncheckedIndexedAccess` and to have an additional option to configure `strict-boolean-expressions` with `allowObject: true`. 

> Nope!

@bradzacher Flexibility is a good thing for configuration, if you don't need something, doesn't mean nobody needs it 🤷‍♂️

**Comment by erik-beus** [comment]
@maksnester I had a similar suggestion a while back. 
And although I initially accepted the suggestion of using noUncheckedIndexAccess access, that leads to a lot of other issues as you mention.

I'll try to make a custom version of the strict-boolean-expression rule and use that to limit the amount of warnings on objects in our project. I'll post it here when it's ready in case anyone else will find it useful. 

https://github.com/typescript-eslint/typescript-eslint/issues/2916

**Comment by bradzacher** [comment]
> Flexibility is a good thing for configuration

It is to some degree.

If there's a big call for functionality, sure it can be added.
But considering this is the first call for it in almost a year since the rule was reworked to its current setup, that indicates to me that for the vast, *vast* majority of users - it's good as is.

But more options = more maintenance. Each changes requires more tests to check more combinations of code paths.
If something breaks, there's more complexity to look into.
I'm a volunteer maintainer - the only maintainer, and I barely keep up with everything as it is.

So if it's "good enough" for 99% of people, then a new option isn't worth the maintenance overhead.
If you have a specific customisation for your usecase - we purposely use a permissive licence so that you can fork the rule and implement whatever you need. You're also allowed to publish it back to NPM and share it with the community.

If there is community interest from that, then that's a good example of need from the community, so it makes sense to upstream the changes.

Otherwise - using `noUncheckedIndexedAccess` will make your entire codebase much safer on the whole, with only a few devx blips to deal with.
