### ISSUE TITLE
New rule: Prefer `Extract<T, U>` over `T & U`

### ISSUE THREAD

**Issue by tom-sherman** [typescript-eslint/typescript-eslint#2983]
`Extract<T, U>` produces better errors messages and compiler output for IDEs and I think is always equivalent to using an intersection. I'm struggling to think of a reason why you might choose an intersection over `Extract`, but I'm pretty sure for at least discriminated unions `Extract` is always preferred.

See the following example where `B` has a much better printed type than `A`, yet they are equivalent:

```typescript
type Action =
 | { type: 'action1', a: number }
 | { type: 'action2', b: string }
 | { type: 'action3', c: string }


type A = Action & { type: 'action1' | 'action2' }
type B = Extract<Action, { type: 'action1' | 'action2' }>
```

https://www.typescriptlang.org/play?#code/C4TwDgpgBAggxsAlgewHZQLwCgoB8oDeUokAXFAOQCGCKqAjBQDRRXmoCuAtgEYQBOUAL458REhHLVaaAEzMoPcgGdg-RKgDmw0YWLhJlGkjQBmBXBVqN2kViwTYmWDPQAyPRKnG6jPEdd5YSgHAygAIWcAUQAPNWMAHngTVBZxA29XP3xpFKChAD4gA

**Comment by bradzacher** [comment]
Are they actually equivalent? It seems like the former is a hacky type (and I don't even know why it works).

I'm not sure if this is something you could detect though. There's nothing really specific about these types that you can look for to distinguish the case.

**Comment by tom-sherman** [comment]
@bradzacher My gut feeling is that it is possible although I'm neither a type system expert or aware of what isn't possible within eslint. 

These two are equivalent when `U` is a subset of `T` (as is the case in my example). In any cases where `U` is a superset, intersections and `Extract` are not equivalent. Here are some examples of how the rule would behave:

```typescript
type Action =
 | { type: 'action1', a: number }
 | { type: 'action2', b: string }
 | { type: 'action3', c: string }

type A = Action & { type: 'action1' | 'action2' } // error: use Extract instead
type B = Action & { d: number } // ok: { d: number } is disjoint and so will be intersected onto Action
type C = Action & { type: 'action99, a: number, b: string, c: string, d: number } // ok: C has type `never`
```

**Comment by bradzacher** [comment]
The problem you've got is that "subset of" implies "assignable to". Assignability is a rather difficult problem to solve in the general case because TS does not expose any utilities for it.

Which means the rule has to deeply understand the entire types model and how things can assign.

Other rules get around this by only tackling smaller, self contained pieces (eg `no-unnecessary-type-assertion` only concerns itself with the case where `type === type`, which requires no understanding of assignability)

The cases you've provided are rather simple, but what about if you do something like

```ts
type Action1 =
 | ​{​ ​type​: ​'action1'​,​ ​a​: ​number​ ​}​
 | ​{​ ​type​: ​'action2'​,​ ​b​: ​string​ ​}​ 
type​ ​Action​ ​=​
 | Action1
 | ​{​ ​type​: ​'action3'​,​ ​c​: ​​Action ​}

type T = Action & {
  c: { type: 'action1' } 
}

const x: T = {
  type: 'action3',
  c: { type: 'action1', a: 1} 
} 
```

Now all of a sudden you're doing recursive assignability checks and things get complicated and **expensive**!

Types are computed lazily, so the more types a rule accesses, the slower it is. From the look of it, this rule would have to deeply inspect the types of every single intersection type in the codebase - which would be pretty costly.

----

Sorry - I'm not shooting down the rule or saying no!

I'm just pointing out some things that make this very hard to solve well.

----

One thing I would make note of is that this rule is really working around a problem in TS's IDE experience.

It's probably better to solve from the TypeScript side? It's likely easier to make the type printer understand that this case is an extraction, and print it as such.

Then it won't matter which form you use, and there's no explicit need for a rule.

**Comment by tom-sherman** [comment]
> One thing I would make note of is that this rule is really working around a problem in TS's IDE experience.

This is a great point, and thanks for the explanation of why this is difficult to solve on the linting side - very helpful. I'll raise a ticket in the TypeScript repo and I'm happy for you to close this issue or keep it open 😄

**Comment by armano2** [comment]
if someone decides to start working on this rule there is few cases that should be taken into account:

```ts
type Action = { type: 'action1', a: number }

type A = Action & { foo: number } 
type B = Extract<Action, { foo: number } >

const x: A = { type: 'action1', a: 1, foo: 2 }
const y: B = { type: 'action1', a: 1, foo: 2 }
```

[playground](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=10&pc=1#code/C4TwDgpgBAggxsAlgewHZQLxQN5VJALigHIBDBFVARmIBopSjUBXAWwCMIAnKAXwChB+aDEywKaKADIcUAGbJkTNpx68o-YVABCYgKIAPYF3LAAPPCRp6uBUqgsO3PlAB8guGgDOwKAaKiWLjCRGQS1HQMRFT0dkQATHz8nqg+UCBEukF44BChppQ09IxQMfKKCUn8QA)

in this case `A` is equal: `{ type: 'action1', a: number, f: number }` and `B` is equal to `never`
