### ISSUE TITLE
Remove `TSParenthesizedType`

### ISSUE THREAD

**Issue by thorn0** [typescript-eslint/typescript-eslint#3136]
The parser currently generates `TSParenthesizedType` nodes, which are totally redundant as far as I know.

Or am I missing something and they're actually used somehow?
Did you consider removing them or probably hiding behind a flag?

Related issue in Babel: https://github.com/babel/babel/issues/9546

**Comment by bradzacher** [comment]
This is a legacy AST node that is leftover from the times that the parser didn't do too much smart stuff, and instead just converted any new TS nodes by prefixing their name with `TS`.

We could probably remove them now, as they only really complicate the AST.
I don't think there's any good arguments for keeping them around.

**Comment by bradzacher** [comment]
Just because I should have probably done this way back when, figured I'd close this loop now as we're making this change now. @nicolo-ribaudo - if you've got questions about the TS AST - don't hesitate to reach out to me somewhere (slack, github, twitter).

A lot of the weirdness in the TS AST you guys generate is likely due to legacy things from when this project was spun up way back when - so I can probably answer your questions. It'd be good for us to keep in sync as well.
