### ISSUE TITLE
[Tutorial request] The extremely common and incredibly reasonable use-case of linting test files while excluding them from compilation 

### ISSUE THREAD

**Issue by CodeOtter** [typescript-eslint/typescript-eslint#3307]
The request is:

✔️ Lint test files
❌ Exclude test files from the transpiled build 

**_This is a reasonable, fair, and highly common use case._**

Trying to do this requires one to muck through dozens of poorly reasoned and extremely fragmented insights from Stack Overflow, Google results, and random Medium articles that are spread out over a three year span.

Many allude to the mythical power of `tsconfig.json` and `tsconfig.eslint.json` without any of the above noise spelling out exactly how this is supposed to work.

Is such a unified and simplified explanation of this very common thing any rational developers would want to do fall within the scope of being explained in the FAQs?  The `tsconfig.eslint.json` file is briefly mentioned in  the README.md, but it is explained in a technical sense exclusively, totally independent of this really common use case.

I'd change the FAQs myself, but:
  1.) I'm unsure if there is some obscure reason why this use case is invalid
  2.) _I don't actually know how to do the thing I'm talking about because no one precisely spells out how to do it._

**Comment by thorn0** [comment]
But how do you run the tests if they're excluded from compilation?

**Comment by thorn0** [comment]
The issue you linked doesn't mention ESLint at all though.

**Comment by CodeOtter** [comment]
The issue is derivative of `typescript-eslint` throwing incorrect errors in VSCode when trying to bring typing to Ava

Ava's recommended recipe for TypeScript breaks other things I'm depending on and the issue itself points to the fact that the recipe no longer works for TypeScript.

From what I can tell, one requires years of experience configuring and debugging the complex relationship between `tsconfig.json` and `.eslintrc.js` in order to bring bring typing to Ava.

We could spend this time trying to drill down to the specific configuration, versioning, and dependency that has resulted in Ava's TypeScript recipe being dated, but I do believe that is outside of the scope of this project and this issue.

Or we could spend time on a more serious concern: **Why would I ever want tests compiled into a production release candidate and why is that opinion being forced on everyone using typescript-eslint?**

**Comment by thorn0** [comment]
I'm not a maintainer. It just seemed strange to me that you somehow run the tests without compiling them, so I thought I'd clarify that. Overall, your issue sounds very Ava-specific to me. Not everyone's configuration is the same. 

Could you explain where did this:

> tests compiled into a production release candidate and why is that opinion being forced on everyone using typescript-eslint?

come from? If you don't import test files in your project files, how do they end up compiled into the release? And how exactly is it being forced?

**Comment by CodeOtter** [comment]
Your statement was:

> But how do you run the tests if they're excluded from compilation?

This statement implies there is no way to run tests unless you compile everything down to the same `build` output directory.  I don't want to do that.  I want the contents of the `build` directory to always be a release candidate, not a sandbox/workspace with mixed states and mixed configurations.

I want to have a separate `tsconfig.json` configuration for testing, which `ava-ts` does for me without firing needless ESLint errors that are near impossible to resolve without years of _lint engineering_ experience.  (Why does everyone have to be a lint engineer to do basic stuff, anyways?)  There is no worthwhile FAQs or tutorials on how to do that.  All we have are issues where things just don't work and you need _lint engineers_ to review your entire configuration only to tell you it's an Ava issue.

The problem being very Ava-specific or not ("passing the buck") doesn't shy away from the fact that setting up multiple build requirements with TypeScript and ESLint is **not intuitive** and **very hard**.

**Comment by thorn0** [comment]
My "statement" was a question (not even a statement) that didn't imply anything. It's just something that anybody who'd want to help you would ask to understand what's going on your end. If you really believe the configuration specifics doesn't matter and a general recipe is possible, I guess that recipe would be as follows. Instead of one TS project you essentially have two: the project proper and the tests. If you can set up linting for one project, set it up for the second one in the same way.

**Comment by CodeOtter** [comment]
I'm not asking for a general recipe.

I'm asking for some insight on how `.eslintrc.js`, `tsconfig.json`, and `tsconfig.eslint.json` are supposed to play together in the very specific situation of keeping `build` exclusively for release candidates while still running tests that don't pollute the build space.  I made this very clear in the title of the ticket: **_linting test files while excluding them from compilation_**  Very specific.  Exclusively so.

The reason I made this a ticket is because I was under the assumption that running tests to their own build output would be a think people would like to do.

There is nothing anywhere that explains in a meaningful way how those three files are even supposed to work together at all, let alone explain how to even achieve the end I'm looking for.

**Comment by bradzacher** [comment]
I'm not sure how much clearer we can make it based on the getting started guide.
In our docs there are 3 places that explicitly mention `tsconfig.eslint.json:
- https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md#i-get-errors-telling-me-the-file-must-be-included-in-at-least-one-of-the-projects-provided
- https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/MONOREPO.md#one-root-tsconfigjson
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/parser/README.md#parseroptionsproject

One contains a link to the `tsconfig.eslint.json` that we use ourselves in this very repo and the other two contain inline examples of one.

To put it plainly here; a `tsconfig.eslint.json` is simply a regular old tsconfig file that lists the files/folders you want to lint with type-information.
The special naming is so that it's clear what it's used for and so VSCode doesn't pick it up as the tsconfig file.

---

Our aforementioned [getting started guide](https://github.com/typescript-eslint/typescript-eslint/tree/master/docs/getting-started/linting) contains a step-by-step walkthrough on how you can setup the config for your project - including inline samples to make it easy.

If you think there are gaps in the guide - let us know so we can fill them appropriately.
