### ISSUE TITLE
[member-ordering] Allow grouping of symbols

### ISSUE THREAD

**Issue by GerkinDev** [typescript-eslint/typescript-eslint#3350]
This is a feature request.

I'd like to be able to apply this rule in regions of my class. In each of those region, ordering would be enforced. 

For instance, for ordering `["instance-field", "constructor", "instance-method", "region"]`, I'd like this to be possible: 

```ts
class Omnivore implements Herbivore, Carnivore {
    private _lastMeal: string;
    public get lastMeal(){
        return this._lastMeal
    }

    public constructor(){}

    // #region Herbivore
    private _lastPlantMeal?: string
    public get lastPlantMeal(){
        return this._lastPlantMeal
    }
    public eatPlant(plant: string){
        this._lastPlantMeal = plant;
        this._lastMeal = plant;
    }
    // //#endregion

    // #region Carnivore
    private _lastMeatMeal?: string
    public get lastMeatMeal(){
        return this._lastMeatMeal
    }
    public eatMeat(meat: string){
        this._lastMeatMeal = meat;
        this._lastMeal = meat;
    }
    // //#endregion
}
```

**Comment by bradzacher** [comment]
Regions are very, very tricky to implement because they aren't concrete things in the AST - they're simply comments in the code.

Which means that in order to detect what region each member falls in we'd have to scan the AST for comments and manually compare ranges to figure out where each member falls.
I believe we'd also have to include logic to separate top-level regions from nested regions.

The rule is already **very** complex, and I don't think that adding this additional complexity adds enough value to the rule to justify its addition.
