### ISSUE TITLE
Flow Imports - Line 14, column 32: ';' expected.

### ISSUE THREAD

**Issue by wSedlacek** [typescript-eslint/typescript-eslint#3363]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "import"],
  "rules": {
    "import/no-cycle": 1,
    "import/no-deprecated": 1
  }
}

```

```TS
import 'react-native';
```

Which includes some flow type imports.
```js
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 * @flow
 */

'use strict';
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
import typeof Button from './Libraries/Components/Button';
import typeof CheckBox from './Libraries/Components/CheckBox/CheckBox';
...
```

**Actual Result**

Linting throws errors

```log
Error while parsing rn-eslint-test/node_modules/react-native/index.js
Line 14, column 32: ';' expected.
`parseForESLint` from parser `rn-eslint-test/node_modules/@typescript-eslint/parser/dist/index.js` is invalid and will just be ignored
```

**Expected Result**

This is difficult to say what I would expect to happen. Obviously parsing Flow is out of the scope of this project, however it is a bit problematic that it is just failing. I would be happy if the warning wasn't so ugly with a clean message saying that it is skipping this check because the file is `flow`.  It would also be nice to fallback to another parser like babel when this happens.

**Additional Info**

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.22.1` |
| `TypeScript`                | `4.2.4` |
| `ESLint`                    | `7.26.0` |
| `node`                      | `14.16.0` |

**Comment by bradzacher** [comment]
In this instance it's because you're using `eslint-plugin-import` that the file is being parsed at all. The `import/no-deprecated` rule, for example, will walk each file's dependencies and will manually call the configured parser for each file.

There's nothing that we cannot do anything about this.
Our parser is built directly on top of TypeScript - which *does not* support this syntax.
So we show the exact error that comes from TS - it's not supported syntax, so TS parses it as best as it can and then errors when it find unknown syntax.

> I would be happy if the warning wasn't so ugly with a clean message saying that it is skipping this check because the file is flow

What makes this file "flow"?
It's just a `.js` file: `rn-eslint-test/node_modules/react-native/index.js`.
The only way for us to tell that it's a "flow" file is if we regex scanned the file for an `@flow` directive, but that's not even technically correct as it has to specifically be in a multiline block comment in the file.

**Comment by wSedlacek** [comment]
> In this instance it's because you're using eslint-plugin-import that the file is being parsed.
The import/no-deprecated rule, for example, will walk each file's dependencies and will manually call the configured parser for each file.
>
> There's nothing that we cannot do anything about this.

Definitely a difficult problem to address with all the interdependencies.
I suppose the best place to address this issue would probably be either with `estlint-plugin-import` or `eslint` core to support invoking different parsers when attempting to parse imports.

Working with anything publish in `flow` is kinda always a pain if you aren't using flow yourself.

**Comment by wSedlacek** [comment]
> They already do support this (based on extension)
> https://github.com/benmosher/eslint-plugin-import/#importparsers

This is what I needed. Thank you!
