### ISSUE TITLE
no-floating-promises is not covered by eslint-plugin-promise

### ISSUE THREAD

**Issue by yang** [typescript-eslint/typescript-eslint#339]
The [Roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) lists `no-floating-promises` as "N/A" because of eslint-plugin-promise.

But that plugin *does not* and has no plans to support floating promise detection:

https://github.com/xjamundx/eslint-plugin-promise/issues/151

FWIW, this check caught a large number of bugs for us in our async code - it's an easy mistake to make.

**Comment by ThomasdenH** [comment]
Note that it is marked as 'unimplemented', not as 'implemented by plugin'. I think this is still planned.

**Comment by bradzacher** [comment]
Thomas is correct, it is specifically this is marked as "🛑 = unimplemented", not "🔌 = in another plugin".
`eslint-plugin-promise` is listed purely as a plugin with many features related to promises. This is done primarily because we can't keep up with every single plugin we link to, so maybe they might have implement it from when the docs were written to today.

![image](https://user-images.githubusercontent.com/7462525/54042419-ec70a200-417e-11e9-8cd6-376afefbb93d.png)

We're happy to accept PRs to add this rule considering it needs type information about the called function.

**Comment by w0rp** [comment]
I think an issue should be opened for adding this rule to `@typescript-eslint/eslint-plugin`, as type information from TypeScript is required for implementing the rule, and `eslint-plugin-promise` doesn't have access to that type information. Perhaps @JoshuaKGoldberg might be able to help.

**Comment by JoshuaKGoldberg** [comment]
@w0rp yes, as bradzacher posted, this repo is accepting PRs. I'll send one in Soon™️ if someone else doesn't get to it first. You're welcome to give it a shot 😉

**Comment by bradzacher** [comment]
@w0rp 
If it's something that you really want done, and want it flagged specifically to be added, then feel free to open an issue.

Otherwise, the roadmap exists for the a number of reasons, one of which being tracking things that could/should be added to the plugin, are low priority (i.e. nobody has asked for them).

We love new contributors, so if you want to give it a go, please feel very free!
Otherwise it'll get done eventually by someone like @JoshuaKGoldberg or another core maintainer. 

(as an aside - I closed this issue because it was about our docs being wrong [which they aren't], instead of being a feature request for the rule).

**Comment by w0rp** [comment]
Thank you, I have opened an issue for it now.
