### ISSUE TITLE
Document default levels (warn|error) of recommended rule sets

### ISSUE THREAD

**Issue by runspired** [typescript-eslint/typescript-eslint#3450]
While updating my tsconfig.json and estlint.rc files I noticed that the rule `@typescript-eslint/no-explicit-any` wasn't logging any errors (or warnings for that matter) unless I explicitly set it to error. Confused, since I believed it to be in the recommended rule-set, I checked the source and noticed that while it is recommended, the recommended level is `warn` (I'm not sure why I don't get a warning, I am not running eslint with --quiet, if I determine this to be a bug I'll open up an issue where appropriate).

I tend to assume recommended rules are set to `error`, not `warn`, so this finding surprised me. Since we have recommended rules that are not set to `error`, it would be great if the table of rules in the README added a column that specifies the default value which the recommended configuration brings.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.21.0` |
| `@typescript-eslint/parser`        | `4.21.0` |
| `TypeScript`                       | `4.2.4` |
| `ESLint`                           | `7.23.0` |
| `node`                             | `14.17.0` |

**Comment by bradzacher** [comment]
The difference between errors and warnings are that errors are things that should never ever be in the code, but warnings are things you should avoid violating.

So we mark a few of our rules as warnings as we recommend people should follow the rule, but it's not absolutely always required. For example with `no-explicit-any` there are *some* valid usecases for `any`, so hence it's not something you should never ever use - hence not an error.

I understand that you might find this surprising - but I don't think it's worth adding more icons to the root readme, as the vast majority of users won't exactly care what the level is as long as it's enabled. I make this assumption based on the fact that you're the first person in over 2 years since we introduced the recommended set that has wanted the levels documented.

> I'm not sure why I don't get a warning

Likely another config turned it off, or your config was not correctly applied for the file. Hard to say without any additional information.
