### ISSUE TITLE
[no-unsafe-assignment] any => unknown assignment triggers error for object shorthand notation

### ISSUE THREAD

**Issue by michens** [typescript-eslint/typescript-eslint#3575]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

[Playground](https://typescript-eslint.io/play#ts=5.3.2&fileType=.tsx&code=C4TwDgpgBAYg9nKBeKBvKAjAhgJwFxQCuAdgNbFwDuxA3FAL40BQAxnMQM7Ca4FbEhkUAIzNW7LlABmCAvEQp02HA2ZtO3GXABMchEKW8eKxkyA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0URNGgdokcGAC%2BITUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDAruuGAL4g9A&tokens=false)

```JSON
{
  "rules": {
    "@typescript-eslint/no-unsafe-assignment": "error"
  }
}
```

```TS
type Foo = { bar: unknown; };
const bar: any = 1;

const foo: Foo = { bar };
const foo2: Foo = { bar: bar };
```

I expect that `foo` will be treated the same as `foo2`

`foo` triggers the unsafe-assignment error, while `foo2` does not

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.26.0` |
| `@typescript-eslint/parser`        | `4.26.0` |
| `TypeScript`                       | `4.1.2` |
| `ESLint`                           | `7.12.1` |
| `node`                             | `14.14.0` |

**Comment by bradzacher** [comment]
So this is a really interesting thing.

`{bar: bar}` creates two separate `Identifier` nodes in the TS AST.
Because of this TS can assign the type `unknown` to the first (as it knows the inferred type), and `any` to the second (which is the type of the value).

OTOH `{bar}` creates just one `Identifier` in the TS AST.
So it just assigned the `any` type to it and that's it. There's no marker from which we can pull the contextual type  that's being assigned to.

I don't know if we can solve this problem.
