### ISSUE TITLE
Cannot parse class method overloads

### ISSUE THREAD

**Issue by paul-uz** [typescript-eslint/typescript-eslint#3638]
I am trying to get to grips with overloads, and with a very basic example, I am getting errors.

```
class Foobarbaz {

  foo(bar:string): boolean;
  foo(bar:string, baz?:number): boolean {
    console.log(bar);
    return true;
  }

}
```

Errors shown in screenshot below

<img width="490" alt="Screenshot 2021-07-15 at 11 34 35" src="https://user-images.githubusercontent.com/73826774/125774441-8056ba5d-a176-4031-9060-f9d51c64e035.png">

My eslintrc:

```
{
  "env": {
    "commonjs": true,
    "es2020": true,
    "node": true
  },
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "extends": ["eslint:recommended"],
  "rules": {
    "semi": ["error", "always"],
    "quotes": [2, "single"],
    "no-empty-function": "error",
    "comma-dangle": ["error", "always-multiline"]
  }
}
```

My tsconfig is the default one created  by `tsc --init`

What am I getting wrong?

**Comment by paul-uz** [comment]
Small bit of testing reveals that if i remove `  "extends": ["eslint:recommended"],` from the eslintrc file, the errors disappear :/

**Comment by bradzacher** [comment]
Please don't delete the issue template. It exists for a reason.

This problem is explained in our FAQ, which is linked in the template:
https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code
