### ISSUE TITLE
[no-namespace] add allow list

### ISSUE THREAD

**Issue by remcohaszing** [typescript-eslint/typescript-eslint#3660]
I believe namespaces in TypeScript should be avoided. However, in some cases namespaces can’t be avoided, i.e. when writing a JSX library, using TypeScript to write Cypress tests, or creating a Monaco Editor plugin. I think it makes sense to be able to add exceptions to the `no-namespace` rule to support these situations. A simple and consistent solution is adding an option `allow` which takes a list of string namespaces that are allowed. Ideally a dot (`.`) may be used for nested namespaces. To support the classic runtime, a wildcard support would be needed to define any nested `JSX` namespace is also acceptable.

Given the following config:

```yaml
rules:
  '@typescript-eslint/no-namespace':
    - error
    - allow:
      - JSX
      - '*.JSX'
      - Cypress
      - languages.yaml
```

The following would be ok:

```ts
namespace JSX {
  export interface IntrinsicElements {}
}

declare function h(tagName: string, props: any, ...children: Node[]): HTMLElement {}
namespace h.JSX {
  export interface IntrinsicElements {}
}

namespace Cypress {
  export interface Chainable {}
}

declare module 'monaco-editor' {
  namespace languages.yaml {}
}
```

The following would not be ok:

```ts
namespace Foo {}

declare function h(tagName: string, props: any, ...children: Node[]): HTMLElement {}
namespace h {
  namespace JSX {
    export interface IntrinsicElements {}
  }
}
```

**Comment by bradzacher** [comment]
How often do you need to declare these namespaces throughout a codebase? Is it regularly, or rarely?
From what I've seen in the past - it's rare that you need to do this.
*Usually* you're augmenting a specific namespace once or twice in an entire codebase - **IF** you need to do it at all.

If that's the case - it means this is better-suited for just using a disable comment.
"I am circumventing this lint rule on purpose and here is a comment explaining why".

The problem with an allowlist option is that it lacks all context. It does not and cannot comprehend ***why*** you're doing something - it only knows that you're doing it.
Which means that it can lead to false-negatives in your codebase and bad code being committed.
I've seen a tendency to not comment on code if the linter is happy with it (ESP among less senior engineers).

This is why I push back so much against allowlists - because more often than not they're a very easy footgun.

**Comment by remcohaszing** [comment]
I normally wouldn’t even write namespaces myself. This rule is mostly to prevent other contributors from adding a namespace.

I usually use my own reusable ESLint configuration. When configuring ESLint in a repository which uses namespaces for a legitimate reason, I’m tempted to disable the rule altogether, although I do feel namespaces are usually a bad idea.

When I see an `eslint-disable` comment, I tend to think there should be a better way. But sometimes a namespace way to go, whether you like it or not. The few namespaces that are necessary, tend to be well known and documented anyway. I.e. when using Cypress with TypeScript, the user probably knows the namespace is necessary, or otherwise the [documentation](https://docs.cypress.io/guides/tooling/typescript-support#Types-for-custom-commands) is easy to find. I don’t think the code requires additional comments to justify the use of the namespace.

**Comment by bradzacher** [comment]
I definitely get where you're coming from. "I *have* no choice but to use a namespace to augment Cypress, so why doesn't the lint rule support that?"
It doesn't support it because it's *contextually* necessary. Humans are good at contextualism. Code is not.

Adding an allowlist is a ham-fisted way of hacking in *some* contextual information, but it's often over-matching.

For example, with `allowed: ['Cypress']` the following code is allowed:
```ts
// module.ts
namespace Cypress {
  export function myFunction() { console.log('namspaces!') }
}

export default Cypress;

// other.ts
import Other from 'other';

Other.myFunction();
```

You just hired two new engineers onto your team. The first one added the above code and the second one approved the PR because there was no lint errors.

This is where the problem lies. The context you added was incomplete. It did not understand that in the context of your project a namespace called `Cypress` should only be used to declare augmented types for cypress tests.

---

All of the examples you've provided are for using a namespace to augment types. Unless I'm mistaken - type augmentations can (and should) be done in a `.d.ts` file.

So why not just [disable the rule in `.d.ts` files?](https://eslint.org/docs/user-guide/configuring/configuration-files#configuration-based-on-glob-patterns) That way you can augment the types using namespace for whatever library you need to, and you have the added benefit that at worst someone can declare a namespace which houses a bunch of types - i.e. the namespaces will never exist at runtime.

Given how rarely projects declare `.d.ts` files (i.e. most will never declare one themselves), it seems like that's a lot safer than an allowlist which applies to every single file.

As an example - we have all sorts of overrides in this project wherein we set different code standards for different folders and file extensions:
https://github.com/typescript-eslint/typescript-eslint/blob/15f718415eb4e522440a5d81f38d65ee81535795/.eslintrc.js#L163-L292

**Comment by remcohaszing** [comment]
> All of the examples you've provided are for using a namespace to augment types. Unless I'm mistaken - type augmentations can (and should) be done in a `.d.ts` file.

That’s an interesting thought. They can, but I’m not 100% sure if they should be. I’m not disagreeing either.

For a classic JSX runtime implementation this isn’t the case though. If a function named `h` implements it, the `h.JSX` namespace needs to be declared in the same file. This is of course really rare.

> So why not just disable the rule in `.d.ts` files?

I’m already doing that. :)

---

Since the rule already has an option `allowDeclarations`, maybe a resolution would be to make that option accept a list of allowed names in addition to a boolean.

I.e. the following would allow to declare, but not define functions on a namespace named `Cypress`, but wouldn’t allow declaring other namespaces:

```yaml
rules:
  '@typescript-eslint/no-namespace':
    - error
    - allowDeclarations:
      - Cypress
```

```ts
// This is ok
declare namespace Cypress {}

// This gets reported
namespace Cypress {}

// This gets reported as well
declare namespace foo {}
```

---

Anyway, I think we’re mostly on the same page, except we don’t agree how to handle the use of namespaces that are unavoidable. This is a matter of preference.

I would like to see an option to allow certain namespaces, but also no hard feelings if the issue gets closed. Ultimately these kind of decisions are up to you, the maintainer, to make. :)

**Comment by bradzacher** [comment]
Revisiting this issue - We want to avoid allowlists unless there's a really, really good reason.

`eslint-disables` are a valid tool to reach for as they clearly document why you're "working around" a lint rule, which is better than an allowlist in config - which is invisible unless someone has access to the config directly (which people won't if it's hidden within a config package).
There is a balance to strike here for sure - if the pattern is very, very common throughout a codebase (eg the code is littered with disable comments for the pattern), then it is definitely a good idea to change the rule to suit.
It's worth mentioning that many projects disabling the rule in the same place, but sparingly, isn't the same. It's just that they're all using the same sparing exception in the same way - which is okay, IMO.

Thanks for the issue and discussion! At this time, we shall be rejecting this proposal.
