### ISSUE TITLE
[Proposal] default-case rule 

### ISSUE THREAD

**Issue by MrNossiom** [typescript-eslint/typescript-eslint#3703]
Hello, 

This is a rule proposal for the TS plugin.

Make a [default case rule like ESLint](https://eslint.org/docs/rules/default-case) but detect the type entry and doesn't require a default statement if we handle all the possibles cases.

Thanks
MrNossiom

**Comment by bradzacher** [comment]
default-case is a bad lint rule in general because it promotes adding useless code and makes it hard to write good code in a lot of cases.

The vast majority of the time you do not actually want to add the useless default, so you end up silencing the rule by adding code like `default: throw new Error("This shouldn't happen");`.

Instead it's better to make code typesafe and use union types. Then you can leverage a rule like

https://www.github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md
