### ISSUE TITLE
[Rule Proposal] `cast-caught-errors`

### ISSUE THREAD

**Issue by rattrayalex** [typescript-eslint/typescript-eslint#3831]
**Proposal**

```JSON
{
  "rules": {
    "@typescript-eslint/cast-caught-errors": "error",
  }
}
```

```TS
// Error:

try { 
  foo()
} catch (err) { // error: must cast caught exceptions.
  handle(err) // reason: we don't want to pass `any` here.
}

const foo = await getFoo().catch((err) => err); // error: must cast caught exceptions.
// reason: this will cause `foo` to be of type `any` instead of type `Foo | Error`.

// Success:
try { 
  foo()
} catch (err as Error) { // pass
  handle(err)
}

const foo = await getFoo().catch((err) => err as ApiError) // pass

// Note that `unknown` should be used when the error could be anything:
try {
  someThirdPartyPackage()
} catch (err as unknown) { // pass
  handle(err instanceof Error ? err : new Error(err))
}
```

**Comment by bradzacher** [comment]
This is not valid TS syntax.
```ts
try { 
  foo()
} catch (err as Error) { // pass
  handle(err)
}
```

This is valid syntax, but it can be considered superfluous syntax as of TS4.4 because they have added the compiler option `useUnknownInCatchVariables` which defaults catch variables too
```ts
try { 
  foo()
} catch (err: unknown) { // pass
  handle(err)
}
```

Note that the only annotation allowed for a catch variable are `any` or `unknown`. Why? Because any other annotation is unsafe as you can throw literally anything at all!

Also note that we have a rule that covers the case of enforcing an annotating on catch variables already [`no-implicit-any-catch`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-implicit-any-catch.md) - though it is being marked as deprecated in the next version due to the aforementioned TS compiler option making it redundant.

---

As for the `Promise.catch` case - considering TS has full support for async/await and for transpiling it to any target, it's probably better to just enable a rule like [`promise/prefer-await-to-then`](https://github.com/xjamundx/eslint-plugin-promise/blob/development/docs/rules/prefer-await-to-then.md) and just use async/await with a try/catch.

**Comment by rattrayalex** [comment]
Thanks @bradzacher ! The reason I got the `catch` syntax was wrong was that I actually prefer the `.catch` style; `try`/`catch` makes for an unpleasant flow of code in my opinion. I'd forgotten about the `any`/`unknown` restriction, and the new option for `unknown` defaults, because of this.

While anything _can_ be thrown, many functions will only throw certain errors. For example, I might construct an API Client which will only ever throw subclasses of `APIError`. In these cases, I'd like to be able to write code like this:

```ts
const result = await getFoo(params).catch(err => err as APIError);
if (result instanceof APIError) return handleAPIError(result)

useFoo(result); // now result is typed as Foo
```
In comparison:
```ts
let result: Foo;
try {
  const result = await getFoo(params);
} catch (error: unknown) {
  return handleAPIError(error as APIError)
}
useFoo(result);
```
7 vs 3 sloc is no joke! And many people, myself included, prefer to avoid `let`,  and also to avoid `try` blocks silencing logic errors rather than errors that come from I/O.

It is unfortunate that TS does not (yet?) have a facility to specify which kinds of errors a function might throw, but in the meantime, I prefer to specify like this than rely on `unknown` and `any`.

Would you consider a rule like this scoped only to use of `.catch()`?

**Comment by rattrayalex** [comment]
Pitching the necessity of this for `.catch()` a little more directly, `promise.catch(err => err)` will cause the result to be typed as `any`, no matter what – it is always type-unsafe! Far better to have to cast to `unknown` (when you're not sure what the error type is) or some kind of `Error` when you do know.

It seems that `no-implicit-any-catch` does not apply to `.catch()`, so some kind of equivalent may be warranted (though as you can tell, I prefer it have different behavior).

**Comment by bradzacher** [comment]
> While anything can be thrown, many functions will only throw certain errors.

True, they *should* only throw certain exceptions. Until they don't and then your application breaks because your `instanceof` no longer matches the error and you passed a different error object into your `useFoo` function call accidentally.

As a general rule of thumb you should try to avoid `as` assertions entirely because they [can easily and ***unknowingly*** introduce unsoundness into your codebase](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UDeBYAUFTUCGAuKAzsAE4CWAdgOYA06WUARvgwPYsA2E25taAvgG506AMYtyRKAA8EyRvhIBXaHxwFYQtOlIAzKAAopAOmxHOVYAAsE8RAAYAlMjpYA9K6gA9bz89QRxNgE1gAmylDALFCKEiwxIeQQBOoUJCxhIhAhjCARltBBagQQxMCk4uh8QA)

---

the "correct" try/catch version would instead be this as you don't need to move the code outside the block, and can continue your code within the `try`

```ts
try {
  const result = await getFoo(params);
  useFoo(result);
} catch (error: unknown) {
  if (error instanceof APIError) {
    return handleAPIError(error);
  } else {
    throw error;
  }
}
```

> 7 vs 3 sloc is no joke!

Technically you could also do use terse coding practices to shorten the above example to 1 line

```ts
try { useFoo(await getFoo(params)) } catch (error: unknown) { return handleAPIError(error as APIError) }

// or a less dumb 3
try {
  useFoo(await getFoo(params))
} catch (error: unknown) { return handleAPIError(error as APIError) }
```

And you could also rewrite your `.catch` example to a more padded 7 lines
```ts
const result = await getFoo(params)
  .catch(err => err as APIError);
if (result instanceof APIError) {
  return handleAPIError(result);
}
useFoo(result); // now result is typed as Foo
```

Line count is not a good metric to base standards on.
We could bikeshed about that till the cow comes home :)

> It is unfortunate that TS does not (yet?) have a facility to specify which kinds of errors a function might throw

The problem is that the only way to create a sound system for declaring thrown exceptions is to go the route of Java - which ends up infecting your entire call tree and quickly becomes ugly/unwieldy AF.


------------------


> Would you consider a rule like this scoped only to use of .catch()?

For this plugin - I would have to say no.

I think that's ultimately a bit to laser-targeted for this plugin.
Put another way - it's only *loosely* related to typescript by the fact that it enforces usage of a type-annotation.

It seems like a better fit for a plugin about promises, like `eslint-plugin-promises`.
If it were there it could also be built to support flow as well (with minimal effort) and thus have impact on more of the JS ecosystem.

**Comment by rattrayalex** [comment]
Yes, I'm familiar with all that. 

If you use prettier, you can't really condense `try`, and fundamentally it's still a statement, not an expression, which limits how you can clean up code. Putting `useFoo(result)` in the try is implying putting _everything_ you do with foo into the `try` block, which is both typically many lines of code and also often not what you want – only I/O should be caught.

Regardless, I think it's fair that this would be a bit narrow of a rule for this plugin, and I do understand why you might not want to encourage use of `as` – it is dangerous and you have to know what you're doing.

I appreciate the `eslint-plugin-promises` suggestion but I doubt they'd be interested in something so TS-specific. 

FYI Flow is largely [closing their doors to typical users](https://medium.com/flow-type/clarity-on-flows-direction-and-open-source-engagement-e721a4eb4d8b). I was on a core JS platform team at a relatively large company using Flow for a while and used it quite heavily, it was a great tool but I don't think it makes sense for the community to try to support it at this point.

**Comment by bradzacher** [comment]
I work at FB - I am well aware that flow does not have great support for OSS :)

But there is still a decent chunk of users using it in the wider world. Which is why plugins like `eslint-plugin-react` support it for their lint rules that deal with types.

**Comment by rattrayalex** [comment]
If I were to create this rule separately, is there a starting point you'd recommend? Perhaps a similar rule I could look at for inspiration?

**Comment by bradzacher** [comment]
ESLint rules are pretty straightforward to write - any of the non-typeaware lint rules in our repo are decent enough starts. `no-implicit-any-catch` is a pretty simple rule to start with.

The [eslint docs on writing rules](https://eslint.org/docs/developer-guide/working-with-rules) are also a good start to learn about the structure of a rule and how it works.

https://astexplorer.net/ is a great tool which will help you figure out the structure of the AST that you care about.

**Comment by rattrayalex** [comment]
Thanks!
