### ISSUE TITLE
Rule Proposal: Add rule corresponding to import-name rule of microsoft contrib

### ISSUE THREAD

**Issue by viditganpi** [typescript-eslint/typescript-eslint#3861]
The roadmap [here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md) suggests that currently `import-name` rule is not available and it suggests [this](https://github.com/import-js/eslint-plugin-import) plugin for same.
However, this plugin currently does not have a rule to replicate the behavior of `import-name` rule under `microsoft contrib`. Given that the `microsoft contrib` rules are used quite frequently, this rule will be a good addition to the `eslint-plugin`.

**Comment by bradzacher** [comment]
Thanks for the issue! This rule contains nothing specifically related to typescript, so it's not a good fit for this project.

Long ago we decided against 100% implementation of tslint rules because it made no sense to do so.

There is a PR for a similar rule that may serve your purpose here: https://github.com/import-js/eslint-plugin-import/issues/1041

Feel free to follow along or champion that if it has stalled.
