### ISSUE TITLE
Getting error `YAMLException: Cannot read config file: .eslintrc` when using the recommended `.eslintrc` with no extension

### ISSUE THREAD

**Issue by kenny1983** [typescript-eslint/typescript-eslint#3870]
- [ x ] I have tried restarting my IDE and the issue persists.
- [ x ] I have updated to the latest version of the packages.
- [ x ] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

1. Name your ESLint config file `.eslintrc` **with no extension** as suggested on the [npmjs homepage](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin#usage).
2. Ensure that its content is valid JSON as suggested by the examples given on that same page.
3. Run `eslint --fix --ext .js,.ts,.tsx` in your terminal.

**Expected Result**

ESLint works without a hitch.

**Actual Result**

ESLint crashes with the error mentioned in the title.

**Additional Info**

First of all I just want to say thanks for the great plugin 👍. This isn't really an *issue* per se; more like a complaint that your copy editor missed something that is crucial IMO. The plugin's *actual features* are all working great for me; much better than the last TypeScript ESLint plugin that I had. So for that, kudos 😄! 

Anyway the problem here is obvious: I am anal retentive, and took your suggestion on the page linked above very literally. So I renamed my `.eslintrc.js` file to `.eslintrc` as it said I should (or at least that's the way I interpreted it) and ended up with a confusing error.

Please consider changing those instructions to either say `.eslintrc.*` as per normal naming conventions, or **be explicit** (`.eslintrc.js`) since it **is usually** a JSON file.

I had to waste 10 minutes of my time Googling for the error and scratching my head before realising the obvious cause. I have now spent **more** time away from my *actual work* to report it to you guys. So a fastidious response would be very much appreciated. Thanks again 😄.

**Comment by bradzacher** [comment]
Sorry for the misunderstanding! The docs aren't suggesting you should rename your file - it's just a shorthand to reference all the different types of `.eslintrc` files, rather than listing out all 4 styles of naming it. There's no requirement to use any specific style of config as ESLint is what parses and handles it, not us!

**Comment by kenny1983** [comment]
Thanks @bradzacher, that's what I'd already figured out on my own, hence my suggestion to say `.eslintrc.*` instead of simply `.eslintrc`. Anyway I'm probably the only person who's anal retentive enough to have noticed this or be tripped up by it LOL. Just thought it might help others in the future though 😉.

**Comment by bradzacher** [comment]
> Anyway I'm probably the only person who's anal retentive enough to have noticed this or be tripped up by it LOL

Given that that particular line [has been in the docs since this project was created 5 years ago](https://github.com/typescript-eslint/typescript-eslint/commit/d2eed09f5711e16cac0cd64bd5950a39b0dfb3c8#diff-f9ef91c8d383354827e650514bcb021c3800229799b49959941bb854d3acac5fR29) I would say so!

Given this, I think the docs are fine as is.

Thanks for the issue!
