### ISSUE TITLE
[New Rule]: must-assign-nonvoid-function-call

### ISSUE THREAD

**Issue by mckravchyk** [typescript-eslint/typescript-eslint#3878]
It would be great to have a rule to disallow calling a non-void function without assigning it to a value.

```
function foo(): void {

}

function bar(): string {

}

foo(); // ok

bar(); // Error: Calling a non-void function without assigning it may be a mistake

const bar_ = bar(); // ok

```

## Use case - error handling

It would be especially useful with error handling - if you use the pattern to either return a result or an error. If the function does not send any meaningful output - that is, if it would be a void function if not for that it has to send an error - it's easy to overlook the error.

```

// This function does not return a meaningful value, but it may return an error result
function foo(): Ok<void> | Error {
  
}

foo(); // Deadly trap

```

Related:
https://github.com/supermacro/neverthrow/issues/212

**Comment by fregante** [comment]
This may be useful, but there are plenty of situations where a return value is just not used. For example `[].push(1)` returns `1`, but this is basically never used.

**Comment by bradzacher** [comment]
Yeah at its core this seems like a great idea - however there are many, many cases where methods return values that you don't want to use.

Two quick examples off the top of my head:
- array methods (examples `.push`, `.pop`, `.shift`, `.unshift`, `.some`, `.sort`)
- the "builder" pattern (methods that return `this` for chaining)

In general the exception to this rule would be "any function with a side-effect that returns a value should be ignored".  
Unfortunately [there's no way to declare a function as being "pure"](https://github.com/microsoft/TypeScript/issues/17181) - so there's no way to statically determine if a function has side-effects.

This means that there a big class of functions for which this proposal will false-positive. This alone makes me very reticent to accept this rule proposal.
For this rule to exist we would need a good way to mark functions as pure (or as impure) so that the rule can ignore them.

**Comment by fregante** [comment]
`void [].push(1)` could be such a way, but I'm pretty sure it'd just turn your files into _VoidScript_ because it will be so common 😃

**Comment by mckravchyk** [comment]
I think that it has potential to be usable if it also came with an option to define a whitelist of method and function names and the developer would add pop, push and other array methods.

Of course it depends on the codebase. I don't think I would run into this issue in mine - except the array methods that could be whitelisted and some eslint-disable-line's in rare cases .  It could still enable some folks that can afford to run it, run it - and it would be disabled by default, of course.

Or what do you think about going all out and checking the return type of the function? Is it possible to implement?

Say you would define that if a function return type matches Error - then the rule should be triggered. Match is a critical word here - i.e. the function  return type may be `true | CustomError` but `CustomError` extends `Error` so it's trigerred.

**Comment by bradzacher** [comment]
> if it also came with an option to define a whitelist of method and function names and the developer would add pop, push, other array methods and any other common method that could be a false positive

The problem with allowlists is that they aren't context sensitive - so they cause a different and many times worse issue - false negatives.

For example imagine if you allowlisted the method called `sort`. Well what happens if someone implements a custom class with a pure `sort` method? Now there's a false-negative and you've got broken code which lints fine.

Allowlists are a poor and hacky solution to linting problems and in general should be avoided and only used as an absolute last resort.

---

> Or what do you think about going all out and checking the return type of the function? Is it possible to implement?

The problem with this is again - the context matters. Say my config is `matchReturnType: ['Error']`.
Then the following code should error:

```ts
declare function foo(): Error;

foo(); // error - unused return value
```

But what happens if I do this:

```ts
class Error {}
declare function foo(): Error;

foo(); // will still error even though
// we're now returning a different "Error" to what the config intended
```

Context matters - so you would need to design a system to somehow provide the full context such that you won't get false positives or false negatives.

---

Another issue that's worth mentioning is performance. This sort of lint rule will be slow - we've learned this the hard way with rules like `no-floating-promise`.
The more types that a rule consumes the slower it is because types are all computed lazily.
So checking every single call expression as a statement will be costly.

Some people are all-in on type-aware linting, others aren't; so performance can be a factor in deciding if the rule is useful for someone.

This is a minor issue and one we don't hugely factor in.

---

It's worth noting that the maintainers have no time to work on this - so it'd be up to the community (or yourself) to implement this.

> I don't think I would run into this issue in mine - except the array methods that could be whitelisted and some eslint-disable-line's in rare cases .

I would hazard a guess that there are a lot of projects that would run into this. Which begs the question - if most people wouldn't turn this on due to false positives, does it belong in a general-purpose plugin like this project?

For this sort of thing I'd lean towards proving it out somewhere first and bringing into this project once it's known to be good.

This is the approach we've taken at FB a few times - first build a lint rule internally, run it and refine it on our codebase, and then push it upstream to a relevant eslint plugin or eslint core.

**Comment by mckravchyk** [comment]
I appreciate your feedback. You are right, it would make more sense as a third party plugin. I'm not sure if I will attempt it, as I'm still considering whether to abandon throwing exceptions in favor of returning errors. If I will make any plugin, I will post an update here.

As for false negatives, of course - but here in this case having false negatives may still provide benefit over no checks at all.

**Comment by bradzacher** [comment]
I definitely think it has value! But I don't think there's a good way to implement it cleanly; without copious false-positives or in a truly performant way.

For that reason - we're going to reject this proposal.
Thanks for raising an issue!
