### ISSUE TITLE
[non-nullable-type-assertion-style] wrong autofix for function calls with generic return value

### ISSUE THREAD

**Issue by FloEdelmann** [typescript-eslint/typescript-eslint#3938]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
    "@typescript-eslint/non-nullable-type-assertion-style": "error"
  }
}
```

```TS
import rewire from 'rewire'
const rewiredModule = rewire('./example-module')
const someFunction = rewiredModule.__get__('myFunc') as (() => void)
```

**Expected Result**

This rule warns about the `rewiredModule.__get__('myFunc') as (() => void)` part. According to https://github.com/typescript-eslint/typescript-eslint/issues/2887#issuecomment-747949438, this is expected. As `__get__` is a function with a generic type only used in the return type (see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/rewire/index.d.ts#L21)), I'd expect no autofix in this case, or this one:

```diff
  import rewire from 'rewire'
  const rewiredModule = rewire('./example-module')
- const someFunction = rewiredModule.__get__('myFunc') as (() => void)
+ const someFunction = rewiredModule.__get__<() => void>('myFunc')
```

**Actual Result**

The autofix applies this (wrong) change:

```diff
  import rewire from 'rewire'
  const rewiredModule = rewire('./example-module')
- const someFunction = rewiredModule.__get__('myFunc') as (() => void)
+ const someFunction = rewiredModule.__get__('myFunc')!
```

**Additional Info**

The `rewire` module's source code: https://github.com/jhnns/rewire

As [already suggested](https://github.com/typescript-eslint/typescript-eslint/issues/2887#issuecomment-747954210), the autofix could just become a suggestion instead.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `4.31.1` |
| `@typescript-eslint/parser`        | `4.31.1` |
| `TypeScript`                       | `4.3.4` |
| `ESLint`                           | `7.32.0` |
| `node`                             | `12.22.6` |

**Comment by bradzacher** [comment]
This shouldn't be reported by the rule - it's a false positive.

It's kind of a funny logic error.

https://github.com/typescript-eslint/typescript-eslint/blob/02c6ff3c5a558f9308d7166d524156dc12e32759/packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts#L54-L72

The logic for the rule does this:
1) get type of expression
2) get asserted type
3) filter nullish types from (1)
4) if all types from (2) in (3) and all types from (3) in (2)
    1) then report
    2) else ignore

In this case however (1) === (2) === (3) - but the rule doesn't check to see if there even was a non-nullish type in (1) - it just assumes there is.

More succinctly this bug can be triggered by this code:
```ts
const x = 1 as 1;
```

The fix is that the rule should ensure that (1) != (3) - something as simple as asserting the array lengths are not the same will do.
