### ISSUE TITLE
RuleCreator's types do not support rules without a documentation URL

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4133]
- [x] ~I have tried restarting my IDE and the issue persists.~ N/A
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TROUBLESHOOTING.md) and my problem is not listed.

**Repro**

Going off the code snippet here: https://github.com/typescript-eslint/typescript-eslint/pull/4124#discussion_r747998259

The recommended `RuleCreator` adds a requirement to provide a `urlCreator: (ruleName: string) => string` parameter. However, when writing rules that don't have a dedicated docs page -such as local one-of rules with [eslint-plugin-local-rules](https://www.npmjs.com/package/eslint-plugin-local-rules), there should not be a `url` attached.

Can we make that `urlCreator` optional so that the `docs` doesn't attach a `url` if not needed?

**Versions**

| package                                 | version |
| --------------------------------------- | ------- |
| `@typescript-eslint/experimental-utils` | `5.3.1` |
| `TypeScript`                            | N/A |
| `node`                                  | N/A |

**Comment by JoshuaKGoldberg** [comment]
Or, alternately, maybe export `createRule` on its own? 💡

**Comment by bradzacher** [comment]
It could probably be optional - yeah.
There's no *explicit* need for it - but it is definitely best-practice to provide one.

By providing a documentation URL, tools can link directly to the docs which helps people understand linting so, so much more! For example, this is how vscode-eslint gives users access to the docs:

(1) Via a quick-action:
![image](https://user-images.githubusercontent.com/7462525/141596983-4a177076-28d8-48b1-8246-5c43e3d89dd8.png)

(2) via a link on the "rule ID"
![image](https://user-images.githubusercontent.com/7462525/141596970-ca80e7de-29de-491f-bd38-a2f25c92cd29.png)

IMO it's probably better to have the default require the function so that docs are the default best-practice. Making it an optional arg means that people will probably just forget about it.
I'd be in support of providing another API like `createRuleWithoutDocs` so that a user can explicitly opt out of providing documentation.
