### ISSUE TITLE
Rework template for individual Rules pages

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4365]
Right now individual rules' pages have a somewhat unwieldy header based on their description. I'd like to swap that with a header equal to the rule name, and move that description into body text.

It'd be nice to also auto-generated an ESLint config snippet for enabling the rule...

![Screenshot of the huge header on https://typescript-eslint.io/rules/adjacent-overload-signatures](https://user-images.githubusercontent.com/3335181/147771032-aa774c83-1c39-46c7-88f9-f3c06ab3630b.png)

**Comment by bradzacher** [comment]
We used this style because it's the standard across the ESLint ecosystem.
I don't know if we should break from the standard unless we think it *really* imported the UX? Maybe we just need to work on better / clearer /ore succinct descriptions?

Examples:
https://eslint.org/docs/rules/array-callback-return
https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/consistent-test-it.md
https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/no-unresolved.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/better-regex.md

**Comment by JoshuaKGoldberg** [comment]
Oh that's very interesting. In general this is kind of a violation of what a heading is supposed to be, no? I don't know of any precedent for using the top level heading in a file to describe anything like this description. Is this exclusively in ESLint?

**Comment by bradzacher** [comment]
I think the idea is that the title is kind of just the tagline for the rule to help people figure out what it does at a glance to save them reading the entire page?

I'm not sure exactly! This convention came from people copying the ESLint core docs.

**Comment by JoshuaKGoldberg** [comment]
Moved to ESLint core: https://github.com/eslint/eslint/issues/15471

**Comment by JoshuaKGoldberg** [comment]
Per https://github.com/eslint/eslint/issues/15471 I think we can consider this accepting PRs! 🙌
