### ISSUE TITLE
[no-unsafe-assignment] diffrent with IDE (vular)

### ISSUE THREAD

**Issue by xtoolkit** [typescript-eslint/typescript-eslint#4466]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
  "root": true,
  "parser": "vue-eslint-parser",
  "parserOptions": {
    "parser": "@typescript-eslint/parser",
    "project": ["./tsconfig.json"],
    "tsconfigRootDir": ".",
    "extraFileExtensions": [".vue", ".scss"],
    "allowImportExportEverywhere": true,
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint", "vue", "prettier"],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:vue/base",
    "plugin:vue/vue3-recommended",
    "plugin:vue/vue3-essential",
    "plugin:vue/vue3-strongly-recommended",
    "prettier",
    "plugin:prettier/recommended"
  ],
  "rules": {
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        "argsIgnorePattern": "^_"
      }
    ],
    "vue/script-setup-uses-vars": "error",
    "prettier/prettier": "error"
  },
  "env": {
    "vue/setup-compiler-macros": true
  },
  "ignorePatterns": ["eslintrc.js"]
}
```

child vue component:
```vue
<template><i/></template>
<script lang="ts" setup>
export interface Props {
  layoutMode: 'static' | 'overlay' | 'slim' | 'horizontal'
}
defineProps<Props>()
</script>
```

parent vue component:
```vue
<template><i/></template>
<script lang="ts" setup>
import {ref} fron 'vue';
import type {Props} from './child.vue';
const layoutMode = ref<Props['layoutMode']>('static')
</script>
```

**Expected Result**

eslint understand Props type

**Actual Result**

In my IDE(vscode) with vular extention it's okay. but eslint think Props is any type!?

**Additional Info**

![screen shot](https://user-images.githubusercontent.com/8210666/150496519-6ea4ad54-ad11-4368-be65-821e56310416.png)

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.10.0` |
| `@typescript-eslint/parser`        | `5.10.0` |
| `TypeScript`                       | `4.5.4` |
| `ESLint`                           | `8.7.0` |
| `node`                             | `16.13.0` |

**Comment by bradzacher** [comment]
The state of Vue support is poor. Vue templates interspersing typescript inside html means that type-aware linting is very difficult to properly support out-of-the-box.

Your IDE works because it has extensions which create a custom language server for Vue files so that it can be understood as if it were a TS file.

Unfortunately nobody from the Vue community had been motivated enough to step up to help improve the state of the linting tooling. As such we're unfortunately stuck with this half-supported state.

If you can create a repro for this outside of Vue, then we can help further. But inside Vue we cannot provide support, sorry.
