### ISSUE TITLE
Current `parserOptions.project` implementation results in inconsistent paths

### ISSUE THREAD

**Issue by is-jonreeves** [typescript-eslint/typescript-eslint#4474]
## Existing Cases
There is already an existing ticket on this topic but it has been closed for comments for a while: https://github.com/typescript-eslint/typescript-eslint/issues/540

## Issue

I believe this is still an issue that should be addressed for two reasons:
1. Eslint will resolve a different path depending on how the project files are opened in VSCode.
2. The `{ "root": true }` does not impact this base path, but seems like it should.

## Reproduction

Consider the following MonoRepo structure:
```
.
├── MyRepo/
│   └── src/
│       ├── backend/
│       │   └── ...
│       └── frontend/
│           ├── admin/
│           │   ├── node_modules/
│           │   ├── src/
│           │   ├── .eslintrc
│           │   ├── package.json
│           │   └── tsconfig.json
│           └── client/
│               ├── config/
│               │   └── tsconfig.paths.json
│               ├── node_modules/
│               ├── src/
│               │   └── index.tsx
│               ├── .eslintrc                          <-- Going to Focus on this one
│               ├── package.json
│               └── tsconfig.json
├── .gitignore
└── README.md
```

Lets focus on `MyRepo/src/frontend/client/`. And assume the content of `.eslintrc` is:
```json
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  }
...
```

If we open the entire MonoRepo in VSCode then Eslint resolves the tsconfig.json as `MyRepo/tsconfig.json` and fails. However if we open the `client/` project directly it resolves `MyRepo/src/frontend/client/tsconfig.json` instead and works. This means Eslint only works if the right folder is opened.

This "feels" inconsistent with how Eslint works and even Typescript and NPM, which all seem to consider paths relative to the config files. For example if I add an override rule in `.eslintrc`, the file path is relative to the `.eslintrc` file. This rule below would impact `MyRepo/src/frontend/client/src/index.tsx`:
```json
...
  "overrides": [
    {
      "files": [ "./src/index.tsx" ],
      "rules": {
        "no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars": ["off"]
      }
    },
  ],
...
```
If I add an extends clause to the `tsconfig.json` the path is relative to that config file. This addition below would find file `MyRepo/src/frontend/client/config/tsconfig.paths.json`
```json
{
  "extends": "./config/tsconfig.paths.json",
...
```

Initially, I'd hoped that perhaps using the [Eslint option](https://eslint.org/docs/user-guide/configuring/configuration-files#cascading-and-hierarchy) `"root": true` would allow me overcome this issue, but it doesn't seem like `@typescript-eslint/parser` makes use of this either.

## Versions

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `4.28.3` |
| `TypeScript`                | `4.3.5` |
| `ESLint`                    | `7.30.0` |
| `node`                      | `16.8.0` |

**Comment by is-jonreeves** [comment]
For what its worth, the following glob can "appear" to workaround this issue:
```json
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./**/tsconfig.json"
...
```

**However**, I get the horrible feeling it could be using all the `tsconfig.json` files from the other projects in the monorepo, it's unclear.

**Comment by bradzacher** [comment]
`root: true` impacts how ESLint resolves configs. It has *nothing* to do with our tooling.

The only thing ESLint passes us is:
- the file contents
- the file path
- the parser options

The reason that ESLint doesn't pass us the config path is simple - because there are many cases where you may not have a config path or you might have multiple config paths. Eg passing config via CLI args, or passing config via API arguments, or having `N` cascading config files.

So if you configure `parserOptions.project` as a relative path, then we only feasibly have one physical point with which to anchor that path against - the current working directory.

But as you've noted, this is bad because it means that your config means a different thing depending on the directory from which you run your lint.

Which is why we have a parser option to tell us your project's root folder - `tsconfigRootDir`. If you provide this, we will use that as the root instead of the CWD.

https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionstsconfigrootdir

You can scroll up to read more about the behaviour of `project` as well.

**Comment by is-jonreeves** [comment]
Thanks for the response and the links. I had already gone through them pretty thoroughly before posting and indeed tried the suggested `tsconfigRootDir`. This didn't work for us because we are configuring using JSON via `.eslintrc` and not `.eslintrc.js`. Without the ability to access `__dirname`, the `tscondigRootDir` prop obviously has the same limitations as the `project` prop.

Sounds like, if we are working in a MonoRepo or happen to use different VSCode Workspaces to access to the code from dev-to-dev, the recommended approach is to use `__dirname` in a `.js` config instead, as noted in your Getting Started guide. I'll get us moved over. Cheers
