### ISSUE TITLE
[no-unsafe-*] Suggestion: have error/warning message reference the underlying "any" that's causing the problem

### ISSUE THREAD

**Issue by jrnail23** [typescript-eslint/typescript-eslint#4504]
When using the `no-unsafe-*` rules, I often encounter what seem to me to be false positives at a glance, but I assume they're triggered by something deeper than what I'm seeing.

As a way to help users figure out what actually needs to be fixed, would it be possible to include a reference to the `any` type that's underlying the reported error/warning?

**Comment by bradzacher** [comment]
Could you please provide some examples?
What do you mean by "reference the `any` type"?

**Comment by jrnail23** [comment]
Hi @bradzacher , when the `no-unsafe-*` rules are triggered, it's typically because you're trying to assign/destructure/etc. an `any` type, right?  Sometimes I find that those rules getting broken, but the variable in question isn't an `any` at all (and my IDE shows the expected type on hover). I assumed there was some kind of tracing in place to determine that the variable's typing had potentially been "contaminated" by `any` at some point, thereby making it unsafe, and as such, perhaps it could tell me where that's happening.
On the other hand, if none of that actually makes sense to you, maybe there's just something about my tsconfig/eslint config that's causing typescript-eslint to raise false positives here. 🤷‍♂️

**Comment by bradzacher** [comment]
The rules do not trace anything - they rely solely on types that TS tells us in order to operate.

If you are seeing false-positives regularly, then generally it means that the state within ESLint is out-of-sync with your IDE state. This can sometimes happen when you're working across multiple tsconfigs (projects).
An IDE reload should get it back in sync, but if it doesn't then generally that suggests config problems.

**Comment by jrnail23** [comment]
Thanks for the feedback, @bradzacher.  I'll see if I can get my configs tightened up a bit.
