### ISSUE TITLE
Support jsDoc/tsDoc in AST

### ISSUE THREAD

**Issue by marikaner** [typescript-eslint/typescript-eslint#4570]
_(Sorry for ignoring the template - this is a feature request. If this is not the right place for this, please let me know where to put this.)_

I want to build my own rules for API docs on TS code, because I can't find any appropriate rules for this \*. I found that `tsc` has information on API Docs in their resulting AST and if I'm not mistaken the `@typescript-eslint/parser` is based on the results from `tsc`. I am also aware of the `@microsoft/tsdoc` package, but this afaik looks only at docs, but not at the relation between docs and code.

I would love to have these information on API docs in the ESTree returned by the `@typescript-eslint/parser`, so that it gets easier to build rules around that.

_\* What I would like to have in a docs plugin:_
_- reports for missing comments_
_- reports for missing parameters/type parameters_
_- reports for documented parameters that do not exist in code_
_- reports for misnamed parameters_
_- options to tag parameters as internal)_

**Comment by bradzacher** [comment]
Thanks for the issue!

We won't be adding any tooling to our plugin to support parsing JSDoc because it's a can of worms to support and the vast, vast majority of users don't care for it (so it'd be niche, low impact work for the volunteer maintainers).

It's very possible to support JSDoc within your own plugin by just accessing the comments in the file.
For example you can access comments on a node using ESLint's [`context.getSourceCode().getComments[Before|After|Inside](node)`](https://eslint.org/docs/developer-guide/working-with-rules#contextgetsourcecode) API.
You can also access every single comment in the AST via via the root `Program` node (the `.comments` property).

You can then parse the comment string and handle it as you wish.
Consider reviewing a plugin like [`eslint-plugin-jsdoc`](https://www.npmjs.com/package/eslint-plugin-jsdoc) for how they support JSDoc.

**Comment by marikaner** [comment]
Thanks, that's actually quite helpful 😊

**Comment by marikaner** [comment]
@bradzacher 

I now played around with this and found that there is a `getJSDocComment` function that seems even more convenient. However this is not part of the typings (`context.getSourceCode() as any).getJSDocComment(node)`).

**Comment by bradzacher** [comment]
https://eslint.org/blog/2018/11/jsdoc-end-of-life

It's deprecated and set to be removed, hence it's not in the types.

**Comment by marikaner** [comment]
> https://eslint.org/blog/2018/11/jsdoc-end-of-life
> 
> It's deprecated and set to be removed, hence it's not in the types.

Oh, damn, thanks! Good to know.
