### ISSUE TITLE
Docs: Remove the redundant configuration from the Installation.

### ISSUE THREAD

**Issue by eai04191** [typescript-eslint/typescript-eslint#4596]
### Suggested Changes

In the [/docs/linting/README.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/README.md), parser and plugins are specified in config, but this is an unnecessary setting if `plugin:@typescript-eslint/recommended` is extended. I think the extra options can be confusing to anyone trying to set up.

Removing the parser and plugin makes the configuration much easier:
```js
module.exports = {
  root: true,
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
  ],
};
```
However, it's better to write why they can be omitted.

The same can be said for .eslintignore. As stated in the [ESLint documentation](https://eslint.org/docs/user-guide/configuring/ignoring-code#the-eslintignore-file), `node_modules/` is implicitly ignored and does not need to be specified.

### Affected URL(s)

https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/README.md

**Comment by bradzacher** [comment]
Thanks for the suggestion!
It is unnecessary, but it's good to have it there so that people can see what is required.

Most people don't interrogate the recommended configs - so they don't know that it's set.
So if someone is coming to our guides to setup and don't want to use the recommended config, then they won't know that the parser is required.
This also allows the guide to have a point about the parser config and what it means - which helps explain how the system works to users.
