### ISSUE TITLE
Improve documentation for `typescript/no-unused-vars`

### ISSUE THREAD

**Issue by OliverJAsh** [typescript-eslint/typescript-eslint#46]
There are several use cases `typescript/no-unused-vars` does not yet support, such as `type` declarations:

``` ts
type Foo = string;
// unexpected error
const foo: Foo = 'foo';
```

Would it be possible to track the status of this somewhere in the documentation? The docs for `typescript/no-unused-vars` do not make any mention of this.

I would be happy to raise a PR, but I don't know the full details of what is and isn't supported.

**Comment by ThomasdenH** [comment]
Another false positive:
```
declare type Checker = (v) => v is number;
const checker: Checker = (w): w is number => true;
```
Here `w` is used in the type guard, but according to the lint it's unused.

**Comment by ThomasdenH** [comment]
Also, since this lint seems to be mostly covered by the Typescript option, maybe it's a good idea to remove it from `/recommended`?

**Comment by bradzacher** [comment]
@ThomasdenH - please raise that error as a separate issue.
This issue is about documentation.

There is discussion about no-unused-vars in the recommended set in #122.

Considering we're working on improving this constantly, I'm going to close this issue.
The team is fixing edge cases and working for a better solution to this.

**Comment by kevinmarrec** [comment]
@bradzacher Does your last comment mean that the issue regarding `no-unused-vars` will be fixed in next release(s) ?

Cause it causes frustation to have to disable the `no-unused-vars` rule for the whole project (even JS files) to be able lint without errors typescript files that are simply using type or interface definitions.

My, minimal reproduction is

```ts
import { IOptions } from './types'
const options: IOptions = {}
... // Use `options` later
```
resulting in
```
'IOptions' is defined but never used
```

Where should we follow the status on this ? We should have a not-closed issue pending until it's not fixed. After more than 1 hour figuring what's going on with the severals issues refering to `no-unused-vars`, this issue seemed the one where people exposed

**Comment by bradzacher** [comment]
@kevinmarrec - which issue? There are a number of edge cases that aren't properly covered by the rule. Some we know about, many we don't.

This issue is specifically about attempting to document the cases that are currently unsupported, but it has accidentally gone off the rails and become a place people are putting bug reports.

A growing thread which has a mixture between discussions, bug reports and examples is not a good way to document issues with the rule. One issue opened per bug, on the other hand, clearly documents what problems are known and open with the rule.

It's very hard to track which bugs are fixed if they are all logged as comments in a single thread: a thread isn't easily searchable, we can't close comments once their issue is fixed, and we can't clearly link to comments in PRs.

This the primary reason I've closed this issue.

Please open a new issue if you find a case that's not properly covered by it so that we can track it easier.
Please use the search first to double check that your bug isn't already logged.

**Comment by kevinmarrec** [comment]
Alright @bradzacher, I understand.

The issue is that `typescript-eslint` simply tag `types` and `interfaces` (that are imported or defined in the file) as unused, even if they are.

Well for my specific case I ended up with this workaround
```
overrides: [
    {
      files: ['*.ts', '*.tsx'],
      rules: {
        '@typescript-eslint/no-unused-vars': [2, { args: 'none' }]
      }
    }
  ]
```
which seems to fit my use case, but I think it should work without having to do this workaround.

**Comment by IgorMing** [comment]
Thank you @kevinmarrec! It's working fine, now.

**Comment by leomotta121** [comment]
@kevinmarrec Thank you!

**Comment by tvvignesh** [comment]
@bradzacher : I had the same problem. The solution which @kevinmarrec provided worked for me as well. using 2.6.1 version of the plugin.
