### ISSUE TITLE
[@typescript-eslint/no-unused-vars] does not work?

### ISSUE THREAD

**Issue by AnderssonPeter** [typescript-eslint/typescript-eslint#4617]
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```JSON
{
  "rules": {
     "no-unused-vars": "off",
     "@typescript-eslint/no-unused-vars": ["warn", { "vars": "all", "args": "all" }],
  }
}
```

```TS
@Injectable()
export class BackendCommunicationService {
    private keepRotating = false; <-- unused

    constructor(
        private logger: Logger, <-- unused
        private database: Database, <-- unused
        private http: HttpClient
    ) {}
```

tsconfig
```JSON
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2021",
    "module": "es2020",
    "lib": [
      "es2021",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

```

**Expected Result**

It should warn me about the unused fields/properties.

**Actual Result**

No warning is given

**Additional Info**

I'm using Angular 13, How do i generate a debug lint? (Normally I just run `ng lint` but it doesn't seem to have a debug flag

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.13.0` |
| `@typescript-eslint/parser`        | `5.13.0` |
| `TypeScript`                       | `4.5.5` |
| `ESLint`                           | `8.10.0` |
| `node`                             | `14.17.6` |

**Comment by JoshuaKGoldberg** [comment]
`no-unused-vars` is specifically for _variables_, not class properties. https://typescript-eslint.io/rules/no-unused-vars -> https://eslint.org/docs/rules/no-unused-vars

I think it'd be reasonable to add in a rule like `no-unused-class-members` that suggests removing `private` ones. Note that it'd have to be a _suggestion_ rather than a _fix_ (https://eslint.org/docs/developer-guide/working-with-rules): https://github.com/typescript-eslint/typescript-eslint/issues/4571#issuecomment-1044838757.

> #private members are completely safe to mark as unused because they are 100%, runtime enforced to be only accessible within the class they are defined.
> 
> However `private` members are not. They are accessible outside the class via `instance['member']` (yes, that's valid and safe TS). And are ultimately just type-only sugar for a normal class member.
> 
> Which means we cannot statically detect the valid usages across module boundaries.
> 
> This is generally I would recommend using #private instead of `private` in all modern code.

In the meantime TypeScript's built-in `noUnusedLocals` setting can catch unused class members.

**Comment by JoshuaKGoldberg** [comment]
`no-unused-vars` is specifically for _variables_, not class properties. https://typescript-eslint.io/rules/no-unused-vars -> https://eslint.org/docs/rules/no-unused-vars

I think it'd be reasonable to add in a rule like `no-unused-class-members` that suggests removing `private` ones. Note that it'd have to be a _suggestion_ rather than a _fix_ (https://eslint.org/docs/developer-guide/working-with-rules): https://github.com/typescript-eslint/typescript-eslint/issues/4571#issuecomment-1044838757.

> #private members are completely safe to mark as unused because they are 100%, runtime enforced to be only accessible within the class they are defined.
> 
> However `private` members are not. They are accessible outside the class via `instance['member']` (yes, that's valid and safe TS). And are ultimately just type-only sugar for a normal class member.
> 
> Which means we cannot statically detect the valid usages across module boundaries.
> 
> This is generally I would recommend using #private instead of `private` in all modern code.

In the meantime TypeScript's built-in `noUnusedLocals` setting can catch unused class members.

cc @bradzacher since I know you've worked around this area a bunch in the past.

**Comment by bradzacher** [comment]
Yeah we definitely could implement a `private` class member rule as suggested in #4571. It's probably a good idea so that we can further help people migrate off of the TS flag.

Though this definitely shouldn't be implemented within `no-unused-vars` - as you mention it's for ***variables***, and properties aren't variables.

So I'll close this and tag #4571 as accepting PRs.

**Comment by ChristianHardy** [comment]
Greetings, I have an error using `no-unused-vars` @bradzacher can you give me a hand with this?

![image](https://user-images.githubusercontent.com/9417617/159543226-26ad708d-334f-4c1e-a256-338b0bd22969.png)
