### ISSUE TITLE
[explicit-function-return-type] option to allow arrow functions with concise body syntax without an explicit return type (feature request)

### ISSUE THREAD

**Issue by dscheerens** [typescript-eslint/typescript-eslint#4621]
This is not really an issue but a feature request: one for which I will be happy to submit a pull request if it has a chance of making it in. I apologize if this has already been requested before, but I wasn't able to find such a feature request. 

So, basically this feature would be to add another option that acts as an exception to allow arrow functions with a concise body syntax (i.e. implicit returns).

Let's say this option is called `allowArrowFunctionsWithConciseBody`, then if this option is enabled it will allow the following:

✔ Correct:
```typescript
const isEven = (value: number) => value % 2 === 0;

const isBlank = (value: string | undefined | null) => (value?.length ?? 0) > 0;

const square = (value: number) => number * number;
```

❌ Incorrect:
```typescript
const isEven = (value: number) => {
  return value % 2 === 0;
}

const isBlank = function (value: string | undefined | null) {
  return (value?.length ?? 0) > 0;
}

function square(value: number) {
  return value * value;
}
```

Motivation:

Although this is not a form I use very frequently I do use it sometimes for very simple functions, where the return type is obvious. This can also be useful in the context of classes when there is need to access the class instance via `this`, without having to explicitly bind the function context first.

None of the existing options allow for this use case without having the completely turn the `explicit-function-return-type` off.

Please let me know if this is an option that would be an acceptable extension for this rule. As stated before, if that is the case, I will be happy to implement it and submit a PR.

**Comment by bradzacher** [comment]
There are a few options which can achieve what you want in a manner of speaking:

[`allowDirectConstAssertionInArrowFunctions`](https://typescript-eslint.io/rules/explicit-function-return-type/#allowdirectconstassertioninarrowfunctions) can be used if you're returning an object, array or any other literal from your arrow function.

[`allowTypedFunctionExpressions`](https://typescript-eslint.io/rules/explicit-function-return-type/#allowtypedfunctionexpressions) can be used to annotate the declaration instead:

```ts
const isEven: (v: number) => boolean = value => value % 2 === 0;

const isBlank: (v: string | undefined | null) => boolean = value => (value?.length ?? 0) > 0;

const square: (v: number) => number = value => number * number;
```

> where the return type is obvious

This is a dubious statement. What does it mean for the return type to be obvious? Is it "obvious" solely because they're binary/logical expressions?
But what about `() => someFnCall()` - is this "obvious"? Clearly not - but it's still a concise bodyless function that's really simple.

What are the rules around such a rule?

Additionally in your correct examples - sure they can be parsed by the reader to understand their return type - but what makes them any more special or more clear than your incorrect cases?

----

Ultimately the point of the rule is to ensure you have strict contracts in your code.

As an example if we tweak one of your examples slightly because we forgot the precedence of operators

```ts
const isBlank = (value: string | undefined | null) => value?.length ?? 0 > 0
```

Is the return type of this obvious? A cursory glance would say "this always returns a boolean", but it doesn't - it returns `number | boolean`. Our contract has been broken because we didn't declare one!

This is why I am against such an option.

**Comment by dscheerens** [comment]
Thanks for your reply.

The `allowDirectConstAssertionInArrowFunctions` would definitely work for some cases, but not for all.

These are typically functions that I would be using solely as part of the implementation of other functions and don't wish for them to be public/exported. Within that context the return type often is obvious and even if you do make a mistake like the one you've illustrated the error is spotted right away in the same function where you're using it (because you'll end up with compile errors).

However, I see your point that this option opens potential issues when no explicit contract is present if they are exposed. So, in light of that I understand why you are against such an option. Thanks for considering it and explaining your concerns. I will withdraw the feature request.

I will probably implement this option anyway for personal use, but with with the added restriction that this will only be used inside other functions and not be exposed on a global level, e.g.:

```typescript
function evenNumbers(numbers: number[]): number[] {
  const isEven = (value: number) => value % 2 === 0; // ✔ correct -- defined inside a function

  return numbers.filter(isEven);
}

const square: (v: number) => number = value => number * number; // ❌ incorrect -- defined at global scope
```
