### ISSUE TITLE
[naming-convention] accept non-primitive types

### ISSUE THREAD

**Issue by bgerstle-quot** [typescript-eslint/typescript-eslint#4672]
I would like to be able to select non-primitive types in the types section, but it seems like only primitives are supported. The specific use case for me is for observables. Generally we try to name all observableLike (Observable, Subject, etc.) objects with a dollar sign at the end. From my understanding from your documentation this isn't possible since the type selection only accepts primitives. (I also tested it and got an error, but I figured the documentation was a better source of truth). Here is an example of the rule I would want to work:
```
{
  "selector": "default",
  "types": "Observable",
  "format": [
    "camelCase"
  ],
  "custom": {
    "regex": ".*\\$",
    "match": true
  }
```
Is this something that would be possible to implement?

**Comment by bradzacher** [comment]
Thanks for the request!

This isn't really possible to do because there's no concrete type for "Observable" like there is for the primitive types. For the primitive types implemented we can use the TS APIs to inspect the type of the name and determine if it's callable, or a string-like, or an array-like, etc.

However there's no API to ask "is this the type named `Observable`?" for a few reasons:
1) What does it mean to be the custom type named observable?
1) What is the difference between the `Observable` defined in file X vs one defined in file Y?
1) It's really easy for you to change the apparent name of a type by aliasing it:
```ts
class Observable<T> {}

type Foo = Observable<string>;

const x: Foo; // x's type name is `Foo`, not `Observable`
```
