### ISSUE TITLE
[prefer-readonly-parameter-types] add option to only check exported function signatures

### ISSUE THREAD

**Issue by qpwo** [typescript-eslint/typescript-eslint#4696]
1. How hard would it be to make `prefer-readonly-parameter-types` fixable?
2. How hard would it be to add an option to only apply the rule to exported functions?

If you could do both 1 & 2, then popular libraries could instantly make their API totally readonly! That in turn would make it much easier to use readonly types inside large apps and tools. It could be a big step towards immutability/FP for the typescript ecosystem.

---

Now here's another piece, but I don't know how realistic it is.

3. Would it be possible to specify a "readonly caster" in the rule's options? 

Because one of the big obstacles to using readonly is that it's somewhat verbose:

```ts
function f(arg: { readonly name: string; readonly id: string, readonly things: []}) {}
```

But this is ameliorated with [`DeepReadonly`](https://gist.github.com/qpwo/a228cc81f8a11a553f385c93a56064f3). Suppose you had it aliased to `RO`. The above snippet becomes

```ts
function f(arg: RO<{ name: string; id: string, things: [] }>) {}
```

If it was in any way possible to get all of 1 & 2 & 3 then adoption of explicitly immutable args could dramatically increase, I think.

## See also

- There's a massive [discussion](https://github.com/microsoft/TypeScript/issues/42357) on typescript itself to permit readonly-everywhere by default if you're not aware.
- [eslint-plugin-functional](https://github.com/jonaskello/eslint-plugin-functional)
- obviously countless other efforts throughout the ecosystem for immutability, from immutablejs to immer to even elm....

---

(It's not a rule proposal but it's not a bug either so I hope I chose my issue template correctly.)

**Comment by bradzacher** [comment]
> How hard would it be to make prefer-readonly-parameter-types fixable?

It is not possible. It is unsafe to convert a mutable type to a readonly type.
Rule number 1 of fixers is don't break the build.

Even a suggestion fixer is mostly impossible.

```ts
type T = { a: { b: string } };

function foo(arg: T) {}
```

How do you make `T` readonly from just the function signature?
With just builtin TS types - you cannot, you need to define a "deep readonly" type.

Simple types like `string[]` or single-level objects - sure you can fix - but otherwise (i.e. most cases) not doable.

----

> How hard would it be to add an option to only apply the rule to exported functions?

This is much easier to do. I do like the idea of just making the module boundaries strictly readonly for the same reason I like `explicit-module-boundary-types`.

The only thing I'd say about this is that in most cases if your module boundary is readonly then most of of your code probably also needs to be readonly. Readonly is infectious like that because you need to pass readonly things to other functions.

----

cc @RebeccaStevens as I know you care about this class of thing.

**Comment by RebeccaStevens** [comment]
This is the sort of thing I'd like to be able to support, but figuring out the details of how it would work has been proving very difficult.

One issue is that due to TypeScript limitations, it is currently not possible to create a `DeepReadonly` utility type that covers every case (call signatures are the main thing that cause problems with this). Hence, we can't just wrap a type in `DeepReadonly` and assume it is good.
One possible way to get around this issue would be if users configured a list of mutable to readonly types.

Another thing we'd need to figure out is [Readonlyness vs Immutability](https://github.com/typescript-eslint/typescript-eslint/issues/4536).

**Comment by qpwo** [comment]
Mm it seems you all have thought deeply about this. I wonder if this fundamentally extends beyond an eslint plugin... It is mentioned in that 42357 discussion I linked that inferring whether data is mutated requires digging into the dependencies a bit or else somewhat heavy layering on top of them.

Is it even possible with typescript types to indicate whether a class method mutates `this`?  ... I suppose you could have the class implement an interface where the method takes a `readonly this` or something.

Anyway thanks for the thoughts you shared 😁

**Comment by bradzacher** [comment]
Thinking about this more:

(1) autofix is not possible - as described above.

(2) I do see *some* value in having an option which limits it to exported signatures only. However the intersection between "projects that want to use this rule" and "projects that want to only check exported signatures" is going to be super small. (The former is already a very small %age of our userbase to begin with).

Because it's not going to be broadly applicable - I don't think that there is a lot of value in  adding an option for this. It would be a not-insignificant amount of effort to define and handle all of the cases which may or may not be considered "exported".

For this reason I'm going to close this issue.
