### ISSUE TITLE
Converting rules to be in TypeScript

### ISSUE THREAD

**Issue by aboyton** [typescript-eslint/typescript-eslint#47]
I was wondering people's thoughts of switching this repository over to using TypeScript. Personally I find it much easier to code using TypeScript, especially on an unfamiliar codebase. One of the nice things about developing rules on TSLint is that you can write rules in either TypeScript or JavaScript.

I was thus curious had we considered allowing people to write rules with TypeScript?

**Comment by 43081j** [comment]
Hello 👋 

Just as an FYI, we currently write our rules in typescript over at 43081j/eslint-plugin-lit so I had a poke around this repo too to see how difficult it is to do the same.

It is all fairly straight forward using `@types/estree` and `@types/eslint`. However, you will struggle when dealing with the custom AST nodes we make use of here (e.g. `TSDeclareFunction`). If you exported your AST node types in a typescript definition file somewhere, you could possibly do some interface merging to sort this.

Also turning on all strict options and inheriting the base `tsconfig.json` you have seems to work nicely once `util` is cleaned up to be stronger typed.

**Comment by bradzacher** [comment]
I started working on this today! [branch:`migrate-plugin-to-ts`](https://github.com/typescript-eslint/typescript-eslint/tree/migrate-plugin-to-ts)
The problem is that we don't have type definitions for the extensions and new nodes added by typescript-estree yet.

Don't hugely want to manually write them all out; [there's a quite few cases](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/convert.ts#L468-L2600) to make sure we've covered correctly, plus we'd have to keep them in sync.

@armano2 has been working on ways to [auto generate it](https://github.com/armano2/typescript-estree-test/blob/master/typescript-estree.types.d.ts).

We just need to decide which is the best way forward for that.

**Comment by 43081j** [comment]
Ah great I'll take a look through the branch. 

We should probably generate the types at build time like Babel does. They simply iterate through an array of node types and output a typescript file. 

I'd also recommend the strict settings in typescript so we maintain nice strong types (especially no implicit any).

**Comment by 43081j** [comment]
A pr would be nice btw, as I have a few other suggestions (I know it's early stages 🙊)
