### ISSUE TITLE
[explicit-function-return-type] Add suggestion fixer

### ISSUE THREAD

**Issue by ilyub** [typescript-eslint/typescript-eslint#4751]
**Repro**

```TS
function f(x: boolean) {
  if (x) return 1;

  return "a";
}
```

**Expected Result**

When linting from command line, show error, but do not fix.

Inside editor (e.g. vscode) suggest a fix:
```TS
function f(x: boolean): 1 | "a" {
  if (x) return 1;

  return "a";
}
```

**Actual Result**

No fix suggested inside vscode.

**Comment by bradzacher** [comment]
Thanks for the issue!
I've thought about this in the past. However we can't OD it for three reasons:

First and foremost - in order to do this we would need to add type information to the rule, which is a big breaking change that precludes a lot of users from using the rule - and thus not one we're going to make.

Second is that a main driver for this rule if declaring strict boundaries as defined by the engineer. If you're just using the suggested type that TS detects - you aren't *really* strictly declaring anything.

Finally is that there are going to be a lot of times the fixer inserts a crappy type or adds really bad formatting. Esp with complex unions, object types, conditional types - the exact type to print could be ugly. Or the human could know a much much better type that has an alias ready to go.
