### ISSUE TITLE
`eslint-recommended` defines its rules as `overrides` for `*.ts` and `*.tsx` files

### ISSUE THREAD

**Issue by DetachHead** [typescript-eslint/typescript-eslint#4803]
this means extending `plugin:@typescript-eslint/recommended` doesn't work for other file types, for example `*.svelte`.

https://github.com/typescript-eslint/typescript-eslint/blob/0126b4f56f9197d561e90b09962ccceb4f88bc41/packages/eslint-plugin/src/configs/eslint-recommended.ts#L7-L9

imo it's not necessary to restrict the ruleset to these filetypes because you wouldn't use it unless you were using typescript.

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

```js
//.eslintrc.cjs
module.exports = {
    extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
    plugins: ['svelte3', '@typescript-eslint'],
    overrides: [
        {
            files: ['*.svelte'],
            processor: 'svelte3/svelte3',
            // WORKAROUND:
            // rules: require('@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended')
            //     .overrides[0].rules,
        },
    ],
    settings: {
        'svelte3/typescript': true, // load TypeScript as peer dependency
    },
}

```

```TS
//main.ts
var foo = 1 //error (no-var)
```
```svelte
<!-- App.svelte -->
<script lang="ts">
    var foo = 1 //no error
</script>
```

**Expected Result**
error in both `*.ts` and `*.svelte` files

**Actual Result**
only error in `*.ts` files

**Additional Info**

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.18.0` |
| `@typescript-eslint/parser`        | `5.18.0` |
| `TypeScript`                       | `4.7.0-beta` |
| `ESLint`                           | `8.13.0` |
| `node`                             | `16.9.1` |

**Comment by bradzacher** [comment]
This is very much done on purpose for two reasons;

1) it means that you don't need to add `--ext .ts` on the cli. Eslint detects the globs and adds the extensions automatically.
2) it means we aren't modifying the core recommended set on files that don't have TS checks. The rules we turn off because TS does the checks better. But if TS isn't checking then turning them off is wrong.

We aim to support TS and provide the best exefor TS. Misc frameworks with non-standard extensions are outside our purview. If we can support them without degrading TS support - great! Otherwise those framework communities are free to build on top of our tooling.
