### ISSUE TITLE
Erroring in `IntelliJ`

### ISSUE THREAD

**Issue by r-priyam** [typescript-eslint/typescript-eslint#4874]
- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest version of the packages.
- [x] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

**Repro**

I haven't created any repro to be specific since the repo is public, here's the link - https://github.com/r-priyam/expecto-patronum

`.eslintrc.json` -
```JSON
{
	"extends": ["@sapphire", "xo", "xo-typescript", "plugin:prettier/recommended"],
	"plugins": ["@typescript-eslint", "prettier", "import"],
	"parserOptions": {
		"project": "./tsconfig.eslint.json"
	},
	"ignorePatterns": ["/*.*"],
	"rules": {
		"import/order": [
			"error",
			{
				"groups": ["builtin", "external", "internal", "index", "sibling", "parent"],
				"alphabetize": {
					"order": "asc"
				}
			}
		],
		"import/first": "error",
		"import/no-duplicates": "error",
		"import/newline-after-import": "error",
		"new-cap": "off",
		"curly": [2, "all"],
		"no-await-in-loop": "off",
		"@typescript-eslint/no-unsafe-call": "off",
		"@typescript-eslint/no-unsafe-assignment": "off",
		"@typescript-eslint/restrict-template-expressions": "off",
		"@typescript-eslint/consistent-type-imports": ["error", { "prefer": "type-imports", "disallowTypeAnnotations": false }]
	}
}
```
`tsconfig.eslint.json`
```JSON
{
	"extends": "./tsconfig.base.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true
	},
	"include": ["src"]
}
```

**Expected Result**

It shouldn't error when inspect code in directory is run.

**Actual Result**

![image](https://user-images.githubusercontent.com/50884372/165565137-3be4ff7a-ee58-49f4-ae17-2704b2c454fb.png)

When I do this in IDE -
![image](https://user-images.githubusercontent.com/50884372/165566110-a2872292-0fae-4d50-b0cc-dd47bbdcf3cc.png)

It results into -

![image](https://user-images.githubusercontent.com/50884372/165566291-db464a2e-25ef-4edc-a895-819ce56c2f27.png)

**Additional Info**

When running `eslint --ext ".ts,.js" src --debug` in terminal it just works fine -

![image](https://user-images.githubusercontent.com/50884372/165565845-aa764343-e6a2-42d0-bef8-b09c6c98a117.png)

ESLint config of IDE -
![image](https://user-images.githubusercontent.com/50884372/165565315-f6f3295b-667b-416d-92ad-e28cb83544ff.png)

**Versions**

| package                     | version |
| --------------------------- | ------- |
| `@typescript-eslint/parser` | `5.21.0` |
| `TypeScript`                | `4.6.3` |
| `ESLint`                    | `8.14.0` |
| `node`                      | `18.0.0` |

It just works fine on `VSC`

**Comment by bradzacher** [comment]
A bunch of screenshots is a bit hard for us to look into, and IDE specifics are well outside our support domain - but if i had to hazard a guess based on the info you've provided - you're running your eslint cli from your project root, but the root for your IDE is the `src` folder.

You haven't provided `tsconfigRootDir` in your config. Which means we don't know what the root is. Without this option we use the current working directory as the root for relative paths.

So it works in the CLI because you're at the project root, but it fails in the IDE because you're not. I.e. CLI uses `<root>/tsconfig.eslint.json`, and IDE uses `<root>/src/tsconfig.eslint.json`.

https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionstsconfigrootdir

Set `tsconfigRootDir` in your eslint config to tell us the concrete root of your project, then it should work.
Beyond that - it's pretty much impossible for us to provide any support here based on IDE specifics for your project when

**Comment by r-priyam** [comment]
Uh ok guess I found it, https://youtrack.jetbrains.com/issue/WEB-52564/ESLint-complains-about-parsing-error-and-file-not-matching-proje
