### ISSUE TITLE
Docs: Add our opinion on delegating stylistic issues to a tool such as Prettier

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#4907]
### Suggested Changes

We recommend people use Prettier or an equivalent tool for formatting concerns. You should not be primarily using ESLint to manage your whitespace. Linters are not well-suited to that concern.

I think this should be mentioned on the website somewhere. That way, when someone has troubles with formatting -or mentions it in the issue tracker- we have a good canonical docs site location to send them.

A few random supporting things:

* https://typescript-eslint.io/docs/linting/troubleshooting/#the-indent--typescript-eslintindent-rules: the closest thing to a recommendation I could find on our site
* https://github.com/typescript-eslint/tslint-to-eslint-config/blob/main/docs/FAQs.md#should-i-use-prettier
* Todo: where is the ESLint team's opinion on this? I swear I saw it somewhere...

### Affected URL(s)

Maybe https://typescript-eslint.io/docs/linting/troubleshooting?

**Comment by Josh-Cena** [comment]
FWIW, I know a non-trivial number of people who hate Prettier with a passion and would rather configure all the ESLint formatting rules. The broken indent rule is unfortunate and understandable, but it should not justify a linter actively depreciating its own work. I don't _quite_ remember the ESLint team wanting to freeze their formatting rules; if at all, they've restricted new rules to new ES features, which means if there are new syntax constructs, they would probably update their formatting rules as well. (I could be wrong.) Having both formatting rules and an admonition saying "don't use it unless you want [insert zalgo]" is... confusing, to say the least.

**Comment by bradzacher** [comment]
> I don't quite remember the ESLint team wanting to freeze their formatting rules

https://eslint.org/blog/2020/05/changes-to-rules-policies#what-are-the-changes

> Stylistic rules are frozen - we won't be adding any more options to stylistic rules. We've learned that there's no way to satisfy everyone's personal preferences, and most of the rules already have a lot of difficult-to-understand options. Stylistic rules are those related to spacing, conventions, and generally anything that does not highlight an error or a better way to do something. Update 2021-01-29: We clarified in the README that we will still support newly-added ECMAScript features.

They're not changing existing rules at all except to add support for new syntax if it makes sense to.

And new rules are limited and won't be accepted unless they're in the narrow scope of new rules about new language features that don't just ban syntax.

> New rules are limited - we will only accept new rules when they relate to new ECMAScript features that reached stage 4 in the preceding 12 months. The community relies on ESLint to help teach them the correct way to use new language features, and we want to continue doing that. We won't be accepting new rules that are suggestions or preferences unrelated to new ECMAScript features.

**Comment by Josh-Cena** [comment]
Ah, yes, that's the one I remember about "restricted new rules to new ES features" 😄

I'm not against recommending Prettier, I'm saying we should not do it in the spirit of deflecting reports about problems in our own rule implementation.

**Comment by bradzacher** [comment]
> FWIW, I know a non-trivial number of people who hate Prettier with a passion and would rather configure all the ESLint formatting rules.

I used to be one of them. When I started really using eslint some 6 years ago I didn't use prettier at all and manually configured every single lint rule under the sun to provide a completely custom linting experience.

I remember holding an entire day workshop with my team so we could go through every single rule and vote on how we wanted our code style to work.

Then I joined FB/Meta. At Meta the main JS codebases have prettier turned on. You have no choice but to use it. You have to jump through hoops to land code without formatting it and even then a bot will come through each night and land a change which formats your code.

I hated it when I started. I AM THE HUMAN - how DARE a tool change the code I wrote automatically. I wrote it how I wrote it on purpose.
Then after about a week of fighting it something flipped in me and I realised the incredible value of having code that is formatted in exactly the same way everywhere. I fell in love with it.
Stylistic eslint rules are ultimately flawed because they are very imprecise. This leaves gaps in coverage where personal codestyle can get injected into the codebase - which causes conflict.

The indent rule is a prime example of this because [it doesn't even enforce what people think it does](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IFwiaW5kZW50XCI6IFtcImVycm9yXCJdICovXG5cbmNvbnN0IHggPVxuMTtcblxuY29uc3QgeSA9XG4gICAgICAgICAgICAgICAgICAyO1xuXG5mdW5jdGlvbiBmb28oKSB7XG5cbiB9IC8vIHByb3ZpbmcgdGhlIHJ1bGUgaXMgd29ya2luZ1xuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMiwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==). It's entirely fallible and incomplete. So people have to nitpick style anyways.

But prettier isn't. It's exact and (barring rare bugs) is consistent and reproducible.

On any codebase that uses prettier (like at Meta) there's never any comments on diffs about spacing or brace placement because it's not required. Either the change is formatted or it's not and the linter flags it.
People don't need to waste time reviewing style and instead can just review code.

When writing code you don't need to think about formatting either. You don't care about semis or spacing or indentation - you just write code and save it and it's formatted to spec.

Also no longer do you have people putting up a change which reformats a bunch of existing code to be in their preferred style in addition to their code changes. Because the preferred style is just what prettier enforces, full stop.

For both reviewers AND authors - it's a gigantic mental burden that is just gone. It frees up so much thought capacity so you can focus on solving problems.

Anyone that hates on prettier is because they don't like the nutty gritty of the code style it enforces and they think it's "hard to read".
To that I say let go. Style doesn't matter - consistency is king. It doesn't take long to learn prettier's style and make it your own.
Personally I now really get annoyed when I touch a codebase that isn't formatted with prettier because I'm now they used to prettier's style.

**Comment by Josh-Cena** [comment]
I completely echo with you. I'm also a huge lover of Prettier and I've learned to embrace its philosophy. My comment was by no means saying we should overtake, or even compete with Prettier. I'm saying, for the purpose of tooling docs, saying "we have a rule X, but haha, it's broken, and there's no sign of it getting fixed, so please use tool Y instead, and don't ever look back at our rule X" is a quite confusing position to be in for casual users. I'm speaking as an advocate of both Prettier and TS-ESLint in the community and from my interactions with other skeptics of either tool.
