### ISSUE TITLE
[explicit-function-return-type] Allow implicit void functions

### ISSUE THREAD

**Issue by jorgegonzalez** [typescript-eslint/typescript-eslint#50]
It would be nice if this rule had an option to ignore errors for void functions not explicitly marked as such.

Currently:

```ts
// Invalid: Missing return type on function
function hello() {
	console.log('Hello');
}
```

After:

```json
{
	"rules": {
		"typescript/explicit-function-return-type": [
			"error",
			{
				"allowVoid": true
			}
		]
	}
}
```

```ts
// Valid
function hello() {
	console.log('Hello');
}

// Also valid
function something(props, text): void {
	props.text = text;
	return;
}
```

**Comment by thisissami** [comment]
@armano2 I'm curious if you're still planning on addressing this. I'd be stoked on this capability being added to `typescript-eslint`. Here's the use case that I want this for: https://stackoverflow.com/questions/56402796/can-typescript-eslint-implicitly-understand-a-return-type-of-void-when-writing-j (tl;dr - every `jest` `describe` or `it` has a callback with a `void` return... in a large codebase, kinda annoying to have to keep writing that again and again).

**Comment by bradzacher** [comment]
@thisissami - try the `allowTypedFunctionExpressions` option.
That will make the rule skip reporting errors on functions that are defined somewhere the return type can be inferred.

**Comment by thisissami** [comment]
@bradzacher I have that set already, and it works with things like `Array` functions. it is not working within my `jest` tests. perhaps there's something else I should be doing that I'm missing?

**Comment by bradzacher** [comment]
@thisissami Raise a new issue with some examples and we can have a look into it and discuss there, sounds like it might be a bug?

**Comment by bradzacher** [comment]
Sorry. I mean it's a bug if you're talking about this example:

```
it('should xxx', () => {}) // should be inferred
```

**Comment by thisissami** [comment]
Ok - I'll mess around with this on Monday when I'm back on my work computer
with my eslint setup; if i can't get it to work at all, i'll raise a new
issue! :) Thanks Brad!

**Comment by thisissami** [comment]
So I completely forgot to respond until now: seems like whatever was happening last week was a random issue that has been gone all this week. my `describe` and `it` blocks are working just fine now.

**Comment by davidje13** [comment]
@armano2

> I will like to implement this feature, but not before we are going to update parser to v21.*

Is there a separate issue for tracking this? I couldn't find anything.

**Comment by bradzacher** [comment]
@davidje13 type information has been available to rules for quite a while.

---

Looking at this enhancement again, I think that whilst it's easy to do, it goes against the intention of the rule. We don't want a special case for `void`. It's 4 characters, and not including it creates a lot of inconsistencies (which this rule is attempting to stop).

**Comment by davidje13** [comment]
@bradzacher my main interest in this is for Jasmine/Jest testing. To give you an idea of what that looks like:

```typescript
describe('some thing', (): void => {
  describe('some method', (): void => {
    it('does stuff', (): void => {
    });
    it('does more stuff', (): void => {
    });
    it('does something asynchronously', async (): Promise<void> => {
      await foobar();
    });
  });
});
```

Clearly this is very verbose (especially for the `async` block). Allowing implicit `void` returns (and `Promise<void>` in the async case) would be hugely beneficial.

Currently I am setting `'allowExpressions': true`, but this is not ideal because it means there are many other places I may be getting an unexpected return type. Essentially I'm currently forced to abuse another flag to get behaviour which is close to but not actually what I need, causing me to miss issues I'd like to catch.

**Comment by davidje13** [comment]
An alternative fix which would work for my use-case is extra logic if a function is defined inline as a parameter to another (typed) function: if the return type could implicitly match the expected return type, and it can be verified that the implementation does indeed conform to it, omitting an explicit return type seems logical.

In the above case, because `describe` and `it` expect (approximately) a `() => (void | Promise<void>)`, the given lambdas can be checked against that requirement. This makes it clear that explicit return types are just noise in these cases (and this applies to more than just testing APIs)

**Comment by bradzacher** [comment]
I direct you to either have a look at the rule's documentation, or read the collapsed comments where another user had the same problem you have.
`allowTypedFunctionExpressions` will do what you want.

---

For tests specifically, you could use [eslint overrides](https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files) to disable the rule. Considering tests aren't production code, it isn't a problem to have more relaxed linting.

**Comment by davidje13** [comment]
@bradzacher in theory that seems to be what I'm looking for, though I'm observing the same behaviour as thisissami. Presumably it's a bug; if I can narrow it down I'll open a new issue.

I'm already using eslint overrides for relaxing rules for tests, but I still have helpers, etc. which I'd like to have some certainty around.

**Comment by davidje13** [comment]
@bradzacher I have created #679 which demonstrates this not working in a minimal case.

**Comment by thisissami** [comment]
@davidje13 on my computer, all it took was a VScode reload for this to work properly.

**Comment by davidje13** [comment]
@thisissami that's weird considering the feature was apparently never implemented (see the PR for the issue I raised); are you sure you didn't set another option or disable the rule entirely somehow?

**Comment by thisissami** [comment]
@davidje13 i have the following in my `.eslintrc.js`:

```typescript
    "@typescript-eslint/explicit-function-return-type": [
      "warn",
      {
        allowExpressions: true,
        allowTypedFunctionExpressions: true,
      }
    ],
```

When I first chimed in this thread, I had first set the rules as per immediately above - and was getting warnings on all my `jest` `describe` blocks. When I next opened VSCode, all the warnings were gone. 

However, doing some digging now - it's the `allowExpressions: true` that makes the warnings go away - not the `allowTypedFunctionExpressions`. Sounds like there is indeed a bug!

**Comment by tomnar** [comment]
Man I wish this feature existed. 95% of my functions are void - it would be very nice way of telling me "hey, this function actually returns something, is this the expected type?". But adding void, void, void everywhere makes it harder to read/write and adds no value.

**Comment by johannesjo** [comment]
Can't believe that this is closed....

**Comment by johannesjo** [comment]
Can't believe that this is closed....

> @davidje13 type information has been available to rules for quite a while.
> 
> Looking at this enhancement again, I think that whilst it's easy to do, it goes against the intention of the rule. We don't want a special case for `void`. It's 4 characters, and not including it creates a lot of inconsistencies (which this rule is attempting to stop).

It's just a sensible default to save oneself a lot of time not an inconsistency. The way it is, I am so annoyed by having to write `void` all the time that I disable the rule completely, which is really not ideal neither.

**Comment by bradzacher** [comment]
We won't be building type information into the rule because:
- many users don't use type information, so adding it to an existing rule severely limits the userbase that can use a rule.
- adding it to an existing rule is a breaking change, which needs a major version bump.
- type information is created lazily by typescript, which means that each new piece of type information consumed comes with a non-trival performance overhead. So we opt for static analysis of the AST where possible.
- we don't like to conditionally consume type information in a rule because it creates a confusing experience for users; a rule might work in their setup until they turn on a certain option. This creates maintenance burden for the maintainers, who volunteer their time to support this project.

If this is something that you few would find valuable, this code is released under an MIT licence, so you're welcome to create, say, `eslint-plugin-explicit-function-return-type`, and create a new version of the rule which supports your use case.
