### ISSUE TITLE
Discussion: when should version 6 release?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5037]
## Overview

Following discussions in #5032 and #5036: it's been 7 months since 5.0 was released. We've got a few [open breaking change issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+is%3Aopen+label%3A%22breaking+change%22) and [pending breaking change PRs](https://github.com/typescript-eslint/typescript-eslint/pulls?q=is%3Apr+is%3Aopen+label%3A%22breaking+change%22). How frequently / at what point should we release breaking changes?

Starting strawperson proposal: how about once a year? That would give us time to tackle larger issues such as #1417 and #1852.

**Comment by bradzacher** [comment]
Traditionally we haven't done major releases on a timeline because it's hard for any of us to commit time on any regular schedule.

In the past it's really been whenever there was some pressing need to do one (like requirements for a new TS version).

I had hoped that I would have time enough to get the AST enforcement in, but it'll be a while before I can truly tackle that.

So if we have anything that we want to do sooner rather than later, we can start the process now!

The general process for a major release has been
1) branch from main with the name `v\d+`
2) setup a canary release from this branch to a tag `rc-v\d+`
3) start merging until we've ticked off all of the issues we want.
4) let it bake in RC for a week or so and publicise it to get community eyes on it.
5) release! (this I think might take some manual intervention from memory - James usually hops in to do it IIRC)

**Comment by JoshuaKGoldberg** [comment]
I've started working on this in #5883, and we started documentation in #5874. This issue can be closed. ✨
