### ISSUE TITLE
Docs: Automate the Options heading in rule docs pages

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5058]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now, rules pages manually include their options according to a light spattering of tests (#4367). But the part of the _Options_ section that includes the opening sentence(s) & code block description of the options can be generated using the rule's schema and/or code source.

Some rules, such as https://typescript-eslint.io/rules/adjacent-overload-signatures, have no options. They're the easier case.

Other rules, such as https://typescript-eslint.io/rules/array-type, have an options type, some ancillary type alias(es), and a `const defaultOptions: Options = { ... };`.

There are a few reasonable starting possibilities for how we could automate the creation of those options docs:

* Base them purely on the rule's `meta.schema[0]`
    * Upside: simplest, and most portable (we could make a utility library for it!)
    * Downside: some values might get duplicated (would we have to add logic to dedup?)
* Base them on the types & interfaces used in the rule's source file
    * Upside: matches the internal implementation closer
    * Downside: do we want it to match the internal implementation? and, is much more complicated
* Some combination of both

My proposal would be to base them purely on the rule's meta and see how that looks.

### Affected URL(s)

https://typescript-eslint.io/rules/*

**Comment by bradzacher** [comment]
> Base them on the types & interfaces used in the rule's source file

I would warn against this because the types we use internally are often incorrect / simplified. I.e. instead of declaring a union like `{ x: string } | { y: string }`, we'll declare an optional type like `{x ?: string, y?: string}` because it makes it easier to work with (it's impossible for us to do discriminated unions for the config types!).

> Base them purely on the rule's meta.schema[0]

There is the [`json-schema-to-typescript`](https://www.npmjs.com/package/json-schema-to-typescript) package which makes this pretty easy to do! I've used it before and it works pretty well for most cases.

Example output I've generated: https://github.com/bradzacher/eslint-config-brad/blob/master/src/types/%40typescript-eslint/array-type.ts
There are some issues with the types it generates, however. I think we can fix most of these up  by fixing the schemas.

Note that the package also supports auto-adding comments to the types - we just need to add a `description` field to the schema!

**Comment by Josh-Cena** [comment]
> because it makes it easier to work with (it's impossible for us to do discriminated unions for the config types!).

Would narrowing with `"x" in options` be an option?

**Comment by bradzacher** [comment]
> Would narrowing with "x" in options be an option?

Yeah it would - but you have to do that narrowing everywhere, otherwise you can't access the property 😢.

i.e. everywhere you must do `if ('y' in x && x.y === 'foo') { ... }`, when it's much easier to do something like `if (x.y === 'foo') { ... }`
[playground](g.org/play?#code/C4TwDgpgBAKlC8UDeUAeAuKBnYAnAlgHYDmUAvlAD7JQiY4EnkDcAsAFAcAmEAxgDYBDXNF4B7QjjSYYbTu3wAzKAApUAOhAJ4iAOSKxY3QEpkFAPTnsgrosG8IHDktW6QuqETRQAZD7Sa2noGRqZIFlYAbhC4AEZiWBAANFCxAK7A1ooQQA)

**Comment by Josh-Cena** [comment]
Ah, I see what you mean...
