### ISSUE TITLE
Repo: auto-lock stale issues and PRs after a more aggressive period of time

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5089]
## Overview

Our maintenance policy is that users should not post unrelated questions on previously resolved issues or PRs. Those unrelated threads are not very discoverable for other users researching the same problem. It also makes it harder for us, the maintainers, to keep track of requests when they're in all sorts of random unexpected places.

Yet, it's still happening. Even with users who have very positive intentions -- and are reporting real things that should be addressed!.

We should add some kind of stalebot/whatnot that locks issues automatically. I've seen other repos do it.

**Comment by PabloLION** [comment]
I think I understood you wrong about "post unrelated questions on previously resolved issues" and I'm trying to get a clearer vision on this:  
Take the issue #5031 as an example, it was derived by #5030 hence "related". Today I was organizing my notes and I had one more look on #5030. I found it was the exact thing I wanted to suggest but since it was locked, I'd like to reopen that one, so I posted a request/question in a related issue. 

### One more thing

As for the reason I didn't want to create a new issue:
1. It's bad for search. As we want users to make sure not asking repeated question, the search would give many answers on a repeated topic, and we have to read and maybe open all those links.
2. Create the issue consumes time with the table, and I couldn't (don't know how to) copy the original question in markdown format after it's locked.

I think this process is limited by GitHub capability, I have no suggestion on how to resolve this yet.

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/c4310b1aac35c7d31b826f0602eca6a5900a09ee/.github/workflows/lock.yml

We lock issues and PRs daily!
They have to have been closed for >30 days though.
I think I was just being conservative back when I configured it because some people respond very slowly.

We can probably drop that down to 7 days?
