### ISSUE TITLE
Bug: [consistent-type-import] and [no-shadow] conflicts with declaration merging

### ISSUE THREAD

**Issue by vidarc** [typescript-eslint/typescript-eslint#5181]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=JYWwDg9gTgLgBAbzgMQIYGcbAGYE8CSAdpqoQMYCmcAvnNlBCHAOTYZZ7MBQXAJhWQA2qKFRAReAV0FVW7HLmaIucOMEIwKUNpRTy8REuSoIVquOkYVCFAO4A1VIMkUAXBZhR1AczPUu-lwUAB6QsHSS5FgQhHCamD4AFGwJeO5oqQTEMKSUAJTKqmQxljIAdIIQ3sn6uHkA3AFcQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUFvcgAQBcBPABxQGNoBLEggWhXioDsCB6cge2eSuQMSs6xMnSoBbEp2gFUGANrgcyyImjRpkJcrABdADTaduQqQrVaDZE1ZtmnOsgAWAQwAmnAO7owi48dV1TSN-AxDce0dXD28MSE4AMwStCABfEFSgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code
Throws `All imports in the declaration are only used as types. Use `import type``

```typescript
import { FastifyInstance } from 'fastify'

declare module 'fastify' {
  interface FastifyInstance {
    somenewValue: string
  }
}

export function testing(fastify: FastifyInstance) {
  console.log(fastify);
}
```

`'FastifyInstance' is already declared in the upper scope.`
```typescript
import { type FastifyInstance } from 'fastify'

declare module 'fastify' {
  interface FastifyInstance {
    somenewValue: string
  }
}

export function testing(fastify: FastifyInstance) {
  console.log(fastify);
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/consistent-type-imports": ["error"],
    "@typescript-eslint/no-shadow": ["error"],
    "no-shadow": "off",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

I would expect these two rules to live in harmony together, or for potentially another rule/message to explain why they cannot.

### Actual Result

Appears that `consistent-type-import` and `no-shadow` conflict with one another under certain circumstances. In this instance, I am trying to use some interface declaration merging to add some fields to a 3rd party interface

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.27.1` |
| `@typescript-eslint/parser`            | `5.27.1` |
| `TypeScript`                           | `4.7.2` |
| `ESLint`                               | `8.16.0` |
| `node`                                 | `16.15.0` |

**Comment by bradzacher** [comment]
This is actually correct - `declare module 'foo'` declares its own block-scope
Even though it's intentional - you are still shadowing the top-level variable within the `declare module` scope.

So why does it error when you switch to a type-only import?
Well with a "normal" import we don't know what the imported thing is - it could be a type, or it could be a value; we cannot know - so we have to be cautious and assume it might be a value. Because we assume it's a value, and we know your interface is a type, the rule sees you shadowing a value with a type.

As per the default rule config - [`ignoreTypeValueShadow`](https://typescript-eslint.io/rules/no-shadow/#ignoretypevalueshadow) is turned on, so the rule does not report.

When you switch it to a `type`-only import, well we now know for sure that the variable is a type, not a value. Which means you're now shadowing a type with a type - which is not covered by the aforementioned option, and thus it errors.

The rule does have special handling for the case of external declaration merging, [but it requires you to `export` the types you're augmenting](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=JYWwDg9gTgLgBDAnmApnA3nAYgQwM4zABmiAkgHYE7kDGaAvnEVBCHAORH6EnsDcAKAEATFDQA2OKGhARhAV3FpO3YonYYBcOCgAekWHGDkYKKFzrZVJClVpp0W7XDysU5FAHcAajnHyUAC4XGChjAHMnegFogT0DeCJ5WkIIcgQUAgiACi4skmDcfLJKGGo6AEpNbRo01yUAOnEIcNzrRArBaKA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUFvcgAQBcBPABxQGNoBLEggWhXioDsCB6cge2eSuQMSs6xMnSoBbEp2gFUGANrgcyyImjRpkJcrABdADTaduQqQrVaDZE1ZtmnOsgAWAQwAmnAO7owi48dV1TSN-AxDce0dXD28MSE4AMwStCABfEFSgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

Why does it do this? Well it's really hard to get this case exactly right - there's a very, very fine line between "intentional shadowing for augmentation" and "accidental shadowing". Requiring the augmented interface to be `export`ed was the compromise to delineate the cases.
