### ISSUE TITLE
Rule proposal: Functions that throw must include a "never" type in their return signature

### ISSUE THREAD

**Issue by flowstate247** [typescript-eslint/typescript-eslint#5196]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I would like a rule to check that the "never" type is included in the return signature of every function that can throw.

### Fail Cases

```typescript
function foo(): void {
  throw new Error()
}

function bar(): void {
  foo()
}

function foo(x: number): number {
  if (x >= 42) return x
  throw new Error()
}
```

### Pass Cases

```typescript
function foo(): never {
  throw new Error()
}

function bar(): never {
  foo()
}

function foo(x: number): number | never {
  if (x >= 42) return x
  throw new Error()
}
```

**Comment by bradzacher** [comment]
Whilst it's definitely possible to enforce that functions that `throw` annotate their return type with `never`, beyond that it's not really possible.

Because of TS's type collapsing - `never` is collapsed into any other type. This means that the return type of your last `foo` function isn't `number | never`, it's just `number`.
[repl](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUBKAXIsBTANzwCdEBvAKEWsSgAti4B3XPFgUWMeMwG4KAvhQqhIsBIgBGAQx4QEAExyTUAGzzSw2VkVIAfXCAC2kkuSo0YwRGnlgFGczWfJUfC9SHPieKCGJIAIz8QiLg0PBIMgBemE40dgDOUIgAHogAvFKyaFDEIHgY-M4A9CXOAHoA-IJAA)

This means that even with type-information, we cannot tell that a random function returns `never`.
So I'm not sure if it makes sense to have a lint rule which just enforces that a function that always throws is marked as returning `never`?

**Comment by flowstate247** [comment]
The most valuable part of my proposal, from a developer point of view, is the propagation of the never type as illustrated by the bar function.

I agree that ideally this issue should be handled by the TypeScript compiler itself. Unfortunately the TypeScript team rejected my issue of their github: https://github.com/microsoft/TypeScript/issues/49549

Practically speaking the value for the developer of this lint rule is that by reading the code of a function we can be sure simply by reading the return signature type whether or not that function can possibly throw, even if it doesn't have the throw keyword explicitly written in the function body.

**Comment by bradzacher** [comment]
Sorry - to clarify - our lint rules come in one of two flavours:

1) pure AST rules. These rules can only use information gathered from ***single file** AST analysis. There are no types available, nor is there information across module boundaries.

2) type-aware rules. These rules are like (1), except they can also use the type information that TS has calculated for the code.

For (1), the best we can do is enforce that  that `throw` are annotated with `never`.

For (2) we can only rely on the information that TS provides. Which means that we can do marginally better than (1) in that we can also enforce that functions that ***only*** return `never` cascade upwards.
Note that if a function returns a union with `never`, then we cannot know - due to the aforementioned type collapsing. We can only detect if the return type is exactly `never`.

Given this information - it's relatively low value to do (2) when compared with the perf tradeoff. Type information is calculated lazily - meaning you pay for every type you access. In order to determine the case - we would need to inspect the return type of every single call expression in your application. As you can guess - this would be ***very*** expensive and slow.

(1) is easy to do and is also fast - so we could consider this, but it does mean a very, veryimited scope.

TBH I don't hugely like this lint rule because of the false positives it will produce. As mentioned in your linked TS issues - it's perfectly valid to throw inside a non-never returning function; for example in an unimplemented method.

**Comment by flowstate247** [comment]
From your (2), I understand that the return signature in the baz function cannot be detected as an error by the linter due to the internal collapsing of types by TypeScript:

```typescript
function foo(x: number): number | never {
  if (x >= 42) return x
  throw new Error()
}

function baz(x: number): number { // the return type should be number | never
  if (x < 0) return x
  return foo(x)
}
```

But this is really this type of code problems that we want detected because this is where this proposal brings the most value to the developer.
And only being able to implement the (1) point means solving only a small portion of the problem.
So I agree that this problem makes little sense to be implemented as a lint rule.
This is an issue that has to be handled by the TypeScript compiler itself, not by the linter.

**Comment by bradzacher** [comment]
I'll go ahead and close this for now, then.
If the TS team does add tooling to support inspecting `never`, then we can revisit this idea then.
