### ISSUE TITLE
Docs: Add an overview of the project's history

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5202]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

A question I posted on our Slack:

> What is the history of tseslint? What were the first projects that went into it, by whom, and how did it get to where it is today?

> Context: I was asked this on a podcast and drew a blank 😞 

Maybe it'd be reasonable to put this somewhere for reference? Is this information interesting to folks? (I think yes?)

### Affected URL(s)

Unclear.

**Comment by bradzacher** [comment]
Pasting from our chat:

In the beginning (late 2015) there was [`typescript-eslint-parser`](https://github.com/eslint/typescript-eslint-parser).
An effort by the ESLint team (IIRC it was Nick Z and James) to support TS in ESLint via a custom parser. IIRC this was really ESLint's first foray into supporting things other than pure JS.

In late 2016 [`eslint-plugin-typescript`](https://github.com/bradzacher/eslint-plugin-typescript) was created (by Nick Z and James again). As they had reached a decent level of support for parsing TS in ESLint - the next logical step was writing lint rules to target TS features! It started as a repo under Nick on GH, then transferred to James at some point, then in late 2018 it transferred to me.

I don't know when exactly, but at some point the ESLint team mostly stepped back from the projects - James was heading the efforts on the parser and plugin, and the ESLint folks wanted to double-down on making ESLint core better. That's not to say they did nothing - they added new features which helped ESLint grow into a better system so it could support 3rd-party parsers. For example they added support for custom scope managers and parser services - both crucial features for us to have full TS support AND type-aware lint rules.

In late 2018 James split the ast converter logic out of `typescript-eslint-parser` and into its own package - [`typescript-estree`](https://github.com/jameshenry/typescript-estree/). This was done for the purpose of using that logic in prettier without the bloat of the ESLint requirements.

For a few months at the end of 2018 we worked mostly in silos - the parser side and the plugin side. It *kind of* worked but also had some real problems: users frequently reported issues in the wrong repo because they didn't know how it all fit together, and it was pretty well impossible to figure out which version went with what. For example at the end we had `typescript-estree` at v18, `eslint-plugin-typescript` at v0.15, and `typescript-eslint-parser` at v22. The general advice we had for people was to just "make sure everything is on the latest version and good luck".

In early 2019 James approached me and asked if I wanted to merge the projects into one monorepo. In a nutshell the pitch was that we were tightly dependent on one another - so a monorepo would mean we could more closely work together and move in lock-step. I was all for it, of course - and James got onto importing the commmits and setting up the monorepo.

We went back and forth on the naming for a while - should we keep the names, or rename to unify them? One important point of consideration was versioning - we wanted to unify the versioning to make it easier for people. Keeping the existing names would have meant bumping all the packages to v22 to match the parser. Ultimately we decided against this because there is a bit of an optics problem with large major version numbers, and we wanted a fresh start with new names. Luckily just a short time earlier ESLint had released support for npm namespaces! This made it a no-brainer, and thus `@typescript-eslint` was born!

The rest, as they say, is history.

**Comment by JoshuaKGoldberg** [comment]
I haven't referred to this issue since June and there's not any need for it from other folks that I can see. I think it's fine to close it here and let this be the reference if anybody needs.

I started working on a docs-page-ready text blurb. Super draft-y, not completely checked for accuracy...

---
id: project-history
title: Project History
---

The typescript-eslint project grew out of two needs:

- Allowing ESLint to run on TypeScript files
- Providing an ESTree parser for other tools such as Prettier

## ESLint Roots

In the beginning (late 2015), two members of the ESLint team, [James Henry](https://github.com/JamesHenry) and [Nicholas C. Zakas](https://github.com/nzakas), created a prototype [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser) custom parser that allowed ESLint to read in TypeScript code.
It was the first major foray of ESLint in supporting languages other than pure JavaScript.

With the TypeScript parser working, James and Nicholas created [`eslint-plugin-typescript`](https://github.com/bradzacher/eslint-plugin-typescript) for TypeScript-specific features.
It started as a repository under Nicholas on GitHub, then transferred to James, then in late 2018 transferred to [Brad Zacher](https://github.com/bradzacher) - a frequent contributor to both `eslint-plugin-typescript` and `typescript-eslint-parser`.

### Changes in ESLint

After the initial rush of creating the two parser and plugin was over, the ESLint team mostly stepped back from them to focus on ESLint core.
They still iterated on features in the core project to support TypeScript and other languages.
Two features in particular were critical for TypeScript support and type-aware lint rules: [custom scope managers](https://eslint.org/docs/latest/developer-guide/scope-manager-interface) and [custom parsers]s

## Prettier Support

In late 2018 James split the AST converter logic out of `typescript-eslint-parser` and into its own package: `typescript-estree`.
This allowed using that logic in Prettier without the bloat of the ESLint requirements.

## Merging Projects

For a few months at the end of 2018 the projects worked mostly in silos: James on the parser and Brad on the plugin.
It worked but also had some real problems:

- Users frequently reported issues in the wrong repo because they didn't know how it all fit together
- It was pretty well impossible to figure out which version went with what.
  - For example at the end we had `typescript-estree` at v18, `eslint-plugin-typescript` at v0.15, and typescript-eslint-parser at v22.
  - The general advice we had for people was to just "make sure everything is on the latest version and good luck".

In early 2019 James approached Brad offering to merge the projects into one monorepo.
The pitch was that the two projects were tightly dependent on one another already - so a monorepo would mean they could more closely coordinate and work together.

### Project Naming

TODO

We went back and forth on the naming for a while - should we keep the names, or rename to unify them?
One important point of consideration was versioning - we wanted to unify the versioning to make it easier for people.
Keeping the existing names would have meant bumping all the packages to v22 to match the parser.
Ultimately we decided against this because there is a bit of an optics problem with large major version numbers, and we wanted a fresh start with new names.
Luckily just a short time earlier ESLint had released support for npm namespaces! This made it a no-brainer, and thus @typescript-eslint was born!

## Separately: TSLint

Starting in around 2013, [TSLint](https://palantir.github.io/tslint) was the standard linter for TypeScript code.
It worked reasonably well an equivalent to ESLint.

However, TSLint was a completely separate project from ESLint.

- ESLint had a much larger community and maintenance team, allowing it to develop new features more often and more quickly than TSLint.
- TSLint could not run ESLint rules natively, so popular community ESLint plugins needed to be rewritten for TSLint.

The TSLint team [announced TSLint's deprecation in 2019](https://blog.palantir.com/tslint-in-2019-1a144c2317a9) and [gradually deprecated the project in 2019 through 2020](https://github.com/palantir/tslint/issues/4534).
