### ISSUE TITLE
Bug: [method-signature-style] doesn't work on classes

### ISSUE THREAD

**Issue by DetachHead** [typescript-eslint/typescript-eslint#5243]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=MYGwhgzhAEBiD29oG8CwAoa0BmBXAdsABQCUAXNAG7wCWAJigL7QD0L0+SApgE4-w8MjDGABGEAC48wwCdFCQYAITA8UGLGMnTZOAsXJVaDNh258BQjBgkBPAA5doKgF7QAvOsx7CpCtXpWdl5+QXRhdBp8CV5sGScARVwADy8sPF9DAJNgizCIoA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XwAsB7AE1rJKAcyYBDfLGiIhRJOiiJo0XtEjgwAXxBagA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
class Foo {
  func(): void {} // no error
}
abstract class Bar {
  abstract func(): void // no error
}

type Baz = {
  func(): void // error
}
interface Qux {
  func(): void // error
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/method-signature-style": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

error when using old function syntax in classes

### Actual Result

no error

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.29.0` |
| `@typescript-eslint/parser`            | `5.29.0` |
| `TypeScript`                           | `4.7.2` |
| `ESLint`                               | `8.15.0` |
| `node`                                 | `16.11.1` |

**Comment by bradzacher** [comment]
Method signatures by definition only exist in object types.
Method definitions exist on classes.

The latter is intentionally not handled by the rule.

The reason the rule checks method signatures is because those are used for object types which are passed around and used to match against other objects - meaning they are subject to the variance issue (see [the rule docs for an explainer](https://typescript-eslint.io/rules/method-signature-style)).

Classes are technically subject to the same issue, but you don't typically match class methods against random types - so the variance isn't an issue.

If you want to ban method definitions in your codebase - please read this FAQ article
https://typescript-eslint.io/docs/linting/troubleshooting/#how-can-i-ban-specific-language-feature

**Comment by DetachHead** [comment]
@bradzacher classes have the same issue as well:
```ts
abstract class Foo<T> {
  abstract func(value: T): void
}
class Bar<T> extends Foo<T> {
  func(value: T): void { }
}

const foo: Foo<unknown> = new Bar<number>() // no error

abstract class Foo2<T> {
  abstract func1: (value: T) => void
}
class Bar2<T> extends Foo2<T> {
  func1 = (value: T): void => { } 
}

const foo2: Foo2<unknown> = new Bar2<number>() // error
```
imo this is a fairly common example of the variance issue that this rule aims to prevent, so it doesn't make sense not to support it

**Comment by Josh-Cena** [comment]
@DetachHead Not very related, but if you use classes like that, you are probably better off using factory functions. The point of using class methods is that the method is declared on `Foo.prototype` instead of every instance, hence saving memory.

**Comment by bradzacher** [comment]
Yeah there is a bigger point here in that changing signatures grants more safety for no cost.

But changing methods to properties has deep runtime semantic changes. Its not actually safe to autofix a property to a method if the class has a superclass. Why? Because if the superclass accesses the member in the constructor - a method will use the subclass's value (as its defined on the prototype before the constructor is run) but a property will use the superclass's value (because the subclass's value won't be defined until the superclass constructor returns).

I learned this the hard way earlier this year codemodding Meta's codebase 😅.

With 4.7 variance annotations I believe you can control the variance of your parameters now, which further narrows the scope of necessary changes to classes.

**Comment by Josh-Cena** [comment]
[Unfortunately no...](https://www.typescriptlang.org/play?ssl=10&ssc=1&pln=1&pc=1#code/IYIwzgLgTsDGEAJYBthjAgYge2wHgEsA7BbAV0QBUA+BAbwCgEFRIZ4EAzMo2ACgBuwZGQCmALgSUAlJIHYCAEwYBfBijQYAQsCiES5KrVEAPCKKKKMOfDXpMuPfkJESpshPKX0EateuwiSC5cSRs8HgBrImwAdyJaAF4EIlFYhB09IjIAWxBRKGo+aQBuBk5cADpuXj4AIgALUQBPOtKGIA)

**Comment by DetachHead** [comment]
> @DetachHead Not very related, but if you use classes like that, you are probably better off using factory functions. The point of using class methods is that the method is declared on `Foo.prototype` instead of every instance, hence saving memory.

@Josh-Cena not sure what you mean, can you show an example of how that code could be rewritten using factory functions?

i don't think using classes this way is uncommon. in fact it seems to be a supported pattern at least as recently as typescript 4.3 with the [addition of the `override` keyword](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag)

regardless, perhaps this is a better example?

```ts
interface Foo<T> { 
  func: (value: T) => void
}

class Bar<T> implements Foo<T> {
  func(value: T) { } // no eslint error
}

const bar: Bar<unknown> = new Bar<number>() // no typescript error
```

> But changing methods to properties has deep runtime semantic changes. Its not actually safe to autofix a property to a method if the class has a superclass.

@bradzacher i agree, i wouldn't expect it to be autofixable either. is it possible to enable autofix for interfaces/types but not classes? if not, maybe this would need to be a separate rule?

> With 4.7 variance annotations I believe you can control the variance of your parameters now, which further narrows the scope of necessary changes to classes.

unfortunately as @Josh-Cena pointed out, all the `in` and `out` keywords do is allow you to enforce whether generics are allowed to be used as input or output types:
```ts
abstract class Foo<out T> { // error
  abstract func: (value: T) => void
}
```
but the existing functionality remains the same (as in, there's still no variance checking on the old method syntax):
```ts
abstract class Foo<out T> { // no error
  abstract func(value: T): void
}
```
