### ISSUE TITLE
Lint issues stop showing up after referenced TS project is built

### ISSUE THREAD

**Issue by alexvy86** [typescript-eslint/typescript-eslint#5357]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Issue Description

I'm seeing weird behavior linting a file in two scenarios.

Context: there's a `src/` folder at the root of the repo, and a `tsconfig.json` file that uses it as its `rootDir`. There's also an inner folder `src/inner` which is supposed to be a separate TS project, and its `tsconfig.json` file references the one at the root of the repo. A file in `src/inner` has 2 lint rule issues.

The two weird scenarios are:

- If the root `tsconfig.json` file has an `exclude` node so that `src/inner` isn't built along with the rest of `src`, linting the file in `src/inner` produces different results before and after building the main project (not the one in `src/inner`, just the one it references in its `tsconfig.json`). Before the build the linter outputs 2 rule issues, but after it only outputs 1.

![image](https://user-images.githubusercontent.com/716334/180020765-87fe1388-4b5d-4a83-8cf0-9abbefef0621.png)

- If the root `tsconfig.json` does *not* have an `exclude` for `src/inner`, then the second rule issue (the one that disappears after the build in the other scenario) never shows up in the linting output for the file.

![image](https://user-images.githubusercontent.com/716334/180020829-cb7ce963-2975-44f1-8573-a6f5e8f2c972.png)

### Reproduction Repository Link

https://github.com/alexvy86/ts-eslint-exclude-bug-repro

### Repro Steps

- Clone this repo.
- Run `npm i` at the root.
- Run `./test-with-exclude.sh` to see the scenario where a linter issue in `src/inner/myOtherModule` disappears after building the main project.
- Run `./test-without-exclude.sh` to see the scenario where the same linter issue does not show up in the output at all.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.30.7` |
| `@typescript-eslint/parser`            | `5.30.7` |
| `TypeScript`                           | `4.7.4` |
| `ESLint`                               | `8.20.0` |
| `node`                                 | `14.19.3` |

**Comment by alexvy86** [comment]
I kept experimenting with this and found out it reproduces in even simpler scenarios (folder-structure-wise):

- If the second TS project is in a sibling folder instead of a child one but the main tsconfig is still at the root of the repo: [Branch sibling-project-same-issue](https://github.com/alexvy86/ts-eslint-exclude-bug-repro/tree/sibling-project-same-issue)
- If the second TS project is in a sibling folder instead of a child one and the tsconfig for each project is in the project's subfolder: [Branch sibling-project-same-issue-2](https://github.com/alexvy86/ts-eslint-exclude-bug-repro/tree/sibling-project-same-issue-2). I think of this case as the two projects having no parent-child-folders relationships at all (besides their shared `tsconfig.base.json` being in the parent folder to both projects).

I'm renaming the issue to reflect this.

**Comment by bradzacher** [comment]
If I'm understanding the problem correctly - this is to be expected. We do not support project references that have not been built (it's really complicated - https://github.com/typescript-eslint/typescript-eslint/issues/2094).

Your [full include tsconfig](https://github.com/alexvy86/ts-eslint-exclude-bug-repro/blob/main/tsconfig.json) includes *all* files in src. This means that when TS generates the types for the import `import { myConst } from '../myModule';`, it knows exactly how to calculate those types.

However your [exclude tsconfig](https://github.com/alexvy86/ts-eslint-exclude-bug-repro/blob/main/tsconfig.withExclude.json) splits your code into two separate projects. This means when it attempts to calculate types for that same import, it can't do it because `../myModule` isn't part of the project. So TS just reports `any` for the import and silently continues.

Once you have done the build, TS has some inner magic to understand the mapping from source file to `.d.ts` file for linked projects, so then it can understand that `../myModule` actually references `./dist/myModule.d.ts`, and so it can calculate the types.
Without the build step - TS just sees nothing because it's not allowed to reference the `.ts` file by design.
