### ISSUE TITLE
Rule proposal: Ban type coercion from operators on non-primitive types

### ISSUE THREAD

**Issue by maritaria** [typescript-eslint/typescript-eslint#5360]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

A new rule that restricts usage of arithmetic operators on non-primitive types.
With the specific goal to prevent coercion of user types (e.g. classes, interfaces) to primitives accidentally.

An example of this is `Maybe<T>`, which is a holder for a value (or not).
It essentially is a container for a single value, which makes it easy to mistake the container for the value itself.

### Fail Cases

First, a minimal example:

```typescript
// Function that accepts primitive value
function test(arg: number) { return arg; }

// A non-primitive value
const b = {};

test(b); // This is an error, yay!
test(-b); // But this is not, and it is not obvious that this should not be suspicious by default.

```

Now the situation I faced, which is why I'm opening this request.
I was introducing a `Maybe` type in my vector math code, specifically a method on a 2d-vector class that computes the vector's direction (from `[0,0]`). There is an edge-case if the vector itself is `[0,0]`, then the vector has no length nor direction.
To force myself to always take these edge-cases into account (to avoid divide by zero and other NaN troubles) I introduced the `Maybe` for some of the methods that would fail in such "zero" cases.

Here is a snippet to illustrate the situation, note the `Vec2.angle_{old,new}` properties as those show the first and refactored version of the `Vec2.angle` getter.

```typescript
interface Maybe<T> {
  get empty(): boolean;
  get value(): T; // throws if empty
}

const fillMaybe = <T>(value: T) => ({
  get empty() { return false; },
  get value() { return value; }
});

const EmptyMaybe: Maybe<never> = {
  get empty() { return true; },
  get value(): never {
    throw new Error('Maybe is empty');
  }
};

class Vec2 {
  constructor(
    public readonly x: number,
    public readonly y: number
  ) {}

  get isZero() {
    return this.x === 0 && this.y === 0;
  }

  get length() {
    return Math.sqrt(this.x ** 2 + this.y ** 2);
  }

  get angle_old(): number {
    return Math.atan2(this.y, this.x);
  }

  get angle_new(): Maybe<number> {
    return this.isZero
      ? EmptyMaybe /* Vector has zero lenght, no direction. */
      : fillMaybe(Math.atan2(this.y, this.x));
  }

  rotate(rotation: number): Vec2 {
    if (this.isZero) return this;
    const newAngle = this.angle.value + rotation;
    return new Vec2(
      Math.cos(newAngle) * this.length,
      Math.sin(newAngle) * this.length
    );
  }
}
```

So in short the return type of a property changed from `number` to `Maybe<number>`.

When I started refactoring the places where the changed code was being used there was one spot that was obviously wrong but did not trigger a compile error like all other places.
What was different there is that I negated the result before passing it into another function.

Because the unary `-` changes objects into `0` this remained valid code, but really only in the sense of types.

```typescript
const myPoint = new Vec2(123, 123);
const someDelta = new Vec2(123, 123);

// Problem: coercion of Maybe<T> to number is unintentional and does not create a compile failure.
const newPoint = myPoint.rotate(-someDelta.angle);
```

### Pass Cases

This rule is to protect against accidental use of type coercion to primitive types.
The acceptable case is to use the intended value correctly, or mask the exception by ignoring the rule.

#### Allowed coercion

- String
- Date
- Numerics
- Types that implement `Symbol.toPrimitive`

#### Symbol.toPrimitive

There are three targets for coercion:

- For truthy-tests (`if (myVar) {...}`)
- For arithmetic (`-myVar`)
- For string conversion (`"" + myVar`)

The usage of truthy-tests is well known to typescript users, and so the intention of coercion is clear.

The arithmetic case I am challenging with this request.

But the string conversion sits in the middle here. Most often the conversion to string is intentional, but with arithmetic it can be accidental (e.g. `a + b`, with `a` a string and `b` a class instance of sorts).
We could catch the accidental case by causing lint errors for certain types of string coercion.
Something like "all string coercion, except those due to usage of `+` in combination with a string literal, and except those due to usage in string template literals". In two cases it is clear that the type is being coerced.

**Comment by bradzacher** [comment]
> Because the unary - changes objects into 0 this remained valid code, but really only in the sense of types.

It shouldn't do that - it should convert them to `NaN`.
`-` will coerce the argument to a number which looks something like:
1) if is number - use value
1) if is string/boolean - call `Number(val)` to coerce to a number
1) if implements `Symbol.toPrimitive` - call and and goto (1) with value
1) if implements `toString` - call and goto (1) with the value

So for `-({})` - it calls `toString` which results in `[object Object]` and hence it results in `NaN`.

> Allowed coercion

> String

Strings shouldn't be allowed to be coerced because if they contain any non-numbers, they'll be coerced to `NaN`. EG `-'1a' === NaN`

> Types that implement Symbol.toPrimitive

TypeScript does not track this in their library types - so types like `Date` that *do* implement it won't be recognised and will need to be manually hardcoded into the rule.

---

Personally I think this rule should only allow `number` and force you to be explicit about how you're converting values to numbers.

For example:
- instead of allowing `-'1'` because it's technically safe, we should ban all strings
- instead of allowing `-(new Date())` because `Date` implements `Symbol.toPrimitive`, we should ban it and force you to use `.valueOf` like `-myDate.valueOf()` so it's explicit you're doing the right thing.

**Comment by Josh-Cena** [comment]
Unary minus is fixed by https://github.com/typescript-eslint/typescript-eslint/pull/7390 (see https://typescript-eslint.io/rules/no-unsafe-unary-minus/). String concatenation is covered by https://typescript-eslint.io/rules/restrict-plus-operands. Conditions can be handled by https://typescript-eslint.io/rules/strict-boolean-expressions. Let's consider it fixed.
