### ISSUE TITLE
Bug: @typescript-eslint/no-unused-vars  ignoreRestSiblings errors

### ISSUE THREAD

**Issue by xenoterracide** [typescript-eslint/typescript-eslint#5391]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=KYDwDg9gTgLgBAYwgOwM7wNrIgE2AGjgEMwwA5IgWwLgDp6ioBzVAXTgF44MByInwjwBGAuDwQ9WAKClA&eslintrc=N4KABGBEBOD2sBdIC4wOgVwKYBoSSwDsA3FMYKLAZwDYz1sBfMPAgDwSIBMqyBtcFAAOAGwwBzAJaFkAAQQBPIdQDG0SUIQBaaiOkIA9NCwrYAWzPcsXSCAC6rIQENoVLNDKR5S1es06qPUJDZ1d3SEcXN2gAeU1JWEJeMFRQCAIVMycANXcqBMIyACYABgBGAA48dKpYDGgVLAAVH08zWC4MESwIwUghOAArEyRUPkgAKgmDBCpTQgAzSXEAOkHawrsQRkcxKST+L0VlOb9tXX1IB3xvE7UNc8D9A0JYLQxCDDcuLWIXT3ccA82yAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEk6JAsrACYCuGAkkXlrIhWDyZW6ADTgakPAENMAc3R4BdEgCYADAEYArJHE0o8Fu3QAlerFSsCxZURbo9E2iVitM0dA2n9KQkfqSqMgARgIA2s6S9BqaAByQUQC6gbToAB6IWMjw6NzSqAAi6HCY0niwmGR+wmJRdPDIeMWl5ZUMitLM5dIC-nUGkMwlqLLlhER9talQIdIk6ACqmKjKAHROg0ZsGMpw8EZEAFZkM5AFqLAA7gBS1WAAZgULZ9AAFiUA1ncCT6gv9XsHCQwWgTQAgkQAJ5TAL1YbQUZlGxEby+QTTeokITIaBKGpwwYkT7IRAAGVCAGEPtBPr9ngNJNjMLi8AA5dioalfe79M6YCyoABu6DuxCYO0cBMZtAelU8lOIJGQ2LyeEp82QRDkXAAYmh0GzpLleZjBirLOV0MwJSZTYTJPYAKKNfEYkQSAC+gTo6URrGGEUBDgA+ts7ZtJMwVUoJCkJJAHgb7uEkiBPUA

### Repro Code

```typescript
playground link doesn't actually work, I'll try to fix it later, but I can't do those kind of github actions from my work computer

import { Cli } from 'clipanion'
import process, { argv } from 'node:process'

import { App } from './app'

const [_node, _appName, ...args] = argv

const cli = new Cli({
  binaryName: `fcos`,
})

cli.register(App)
cli.runExit(args)
```

### ESLint Config

```javascript
'@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: true
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "esModuleInterop": true,
    "target": "ES2018",
    "moduleResolution": "node",
    "sourceMap": true,
    "lib": ["es2018"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "baseUrl": ".",
    "module": "CommonJS",
    "allowJs": false,
    "checkJs": false,
    "noImplicitAny": true,
    "declarationMap": true,
    "strict": true,
    "skipLibCheck": false,
    "strictNullChecks": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "exclude": ["node_modules", "dist"],
  "files": []
}
```

### Expected Result

no error

### Actual Result

```
/Users/nqy642/IdeaProjects/E1-Http/packages/fake-chamber-of-secrets/src/cli.ts
  15:8   error  '_node' is assigned a value but never used     @typescript-eslint/no-unused-vars
  15:15  error  '_appName' is assigned a value but never used  @typescript-eslint/no-unused-vars
```

### Versions

Yarn Plugin Envinfo
```
  System:
    OS: macOS 11.6.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 528.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.asdf/installs/nodejs/16.14.2/bin/node
    Yarn: 3.2.1 - ~/.asdf/installs/nodejs/16.14.2/.npm/bin/yarn
    npm: 8.6.0 - ~/.asdf/plugins/nodejs/shims/npm
  Monorepos:
    Yarn Workspaces: 3.2.1
  npmGlobalPackages:
    npm: 8.6.0
    yarn: 1.22.19
```
```
└─ @cof/e1-lib@workspace:.
   ├─ Version: 0.1.5
   │
   └─ Dependencies
      ├─ @cof/e1-fake-chamber-of-secrets@workspace:* → workspace:packages/fake-chamber-of-secrets
      ├─ @jest/types@npm:^28.1.3 → npm:28.1.3
      ├─ @types/lodash@npm:^4 → npm:4.14.182
      ├─ @types/node@npm:^14 → npm:14.18.22
      ├─ concurrently@npm:^7.3.0 → npm:7.3.0
      ├─ eslint-plugin-editorconfig@npm:^4.0.2 → npm:4.0.2
      ├─ eslint@npm:^8.20.0 → npm:8.20.0
      ├─ husky@npm:^8.0.1 → npm:8.0.1
      ├─ lint-staged@npm:^13.0.3 → npm:13.0.3
      ├─ prettier@npm:^2.7.1 → npm:2.7.1
      ├─ typescript@patch:typescript@^4.7.4#~builtin<compat/typescript> → patch:typescript@npm%3A4.7.4#~builtin<compat/typescript>::version=4.7.4&hash=7ad353
      ├─ @typescript-eslint/eslint-plugin@npm:^5.31.0 → npm:5.31.0 [d97b7]
      ├─ @typescript-eslint/parser@npm:^5.31.0 → npm:5.31.0 [d97b7]
      ├─ eslint-config-prettier@npm:^8.5.0 → npm:8.5.0 [d97b7]
      ├─ eslint-plugin-functional@npm:^4.2.2 → npm:4.2.2 [d97b7]
      ├─ eslint-plugin-import@npm:^2.26.0 → npm:2.26.0 [d97b7]
      ├─ eslint-plugin-jest@npm:^26.6.0 → npm:26.6.0 [d97b7]
      ├─ eslint-plugin-lodash-fp@npm:^2.1 → npm:2.1.3 [d97b7]
      ├─ eslint-plugin-prettier@npm:^4.2.1 → npm:4.2.1 [d97b7]
      ├─ eslint-plugin-simple-import-sort@npm:^7.0.0 → npm:7.0.0 [d97b7]
      ├─ eslint-plugin-sonarjs@npm:^0.14.0 → npm:0.14.0 [d97b7]
      ├─ jest@npm:^28.1.3 → npm:28.1.3 [aec87]
      ├─ ts-jest@npm:^28.0.7 → npm:28.0.7 [aec87]
      └─ ts-node@npm:^10.9.1 → npm:10.9.1 [aec87]
```

**Comment by bradzacher** [comment]
`ignoreRestSiblings` only applies to object patterns, not array patterns.

In an object pattern variables are **required** to exist as they effect the result of the spread.
In an array pattern variables are not required because array patterns can have holes.

The correct code is

```js
const [, , ...args] = argv;

// or if you want to keep documentation

const [/*node*/, /*appName*/, ...args] = argv
```

**Comment by xenoterracide** [comment]
huh, I totally missed that... why didn't the playground show the error then? I assumed something more complicated was required... 

I totally wonder why ignoreRestSiblings isn't designed to do arrays too...

**Comment by bradzacher** [comment]
> wonder why ignoreRestSiblings isn't designed to do arrays too

It's because of what I mentioned above. Object rest siblings are required, array rest siblings are not.

You can use the ignore variables pattern option to ignore array pattern variables using some naming convention.
Object pattern variables need to be manually renamed to match a pattern, which is much more cumbersome.

> why didn't the playground show the error then?

Three reasons:
1) you exported the variable decl - so all variables are considered used.
2) your config was incorrect - you did not declare a `rules` section.
3) you did not use the correct rule name (you wrote "no-unused-var")

[Actual working playground](https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=MYewdgzgLgBA2mEATApgGhgQwA7YHKYC26MAdOZgE4DmEAujALzwDkmLGLARhzC8CzoAoISgAe2EJVgBvGAF8A3EKA&eslintrc=N4KABGBEBOD2sBdIC4wOgVwKYBoSSwDsA3FMYKLAZwDYz1sBfMPAgDwSIBMqyBtcFAAOAGwwBzAJaFkAAQQBPIdQDG0SUIQBaaiOkIA9NCwrYAWzPcsXSCAC6rIQENoVLNDKR5S1es06qPUJDZ1d3SEcXN2gAeU1JWEJeMFRQCAIVMycANXcqBMIyACYABgBGAA48dKpYDGgVLAAVH08zWC4MESwIwUghOAArEyRUPkgAKgmDBCpTQgAzSXEAOkHawrsQRkcxKST+L0VlOb9tXX1IB3xMbt5U-G8TtQ1zwP0DQlgtDEIMNy4WmIUU87jgHm22yAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEk6JAsrACYCuGAkkXlrIhWDyZW6ADTgakPAENMAc3R4BdEgCYADAEYArJHE0o8Fu3QAlerFSsCxZURbo9E2iVitM0dA2n9KQkfqSqMgARgIA2s6S9BqaAByQUQC6gbToAB6IWMjw6NzSqAAi6HCY0niwmGR+wmJRdPDIeMWl5ZUMitLM5dIC-nUGkMwlqLLlhER9talQIdIk6ACqmKjKAHROg0ZsGMpw8EZEAFZkM5AFqLAA7gBS1WAAZgULZ9AAFiUA1ncCT6gv9XsHCQwWgTQAgkQAJ5TAL1YbQUZlGxEby+QTTeokITIaBKGpwwYkT7IRAAGVCAGEPtBPr9ngNJNjMLi8AA5dioalfe79M6YCyoABu6DuxCYO0cBMZtAelU8lOIJGQ2LyeEp82QRDkXAAYmh0GzpLleZjBirLOV0MwJSZTYTJPYAKKNfEYkQSAC+gTo6URrGGEUBDgA+ts7ZtJMwVUoJCkJJAHgb7uEkiBPUA)
