### ISSUE TITLE
Rule proposal: Prefer `stream.pipeline` over `stream.Readable#pipe` in Node.js

### ISSUE THREAD

**Issue by sindresorhus** [typescript-eslint/typescript-eslint#542]
In Node.js, you use the [`.pipe()`](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options) method on readable streams to chain multiple streams together. However, this method has many problems. It doesn't forward errors and it doesn't always properly clean up. Node.js 10 introduced an alternative better API for chaining streams together called [`stream.pipeline()`](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback).

I would like to enforce using `stream.pipeline` over `stream.Readable#pipe`.

---

I considered opening this request on [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node), but it would have too many false-positives without type information.

**Comment by bradzacher** [comment]
@sindresorhus - there's no reason that `eslint-plugin-node` can't consume type information if it's available.

I'll leave this open, but any plugin is free to use the type infra provided by the parser

**Comment by mysticatea** [comment]
Yeah, I'm OK that `eslint-plugin-node` looks type information.

**Comment by sindresorhus** [comment]
> there's no reason that eslint-plugin-node can't consume type information if it's available.

@bradzacher How would that work? Will an ESLint plugin rule need to have a lot of conditionals for when there are types available and not? Or will it also work with JS?

**Comment by bradzacher** [comment]
Well it depends i guess.
Something like this would probably *require* type information to work properly (or else you'd get a lot of false positives).

There's 3 cases I can see:
1) The rule _requires_ type information to work.
2) The rule needs type information for some of its features, but can work okay without it.
3) The rule doesn't need type information.

In the latter 2 cases - I would say that the rule should gracefully handle missing type information.
In the first case, the rule should hard fail if it's missing (which is what we do in this plugin).

I don't think there's a problem with hard failing a rule outside of this plugin if it's missing type information, as long as it's properly documented.

**Comment by sindresorhus** [comment]
> Something like this would probably require type information to work properly (or else you'd get a lot of false positives).

Correct. I can't imagine having this one without type information.

Would it be possible to get type information even from JS files? For example, VS Code shows best-effort type information for JS files.

I'm asking because I would really want to take advantage of type information in [`eslint-plugin-unicorn`](https://github.com/sindresorhus/eslint-plugin-unicorn), but I cannot abandon JS users. So I either need to make the rules support with and without types or create separate JS/TS rules. I was kinda hoping I could create the rules with type information, and have them just gracefully be more naive without.

**Comment by bradzacher** [comment]
I personally don't think there's a problem having a handful of rules within _every single_ eslint plugin which don't work without typescript installed, as long as it's not the majority, I don't think that's abandoning JS users.
Abandoning JS users would be going back and breaking existing rules so they only work with TS installed, but I doubt you'd be do that.

Within this repo we use [this function](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/util/getParserServices.ts) to get type information - we intentionally have no grace and hard fail if the user doesn't correctly configure things, because our rules are firmly in the first case of all-or-nothing.

----

>  I was kinda hoping I could create the rules with type information, and have them just gracefully be more naive without

No reason you can't do that. If they don't use our parser, and don't provide `parserOptions.project`, then it should still work fine - it's just that `context.parserServices.program` and `context.parserServices.esTreeNodeToTSNodeMap` will be `null`/`undefined`.

You can certainly have a number of `if (parserServices != null)` checks if you'd like to enhance your rules with type information, if it exists.

> Would it be possible to get type information even from JS files? For example, VS Code shows best-effort type information for JS files.

TBH I'm not actually sure what it gives us if it's not a TS file. I haven't ever tried because all of my projects are pure TS.
I *assume* that it'll do the same thing VSCode does, and give you best guess types with a lot of `any`s.

But ofc if they don't install typescript + the parser, and don't provide a `parserOptions.project`, they won't have any type information for JS files.

**Comment by JamesHenry** [comment]
I believe the resolution here is that there is no action to be taken within this project, so closing for now. Please feel free to reopen if further discussion makes sense.

Thanks all 🙏
