### ISSUE TITLE
Bug: [rule name here] <short description of the issue>

### ISSUE THREAD

**Issue by Laurin-W** [typescript-eslint/typescript-eslint#5443]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=GYVwdgxgLglg9mABDAzikBTAFABwE5wBGAhoQDYCeAkmFBgOYZ4Bci4A1mHAO5gCUiAN4AoRMmCIsAORABbQkwB0qAMrFgGGnUZ5cBEuWq0GTPgJFixEBCijIUANWJlMAcTwZidPABUAFsRgAFpMcIgAvIj4RKSUWiZ4iAB8iAAMANyiiAC+wrlAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
function issue(probablyInteger: unknown) {
  if (Number.isSafeInteger(probablyInteger)) {
    const isValueGreaterThanZero = probablyInteger > 0;
//                                 ^^^^^^^^^^^^^^^ Object is of type 'unknown'.(2571)
  }
}
```

### ESLint Config

```javascript
{
  "rules": {}
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Variable `probablyInteger` is recognized to be of type `number` within the if-clause.

### Actual Result

Variable `probablyInteger` is _not_ recognized to be of type `number` within the if-clause and problem is generated.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | `5.32.0` |
| `@typescript-eslint/parser` | `5.32.0` |
| `TypeScript` | `4.7.2` |
| `ESLint` | `8.15.0` |
| `node` | `web` |

**Comment by JoshuaKGoldberg** [comment]
@Laurin-W thanks for mostly filling out the bug form! The heading was still the default so I just edited that real quick just now. Also, your issue doesn't mention any specific typescript-eslint rules -- because this is a TypeScript issue, not typescript-eslint. If you hover your mouse over `probablyInteger` on the offending line, you can see that TypeScript still considers it to be type `unknown`, not `number`. See https://github.com/microsoft/TypeScript/issues/44665 for why that's the case.

We in typescript-eslint roughly only use the TypeScript compiler to determine node types. If it's not working as expected in TypeScript-land, it's not working as expected here either.

For an explanation of what typescript-eslint is compared to TypeScript itself, see the homepage of https://typescript-eslint.io. https://sourcegraph.com/notebooks/Tm90ZWJvb2s6MTA2OA== is a nice deep dive into typescript-eslint itself.
