### ISSUE TITLE
Rule proposal: Prevent declaring variables without the type known at declaration

### ISSUE THREAD

**Issue by Clonkex** [typescript-eslint/typescript-eslint#5526]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [x] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I'd love a rule that prevents declaring a variable without the type being immediately known. Most variables I use can be declared as `const`, but sometimes I need to create a variable that can be changed later. For instance:

```
let someVar; // Whoops, forgot the type annotation here! Now it's of type "any" until the point where it's first used
if(expression) {
    someVar = 'valueOne';
} else {
    someVar = 'valueTwo';
}
```

In those cases, it would be great if the linter could tell me I've forgotten to annotate the type. I don't want to be allowed to assign whatever I want to the variable, plus I want the IDE to always know what the type of the variable is. Essentially I want to behave more like using `var` in C# (where I can't do `var someVar;` because I don't give it a value with a known type).

### Fail Cases

```typescript
// Bad
let someVar;
...
someVar = '123';
...
someVar = 123;
```

### Pass Cases

```typescript
// Good
let someVar: string;
...
someVar = 'someValue';

// Good
let someVar = 'someValue';

// Good
let someVar = SomeFunctionWithAnnotatedReturnType();

// Good
let someVar = expression ? 'valueOne' : 'valueTwo';
```

**Comment by bradzacher** [comment]
In general we don't want to create rules that just ban a feature/syntax unless
1) there's some additional value we can create beyond just flagging it (like fixers, for example)
2) detecting the problem is more complex than a simple selector can handle

I don't think that either (1) or (2) apply to this case, so I'm going to reject this proposal.\

Check out this FAQ article:
https://typescript-eslint.io/docs/linting/troubleshooting/#how-can-i-ban-specific-language-feature

This selector should flag it:
`VariableDeclaration[kind = 'let'] > VariableDeclarator[init = null]:not([id.typeAnnotation])`
[playground](https://typescript-eslint.io/play/#ts=4.7.4&sourceType=module&showAST=es&code=PQKgUApgzgNglgOwC4AIEHsC0AnaTtwDGSEAJplAJ7ICGAHgFwoDaYKKARBNtuthwBo2KAN7D2HKBBgRifDkw4A1GgRoAjGQBFZMVTSRx0CZgGtEpFAF4UAchlJbAXRQA+FCrWaIOwnuwGfMyIcKg2CACuMDBODBhIABTBpAB0SJQADhAAggjxBkYITgCUguKcALbQUDQA5hAKnAAKvABucKQQKDQo6VndeehIBcYcwgC+YE5gIMBgYMDAKABCNKRgDihQ6FWeAIwA3GDbu6p71nZ7AEwAzLZHJxD7F9c3RwtLAOLo6Oubj54rkwoPhELUHjsnqorhdbACaDAIhB7vNFihvr8NhBUPDsDdYfDEcj3miMX9sVtIZ4ACwXepIADK0lkhmMCWKJK+P3JOKpqgArBdcfiAPx2VoIpEAeQQyJQTFsEqJABUAO7oe5AA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUhFYASSSomyPAEEiATwphR6KQF8Q+oA)

**Comment by Clonkex** [comment]
Wow, I had no idea that was a thing. That's super cool, thanks!
