### ISSUE TITLE
Rule Proposal: no-disable-auto-sanitization

### ISSUE THREAD

**Issue by a-tarasyuk** [typescript-eslint/typescript-eslint#554]
Add rule `no-disable-auto-sanitization` from [tslint-microsoft-contrib](https://github.com/Microsoft/tslint-microsoft-contrib)

> Do not disable auto-sanitization of HTML because this opens up your page to an XSS attack. Specifically, do not use the execUnsafeLocalFunction or setInnerHTMLUnsafe functions.

**Comment by bradzacher** [comment]
out of curiosity - how often does this come up in codebases?
I've never even heard of either of the functions.

**Comment by a-tarasyuk** [comment]
@bradzacher This rule is part of [tslint-microsoft-contrib](https://github.com/Microsoft/tslint-microsoft-contrib), which listed in [ROADMAP](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#security) as not implemented. Some of the projects which I contribute use rules from `tslint-microsoft-contrib`. What do you think does that make sense to add these rules including `no-disable-auto-sanitization` to `eslint-plugin` or better to implement them in a new repository?

**Comment by bradzacher** [comment]
Like I mentioned in my email - ultimately it depends on the what the rule does.
If it is related to typescript language features, or relies upon typechecking (and is not directly concerning a specific library), then it's something that fits in here.



I'm just curious what this rule is guarding against because I haven't ever seen either of these two functions, and I've worked on codebases for IE specific applications.
How often do they come up in typescript codebases?

**Comment by a-tarasyuk** [comment]
@bradzacher OK, thanks for the clarification. I think better to implement rules related to `tslint-microsoft-contrib` as a new plugin.
