### ISSUE TITLE
Also remove pre-push hook?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#556]
Following #259: it's inconvenient to wait for a full lint + typecheck after every `git push`. CI builds reinforce them anyway. Can they be removed, please?

**Comment by bradzacher** [comment]
If you're confident that they're correct can't you just use `--no-verify` on push?
I like to have them there because it can help to catch users that haven't done those super basic checks (i.e. don't have a prettier plugin installed in their editor).
The typecheck step could be removed if it's too slow. The lint too if it's still too slow.

But one of the most common forms of CI build failures is formatting, so I'd like to at a minimum keep that. That at least saves time by not having to re-review PRs and such.

**Comment by JoshuaKGoldberg** [comment]
> can't you just use --no-verify on push?

Yes, but it's a pain to forget it. 

> not having to re-review PRs and such

Interesting: from a reviewer/maintainer perspective, do you re-review when a build is failing?

I'll try to send a PR soon to remove typecheck and linting, thanks!

**Comment by bradzacher** [comment]
If we approve a PR, and then a new commit comes in (that's not a straight merge commit), github dismisses the review (because it's stale - the code has changed).

So if we approve then the user commits to fix a formatting issue, it'll dismiss the review and we'll have to be conscious of it and re-approve. That or we request changes then have to approve once they fix the formatting.

Having it checked pre-push helps guard against people that "fire and forget" their PRs and only update them once they're commented on.
