### ISSUE TITLE
Rule proposal: no-enum / ban-enum / no-use-enum

### ISSUE THREAD

**Issue by kachkaev** [typescript-eslint/typescript-eslint#561]
After switching to TypeScript, our team's monorepo ended up with quite a few [enums](https://www.typescriptlang.org/docs/handbook/enums.html) in various parts of the code. Initially, referring to enums felt better than exporting named constants as we did in the good old JavaScript times (`export const STATUS_READY = "ready"`). However, we noticed a few issues with enums afterwards and decided to switch to TypeScript discriminated unions instead. The most irritating issue with enums for us was that their imports could cause cyclic module dependencies, thus magically resulting `undefined` in unexpected places, e.g. when running Jest tests.

We have removed all enums from the codebase, but there is still a chance that someone can introduce a new enum via a PR and this will be overlooked. I'm wondering if `@typescript-eslint/eslint-plugin` could have a rule named like `no-enum` / `ban-enum` / `no-use-enum` to prevent this from happening.

> Example of **incorrect** code for this rule:
> 
> ```ts
> enum Direction {
>   Up,
>   Down,
>   Left,
>   Right,
> }
> ```
> 
> Example of **correct** code for this rule:
> 
> ```ts
> type Direction = "up" | "down" | "left" | "right"
> ```

All the rule would have to do is searching for the `enum` token – that does not seem too complex. WDYT folks?

Related: https://github.com/typescript-eslint/typescript-eslint/issues/280 (see [comment](https://github.com/typescript-eslint/typescript-eslint/issues/280#issuecomment-494501481) by @leoyli with a similar request)

**Comment by leoyli** [comment]
I think this also kind of useful, and perhaps it can be auto-fixed in some cases. :+1:

**Comment by bradzacher** [comment]
we don't like to implement rules that just ban a language feature, because we've found that different people like different things, and unless it's preposterous that you'd use the inverse (like `no-ts-ignore`), we would want to support the opposite as well.

Happy for something like this to be implemented, but we may want to review it in conjunction with the other enum rules with PRs (#290, #315)

**Comment by leoyli** [comment]
True, I feel there are many similar rules flooded, and would like to have 1 entry point to regulate how `enum` could be used.

We are using TS as just **a pure type checker**, so any non-type-system-related syntax/operators will out of our interests. `Enum` surely have its own syntactical advantages, but because of Babel won't be able to support it properly, then this could be 1 exception here. This rule is helpful to avoid surprise to see why "my `const enum` code doesn't work".

**Comment by platinumazure** [comment]
Will the core [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax) work here? I think it should since the enums are language constructs that are traversed-- you would just need to know the proper selector for reporting on them when they are used. (I don't know what that proper selector is, sorry.)

**Comment by bradzacher** [comment]
I believe that would work @platinumazure 

```
{
  "rules": {
    "no-restricted-syntax": [
      "error",
      {
        "selector": "TSEnumDeclaration",
        "message": "Don't declare enums"
      }
    ]
  }
}
```

**Comment by leoyli** [comment]
Tested, the above is the one I am looking for. But I think this rule might be useful if ESLint-TypeScript would ever provide the recommended default setup for Babel users. 🤔

**Comment by kimamula** [comment]
It may be worth noting that you can also disallow either const or non-const enums selectively with `no-restricted-syntax` rule.

Disallow const enums:

```
{
  "rules": {
    "no-restricted-syntax": [
      "error",
      {
        "selector": "TSEnumDeclaration[const=true]",
        "message": "Don't declare const enums"
      }
    ]
  }
}
```

Disallow non-const enums:

```json
{
  "rules": {
    "no-restricted-syntax": [
      "error",
      {
        "selector": "TSEnumDeclaration:not([const=true])",
        "message": "Don't declare non-const enums"
      }
    ]
  }
}
```

**Comment by halfnibble** [comment]
Is there any way to selectively do this so that const enums are allowed for internal package use, but cannot be exported for external consumption?

**Comment by bradzacher** [comment]
It's pretty hard / near impossible to detect this.
What does it mean to not be exported? It's a project dependent definition.
Without bundling, every file is technically available to import by a consumer.
With bundling, what is exported depends on how your bundler is configured - i.e. what entry points you define.

A rule like that would have to understand the above, and be able to scan every export from the "external api", and crawl every single type to find any const enums.

I.e. very hard to do, very niche, and outside of the scope of this plugin.
