### ISSUE TITLE
Enhancement: migrate functional-red-black-tree to js-sdsl

### ISSUE THREAD

**Issue by ZLY201** [typescript-eslint/typescript-eslint#5624]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Relevant Package

eslint-plugin-tslint

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Hey! I'm the developer of Js-sdsl. Official website: https://js-sdsl.github.io/

Now, we published the version 4.1.4.

I see you are using functional-red-black-tree.

In [benchmark](https://js-sdsl.github.io/#/test/benchmark-result?id=rbtree), we have confirmed that Js-sdsl is several times faster than functional-red-black-tree.

I've submitted a PR to eslint and has been accepted.

See https://github.com/eslint/eslint/issues/16255 and https://github.com/eslint/eslint/pull/16267.

I am willing to submit a pull request for this change.

Looking forward to your reply! :D

### Fail

```typescript
none
```

### Pass

```typescript
none
```

**Comment by bradzacher** [comment]
Thanks for the issue!

Whilst we do have it as a dependency, we don't really use the code. It was intended to be part of a complete fork and rewrite of the indent rule to support TS features, but due to time constraints and lack of interest amongst the maintainers it has never actually progressed nor was it ever released.
See https://github.com/typescript-eslint/typescript-eslint/issues/1824

We'll probably delete the chunk of code for now considering it's looking like it's unlikely to be worked on by anyone, which would remove our dependency.

**Comment by bradzacher** [comment]
I have raised #5625 to delete our unused fork.
