### ISSUE TITLE
[no-explicit-any] Adding switches for supported options

### ISSUE THREAD

**Issue by weirdpattern** [typescript-eslint/typescript-eslint#57]
I'd like to propose a change to an existing rule.

How about adding extra options to the `no-explicit-any` rule?
I'm thinking switches for the multiple cases that are currently supported, but my main concern is with the generic array declaration when the array is used as a rest parameter. 

I'm not proposing any specifics and not doing any work on it just yet as I want to hear from the community before I (or who ever wants to take it) start working on it...

So, thoughts?

**Comment by moulikcipherX** [comment]
@bradzacher any work on this issue?

**Comment by bradzacher** [comment]
@moulikcipherX - there hasn't been anything done!
it's difficult though because we don't currently have any "cases" so it'll be a bit of work/discussion to decide what should have options.

However right now there hasn't been anyone asking for options (not even +1's on this issue) - so I wouldn't class this as a high priority enhancement

**Comment by kirstu** [comment]
One such case is typing generic rest parameters / function arguments:
```TypeScript
type HigherOrderFn = <TArgs extends any[], TVal>(fn: (...args: TArgs): TVal): TVal
```
More in [Typescript site](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#generic-rest-parameters)

**Comment by jhnns** [comment]
Seems like this issue is resolved now? :)

**Comment by JamesHenry** [comment]
Yep! Thanks for pointing it out @jhnns
