### ISSUE TITLE
Bug: `@typescript-eslint/promise-function-async` function overloading

### ISSUE THREAD

**Issue by zumm** [typescript-eslint/typescript-eslint#5709]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.8.3&sourceType=module&code=KYDwDg9gTgLgBAMwK4DsDGMCWEVwEYAUAlAFxwAKUEAtpgM7AA8AbhJgCYB8AsAFCiRYiVBmy5CAQzJ4IEADbAJKUnFYc+A6PGTosOfAQkB+abIVKVlGvSZqucAD6q27OAG8+cOJgRxDcAF4AuBQkOTkiOChgGCQoXCtaBgA6aIArYAwCFGAAdzgAUSgqKGIiTzgYAAsqfJz8opLiPgBfPiA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6AewFtLlFaAM1hMy+Spya0AhskKj0URNC7RI4MAF8QmoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
export function b(): Promise<void>
export function b(a: boolean): void
export function b(a?: boolean): Promise<void> | void {
  if (a == null) return Promise.reject(new Error())
  throw new Error()
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/promise-function-async": "error",
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

No error.

### Actual Result

Error.

### Additional Info

Error will disappear if swap line 1 and line 2.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.38.1` |
| `@typescript-eslint/parser`            | `5.0.0` |
| `TypeScript`                           | `4.8.3` |
| `ESLint`                               | `8.15.0` |
| `node`                                 | `v16.15.1` |

**Comment by JoshuaKGoldberg** [comment]
Function overloads, always a fun feature! 🙃 

This function _does_ have the ability to return a `Promise`. So I would say it should be marked `async`, and the bug is that when lines 1 and 2 are swapped, it no lint complaints are reported. [[playground with no reports that should have one](https://typescript-eslint.io/play/#ts=4.8.3&sourceType=module&code=KYDwDg9gTgLgBAMwK4DsDGMCWEVwEYAUAhgFz4QQA2wRKAlGQG4SYAmAUKJLIqhtrkIM4ABSgQAtpgDOwADzM2APk7ho8ZOiw58xAPxk8FarWFjJM+YtZK4AHzjW4Ab3Zw4mBHGJwAvL7gUJEpKOjgoYBgkKFxzKVkAOgiAK2AMAhRgAHc4AFEocSgCOjo3OBgAC3EczJz8wuL2AF92IA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6AewFtLlFaAM1hMy+Spya0AhskKj0URNC7RI4MAF8QmoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)]. Marking as accepting PRs - thanks for filing!

Aside: https://typescript-eslint.io/rules/no-invalid-void-type is relevant here.

**Comment by zumm** [comment]
@JoshuaKGoldberg There is also no error for function b without overloading (if line 1-2 is removed).

Marking such function as async is weird because async forces function to return only promise while it could be unwanted.

**Comment by kirkwaiblinger** [comment]
@JoshuaKGoldberg @ronami 

I think we need to clarify for the record what resolution this issue is accepting PRs for. I interpret the OP's request as suggesting that a function that _may_ need to return a non-promise, due to an explicit type annotation in an overload, should _not_ be forced to be `async` by this rule, as is already the case for non-overloaded functions.

However, I interpet https://github.com/typescript-eslint/typescript-eslint/issues/5709#issuecomment-1264412464 from Josh as suggesting that any function that _may_ ever need to return a promise _must_  be async (and therefore must _always_ return a promise).

The PR currently open, https://github.com/typescript-eslint/typescript-eslint/pull/10304, appears to implement the OP's approach, not Josh's. But I agree with @ronami's PR. @JoshuaKGoldberg, please yell if you want to object!

Note that the [rule doc](https://typescript-eslint.io/rules/promise-function-async/) says 

> When functions return unions of Promise and non-Promise types implicitly, it is usually a mistake—this rule flags those cases. If it is intentional, make the return type explicitly to allow the rule to pass.

My logic is that overloads are a form of explicit type annotation, therefore, code that is written to appease the overloads should pass.

**Comment by JoshuaKGoldberg** [comment]
👍 from me, thanks for the clarification.
