### ISSUE TITLE
Docs: [prefer-nullish-coalescing] missing `forceSuggestionFixer` description

### ISSUE THREAD

**Issue by Dimava** [typescript-eslint/typescript-eslint#5829]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Add information on what `forceSuggestionFixer` does and what is its default value

### Affected URL(s)

https://typescript-eslint.io/rules/prefer-nullish-coalescing/

**Comment by adnanhashmi09** [comment]
Hey I would like to work on this issue. I will submit a PR soon.

**Comment by adnanhashmi09** [comment]
Going through the code made me realize that this option is not needed anymore. This was introduced to convert all cases of the fixer to a suggestion which allowed you to turn the rule on as a warning, and slowly migrate your codebase without worrying about someone running `--fix` and breaking it. Refer [this](https://github.com/typescript-eslint/typescript-eslint/issues/1313#issuecomment-562800040).

Now that this rule isn't `fixable`, it won't fix automatically on someone running `--fix`.

@JoshuaKGoldberg Please confirm this and let me know if I misunderstood something. 

@bradzacher I am also mentioning you since you worked on this.

**Comment by JoshuaKGoldberg** [comment]
One line deletion? Seems perfect for a first PR into the repository. Nice! 😄 

<img width="467" alt="Screenshot of a VS Code search for forceSuggestionFixer showing only one result" src="https://user-images.githubusercontent.com/3335181/196032580-570b4e8a-92a7-4493-84e8-760ee050d1cd.png">

**Comment by adnanhashmi09** [comment]
Yep. Will make a PR shortly. :)

**Comment by bradzacher** [comment]
*technically* this is a breaking change - but i'm happy removing it now cos it hasn't done anything in god knows how long.
