### ISSUE TITLE
Refactor: Remove createIsolatedProgram call from getProgramAndAST

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5856]
## Overview

https://github.com/typescript-eslint/typescript-eslint/blob/09c04fb0d5a5dee0dc266abb2e21aa9a1c489712/packages/typescript-estree/src/parser.ts#L90-L91

That last `|| createIsolatedProgram(code, extra)` _should_ never be hit. We believe it was a just-in-case fallback added long ago that is no longer (and maybe never was) needed.

Removing that case may make #5855 easier. 

Marking as accepting PRs with the caveat that everything still has to work as expected. Which may or may not be doable. Good luck! 😄

This issue is from a pairing I had with @bradzacher going over the parser internals.

**Comment by bradzacher** [comment]
I remembered why it was there.
The isolated program allows us to provide a program always which allows us to power the parser services always.

Most of the time this is going to be useless as you can only get types for the current file and no dependencies, but it does enable you to access diagnostics for the file (variable usage, non type semantic errors, etc).

I added this to power the "no-unused-vars-experimental" rule way back so that I could leverage TS's unused variable logic, but unfortunately it took an average of 50ms per file to calculate diagnostics - which is too slow across an entire codebase.

So I think we should breaking change remove this. I can't think of a reason that someone would want this now.

To double check - does the TS language server API need a program? Or does it create its own?

**Comment by JoshuaKGoldberg** [comment]
Language _server_ or language _services_?

In TypeStat I generate a language _service_ without a program: https://github.com/JoshuaKGoldberg/TypeStat/blob/a43cac385b8a4fcb2263d94e28ce5059de29f159/src/services/language.ts#L42-L54

**Comment by JoshuaKGoldberg** [comment]
#8834 was merged into `v8`. ✅
