### ISSUE TITLE
Refactor: replace module-scoped createWatchProgram variables

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#5891]
### Suggestion

I finally spelunked into `createWatchProgram.ts`. TIL about `knownWatchProgramMap`, `currentLintOperationState`, and other module scoped variables in that file.

https://github.com/typescript-eslint/typescript-eslint/blob/2ee81df5a365d82ef4b3dfc124d4ec39c7bcb725/packages/typescript-estree/src/create-program/createWatchProgram.ts#L21

https://github.com/typescript-eslint/typescript-eslint/blob/2ee81df5a365d82ef4b3dfc124d4ec39c7bcb725/packages/typescript-estree/src/create-program/createWatchProgram.ts#L93

It looks like some of these variables are caches that probably should be global. But I'm dubious about `currentLintOperationState` - perhaps it can go through a similar refactor as #5833?

**Comment by bradzacher** [comment]
`currentLintOperationState` definitely should be able to be localised. I think the original idea was that the implementor thought that TS would do things async, so it needed to be stored like so.

In a nutshell - ESLint asks us to parse file A:
- If there IS NOT a program, we synchronously create one and when TS attempts to read file A from disk we give it the code ESLint gave us.
- If there IS a program, we trigger the watch callback for file A, and then ask TS to update the program. TS then (synchronously) attempts to read the changed files from disk (just file A as that's all we've marked as changed) and we return it to the code ESLint gave us.

There's an interesting property here in that TS caches the code string for us - so in the IDE usecase we don't need to worry about keeping track of this list of files that differ from disk because TS won't re-read them from disk unless we mark them as changed!

**Comment by JoshuaKGoldberg** [comment]
Turns out from #6082 this isn't straightforward. `createWatchProgram` creates a `readFile` function that's called later on. @bradzacher seems to me like we actually want the current behavior, and would want to close this issue?

**Comment by bradzacher** [comment]
@JoshuaKGoldberg Yeah I think that the only way we could make it work is if we changed the code to use callbacks like
```ts
const globalState = { ... };
function getProgram() {
  let lintedFile;
  program.readFile = () => {
    // use lintedFile;
  };

  return { program, updateLintedFile: (newFile) => { lintedFile = newFile } };
}
```

but that's a pain because then we have one callback per project and we need to call every single callback to update the local state.
having a single global state means we can update it once and have all programs read from it when (or rather, if) they need to.

Lets close this!
