### ISSUE TITLE
Rule proposal: no-overtyping

### ISSUE THREAD

**Issue by httpete** [typescript-eslint/typescript-eslint#5923]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I see lots of time in our code where developers will just type things instead of relying on inference. It is just less clutter. You don't need to do a return type where it can be inferred, and in this case when using reduce, it already knows teh type of the members and iterator.

```ts
groupFilters.reduce((prev: string, curr: UIGroupFilter, index: number) => {
    return index ? (prev += `,${curr.id}`) : `${curr.id}`;
  }, '');
```

Should just be:
```ts
  groupFilters.reduce((prev, curr, index) => {
    return index ? (prev += `,${curr.id}`) : `${curr.id}`;
  }, '');
```

### Fail Cases

```typescript
groupFilters.reduce((prev: string, curr: UIGroupFilter, index: number) => {
    return index ? (prev += `,${curr.id}`) : `${curr.id}`;
  }, '');
```

### Pass Cases

```typescript
groupFilters.reduce((prev, curr, index:) => {
    return index ? (prev += `,${curr.id}`) : `${curr.id}`;
  }, '');
```

**Comment by bradzacher** [comment]
The big issue with this request is that it can be surprisingly difficult to determine what is and isn't a necessary type annotation in TS.

Annotations and assertions can cause TS to infer different types for generic parameters.
For example in this code:
```ts
declare const x: string[];
declare const initialValue: any;

x.reduce((arg: number) => {
  // typeof T === number
  return arg;
}, initialValue);

x.reduce((arg) => {
  // typeof T === any
  return arg;
}, initialValue);
```

The `: number` annotation causes TS to infer the generic parameter of the `reduce` function to be `number`. If you omit the annotation, then TS will infer the generic as `any` instead.

However if you inspect the types for the function, you'll only see that the expected type of `arg` is `number` (based on the generic) and the declared type of `arg` is `number` - so that would be a lint error!

Note that this is true of any typings where the explicit type of the accumulator parameter is a super-type of the type of the initial value - `any` is just a convenient and quick example, but you could imagine the initial value being typed like `{a: string, b: string}`, and the accumulator parameter being `{a: string}` - same principle!

Similarly there are cases of "under specified generics" like this:
```ts
declare function wrapCallback<T extends (...args: any[]) => any>(callback: T): T;

wrapCallback((arg: number) => {});
// typeof T = (arg: number) => void

wrapCallback((arg) => {});
// typeof T = (arg: any) => void
```

As above if you inspected the types you'd see that the explicit annotation is unnecessary - but without it the type of the argument is `any`.

And the above case is even weirder if you add a default value - because TS ignores that even though you might expect it wouldn't!
```ts
wrapCallback((arg: number = 1) => {});
// typeof T = (arg?: number) => void

wrapCallback((arg = 1) => {});
// typeof T = (arg?: any) => void
```

These cases are actually a lot more common than you might think! Which is why it's not some rare edge case we can just ignore.

TS unfortunately doesn't provide any APIs to help here - there's no way to speculatively ask TS "what would be the type of this thing if there wasn't an annotation". Which means we're really stuck with the information directly available in your code.

----

There is a big question here of whether you should lean on TS's inference more or less. Ultimately it's really just a stylistic decision.

I'm just not sold on this as something that should be explicitly enforced one way or the other given how much complexity would be involved in solving this without lots of false positives.
I'd be interested in hearing more arguments in favour of this rule!

**Comment by httpete** [comment]
Thanks for your very thoughtful response. I feel relying on inference is just less to see and maintain and does the same thing, and I would argue better. In the simple cases, stating every variable explicitly when it is clearly set to a Boolean or string is not necessary. The source of truth is best one in one place to see and maintain.On Nov 2, 2022, at 10:11 PM, Brad Zacher ***@***.***> wrote:﻿
The big issue with this request is that it can be surprisingly difficult to determine what is and isn't a necessary type annotation in TS.
Annotations and assertions can cause TS to infer different types for generic parameters.
For example in this code:
declare const x: string[];
declare const initialValue: any;

x.reduce((arg: number) => {
  // typeof T === number
  return arg;
}, initialValue);

x.reduce((arg) => {
  // typeof T === any
  return arg;
}, initialValue);
The : number annotation causes TS to infer the generic parameter of the reduce function to be number. If you omit the annotation, then TS will infer the generic as any instead.
However if you inspect the types for the function, you'll only see that the expected type of arg is number (based on the generic) and the declared type of arg is number - so that would be a lint error!
Note that this is true of any typings where the explicit type of the accumulator parameter is a super-type of the type of the initial value - any is just a convenient and quick example, but you could imagine the initial value being typed like {a: string, b: string}, and the accumulator parameter being {a: string} - same principle!
Similarly there are cases of "under specified generics" like this:
declare function wrapCallback<T extends (...args: any[]) => any>(callback: T): T;

wrapCallback((arg: number) => {});
// typeof T = (arg: number) => void

wrapCallback((arg) => {});
// typeof T = (arg: any) => void
As above if you inspected the types you'd see that the explicit annotation is unnecessary - but without it the type of the argument is any.
And the above case is even weirder if you add a default value - because TS ignores that even though you might expect it wouldn't!
wrapCallback((arg: number = 1) => {});
// typeof T = (arg?: number) => void

wrapCallback((arg = 1) => {});
// typeof T = (arg?: any) => void
These cases are actually a lot more common than you might think! Which is why it's not some rare edge case we can just ignore.
TS unfortunately doesn't provide any APIs to help here - there's no way to speculatively ask TS "what would be the type of this thing if there wasn't an annotation". Which means we're really stuck with the information directly available in your code.

There is a big question here of whether you should lean on TS's inference more or less. Ultimately it's really just a stylistic decision.
I'm just not sold on this as something that should be explicitly enforced one way or the other given how much complexity would be involved in solving this without lots of false positives.
I'd be interested in hearing more arguments in favour of this rule!

**Comment by bradzacher** [comment]
The more I think about this - the more I'm in the camp of this not being a good candidate for this general-purpose plugin for two reasons:
1) It is a stylistic decision to use fewer annotations, just like it's a stylistic decision to use more annotations.
2) It's really, really, really hard to validate that a type annotation is unnecessary in a given position. It's easy to enforce more annotations are added because a user adding annotations won't change the types, but removing an annotation can change the types - which can lead to unresolvable false-positives, which is frustrating as a user!

Thank you for the request!
