### ISSUE TITLE
Enhancement: require-override: require use of 'override' keyword if member function overrides superclass

### ISSUE THREAD

**Issue by KurtPreston** [typescript-eslint/typescript-eslint#5957]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html

### Description

TypeScript supports an optional `override` keyword in subclasses:

```typescript

class BaseClass {
  doSomething(): void {}
}

class SubClass extends BaseClass {
  override doSomething(): {
    // Do something else!
  }
}
```

This keyword is particularly useful when using TypeScript's `--noImplicitOverride` flag, as it will throw compile errors if a subclass overrides a member function without explicitly declaring `override`. This can prevent issues where a subclass's member function is added that unintentionally duplicates the name of a member function in the base class, breaking functionality.

The only thing preventing me from using the `--noImplicitOverride` flag is the tens of thousands of overrides throughout my code base, most notably in React class components (all `render` or `componentDidMount` are technically `override`).

Eslint's autofixer has been extremely valuable in the past for migrating a codebase to use a best practice. An eslint rule that enforced use of `override` and provided an autofixer would make migrating to use this keyword much easier. Even without the autofixer, it'd be great to be able to have eslint give a `warn`-level notification on a missing override, which could help us gradually fix all our implicit override.

### Fail

```typescript
class BaseClass {
  doSomething() {}
}

class SubClass extends BaseClass {
  doSomething() {} // Oh no! We didn't say override! Fail here!
}
```

### Pass

```typescript
class BaseClass {
  doSomething() {}
}

class SubClass extends BaseClass {
  override doSomething() {} // 'override' keyword detected. All good.
}
```

### Additional Info

Doucmentation for the `override` keyword:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html

**Comment by bradzacher** [comment]
Thanks for the request.
We don't look to re-implement TS features in this project.
The `noImplicitOverride` flag as you have mentioned is built into TS.
We avoid doing this because it reduces the maintenance burden - TS doesn't expose apis to do a lot of things, meaning we have to attempt to rebuild logic exactly - which is time consuming and error-prone.

Similarly we don't look to implement "migration" rules - rules that are really intended to be turned on temporarily, esp when the goal is turning on a compiler option.
Whilst well intentioned, these migration rules have a habit of being left on forever as they remove the driving force - "why push to update the entire codebase to the compiler option when we can just use the lint rule and do less work?"
We suggest users write codemods (scripts that transform code) to do migrations and "rip the bandaid" so that the codebase is migrated and standardised to prevent limbo states.

This request falls into both of those buckets, so we won't be implementing it in this project. Our tooling is free and open for anyone to build with, and we encourage people to build their own lint rules.
