### ISSUE TITLE
Bug: <short description of the issue>

### ISSUE THREAD

**Issue by A-Shleifman** [typescript-eslint/typescript-eslint#5994]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Relevant Package

utils

### Repro Code

```typescript
ESLintUtils.getParserServices(context, true).program.getSourceFile('/Users/user/Documents/repo/src/context.ts');
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "./tsconfig.json",
  },
  plugins: ["@typescript-eslint", "import-access"],
  extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"],
  ignorePatterns: [".eslintrc.js", "node_modules"],
  rules: {
    "import-access/no-imports-outside-package": [
      "error",
      {
        strictMode: true,
      },
    ],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "eslint-plugin-import-access",
        "strictMode": true
      }
    ],
    "target": "ES2017",
    "module": "CommonJS",
    "esModuleInterop": true,
    "noEmit": true
  },
  "include": ["./src/**/*"]
}
```

### Expected Result

`program.getSourceFile('...')` returns requested file when `parserOptions.project` is specified in `.eslintrc`, but when `parserOptions.project` is missing, `getSourceFile('...')` returns the file that is being linted. I would like to remove this setting from .eslintrc, but I can't as it breaks [my plugin](https://github.com/A-Shleifman/eslint-plugin-import-access).

### Actual Result

the wrong file is returned

### Additional Info

Provided configs are the configs of the project using the plugin, not the project that compiles the plugin

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/utils`             | `^5.42.1` |
| `@typescript-eslint/eslint-plugin`     | `^5.42.1` |
| `@typescript-eslint/parser`            | `^5.42.1` |
| `eslint`                               | `^8.19.0` |
| `eslint-plugin-eslint-plugin`          | `^5.0.0` |
| `eslint-plugin-node`                   | `^11.1.0` |
| `typescript`                           | `^4.8.4` |
| `node`                                 | `v16.17.0` |

**Comment by bradzacher** [comment]
This is expected.
The second argument to `getParserServices` is `allowWithoutFullTypeInformation`.
https://github.com/typescript-eslint/typescript-eslint/blob/0fb44ba3f46cef0a35fbd1eb862808cd106287d0/packages/utils/src/eslint-utils/getParserServices.ts#L15
You're setting it to `true`, so you're saying "i'm okay not having full type information for the project".

Which is why the util doesn't explicitly throw when `parserOptions.project` is not set. If this argument is omitted or `false`, then the util will throw in cases where you don't have full type information.

https://typescript-eslint.io/docs/linting/typed-linting

**Comment by A-Shleifman** [comment]
Thank you for a swift response @bradzacher. I understand, but that's not the problem I'm having. The problem is that `getSourceFile` gets the **wrong** source file when `parserOptions.project` is not specified.

**Comment by bradzacher** [comment]
Without `parserOptions.project`, the parser does an isolated file typecheck on the current file - that's it - no dependencies are parsed and all imports are typed as `any`. For most type-aware usecases that's not good enough, for obvious reasons.

By passing `true`, you're saying "I'm okay with having incomplete types". So if you go and attempt to access types/source files for other files - you're entering the realm of "undefined behaviour"! You're going get back whatever TS wants to give you, who knows what that is.

If you're using parser services at all, you shouldn't be passing `true`. That second argument was added for one usecase - to enable consumers to grab diagnostics for the file. Not types - just diagnostics like local unused variables diagnostics.

We're going to be removing it in the next version because it's a pretty useless setting and is (as you've noticed) confusing and difficult to work with.

**Comment by A-Shleifman** [comment]
Got it! Thank you very much!
