### ISSUE TITLE
[no-redeclare] error for declare namespace

### ISSUE THREAD

**Issue by ficristo** [typescript-eslint/typescript-eslint#60]
**Repro**
See below.

```JSON
{
  "rules": {
    "no-redeclare": "error"
  }
}
```

```TS
export = CodeMirror;
export as namespace CodeMirror;

declare function CodeMirror(host: HTMLElement, options?: CodeMirror.EditorConfiguration): CodeMirror.Editor;

declare namespace CodeMirror {
}
```

**Expected Result**
No error.

**Actual Result**
`no-redeclare` error for `declare namespace CodeMirror` line.

**Additional Info**

**Versions**

| package                    | version |
| -------------------------- | ------- |
| `eslint-plugin-typescript` | `1.0.0-rc.0` |
| `typescript-eslint-parser` | `eslint-plugin-typescript/parser` |
| `typescript`               | `3.1.6` |

**Comment by despian** [comment]
+1 have also come across this issue.

Would be nice if [declaration-merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) was supported.

**Comment by G-Rath** [comment]
This also errors on global augmentations, which seems fixable to me b/c it actually only happens when wrapped in a `declare global`:

```
declare global {
  namespace jest {
    interface Matchers<R, T> {
      /**
       * Tests that the expected {@link TFBlockBody} contains only one {@link TFDynamicBlock}
       * with the given `name`
       *
       * @param {string} name
       */
      toContainTFDynamicBlock(name: string): R;
    }
  }
}
```

So you should just be able to look for the `declare global` and go off that.

Let me know if you'd like a separate issue to track this, or if I've missed something :)

**Comment by G-Rath** [comment]
Additionally, a question: is `no-redeclare` actually picking up errors that TypeScript itself isn't?

Aside from the potentially nicer error messages, I'm wondering how much value there is in actually having `no-redeclare` in a TypeScript codebase?

**Comment by bradzacher** [comment]
In response to your second comment - AFAIK it doesn't catch anything.
For these sorts of rules which catch things typescript catches itself, usually people use it because either:
- they have webpack builds wherein they use the typescript in isolated modules mode (or they use babel to transpile).
- they haven't thought about the fact that it does something TS does.

This duplicating a TS compiler error is why this issue (and really all scope analysis rules) have been sitting open for 1yr+++. To the core maintainers the issues are high effort + low value, and there's yet to be a contributor that has cared enough to look into it.

**Comment by bradzacher** [comment]
Merging into #1856
