### ISSUE TITLE
Bug: [naming-convention] Overriding class method doesn't work. (ignore name)

### ISSUE THREAD

**Issue by twoco** [typescript-eslint/typescript-eslint#6064]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link

[Playground](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=MYGwhgzhAECyCeBhcVoG8CwAoa0AuA9gFIDKA8gHIAUAlOtrrgE4CmeArkwHboC+A3A2i9sIrEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgQwFtmBzWsgHsmAN0QtKw9GADa4bDgDuHaE0gAaeQqwLskZIiRl8g6NMgATRADMOCfBq27ISDhb4BVJlejIh0RHMOeHhBRUddPWtTLg4HDDlIhX18KmMAYW5DTINIJwUAXXywAF9NSJ1I-UNEY1NzMngOZGQAWUR8AAtBCwikl0Q3T29EX39AjEhg0PDy-ujoWPjZYuTkVMoMrPgcwNWwArmq60p4fFHpSv6A3kQAD3MAPQAKEwApAGUAeQA5AEoACR9JJQJZkTrSWzwAz7ErFMrFK5rGp1MyTEQqSgcABGSGBzi4PUoJ1GqAS+xwQiY6zyIMO+0gCyW0kSIKgZG2u3xVQ8AAVeQBRABKAH10gBBD4C2lJIqRBEVBkGIwmNFQIikAAylAA1oEjs4mXEWRSoB8NsZec0OTtmns6fCDRAkXplbVVeZxLAuO0uNiLk6ojFjeS2WaLfgrX5glz9nLdHDCvI4SUgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA) 

### Repro Code

```ts
class MyClass {
  toJSON() {
    return {};
  }
}
```

### ESLint Config

```json
{
  "rules": {
    "@typescript-eslint/naming-convention": [
      "warn",
      {
        "selector": "default",
        "leadingUnderscore": "allow",
        "format": [
          "strictCamelCase"
        ]
      },
      {
        "selector": "classMethod",
        "leadingUnderscore": "allow",
        "format": [
          "strictCamelCase"
        ],
        "filter": {
          "regex": "^(toJSON)$",
          "match": false
        }
      },
      {
        "selector": "variable",
        "modifiers": [
          "const"
        ],
        "format": [
          "camelCase",
          "UPPER_CASE"
        ]
      },
      {
        "selector": "typeLike",
        "format": [
          "StrictPascalCase"
        ]
      },
      {
        "selector": "enumMember",
        "format": [
          "StrictPascalCase"
        ]
      }
    ]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

Keep `strictCamelCase` but ignore it for JS pre-defined names like `toJSON` (used from `JSON.stringify`). Unfortunately `toJson` does not work. 

### Actual Result

> Class Method name `toJSON` must match one of the following formats: strictCamelCase

### Additional Info

[Docs](https://typescript-eslint.io/rules/naming-convention/#ignore-properties-that-require-quotes) ([Alt](https://github.com/typescript-eslint/typescript-eslint/blob/v5.3.0/packages/eslint-plugin/docs/rules/naming-convention.md#ignore-properties-that-require-quotes))

We could add some real world examples. Like ignoring `toJSON` when using with `strictCamelCase`.

Update: Hmm, chaning `format` of `classMethod` does not change the required format from error message. Maybe the override (of `default`) does not work or the selector is wrong? But what's correct? 😕 

Workaround: 

```json
{
  "selector": "default",
  "leadingUnderscore": "allow",
  "format": ["strictCamelCase"],
  "filter": {
    "regex": "^(toJSON)$",
    "match": false
  }
}
```

How to override only for class methods? I mean for `typeLike` it works. But what's the selector for class methods if not `classMethod`.

### Versions

See versions in Playground (above). Locally I'm not on latest. But I can reproduce this on latest version in Playground. I guess it's my mistake. Sorry if so. But I'm currently confused and think it's a bug.

**Comment by bradzacher** [comment]
Yes - `naming-convention` has no concept of "overridden base" members or the like - it simply looks at names.
If you have some specific cases that must be cased in a specific way that is contravene to your config, then I would either filter those names out as you have shown in your config or I would use a disable comment.

You probably want to read the section in the rule docs explaining how the rule evaluates selectors - https://typescript-eslint.io/rules/naming-convention#how-does-the-rule-evaluate-a-selector. Specifically point `2.iii` is relevant - if you have a filter and the name doesn't match it, then skip the selector. This causes the identifier to be checked by the next matching selector (which would be the `default`).

Because of this I would suggest inverting the filter to apply no formatting at all for matched members:
```json
      {
        "selector": "classMethod",
        "format": null,
        "filter": {
          "regex": "^(toJSON)$",
          "match": true
        }
      }
```
[playground](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=MYGwhgzhAECyCeBhcVoG8BQ1oBcD2AUgMoDyAcgBQCU6W20ATgKY4CuDAdugL4Dcd3DIKA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgQwFtmBzWsgHsmAN0QtKw9GADa4bDgDuHaE0gAaeQqwLskZIiRl8g6NMgATRADMOCfBq27ISDhb4BVJlejIh0RHMOeHhBRUddPWtTLg4HDDlIhX18KmMAYW5DTINIJwUAXXywAF9NSJ1I-UNEY1NzMngOZGQAWUR8AAtBCwikl0Q3T29EX39AjEhg0PDy-ujoWPjZYuTkVMoMrPgcwNWwIsiy4srnAyMTM0nG5raO7t65qoWl6SYEeCfna0p4fFHpKcqgFeIgAB7mAB6AAoTAApADKAHkAHIASgAJH0klAlmROtJUrBEPsSsVjhV9tULvVJiIVJQOAAjJDY5xcHqUH6jVAJfY4IRMdZ5HEFL7JF5xaSJHFQMjbXZsqoeAAKKoAogAlAD66QAggj1SKkoddBTdEC9OdapdzERSAAZSgAa0C4qiMSlfNlUARG2MKua8p2zT2ovJ7stOGtdSuUHEsC47S4TIB7pwkuWMpxkD9aXwgb8wUV+1NCjJhXkZJKQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)
