### ISSUE TITLE
Enhancement: [prefer-readonly-parameter-types] ignore rest parameters

### ISSUE THREAD

**Issue by davidaurelio** [typescript-eslint/typescript-eslint#6127]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/prefer-readonly-parameter-types

### Description

It would be great if there was an option to make `prefer-readonly-parameter-types` ignore rest parameter arrays. This refers only to the type of the array, not the types of its members.

The array for a function accepting rest parameters is _allocated per call,_ and in consequence, it is irrelevant whether the callee modifies it. There won’t be any observable side effects outside of the function. 

Arguably, this should be the default behaviour, but an option to opt in would be fine.

### Fail

```typescript
// the option would make the rule more permissive. No new failures required.
```

### Pass

```typescript
function apples(
  a: number,
  b: Readonly<Record<string, number>>,
  ...rest: Array<string>
) {}

function bananas<Extra = undefined>(
  a: string,
  ...extra: Extra extends undefined ? [] : [Extra]
) {}
```

**Comment by Josh-Cena** [comment]
Should it flag this?

```ts
function apples(
  a: number,
  b: Readonly<Record<string, number>>,
  ...rest: ReadonlyArray<{ a: number }>
) { }
```

Right now, we require parameter types to be deeply readonly; your proposal seems to only allow the top-level array to be mutable?

**Comment by davidaurelio** [comment]
Yes, exactly. My intent is not to disable the rule recursively for rest arguments, just for the top level array. The rule should still ensure that array items are readonly.

I came across this with some conditional types and tuples used for rest params, where I had to add `readonly [...]` in multiple places, which decreased readability.

**Comment by bradzacher** [comment]
Personally I fundamentally disagree that:
1) the fact that the array is allocated per call should mean it doesn't need to be readonly.
2) that typing the array as readonly decreases readability.
3) skipping `readonly` just for rest parameters would make the rule easier to use.

> The array for a function accepting rest parameters is allocated per call, and in consequence, it is irrelevant whether the callee modifies it.

I disagree here - IMO this rule isn't just about accidental modifications to input values that have external side-effects - it's about preventing a whole class of errors and dead code related to mutating parameters.

Whilst, yes, it's completely safe and side-effect free to write code like this:
```ts
function foo(...args: string[]) {
  args.push('a');
}
```
However it's clearly incorrect code, and if the rest parameter were a readonly array we'd be able to tell very quickly that we had done something wrong!

Another example in the same class would be react functional components. A react functional component's "props" input object is a new object every time your component is rendered. Which means it's perfectly safe to mutate the object itself however you see fit. However it's really not good practice to do so and instead the object should be treated as readonly.
I'm sure other frameworks have similar examples.

To reiterate - just because an argument is provably safe to mutate doesn't mean you should be mutating it in your function and thus doesn't mean the type should be mutable.

**Comment by Josh-Cena** [comment]
@bradzacher One use case is default parameters.

```js
function foo(...args) {
  switch (args.length) {
    case 0: args.push("default 1");
    case 1: args.push("default 2");
    case 2: args.push("default 3");
  }
  return args.join(", ");
}
```

This is fairly contrived, but my point is that mutating the rest array allows you to avoid creating duplicate identifiers (`args` => `argsWithDefault`) while still using the array in a generic way (mapping over it, joining it, etc.), which is not possible with default parameters.

The motivation for the rule states:

> This contract makes it easier for a consumer to reason about if a function has side-effects.

IMO, that's a more convincing argument than "reporting dead code". I believe many people also turn the rule on just to avoid external side effects.

**Comment by bradzacher** [comment]
I think it both are valid arguments for the rule. By not mutating arguments at all you create predictability and safety for callers. Additionally by not mutating arguments you ensure that you don't write incorrect and possibly broken code by pushing onto the wrong array or assigning to the wrong object.

---

The reasoning provided FOR this change thus far is:
1) it's not a side-effect because it's not a user-generated array
2) adding `readonly` to the rest arg decreases readability (I don't personally understand or agree with this argument)

IMO there's not a compelling enough reason here yet to justify the maintenance burden of an option to allow this.

**Comment by JoshuaKGoldberg** [comment]
Closing as we don't believe there's much need for this very particular option. You can always fork / make your own version of the rule and publish it as a standalone ESLint config. Thanks everyone!
