### ISSUE TITLE
Bug: [no-use-before-define] Doesn't check variable inside function

### ISSUE THREAD

**Issue by KelvinOm** [typescript-eslint/typescript-eslint#6135]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/docs/linting/troubleshooting) and my problem is not listed.

### Playground Link
https://typescript-eslint.io/play/#ts=4.9.3&sourceType=script&code=DYUwLgBATiDmCWBnMIoQLwQBQGMCGwwARnjgNYCUGAfBAN4BQEE+hJ5WFT04ArlADsIAIkQB7ALYgIANwK8QwgNwMAvgwahIvAYl5FEOKPCLTMWeABMq6Wo2Y4xusaAB0wMbAvW1GrRCsMHgRkVCxOGnpuAHpoiABJCFNgeBAZaTAAC1RpCV5kJOk8CFQoMShuHT0DIxMQbwoVVUagA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaWZRQgI0QDN9oyATagS10XTAG1xsdFppakADTceWHtkhVYuAMYAXJvlyoM8uIhETJs+AENkpVWHWxNoiZABue6Ez3kkx0+e0498ePgDuAOT0Atoj0AKIAHgAOtPLGVB6kFhAAvhYAulqSAALyAJ4RKLJ2EfKEKPAs8gD0BMSkFNS0DMys7JB8AtDC3ClJQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
https://github.com/KelvinOm/no-use-before-define
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  "rules": {
    "no-use-before-define": [
      "error",
      {
        "functions": true,
        "classes": true,
        "variables": true,
        "allowNamedExports": false
      }
    ],
    "@typescript-eslint/no-use-before-define": "error"
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

When checking, an error will be displayed

### Actual Result

There is no error

### Additional Info

At work in the codebase, I found a problem after changing target in tsconfig.json from es5 to es6. The project began to fall in runtime with error "Cannot access "var" before initialization"

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.45.0` |
| `@typescript-eslint/parser`            | `5.45.0` |
| `TypeScript`                           | `4.9.3` |
| `ESLint`                               | `8.28.0` |
| `node`                                 | `16.15.1` |

**Comment by bradzacher** [comment]
Could you please provide more information? What line do you expect an error on?

**Comment by KelvinOm** [comment]
let someVar = someFunc(() => {
  // I believe there must be a error
  anotherFunc(id);
});

**Comment by Josh-Cena** [comment]
@KelvinOm This rule is an extension rule, which means it only takes care of TS-exclusive features, and defers the rest to ESLint's implementation. And indeed, ESLint doesn't [throw an error](https://eslint.org/play/#eyJ0ZXh0IjoibGV0IHNvbWVWYXIgPSBzb21lRnVuYygoKSA9PiB7XG4gIC8vIEkgYmVsaWV2ZSB0aGVyZSBtdXN0IGJlIGEgZXJyb3JcbiAgYW5vdGhlckZ1bmMoc29tZVZhcik7XG59KTtcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tdXNlLWJlZm9yZS1kZWZpbmUiOlsiZXJyb3IiLHsiZnVuY3Rpb25zIjp0cnVlLCJjbGFzc2VzIjp0cnVlLCJ2YXJpYWJsZXMiOnRydWUsImFsbG93TmFtZWRFeHBvcnRzIjpmYWxzZX1dfSwiZW52Ijp7ImJyb3dzZXIiOnRydWV9fX0=) for this either.

Callbacks are always hard to analyze: for example, [type narrowing doesn't across callback boundaries](https://github.com/microsoft/issues/9998), because TS has to account for the case where the callback is asynchronous, in which case the variable it closes over may have changed. It's the same case here: if `someFunc === setTimeout`, your code would work. TS needs to be sound, while we need to allow the valid cases without false positives.

**Comment by bradzacher** [comment]
Yup - this is working as intended. ESLint cannot know exactly how your callback is called because it can't interrogate your `register` function or interrogate it's control-flow.

So the rule has to work on assumptions. Either you can assume the callback is called immediately, or you can assume the callback is called in the future. It's impossible to be right 100% of the time.

The rule assumes that the callback is called later as its a common pattern and it is much easier to implement in the rule logic.
TS makes exactly the same assumption and checks the code in the same way as Josh mentioned.

So overall this is working as intended. 

As Josh mentioned this is an extension rule and we don't seek to break from the base rules core logic. So if you would like to see this improved then please file an issue with eslint core.

**Comment by KelvinOm** [comment]
@Josh-Cena @bradzacher thank you guys. I get what you're talking about. Didn't think about behavior like `setTimeout`.
