### ISSUE TITLE
Repo: Can't develop because of yarn1

### ISSUE THREAD

**Issue by liuxingbaoyu** [typescript-eslint/typescript-eslint#6150]
### Suggestion

There are some issues with yarn1 that will never be fixed, such as not being able to run any commands with yarn1 when there are unicode characters in the windows username.
This pretty much means that these users (like me) can't build, debug and develop at all.

Migrating to yarn3 seems like a good approach, it is actively maintained.

**Comment by JoshuaKGoldberg** [comment]
Hmm, that doesn't sound great.

> some issues with yarn1

I need more specificity please 😄. What are the exact list of issues that are blocking you from developing on us? For example...

> not being able to run any commands with yarn1 when there are unicode characters in the windows username

Issue link please?

Btw, I renamed this issue because we might not necessarily go to yarn3. I've been using pnpm successfully in other projects. More investigation required.

**Comment by Josh-Cena** [comment]
I strongly recommend Yarn3. It has a better CLI interface. It supports plugins. By switching to the node-modules mode, you basically get everything you miss from the old days (easy debugging by hacking node_modules; hoist-everything, which Docusaurus actually relies on because it shares contexts between packages; no cross-platform issues you get with symlinks). While the performance gains of pnpm is not that significant because you won't run install every hour.

**Comment by liuxingbaoyu** [comment]
![image](https://user-images.githubusercontent.com/30521560/205328475-ac7c3831-ea5d-4973-8de7-21112a960a79.png)
https://github.com/yarnpkg/yarn/issues/7939
I opened a pr, but unfortunately it was not merged.

**Comment by JoshuaKGoldberg** [comment]
> strongly recommend Yarn3

Cool, those points sound good to me 😄 and I'm convinced. Since this is a pretty farreaching change also want to hear from @bradzacher @JamesHenry - especially on how it interacts with Nx, if at all.

**Comment by JamesHenry** [comment]
It's less Nx and more Lerna that comes to mind for this, but for that reason I think it's great! It would give me a real world repo to dogfood on. We focused a lot on pnpm recently on the lerna side and it is in a good state now, but yarn 2+ hasn't yet been in focus. So maybe I'll take this one and verify that everything looks good across Nx and Lerna?

**Comment by bradzacher** [comment]
As long as we keep the `node_modules` folder to patch locally and poke around in I'm good with upgrading.
We have some patches we need to apply to TS types for our repo to work.

I also tend spend a lot of time looking at our dependencies' code whilst working (tsutils and eslint in particular) so that is something important to me to be able to keep doing.

Plus I personally never really liked the external linking thing considering they have to hack and patch packages on install (like TS) to make that work.

**Comment by JamesHenry** [comment]
Thanks @bradzacher - that's a great call out, we will not use any of the PnP features etc, the usage needs to match how we do things today.

If that's not adequately doable in yarn 3, then probably npm v9 workspaces make the most sense, if yarn 1 is proving a barrier to contributions?

**Comment by Josh-Cena** [comment]
> If that's not adequately doable in yarn 3

Yarn3 + node-modules mode will behave almost exactly like today.

**Comment by liuxingbaoyu** [comment]
> If that's not adequately doable in yarn 3


This is possible. Except that the commands are different from yarn1, other changes are not significant. (babel is doing this)
