### ISSUE TITLE
Add docs on using type information in rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#63]
Spinning off of https://github.com/bradzacher/eslint-plugin-typescript/issues/276 and as a backing documentation request to help with #62: would you mind writing some docs on how to use TypeScript-specific features _(the type checker? anything else?)_ on top of ESLint?

**Comment by j-f1** [comment]
Here’s what I had to do: https://github.com/desktop/desktop/pull/6912/commits/e1f7b9b374039113afc72d2238f514bb0813f5fc (check the [`eslint-rules/types`](https://github.com/desktop/desktop/tree/e1f7b9b374039113afc72d2238f514bb0813f5fc/eslint-rules/types) directory)

**Comment by bradzacher** [comment]
@j-f1 - couldn't you import some of that from `typescript-estree`?

I.e. your file `eslint-rules/types/ast-node-types.ts` is [exported from the package](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/parser.ts#L416)

Also you're probably thinking of this issue which is about converting the plugin code to TS #40
This issue is about documenting how to write rules which use type information

**Comment by Rodion8888** [comment]
workspaceFolder}/node_modules/.bin
