### ISSUE TITLE
Rule proposal: indexed object types with infinite keyspaces must express undefined as a possible value type

### ISSUE THREAD

**Issue by DuncanWalter** [typescript-eslint/typescript-eslint#6302]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Enforces that indexed object types do not have (some) pseudo-infinite key spaces while also not listing undefined as a possible value type.

The type `Record<string, number>` can only be expressed at runtime using weird/uncommon/freaky language features like proxies. In 99 out of 100 cases, the author would prefer to express `Record<string, number | undefined>` so they can't accidentally cause runtime errors where an expected number was undefined at runtime. There isn't a way to express that indexed properties are optional in TypeScript from what I can tell, so adding `| undefined` is the best fix we can recommend regardless of whether strict property settings are on.

The type `Record<'hi'|'bye', number>` is very different- TS catches most patterns that make the `Record<string, number>` case risky. Indexed object types with finite key spaces should be ignored by the rule.

I think it's worth leaving this rule as a non-type-aware rule (or at least having a non-type-aware version), even though technically in some cases it would benefit from having type info. Cases where the value type is a reference to a union type that already incudes `undefined` would lead to some funny looking but ultimately harmless extra `| undefined` in the code base. Key types that are infinite without being direct references to string or number are uncommon (in part because TS bans most cases like that). 

### Fail Cases

```typescript
const foo: Record<string, number> = {}
const bar: { [key: string]: number } = {}
const foo: Record<number, number> = {}
const bar: { [key: number]: number } = {}
```

### Pass Cases

```typescript
const baz: Record<'hi' | 'bye', number> = {hi: 1, bye: 1}

const foo: Record<string, number|undefined> = {}
const bar: { [key: string]: number|undefined } = {}
const foo: Record<number, number|undefined> = {}
const bar: { [key: number]: number|undefined } = {}
```

### Additional Info

We (meaning my coworkers and I, not maintainers of ts-eslint) could conceivably contribute a PR with the rule if the idea is well received. We're thinking about implementing this rule for ourselves anyway. cc @aem

**Comment by DuncanWalter** [comment]
Calling `Record<string, number | undefined>` dangerous doesn't feel compelling to me. When using that type, checks for undefined would need to be performed everywhere downstream, so the ability to add undefined properties isn't risky- It just goes against crufty JS idioms.

I do hear you on the `Object.values` and `Object.entries` case- we see that misuse a lot. However, I've taken to pinning blame on those functions + the associated JS idioms rather than anything TS related. There is no way to use those methods safely in TypeScript because there is never a guarantee that a value of type `{ prop: string }` doesn't include arbitrary other properties (not to mention that some typed properties could come from up the prototype chain). Advising engineers to use native JS Maps instead of objects to model hashmaps in net new code is a more complete solution, and no change to TypeScript itself will ever make indexed objects better than Maps for that use case.

I gather that you're interested in avoiding having the rule advise adding checks for undefined where it isn't strictly intended to be necessary, but there is some nuance here. Whether those checks are intended to be necessary and whether those checks are necessary in order to have coherent code aren't necessarily the same thing. Allowing indexed objects to collapse into a simpler form that works in more cases isn't necessarily a downside, even if that means disagreeing with some patterns found in idiomatic JavaScript.

On `noUncheckedIndexAccess`, while that setting is cool and appreciated in new projects, it's functionally impossible to turn on in codebases that existed before that setting was added. It was added in 4.1. so that means basically everywhere. Even newer code can't enable that setting assuming it imports any TypeScript source from older libraries. Pragmatically I don't see how `noUncheckedIndexAccess` can address the community wide problem posed by unsafe index checks today. It feels like we're much better positioned to address these potential bugs from the eslint angle today rather than from the compiler itself. Even basic things like array indexed access break when enabling `noUncheckedIndexAccess` in older code.

**Comment by bradzacher** [comment]
> checks for undefined would need to be performed everywhere downstream

[Unless someone does an `as` assertion to remove the `undefined` from the value.](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEAuGAlApqATgEwDzRYCWYA5gDQyEmkwA+MArmDunCejgHwwC8MAbwBQMGIgAOEFM1bswnckIC+QoaEiwARgEMsfeIhjaIaTCFx4A5BIiXK1MlwDcqnVgB0N9wBt0ZKAAWMAD0wTBYzFBEALboMMBYxgFAA), which is valid TS.



> There is no way to use those methods safely in TypeScript

Problems with the inexact structural typing model aside - for the vast majority of code they are completely safe to use. Unsafe usecases are very much the exception, and isn't actually a real problem in any TS code that I've seen.

> it's functionally impossible to turn on in codebases that existed before that setting was added

Why? Turn it on, add `@ts-expect-error` comments to suppress errors and you're done. Engineers are then forced to write safe code, and can address the tech debt over time.

> It feels like we're much better positioned to address these potential bugs from the eslint angle today rather than from the compiler itself.

Strongly disagree for the reason I've stated. You don't want write time undefined, only read time undefined. There's no way for userland types to do this, thus there's no way for a lint rule to properly solve this problem.

The TS compiler OTOH can enforce consistent, non undefined writes whilst ensuring reads are safe. It can also properly track values using control flow.

One additional example of a case that unioning undefined is unsafe (whereas its safe with the flag):

```ts
declare const foo: Record<string, string | undefined>;

function mutateThing(thing: Record<string, string | undefined>) {
  thing.bar = undefined;
}

if (foo.bar) {
  mutateThing(foo);
  foo.bar.length; // runtime crash
}
```

Side-effectful functions are obviously not good, but people do use them, and TS can't track their effects. By unioning in `undefined` it creates a other vector for unsafety that doesn't exist with the flag.

> Even basic things like array indexed access break

There's a lot of unsafety in array index access that can occur and the flag is just exposing that to you.

For example:
```ts
const x: Array<number> = [];
x[0] = 1;
x[5] = 5;

// x === [1, undefined, undefined, undefined, 5]

if (x.length > 0) {
  x[1].toString(); // runtime crash
}
```

If instead the check was `if (x[1])`, then not only would the code not error with `noUncheckedIndexAccess`, it would also be truly runtime safe!

This may seem like a non-issue in real code, but it does come up more than you'd think thanks to:
- sparse arrays: `[1 , , , , 5]`
- the array constructor: `Array(5)`
- bad array deletion `delete arr[3]`

It's still a rarer case for sure, but it is a real issue highlighted by the flag.

---

If this is a code style you'd like to use in your projects - feel free! You can create a local lint rule using our tooling and enforce this style in your project (many companies do this!).

However this is not a lint rule we will be looking to implement in this project. Namely because:
- we do not want to lint rules that duplicate compiler options
- we do not want lint rules that enforce what we consider to be a bad practice in the general case (the reason that we consider this to be bad practice I've outline above)

Thanks for your submission!
