### ISSUE TITLE
Repo: Scheduled workflow "Lock threads" also runs on forks, causing an error

### ISSUE THREAD

**Issue by marekdedic** [typescript-eslint/typescript-eslint#6333]
### Suggestion

Hi,
the scheduled GitHub actions workflow "Lock threads" also runs on forks where it fails due to rate limiting, producing noise in notifications for those of use with a fork of the repo.

I suggest adding a check to the workflow file - PR incoming.

**Comment by bradzacher** [comment]
Generally when it comes to actions you have the option of specifically turning them off for your fork.

I'd suggest doing that because you don't really have a need for any actions to run at all in your fork - any per commit actions aren't needed, nor are the scheduled actions, or the PR actions. Any relevant actions will be run by GH when you raise a PR.

I don't think adding a guard for an action is the thing you're *supposed* to do.

**Comment by marekdedic** [comment]
Hi,
thanks for pointing out the option of turning off actions altogether on a fork - I didn't realize that would actually be a viable solution as actions probably aren't needed on the fork indeed.

As for whether this is the thing you're *supposed* to do - that's probably really subjective :( I think adding a "gate" to the workflow is painless, doesn't negatively impact typescript-eslint and makes the *default* behaviour for forks that they just work... Also, it is what the [TypeScript repo does](https://github.com/microsoft/TypeScript/blob/ef58695fbcdac632f035a971d99df739f937916d/.github/workflows/update-package-lock.yaml#L13), if that's of any relevance - that's where I got the idea ;)

**Comment by JoshuaKGoldberg** [comment]
🤔 sometimes we do intentionally make a fork to test things out though. Hasn't happened in a little while, but it's useful to be able to play with the workflows.

**Comment by JoshuaKGoldberg** [comment]
I'll close this out for now to keep our queue small. But thanks for sending, and please do let us know if we missed a good reason to reconsider! ❤️
