### ISSUE TITLE
Public site: docusaurus build cache isn't getting overridden between deploys

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6350]
### Suggestion

Continuing #6081: on typescript-eslint.io right now, the _Get Started_ buttons are the wrong size:

<table>
<thead>
<tr>
<th>Local</th>
<th>Production</th>
</tr>
<tbody>
<tr>
<td>
<img width="472" alt="Screenshot of large font size and padding Getting Started button" src="https://user-images.githubusercontent.com/3335181/213286562-651a19ea-1ce9-4b79-b09d-29416aae61c2.png" />
</td>
<td>
<img width="472" alt="Screenshot of small font size and padding Getting Started button" src="https://user-images.githubusercontent.com/3335181/213286617-eac8c64b-f39f-4f69-bd1e-ca5d2def615b.png">
</td>
</tr>
</tbody>
</table>

Specifically, the server-rendered HTML has the right HTML+CSS, but once the main JS chunk loads in, the button becomes small again. I believe it's from React hydrating with old component JS data.

I poked at things locally (thanks very much again to @AgentEnder for the help!):
* It happens on local dev, not just Netlify deploys
* It happens even if we _Clear Cache and Deploy Site_ on Netlify
* It happens even if we upgrade Nx and Lerna
* It goes away _locally_ if you `rm -rf packages/website/build`

...so I believe the conclusion is that there's something wrong with how `build/` outputs are not getting cleaned between Docusaurus rebuilds. 

@Josh-Cena - do you have any insights here?

**Comment by Josh-Cena** [comment]
How can I reproduce it? Do I need to switch between two commits?

**Comment by JoshuaKGoldberg** [comment]
It happens for me on `main`. The linked issue has a video

**Comment by Josh-Cena** [comment]
> * It goes away _locally_ if you `rm -rf packages/website/build`

Does the `packages/website/build` before come from an older commit? Or do I just need to build and build again?

**Comment by Josh-Cena** [comment]
This is not a cache problem (because I started fresh), but a hydration issue. Here's the HTML before hydration (with JS disabled):

<img width="886" alt="image" src="https://user-images.githubusercontent.com/55398995/213365637-b7dae444-ed08-4ff2-b69f-6e67ea81196b.png">

Here's what's after:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/55398995/213365670-b91873ae-83ec-47ce-bcac-ecd836be962b.png">

The `className`s are applied to the wrong element. This is a quintessential issue of markup mismatch between SSR and first CSR. In this case, the culprit is that the HTML is wrong—note how there's an empty `<p>` tag! This prompts me to think it's caused by the minifier trying to parse invalid HTML. So I went back and noticed a common pitfall: we are rendering a `<div>` inside a `<p>`, which is invalid because `<p>` only accepts phrasing content. Because the end tag of `<p>` can be omitted, a conforming HTML parser can interpret the `<div>` tag as the implicit end of the `<p>` tag, which is what the minifier is doing, thus causing the issue. A similar issue of invalid HTML was reported here: https://github.com/facebook/docusaurus/issues/8235

You can see for your self with this very simple repro:

```js
const $ = require("react").createElement;
const { minify } = require("html-webpack-plugin/node_modules/html-minifier-terser");

function Home() {
  return $("p", null, $("div", null));
}

const html = require("react-dom/server").renderToString($(Home, null));
console.log("Raw render:");
console.log(html);
console.log("Minified:");
minify(html).then(console.log);
```

```
Raw render:
<p><div></div></p>
Minified:
<p></p><div></div><p></p>
```

The solution is to fix the markup because we should write conformant HTML.

**Comment by bradzacher** [comment]
I'm surprised there isn't a lint rule in `eslint-plugin-react` for this.

I found this 3rd party plugin:
https://github.com/MananTank/eslint-plugin-validate-jsx-nesting

**Comment by Josh-Cena** [comment]
This is quite hard to validate, particularly in this case where it's `<p>{description}</p>` and `description` is an external variable containing a `<div>`... It needs some sort of reference tracing.

**Comment by bradzacher** [comment]
I'm also pretty sure react does log a warning here when it does the rendering. It contains utils that validate the DOM structure iirc.

**Comment by JoshuaKGoldberg** [comment]
Yeah we should add an end-to-end test to make sure no React warnings are logged. #6354

Thanks!
