### ISSUE TITLE
Enhancement: [await-thenable] <strict mode that requires all types in a union to be thenable>

### ISSUE THREAD

**Issue by issacgerges** [typescript-eslint/typescript-eslint#6381]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/await-thenable/

### Description

At the moment (somewhat unclearly) `await-thenable` only requires any member of a union type to support `then`. This appears to be [by-design](https://github.com/ajafff/tsutils/blob/master/util/type.ts#L164-L165) in `tsutils` as well as [tested behavior](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/tests/rules/await-thenable.test.ts#L72-L81) in this plugin. I think there might be some ambiguity about considering a `thenable` if it _may_ have `then` or is guaranteed to.

I think the original intention of this rule is to prevent against accidentally `await`ing functions instead of their result. The way the rule works today will likely catch that, but I think it could also be used to prevent runtime errors from transforms like `async-to-generator`, which, in [certain configurations](https://babeljs.io/docs/en/babel-plugin-transform-async-to-generator#bluebird-non-promise-runtime-error) can cause runtime errors if any non-promise value is awaited. I'd propose a `strict` (or better named :P ) option that requires that every type in the union to satisfy being `then`-able.

### Fail

```typescript
// https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/tests/rules/await-thenable.test.ts#L72-L81 would fail

async function test() {
  await (Math.random() > 0.5 ? numberPromise : 0);
  await (Math.random() > 0.5 ? foo : 0);
  await (Math.random() > 0.5 ? bar : 0);

  const intersectionPromise: Promise<number> & number;
  await intersectionPromise;
}
```

### Pass

```typescript
async function test() {
  function returnsUnionedPromise() {
    return (Math.random() > 0.5 ? Promise.resolve() : Promise.resolve(10));
  }
  await returnsUnionedPromise();
}
```

**Comment by bradzacher** [comment]
As per the JS spec, using `await` on a non-promise value is completely valid and is a no-op.

The reason this rule exists is to help catch cases where you use await unnecessarily. There are cases where you may forget to call a function and await a function reference, or times that you remove a promise due to refactoring. In such cases the rule can help you find this case and either correct the expression or remove the unnecessary await.

The reason that the rule specifically allows unions if one type is a promise is because it's reasonably common to have code like this:

```ts
function test(cb: () => Promise<boolean> | boolean) {
  await cb();
}
```

I.e. Allow a consumer to pass a promise if they like.

Forcing the code to do an `instanceof` check to narrow out and only `await` if the value is a promise is really cumbersome, and not something I personally see done because it's not necessary.

Using a non-standard transform that makes it an error is going against the defined behaviour of JS, and not a motivation that we are specifically going to support.

I don't think this is something that is going to be useful to the broader TS community. I say this because the `await-thenable` rule is one of the oldest type-aware rules, going back all the way to 2017, and AFAIK this is the first request for such a feature.

For the above reasons, this is not an enhancement that we shall be accepting into this project. Thanks for taking the time to file it!

**Comment by issacgerges** [comment]
Sounds good, totally understand if there's no interest!

One clarification:

> Forcing the code to do an instanceof check to narrow out and only await if the value is a promise is really cumbersome, and not something I personally see done because it's not necessary.

I'm not asking for that, nor is it being done. AFAIK type system is already aware of of the union type and instead of asking "do **any** satisfy a `then` property that access a `callback`" I would just ask do **all**. 

Ex:

```
function isStrictThenableType(checker, node, type = checker.getTypeAtLocation(node)) {
	const arePartsThenable = unionTypeParts(checker.getApparentType(type)).map((ty) => {
		const then = ty.getProperty('then');
		if (then === undefined) return false;
		const thenType = checker.getTypeOfSymbolAtLocation(then, node);
		for (const t of unionTypeParts(thenType)) {
			for (const signature of t.getCallSignatures()) {
				if (signature.parameters.length !== 0 && isCallback(checker, signature.parameters[0], node)) return true;
			}
		}
		return false;
	});
	return arePartsThenable.every((truthy) => truthy);
}
```

> The reason this rule exists is to help catch cases where you use await unnecessarily. There are cases where you may forget to call a function and await a function reference, or times that you remove a promise due to refactoring. In such cases the rule can help you find this case and either correct the expression or remove the unnecessary await.
> 
> The reason that the rule specifically allows unions if one type is a promise is because it's reasonably common to have code like this:
> 
> ```
> function test(cb: () => Promise<boolean> | boolean) {
>   await cb();
> }
> ```
> 
> I.e. Allow a consumer to pass a promise if they like.

Very clarifying! This level of the detail in the docs would have probably prevented me from opening this ticket

Thanks for taking the time to maintain this project and have a great day.
