### ISSUE TITLE
Bug: [key-spacing] Crashes on Node 14

### ISSUE THREAD

**Issue by kanongil** [typescript-eslint/typescript-eslint#6396]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

This is a ~~critical~~ issue with the 5.50.0 release, which is _not entirely compatible_ with node v14.x.

```TypeError: node.parameters.at is not a function```

`Array.at()` usage has been introduced here:
https://github.com/typescript-eslint/typescript-eslint/blob/99c091e0e3cf38a28aa5e1d1d2b03b602d51aa0a/packages/eslint-plugin/src/rules/key-spacing.ts#L105
This does not exist on node v14, and no polyfill has been provided in the released package.

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.50.0` |
| `ESlint`                                 | `8.33.0` |
| `node`                                 | `14.21.2` |

**Comment by bradzacher** [comment]
> critical issue

The usage is in a brand new, not-recommended rule, so I wouldn't deem this as critical.
It is certainly a bug that needs to be fixed though!

---

How did this slip through?

https://github.com/typescript-eslint/typescript-eslint/blob/99c091e0e3cf38a28aa5e1d1d2b03b602d51aa0a/.github/workflows/ci.yml#L144-L147
The CI is mis-configured - above you can see that we pass `env.PRIMARY_NODE_VERSION` instead of `matrix.node-version`.

So we're not actually testing against Node14, just Node18 - big oof.

---

Separately it also looks like [the implementing PR added a duplicate key to our package.json](https://github.com/typescript-eslint/typescript-eslint/pull/6211/files#r1091926102) - oops!

**Comment by kanongil** [comment]
Thanks for looking into it. I didn't do anything to enable the new rule. My workflow just breaks with the new release.

**Comment by kanongil** [comment]
Ah, I'm encountering it because I have an computed eslint config that updates plain rules to any matching `@typescript-eslint` rule.

**Comment by JoshuaKGoldberg** [comment]
@coyotte508 since you authored the rule, do you want to make this fix real quick?

We should have indicated to you that we can't use `.at` yet in this repo, sorry for the noise. 🙂
