### ISSUE TITLE
Bug: no-misused-promises does not care about functions with multiple return types

### ISSUE THREAD

**Issue by kevinMEH** [typescript-eslint/typescript-eslint#6421]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [x] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=GYVwdgxgLglg9mABAJwIZgCZwLYDFzTxgAUAlAFyIBGccANgKbqIA+iACsjjAM4MA8NekzAA+RAG8AUIlmIYwYgFlUUABYA6NJhxlE-RAAYNAVlIoGUEMiQr1W9Fmx7xxkwG4ZchnT4WrNhxc2LwMWgw89ABuDMqqmtpOLkampJ4AvlJSoJCwCIjgDAAeAA4M0AwYAEIMaqhR8Mh60nLyiok4+LlEZOYSiAD0A4gAInARiGBwUBYlcMgzzAzIXMgaXq2yEAiRjBp0cADmxABEABI+BydpG4iZ6UA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa1i0Dr0GoMAbXDYciaOOiQANPIVYF2SGQAWiMgGtkAYQ5MhlfJUsBDeNLD44iDTt0GjpgGodKIQAlRHxYaCZ0MAAzR0FNbABfBIBdeWTEoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

I have a function that returns either a boolean or a Promise<boolean>.
When I use that function as a condition in an if statement, ESLint does not report a problem asking me to preface the function call with an await:

Perhaps this is intended behavior, but I think that it shouldn't be.

I'm going to assume that this is intended behavior:
If a regular boolean is returned, everything works as expected
If a promise boolean is returned, it makes the conditional always true, producing unexpected behavior

If this is not intended behavior:
If a regular boolean is returned, the evaluation of the conditional gets deferred to the next tick, slowing down slightly but nonetheless producing expected behavior
If a promise boolean is returned, it waits for the promise, producing correct behavior

To fix: Check if the set of the function's return type contains a promise

```typescript
function randomFunction(): boolean | Promise<boolean> {
    if(Math.random() < 0.5) return Math.random() > 0.5;
    else return Promise.resolve(Math.random() > 0.5);
}

function unexpectedBehavior() {
    if(randomFunction()) { // Does not report an error.
        console.log("Hello");
    }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
        "@typescript-eslint/no-misused-promises": [
            "error",
            {
                "checksConditionals": true,
                "checksVoidReturn": false
            }
        ],
  },
};
```

### Expected Result

`if(randomFunction())` should raise an error, as randomFunction() will possibly return a promise that is not awaited.

### Actual Result

No error.

**Comment by bradzacher** [comment]
This is intentional because it's simply not possible for a rule to understand the context in which your value is intended to be used.

Some codebases may define `boolean | Promise<boolean>` with the intent to use the two values separately. Other codebases may intend to mix them together.
There may even be places in a codebase where you want one behaviour and other places where you want the other behaviour.

For example, imagine code like this:
```ts
declare const foo: Promise<unknown> | null;

if (foo) {
  foo.catch(handleError);
}
```

In this code it's completely correct to "misuse" the promise in a logical because it narrows out the `null`. All non-object primitives have a falsey value, so it could conceivably be okay to do a logical check on the value instead of `await`ing it.

There just isn't a 100% right answer here, and an option would only be right half the time.

---

As an aside - personally I believe you should mark functions that return promises as `async` always and should completely avoid this sort of behaviour.

**Comment by JoshuaKGoldberg** [comment]
Dup of #5767?
