### ISSUE TITLE
Bug: [no-confusing-void-expression ] <The rule checks return values of target functions without consider generic types>

### ISSUE THREAD

**Issue by LvChengbin** [typescript-eslint/typescript-eslint#6422]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeyAvgFCiSyIoDCuIECWuRpF408SytcANvwBGiANZtyZACZN+cKChgBXEMxwhkCXDGABzADwAlZAF5kcEAE8AfAAoAlAC5khgNxlps+YpVrWWkEY-EFtNAWExAH5nPkERBHEnZAA3bGApdxkEOQVkZVUWDQCgwtDsTHU8aLQK3AIk+kCmQvcyALwwTW1TLqbg2wCdXQd7d3bOwYAmHuLm9VDBvX0MQrw7e2RRoA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1rI6YDNYyZgHNaANw6UAJvQAexaCiG9IYDJETRoHaJHBgAviANA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA

### Repro Code

```typescript
interface Options { }
interface Connection { }
interface Callback { }

declare function config<R = any>(): R;

declare function connection( callback?: Callback ): void;
declare function connection( options?: Options ): Connection;

const conf = connection(config());
const conf2 = connection( config<Options>() );
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-confusing-void-expression" : "error"
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

The code above should not emit any exception cuz return value of `config<Options>()` matches the type `Options`.

### Actual Result

Getting error message `Placing a void expression inside another expression is forbidden. Move it to its own statement instead. 11:15 - 11:46`.

**Comment by bradzacher** [comment]
Your example code makes little sense because you have two overloads with the exact same parameter type.

TS does not create unique types for every interface - an interface is just an alias for an object type.

Because of this problem, TS selects the very first overload every single call - hence the retuen type is always `void`.
[You'll notice that if you flip the order of overloads in this case you'll get a different behaviour](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeyAvgFCiSyIoDCuIECWuRpF408SytcANvwBGiANZtyZACZN+cKChgBXEMxwhkCXDGABzADwAlZAF5kcEAE8AfAAoAlAC5khgNxlps+YpVrWWkEY-EFtsTHU8AH5nDBZ8J14GJjj3GQQ5BWRlVTjNJODbTQFhMWjeYpEEcQSAN2xgKXcyALwwPJAYU3aguNsAnV0He3cWtv6AJi6AnvU+7T19WIi7e2GyIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1rI6YDNYyZgHNaANw6UAJvQAexaCiG9IYDJETRoHaJHBgAviANA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA).

Have you got a correct example for your issue?

**Comment by JoshuaKGoldberg** [comment]
It's been ~2.4 months without a response, closing this issue. Please post back or file a new issue (following the template & including a correct example) if you want action to be taken. Thanks!
