### ISSUE TITLE
Configs: add a config that turns off all base ESLint rules that conflict with the TypeScript compiler

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#6449]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

## Why `eslint-config-prettier` is useful

[`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) is an example of an extremely popular config that ONLY turns off core ESLint rules that conflict with Prettier. Configs like this are very useful, as they are intended to be put at the end of your `extends` chain.

For example:

```js
module.exports = {
  extends: [
    "airbnb-base",
    "airbnb-typescript/base",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:@typescript-eslint/strict",
    "plugin:eslint-comments/recommended",
    "plugin:n/recommended",

    // See notes below!
    "prettier",
  ],
}
```

Once the ESLint parser has reached the "prettier" line, it has already turned on a bunch of rules from all of these parent configs. At this point, as an end-user, it is extremely difficult to know which exact rules are turned on and turned off. (Various rules are turned on AND turned off in the parent configs, making this a nightmare.)

The reason that we put "prettier" at the end is because it excuses us from knowing the details of what is turned on and what is turned off. We just stick it and the end, and all conflicting rules are unconditionally turned off. Nice!

## TypeScript config

In the same vein, this plugin should expose a config that ONLY turns base ESLint rules off that overlap with the TypeScript compiler. That way, people can put it at the end of their `extends` chain to ensure that no pointless rules are sneaking in.

We have the basis for such a config already: https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts#L2

It just needs to be abstracted a bit more; `eslint-recommended` should inherit from `eslint-typescript-conflicts` (name up for debate). Also, any conflicting rules that are not part of `eslint-recommended` should also be added.

**Comment by bradzacher** [comment]
What rules would you have the config turn off that aren't already in the `eslint-recommended` set?

**Comment by Zamiell** [comment]
I don't know yet. The comment in [this file](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts) reports that it contains every rule that conflicts with TypeScript that is also contained  within `eslint:recommended`. But presumably, there would exist more rules that also conflict that are not contained within `eslint:recommended`.

To be honest, I was planning on performing an audit on every single ESLint rule that exists, so I'll get back to you on that.

**Comment by Josh-Cena** [comment]
@Zamiell I'm doing quite the same thing for https://github.com/jc-verse/js-style-guide. Would be great to hear your results!

**Comment by bradzacher** [comment]
I think there is some value in this, but the difficulty is that this crosses plugin boundaries beyond just ESLint core and our project.
I think that if anything this should be a separate NPM package and repo in of itself so that it's not hampered by our major release cycle and can freely reference the entire ecosystem - in much the same way that `eslint-config-prettier` is its own repo.

More than happy to promote the config in this project - I just don't think it's something that we should own specifically.

The prettier config disables rules that conflict with prettier and will report on code that's formatted by prettier. It's a safe bet to disable all of these rules, even those that aren't recommended because they are formatting rules. They don't catch bugs or larger "stylistic" issues. It's not really an issue if you disable rules other configs turned on because you're not hiding any bug-catchers or anything.

In contrast this TS config is going to be difficult to get exactly right because you need to be sure that each rule disabled is completely covered by TS (coverage that could change from version-to-version of TS).
It's easy to make a mistake! For example we currently disable the [`valid-typeof`](https://eslint.org/docs/latest/rules/valid-typeof) rule, but it's not actually 1:1 covered by TS, so we'll be removing the disable in the next major (it's taken us so long to do this because major release cycles are long for us #3797).

There's also a real chance that you might turn off a rule that the user actually completely wants turned on - which is obviously not going to be good because you'll cause the user to lose potential error signal. There's a lot to think about with this.

Again - I think this would be a super valuable piece for the ecosystem!
I just don't think it should live within this project specifically.
