### ISSUE TITLE
Docs: Show default values and reason.

### ISSUE THREAD

**Issue by infacto** [typescript-eslint/typescript-eslint#6479]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

We could add default values of configuration for the rules. And if used, about the recommended config. Please see demo below.

The following brought me here. I knew the rule [no-inferrable-types](https://typescript-eslint.io/rules/no-inferrable-types/) and I was just wondering why it doesn't work on method parameters. In the docs I see `ignoreParameters` "when set to true, the following pattern is considered valid:" ... So I would expect the default value is false / undefined. But it doesn't seem so. The parameters are ignored. I checked the recommended config and see it's only enabled without details.

https://github.com/typescript-eslint/typescript-eslint/blob/725e7f509299c28b23ec40b3a52d7c493fe64e12/packages/eslint-plugin/src/configs/recommended.ts#L20

- Why is `ignoreParameters` default `true`?
- Could we add info about default values in docs?

### Affected URL(s)

https://typescript-eslint.io/rules/no-inferrable-types/

[Demo in eslint playground](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=MYGwhgzhAECyCeAVAphALtA3gWAFDWgHpDoAlZAWwHsA3ZaNAC3oCcBXEZALmgAE14AB1TAWAS0FoAtKhBiAdmkLyqUhQDNkLFmABGnKQOEQ8BYgyrQ2Eek1bJgVChWTyAJsjfQbaNAoDmEAB0ptCCbPpiwNAUSKhoABRo8Ty6VFScYPLQALzQ6mAgNgCUWKEEjvIQGchBIFT+SfHFANyhAL54nbhAA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2uCU0aANgJZLyYBO0AxgPYC2jyK0KkANPhJAA7EArgHNymAALwAnnyK0qpPvAC0RMhQD0NBs1btI+ALrdeVQcSJYwoAlEky5CpapLl4GpPWXkAZtCpUAIYARhbK0rIY2Hi2vADugVRIXDwENrG8pMKeNAAKiYEsiFRRYD6BxGjQqRAAvqmG+PW1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)

We could also transform this into another issue type like bug or improvement.

**Comment by bradzacher** [comment]
Every single rule doc page contains an auto-generated code block that describes all of the options in addition to showing the default values.

For example this is `no-inferrable-types`:
![image](https://user-images.githubusercontent.com/7462525/219347347-a4d7efc2-87d7-4b8b-8d68-d93322039690.png)

If you use the rule with the default config ([playground](https://typescript-eslint.io/play/#ts=4.9.3&sourceType=module&code=MYGwhgzhAECyCeAVAphALtA3gWAFDWgAcBXAIxAEthoBbJVNACjQYC5pSB7TkZMAO2gBeaADMwICMgCUWPAQLBO-CD2QA6EJwDmzBtIDc86AF88Z3EA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1uYDNFpoAQwBGSWkVKoMAbXDYcAd0HQmkORAC6cgL4htQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)) then it reports on the code as expected because the default (as above) is `ignoreParameters: false` meaning "do not ignore parameters".

---

I'm not quite sure what the ask is here the rule is working as you describe and the rule docs include the default option values (if they're set) - could you please explain what more are you looking for?

**Comment by infacto** [comment]
Thanks, I missed the default values code block. And big sorry, my fault or the fault of angular-eslint. They set it to true. -.-

https://github.com/angular-eslint/angular-eslint/blob/9ecf4acc786d8529c6110db8842303286df80103/packages/eslint-plugin/src/configs/recommended--extra.json#L33-L36

I promise to test with minimal project and suggestive include other libs to exclude next time. ^^ Sorry again... I was confused.
