### ISSUE TITLE
Rule proposal: prefer-public-readonly

### ISSUE THREAD

**Issue by yf-yang** [typescript-eslint/typescript-eslint#6562]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

In a class, readonly controls both internal access and external access, while getter/setter controls external access only. Therefore, a internal readonly property would have two coding styles:
``` typescript
class Foo {
  constructor(private readonly _bar: any) {}
  get bar() { return this._bar; }
}

class Foo {
  constructor(public readonly bar: any){}
}
```

For such cases, the latter one could be more straightforward, because this is exactly one declarations, not getter declaration + private field declaration. Moreover, some projects follow the previous style. 
Therefore, I propose a rule to clearly distinguish those two styles, users can choose which style to follow, and offer a fix if one violates it.

Some implementation considerations:
- to detect the previous style:
  - a field is marked as private/protected readonly
  - a getter method directly returns the field
  - (a field which is marked as private/protected without any write operation could be detected as well, but @typescript-eslint/prefer-readonly has already done that)
- to detect the latter style:
  - a field is marked as public readonly

### Fail Cases

```typescript
class Foo {
  constructor(private readonly _bar: any) {}
  get bar() { return this._bar; }
}

class Foo {
  protected readonly _bar: any
  constructor(bar: any) {
    this._bar = bar;
  }
  get bar() { return this._bar; }
  workWithBar() {
    const barValue = this._bar;
    baz(barValue);
  }
}
```

### Pass Cases

```typescript
class Foo {
  constructor(public readonly bar: any) {}
}

class Foo {
  public readonly bar: any
  constructor(bar: any) {
    this.bar = bar;
  }
  workWithBar() {
    const barValue = this.bar;
    baz(barValue);
  }
}
```

**Comment by yf-yang** [comment]
Additional requirement to detect the previous style:
- return type of the getter should be exactly the same the internal readonly field. (which means `bar` extends `_bar`, and by checking the return value of the getter `bar` is exactly the internal field `_bar`, `_bar` extends `bar` is implicitly guaranteed)

Additional Pass Case:
``` typescript
interface IBar{};
class Bar implements IBar {};
interface ExtendIBar extends IBar {};
class Foo {
  constructor(private readonly _bar: Bar, private readonly _extendBar: ExtendIBar) {}
  get bar(): IBar { return this._bar; }
  get baseOfExtendBar(): IBar { return this._extendBar; }
}
```

**Comment by bradzacher** [comment]
I don't think there's enough here to be a candidate in our general purpose plugin.

A `private` field can be seen as an internal part of the API, whereas a `public` field is part of the external API. This difference is important because you may want to strictly control the external contract.

Additionally there are cases where you are going to want to use a getter as an intermediary because they are truly readonly, as opposed to `readonly` which is type-system readonly.
`readonly` also provides really terrible guarantees in the type-system - TS actually ignores it in a lot of cases eg:
```ts
class Foo {
    readonly a = 1;
}

const foo1 = new Foo()
const foo2: { a: number } = foo1;
foo2.a = 2;
// oops - we just did a type-safe update to the value of a "readonly" property
```

TS also treats a getter in the same way, but the difference is the above code will provide no errors in types or at runtime and will silently cause you to mutate your "constant", whereas a getter will provide no type errors, but will crash at runtime.

```ts
class Bar {
    private readonly _a = 1;
    public get a() {
        return this._a;
    }
}

const bar1 = new Bar();
const bar2: { a: number } = bar1;
bar2.a = 2; // this will actually crash at runtime instead of silently working
// Uncaught TypeError: Cannot set property a of #<Bar> which has only a getter

// this isn't allowed in the type-system - so we can't accidentally mutate the private member
const bar3: { _a: number } = new Bar();
```
[playground](https://www.typescriptlang.org/play?ssl=9&ssc=1&pln=1&pc=1#code/MYGwhgzhAEBiD29oG8CwAoaXoCcCmYAJvAHYgCe0Y0AvNAIwDcGAvhhsKRAC7QBmierWgk8AdziIAFAEoOXXgPgAmAFwoq6kgFcAtgCM8OaC2FKmGJcoB01OsuboA9E+iIADjAC00MXmgAVto80IQAloRU0Nzk7nheEGB8-truhGDc-txI3AAW-gBuYCDa-vB8UQBE+ESkFJXQ7jjwcTgx7Ogc4FDQAEJgxmiY2E1hRZm4BMRklAD6dgyO2I3a+iBhwNAA5ni8YLIoGMvL+NzaOCTRuWEQ1vNL2GzoT-IkIfoDQnSiEv04so5OG9eB8cGoNGAtHpDMZTHRQRZ0KCbAsHNAXFcbr4wiAQFRgGdihRoMAcJBclReDhtCRuGFdP4wsCpm4KhAcXhacSxPAcABrJlbDAYgCqJGAYG0W1yvAAKrE8ABRHDNHDqADCYBIJHgvAgu0azVaMSi5WgAGIADx-AB8vmuwApuUgbhmUR23EyOAwQA)

For the above reasons - I'm going to reject this proposal for this project.
Thanks for the writeup!
