### ISSUE TITLE
Enhancement: [consistent-indexed-object-style] forbidden from using the "in" keyword in index signature if `Record` is preferred

### ISSUE THREAD

**Issue by yeung108** [typescript-eslint/typescript-eslint#6598]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/consistent-indexed-object-style/

### Description

When `"record"` option is chosen in `@typescript-eslint/consistent-indexed-object-style`, we should also be forbidden from using the `"in"` keyword in index signature. It's particularly useful for literal types.

Here's the justification:
- we should prefer `Record` versus `Index Signature` whenever we want to use literal types, as index signature accepts only `string`, `number` or `symbol` as key type. 
- And when `Record` is preferred, it also brings an advantage of ensuring no missing property in literal types -> which further ensures type safety, and avoid getting unexpected `undefined` case from non-existing key.
- However, such advantage will not be kept since the current `@typescript-eslint/consistent-indexed-object-style` rule allows people using `{ [key in Option] : string}` 

### Fail

```typescript
/* eslint @typescript-eslint/consistent-indexed-object-style: ["error", "record"] */

type Option = "red" | "yellow";

const optionToString: { [key in Option]: string} = {
   "red": "this is red" // won't be warned that "yellow" is missing
}
```

### Pass

```typescript
/* eslint @typescript-eslint/consistent-indexed-object-style: ["error", "record"] */

type Option = "red" | "yellow";

// if we use Record, it will prompt error if any property is missing; 
// E.g. it should say "Property 'yellow' is missing in type '{ red: string; }' but required in type 'Record<Option, string>'." 
// if we just have "red" as the only property.
const optionToString: Record<Option, string> = {
   "red": "this is red",
   "yellow": "this is yellow",
}


// Or, if we indeed want to get undefined for some keys; making them explicit when defining
// the type and value is better and clearer.
const optionToString: Record<Option, string | undefined> = {
   "red": "this is red",
   "yellow": undefined,
}
```

**Comment by bradzacher** [comment]
I'm surprised that we don't currently handle this case because `Record` is literally defined as `type Record<K, V> = { [Key in K]: V }`.

So I think adding support would be good!

**Comment by kirkwaiblinger** [comment]
I'm a little confused because it appears that TS does give an error in the "Fail" case, for all the version and configs that I tried at least. For example, [TS 3.3 with all the strict options disabled gives a missing properties error](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&ts=3.3.3&exactOptionalPropertyTypes=false#code/C4TwDgpgBA8mwEsD2A7KBeKAiAThAJllAD7YgQA2FSA7lgNwBQjAxqgM7BRLzIoAqSAMrAcCFAHMAXFADeUANoBrCCCjjYvVAF0ZnMZIC+GOYyjncBLDKzAAFgnbqneQlAD07qDVQByLgBG0DQAhjgoBFD2IVxY5FS0RI5QALaO7OISjIZAA). 

Thinking about how we would implement the change to ban mapped types, I'm thinking we might want to try to only flag on "trivial" mapped types, like so:
```ts
type Option = "number" | "string";
// should flag
type ShouldBeARecord = { [key in Option]: string }
// should not flag - modifiers are used
type MappingUsesModifier = { readonly [key in Option]?: string }
// should not flag - uses key in mapped type
type UsesKey  = { [key in Option]: key extends "number" ? number : key extends "string" ? string : never  } 
```
Would maintainers agree?
