### ISSUE TITLE
Rule proposal: no unsafe casting to a class

### ISSUE THREAD

**Issue by chriskuech** [typescript-eslint/typescript-eslint#6625]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

JavaScript supports `class`es for sugar over prototypal inheritance. It also supports the `instanceof` keyword for defining type guards against classes and checking the inheritance chain.

However, TypeScript [allows implicitly casting to a class](https://github.com/microsoft/TypeScript/issues/42698), leading to an inaccurate type system later in the application, and confusing bugs.

I propose an eslint rule to block implicitly casting a value to a class type, to ensure the integrity of the prototype chain.

### Fail Cases

```typescript
// setup
class A {
  a: number;
}

// fail case
const a: A = { a: 1 };
```

### Pass Cases

```typescript
// setup
class A {
  a: number;
}

class B extends A {
  b: number;
}

// pass cases
const a: A = new A(); // baseline requirement for not breaking the type system

const b: A = new B(); // a "nice to have" that could be a fail case in an initial version
```

### Additional Info

class-based deserializers are unavoidable with frameworks like NestJS, which has a big reach. TypeScript is also often used by Java/C# devs trying to break into JavaScript programming while minimizing their learning curve. These green devs are more likely to use inheritance and are vulnerable to this issue.

**Comment by bradzacher** [comment]
> an inaccurate type system later in the application

It's not *really* an inaccuracy - TS's type system is based around "structural typing".

The big inaccuracy is with how people believe TS models types.
In other systems classes behave more like "nominal" types, but in TS they just define a shape.

The `instanceof` case is the only real incorrect behaviour, because TS will treat `A` as a nominal type for an `instanceof` check, and the "negative" branch is treated as "unreachable" code when it isn't actually unreachable.

---

Now as for implementing this rule - I don't think it's really possible in an efficient way.

In order for us to implement this we would need to do something similar to the `no-unsafe-*` rules - which is to check every single possible type of assignment.
However, unlike the `no-unsafe-*` rules which just need to check if the assignee type is `any`, this rule would be a lot more complicated.

TS types do not include any information about whether or not the thing is a class (if it did, then I assume TS would use this information itself!).
Which means that not only do we need to inspect the assignee type to resolve the declaration and determine if it was declared with a class or not, but we also need to do the same for the receiving type to determine if it's declared with a class and if it is, if it's declared with the exact same class (or a super class from the inheritance chain)!

All together such a rule would be prohibitively expensive to say the least.
From my experience it's rarer that people accidentally mix-and-match classes and object types like this, so I'm not sure how wide-spread such a problem is in the broader ecosystem.

For these reasons (complexity, performance, reach) I'm leaning towards rejecting this proposal.

**Comment by bradzacher** [comment]
Worth noting separately to the above that it is possible to make classes behave more like nominal types by [defining a private field on the class](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG9oAcBO83QLzQEZoBfAKFEhgCEwMV0sd8CBuaAYgCMMwA7AEwBc0AK4CApgDMAlr3H8S5cFGgBlEZxp1xADwAu4gdVooyFFTQBe9TNjyE2XHgOFj+U2fMWlSAClS2aMJExNAQYHrSEDLiMAjwAJQsfgGMwSRhEVExxhhJKQzY6aHhkdHSsWoaWvn+hUGEGaXZFcaW+X6+cgDucIi+CQmZZTl9icm+XeK98QNDzeWVNRNTM-2Dwy2V6pq0tatjc5uLbR2TPdBaRwuj8fsXVxs3rZd7Kw+011knVbt579NXhgviMXlYzgcdo95t9boh7oCoZ8nrCwW9OhckcCUaDttV0edEfjsTDcadkhjAVYQVs4vCAb1qTjaUCEYywJYaT8sWzXpzmT9wSwgA). When a private field is defined on a class, then TS will enforce that only instances of that class or its subclasses are assignable.

**Comment by bradzacher** [comment]
Please also take the time to fill out the issue title when you file an issue.

**Comment by chriskuech** [comment]
@bradzacher thanks for the thoughtful investigation! I just added a title.

>The instanceof case is the only real incorrect behaviour, because TS will treat A as a nominal type for an instanceof check, and the "negative" branch is treated as "unreachable" code when it isn't actually unreachable.

There is more incorrect behavior aside from `instanceof` that I'm much more concerned about: getters/setters and decorators wont be applied.

**Comment by bradzacher** [comment]
This issue has been open for 4 months and has not received any community engagement.
As such - we're taking this as signal that this is not important to the broader community, and so we are rejecting this proposal.
