### ISSUE TITLE
Bug: type resolution failure with `nodenext` resolution

### ISSUE THREAD

**Issue by DASPRiD** [typescript-eslint/typescript-eslint#6661]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

When setting `module` and `moduleResolution` in `tsconfig.json` to "NodeNext", typescript-eslint fails to find the type definitions for specific packages, e.g. `libphonenumber-js`.

Setting the module resolution to another value solves that issue, but that introduces other problems of course, so this is not a solution.

I created a simple reproduction repository with a minimal setup. Running `lint` there will falsely report an unsafe assignment of an `any` value.

### Reproduction Repository Link

https://github.com/DASPRiD/typescript-eslint-bug-nodenext-resolution

### Repro Steps

1) clone the repo
2) `npm i`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `5.55.0` |
| `@typescript-eslint/parser`            | `5.55.0` |
| `TypeScript`                           | `4.9.5` |
| `ESLint`                               | `8.36.0` |
| `node`                                 | `18.15.0` |

**Comment by Josh-Cena** [comment]
Hiǃ Your error is because the second `defaultCountry` parameter is `any`.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/55398995/226033669-1a9b864b-ef96-4df7-9278-6bc842aecb05.png">

If you go to the lib def of `libphonenumber-js`, you see that the second parameter has type `CountryCode`, which is imported from `./types`. However, because the package has `"type": "module",`, the file in which the declaration is contained is treated as a module, so `./types` resolves to nothing (because it needs an explicit extensionː `./types.js`).

The lib def of `libphonenumber-js` needs to be fixed. TS-ESLint actually saves you from a potentially unsound assignmentǃ

**Comment by DASPRiD** [comment]
Thanks a lot for that deep analysis! I've created an issue in their issue tracker, referencing your comment!
https://gitlab.com/catamphetamine/libphonenumber-js/-/issues/96

**Comment by catamphetamine** [comment]
@Josh-Cena Hi. If we change all imports from `./types` to `./types.js`, while the file itself in reality is called `types.d.ts`, will it work correctly and across all (currently used) TypeScript versions?

**Comment by Josh-Cena** [comment]
Yes, it has worked since a long time ago.

However, I recommend you remove `"type": "module"` from your package.json, because your main entry point is in fact a CJS module. You would get more help on configuring your package.json if you ask in one of TypeScript's help channels or ping someone like @andrewbranch 😄
