### ISSUE TITLE
Bug (?): broken autofix in typescript-eslint with @typescript/vfs 

### ISSUE THREAD

**Issue by thorn0** [typescript-eslint/typescript-eslint#6707]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

I'm trying to lint and autofix a set of files stored in memory using `@typescript/vfs`. When I use the `@typescript-eslint/parser` parser and pass an instance of `Program` to it, I get incorrect autofix results for the `prefer-const` rule.
This code
```ts
export {}; var o = 1; let a = 1; console.log(a);
```
gets autofixed to this:
```ts
export {}; let o = 1; constststststststststst a = 1; console.log(a);
```
It works fine with ESLint's default parser.

This looks suspicious, but I'm not sure it's a bug. I just might be doing something wrong. If so, I'd appreciate a point in the right direction.

### Reproduction Repository Link

https://github.com/thorn0/typescript-eslint-vfs-repro

### Repro Steps

1) clone the repo
2) `yarn install`
3) `yarn start`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/parser`            | `5.55.0` |
| `TypeScript`                           | `4.9.4` |
| `ESLint`                               | `8.36.0` |
| `node`                                 | `18.12.1` |

**Comment by armano2** [comment]
generally issue is with sync between eslint and ts-eslint, as is program will not work with fixers as there is no way for it to update code, sadly the only way to make it work is override parser

for a website i had to do something like this:
https://github.com/typescript-eslint/typescript-eslint/blob/a9407fa168bf256819f094cd988901811b50e59c/packages/website/src/components/linter/createParser.ts#L38-L103

----------------

to make update work you have to update program on after every fix pass

```ts
const system = createSystem(fsMap);
const env = createVirtualTypeScriptEnvironment(system, [], ts, compilerOptions);

const linter = new Linter();

linter.defineParser('@typescript-eslint/parser', {
  parseForESLint: (code, options) => {
    console.log('DEBUG: ', code, options.filePath)

    if (options.filePath) {
      // TODO: check if file was already created than updateFile, to improve performance
      env.createFile(options.filePath, code);
    }
    options.programs = [env.languageService.getProgram()];

    return tsEslintParser.parseForESLint.call(tsEslintParser.parseForESLint, code, options)
  }
});

const result = linter.verifyAndFix(fsMap.get("/index.ts"), {
  rules: {"prefer-const": "error", "no-var": "error"},
  parser: "@typescript-eslint/parser",
  parserOptions: {sourceType: "module"},
}, {
  fix: true,
  filename: "/index.ts",
});
```

```
DEBUG:  export {}; var o = 1; let a = 1; console.log(a); /index.ts
DEBUG:  export {}; let o = 1; const a = 1; console.log(a); /index.ts
DEBUG:  export {}; const o = 1; const a = 1; console.log(a); /index.ts
{
  fixed: true,
  messages: [],
  output: 'export {}; const o = 1; const a = 1; console.log(a);'
}
Done in 1.50s.
```

**Comment by thorn0** [comment]
@armano2 This helped, thanks. As an optimization, I recreate the program only when file content is changed. Should we keep the issue open?

**Comment by bradzacher** [comment]
Yeah so the issue is that when you provide your own program we have no mechanism to update it.
Our infrastructure is built around using a "builder program" that we can trigger updates on whenever ESLint asks us to parse a file.

If we're in single run mode we do use an immutable program and we do some ugly stuff to make it work if there's a fixer run.
But if we're in provided program mode we can't do the same ugly stuff because you control the program, not us.

Sadly ESLint doesn't tell us if it's a fix run parse or a normal parse - it just asks us to parse the file - so we can't even bail out and prevent this bad case, sadly - so it's just an edge case we can't handle.
Originally the provided program infra was added just so that teams that write custom typecheck scripts can also utilise the program from that typecheck to also do a lint run and save time and memory. This would mainly be for a CI step where you're linting without fixers and resource usage is at a premium. We've also had sparse few usecases outside of that (I actually haven't heard of any myself) which is why we haven't progressed that line of work any further.

There's a whole piece of work around figuring out how to best integrate vfs for the rule test use case (which would, in turn, support non-test usecases) - https://github.com/typescript-eslint/typescript-eslint/issues/1891, but that's not on our radar any time soon TBH.

So for now I'm going to close this us "sadly working as intended due to factors that are too hard to control and solve for without #1891"

**Comment by bradzacher** [comment]
In a nutshell we dodgily detect if you might be in a fix run by the combination of "are we in single run and has the file been parsed more than once?" - which is super dodgy and cna only work in single run mode.

If we detect this case then we create a "default program" for the file - which is kind of like an isolated typecheck run with tsconfig `{...config, include: [], files: ["theFile.ts]}`. This is obviously not great because it means that we will duplicate the typecheck for the file's dependency tree.

In provided project mode we don't have your tsconfig - we only have the program. We also don't know how to reproduce the program you gave us (I.e. Did you build it with custom module resolution logic or a vfs) so we can't use this same logic.

I don't know how we'd fix this aside from allowing you to pass a callback like `(filename: string) => Program`

**Comment by thorn0** [comment]
> we will duplicate the typecheck for the file's dependency tree

Is it so? It doesn't check the dependency tree in that case as far as I can understand. It has [`noResolve: true`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/typescript-estree/src/create-program/createIsolatedProgram.ts) and its compilerHost has access only to one file.
