### ISSUE TITLE
Docs: Mention extending from base ESLint rule options in extension rule docs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#6841]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Right now, our autogenerated docs for extension rules don't say what the base rule options are. They just provide a link to the base rule docs page and show what we add on top. For example, in https://typescript-eslint.io/rules/no-use-before-define/:

> See [eslint/no-use-before-define options](https://eslint.org/docs/rules/no-use-before-define#options).
>
> This rule adds the following options:
>
> ```ts
> interface Options extends BaseNoUseBeforeDefineOptions {
> ...
> ```

I've always back-of-mind found this to be a little inconvenient/confusing - that I have to go to a separate page to learn what the options are. Perhaps there's a way we can _name_ those options on our page, so folks at least know they exist?

Maybe...

> See [eslint/no-use-before-define options](https://eslint.org/docs/rules/no-use-before-define#options). Base rule options include:
> * [`allowNamedExports`](https://eslint.org/docs/rules/no-use-before-define#allownamedexports)
> * [`classes`](https://eslint.org/docs/rules/no-use-before-define#classes)
> * [`functions`](https://eslint.org/docs/rules/no-use-before-define#functions)
> * [`variables`](https://eslint.org/docs/rules/no-use-before-define#variables)
> 
> This rule adds the following options:
>
> ...

Note that for now we'll definitely want to always link to the base ESLint rule docs as the primary source of information. Those pages have much more detailed information than what we're able to glean dynamically.

Example of a very knowledgeable user asking about how to do something covered by a base rule option: https://twitter.com/TkDodo/status/1643170053691514882

### Affected URL(s)

https://typescript-eslint.io/rules/no-use-before-define & others

**Comment by bradzacher** [comment]
The reason we don't do this is because we didn't want to duplicate the docs - it's just something to maintain that can get out-of-sync very easily.

We actually used to copy paste the entire rule docs, it we stopped doing that because we kept missing updates to the docs (like new options) and people asked why things were missing.

Additionally some of the time we don't add new options - we just added support for new syntax. So use

---

***Personally*** I don't think this is unclear - in the options section the very first line says "see the core rule docs for options"

If we have added options then the next line says "this rule adds the following options" and the options type we display includes `extends BaseRuleOptions` for the interface type.

![Screenshot_20230405-064141.png](https://user-images.githubusercontent.com/7462525/229923563-681d8ce9-1187-4340-befb-a77316929bc3.png)

So there are 3 immediate markers in the options section that signal that there's more than what is written in the docs.

I would personally think we should look to making those more prominent rather than us trying to add content from the core rule docs.

For example we could change the options code fence to be like

```ts
interface BaseRuleOptions {
  // see the base rule docs for details
  // <link to eslint docs here>
}

//... 
```

That way instead of implying there are more options with an small, missable `extends` we explicitly declare that there are more docs not defined here.

**Comment by TkDodo** [comment]
I guess the one to blame is purely me, because I was looking at the docs, I saw the `extends BaseNoUseBeforeDefineOptions`, but didn't understand what it refers to. I also missed the very clear first sentence:

> This rule extends the base [eslint/no-use-before-define](https://eslint.org/docs/rules/no-use-before-define) rule.

Because my brain is wired to reading headings and code snippets, skimming the rest 😔.

I don't think you could've done any better with the docs here ❤️. My instinct to ask on twitter was stronger than reading the page fully once again. Trust me, I know how annoying it is to have people complain about something that turns out works just fine if a bit more effort would've made to understand the tech.

Ironically, an hour earlier, I tweeted this 😅 
- https://twitter.com/TkDodo/status/1643149179835777024

**Comment by JoshuaKGoldberg** [comment]
> Because my brain is wired to reading headings and code snippets, skimming the rest 😔.

Aha I think this is the key bit - that a lot of users (myself included) are like this. If making the docs better for this common reading pattern doesn't hurt overall readability for others, we should do it. So I really like Brad's suggestion of adding comments in the `BaseRuleOptions` interface. Let's go with that!

**Comment by JoshuaKGoldberg** [comment]
I'd really love to automate the base rule options completely. https://typescript-eslint.io/rules/no-use-before-define has a great default options description for the happy case (object rules).

However, core ESLint rule's don't have a `defaultOptions` property the way typescript-eslint rules do. There's no way for us to know what the core rules' defaults are. So if we were to try to auto-generate docs for default values of extension rules, we'd have no way of knowing which option defaults are the same as their core values.

**Comment by JoshuaKGoldberg** [comment]
Coming back to this, I think it'd only really be worthwhile if we auto-generate the rule docs fully. I'm going to close this out pending ESLint adding in a defaultOptions schema.
