### ISSUE TITLE
Repo: Why the version bump to `v5.59.6`?

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [typescript-eslint/typescript-eslint#7031]
### Suggestion

Looking at the [changes between `v5.59.5` and `v5.59.6`](https://github.com/typescript-eslint/typescript-eslint/compare/v5.59.5...v5.59.6), there was only a single commit (for the version bump), none of the changelogs updated in that commit indicate what changed and the only packages updated were `@typescript-eslint` scoped packages.

I assume that one of the updated dependencies has its own repo and changelog, but there doesn't seem to be any way to know what triggered the version bump other than by going to each typescript-eslint repo and checking. Would it be possible to add this information to the changelog?

**Comment by bradzacher** [comment]
https://github.com/typescript-eslint/typescript-eslint/releases

We document all releases using the github releases UI.

The last release was a no-op release. In a nutshell the tooling we use looks across all of the packages and determines what version bumps are required, then increments them all to the largest version.
If there are no changes required for a package the version it calculates is just a patch release. So across the entire repo if there have been no commits then it just does a patch release.

I believe the reason behind this is a "catch all" thing to make sure that incorrectly categorised changes are released even if there are no other user-visible changes. Eg we've accidentally categorised some changes as "chore" before and had the "no-op" release not gone out then the changes would have been held back for a week.

Idk if we should be doing this - it's rare that we have more than a week of no changes. Lately has been a bit of an anomaly due to v6 work and other commitments.

Cc @typescript-eslint/core-team - should we stop these noop releases?

**Comment by JamesHenry** [comment]
I get it... on the other hand, we have been doing this for years and years, to potentially millions of consumers, and how many issues have we had about it? Only a handful I believe?

So I really don't think it's a big deal in practice, and the flip side is the nice predictability that comes with one release to `latest` each and every week (barring a few extra hot fixes on top occasionally)

We could potentially amend the `Version bump only` text to be more descriptive as an alternative resolution here?

**Comment by ehoogeveen-medweb** [comment]
Ah, so this was just a regularly scheduled weekly release after a week with 0 commits to the main branch? If so, that's fine - my assumption was that the release was _triggered_ by some change, and I was confused that I couldn't figure out what it was.

**Comment by bradzacher** [comment]
no it's fair - we don't actually document the fact that we always release, even if there are no changes.

https://typescript-eslint.io/maintenance/versioning

**Comment by JamesHenry** [comment]
Yeah agreed that’s what I meant by amending the text in the changelogs themselves in this case too, to make it clear what happened and why
