### ISSUE TITLE
Enhancement: @typescript-eslint/explicit-function-return-type 'allowedNames' option must accept regular expressions as well

### ISSUE THREAD

**Issue by daniilgri** [typescript-eslint/typescript-eslint#7053]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/explicit-function-return-type/

### Description

@typescript-eslint/explicit-function-return-type rule is having an option called `allowedNames` which takes method names list. We can use it to ignore certain method/function names for this rule.

The issues is it is not working with regular expressions.

The problem:
I would want to ignore this rule for certain methods having their names starting with 'use...' word. All I can do right now is to list all those method names explicitly but it is not an option because I have a lot of those methods.

I could not find any examples of having regexps with 'allowedNames' option and it would be very helpfull to have this featue.

### Fail

```typescript
function dropIt(): void {
...
}
```

### Pass

```typescript
function useDropIt() {
...
}
```

**Comment by bradzacher** [comment]
I don't think that regex support is a good addition to the rule - there's so much scope for false negatives that accidentally introduce a severe lack of consistency across the codebase.

Exact names are good because they're limited in scope and match specific names only - so there's only so much "damage" you can do across your codebase.
OTOH a regex can easily over-match eg accidentally forgetting to use start(`^`) or end(`$`) markers can cause your regex to match exponentially more names than you intended - for example passing the regex `/use/` would match `useDropIt` and also `misuseDropIt` - oops!

We were already reluctant to add `allowedNames` to the rule to begin with, and I don't see a compelling reason to expand it to regexes that broadly match the codebase. If there's significant community engagement here, we might consider it - but given this is the first request since the rule was created many years ago - I don't think it's something that aligns with the broader community.

**Comment by Josh-Cena** [comment]
Curious why you want to ignore all variables starting with `use`? In React hooks don't have to be effects either.

**Comment by daniilgri** [comment]
@Josh-Cena  I'm working on Vue3 project and we have composable functions, it is simple functions and they import methods/properties and it is common case when they have big return object. It is not easy to write return type for every composable method. Right now I'm disabling this rule for every composable function. We have convention to name all of our composables starting with "use*", so that's why it would be very helpful for me to disable all functions starting with "use*" or even better we could override this rule for files including "*.composable.ts" in their names and disable functions starting from "use*" in those files

**Comment by leereichardt** [comment]
> We have convention to name all of our composables starting with "use*", so that's why it would be very helpful for me to disable all functions starting with "use*"

This right here is a compelling reason. In fact, I'm reasonably sure this is the convention for these composables. Having to have a list of 10+ return types is pointless and verbose, and can in fact make navigation around your code base that much slower.

I'm interested to hear why adding 100+ method names for specific matches is better than allowing allowing a user to configure it?

**Comment by bradzacher** [comment]
@leereichardt the vast, vast, vast majority of users don't want generic matches for named patterns - they want to ignore specific names - for example "Ignore this set of methods because they are named framework methods and have a well-defined, well-known return-type".

It's not a common usecase to want to ignore user-defined functions because there aren't many usecases where (a) you have a common naming scheme for an entire class of user-defined functions that can be regex-matched and (b) they have non-uniform return types that you actively don't want to explicitly type. It's just a really, really rare usecase.

With a broadly-used, general purpose plugin like ours we're not looking to satisfy every single usecase. We're also maintained by volunteers - so we want to balance supporting usecases against maintenance burden. Each option exponentially increases test surface, which puts a heavier maintenance burden on us.
There's a give-and-take - we reject many request because they target a small percent of our overall userbase - it's not worth us increasing our volunteer workload to service a small number of users because we don't have enough bandwidth as it is.

In this instance - vue itself is *relatively* small in the front-end world (~4m weekly DL). The number of users that use vue + eslint is smaller still (~2.8m), and the number of users that use vue + TS is a fraction of that (IDK exactly what packages to look at - but the packages in the vue docs only show at most ~500k weekly DL), and finally the number of users that use vue + eslint + TS is an even smaller fraction still (I don't think it's possible to calculate this number).
Then you further reduce this count by taking that small subset and looking at the number of people who "use composable methods" and "want to ignore all composable methods" - you're at a tiny fraction of our overall userbase.

Which is why we push back on this request and have marked it as evaluating community engagement. Right now there's OP, you, and 1 reaction - 3 community members interested in this idea. Which isn't anywhere near the community support we'd want for a feature we're not in favour of to begin with.

> it is common case when they have big return object

Big return types are usually a good thing to explicitly type in TS. Creating a named type is more internally efficient for TS than having TS create new anonymous object types. Anonymous object types are also hard for users to use as they can't ever name them and instead have to do hacky things like `ReturnType<typeof useFoo>` to dynamically extract the return type.

>  It is not easy to write return type for every composable method

This statement is at-odds with what you've described to us - it suggests that some of them are easy to write and some aren't. To me that suggests that instead of blanked ignoring every composable, you err on the side of trying to type it, and opt-out specific and difficult cases with a disable comment.

**Comment by leereichardt** [comment]
Thanks for the in-depth reply @bradzacher, that makes perfect sense and helped me to understand design decision on bigger projects like this

**Comment by aduh95** [comment]
I for one would like to exclude all private field properties/methods from this rule (because I'm only concerned about the type stability of the public API of my lib), it'd be nice to be able to specify that all function names that start with `#` are excluded.

**Comment by bradzacher** [comment]
@aduh95 consider our [`explicit-module-boundary-types`](https://typescript-eslint.io/rules/explicit-module-boundary-types/) rule

**Comment by JoshuaKGoldberg** [comment]
It's been >6 months and this issue hasn't been positively mentioned in other contexts. Closing this out as a wontfix on our end.

If anybody comes across this later and wants it: you can always build new rules and/or fork ours! See docs on https://typescript-eslint.io/developers/custom-rules. Cheers!
