### ISSUE TITLE
Docs: instructions on how to integrate custom rules into your project

### ISSUE THREAD

**Issue by flut1** [typescript-eslint/typescript-eslint#7066]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

typescript-eslint has some [great documentation](https://typescript-eslint.io/custom-rules) and [utils](https://typescript-eslint.io/architecture/utils/) to write a custom linting rule 👍 The first line reads "_custom ESLint rules generally work the same way for JavaScript and TypeScript code_", so the [plugin docs from eslint](https://eslint.org/docs/latest/extend/plugins) are a good starting point. However, it still left me with some questions around how to utilize such a rule in a project. 

Writing custom rules on top of typescript-eslint might not be incredibly common, so I don't expect there to be a extremely detailed step-by-step guide. But I think some pointers around the questions listed below would be a great addition to the documentation:

1. Can the `rule` from the [code snippet in the documentation](https://typescript-eslint.io/custom-rules/#rulecreator) be directly consumed in your eslint config, or does it need to be wrapped in a plugin?
   -  my guess is this is generally the same as eslint, but is anything like "[Runtime Rules](https://eslint.org/docs/latest/extend/custom-rules#runtime-rules)" also possible?
2. Do rules need to be compiled to JS before being usable? 
   - my assumption is yes, but this was optional in `tslint` if you utilized `ts-node`. So it would be nice to mention this explicitly.
3. What tsconfig is recommended when compiling a rule?
   - I tried copying configuration from the `@typescript-eslint/eslint-plugin` package (given that one contains the rules). Not all of it seems to be relevant for creating rules though
4. If you want to publish a package with a rule: 
   - are there package naming recommendations on top of the [naming instructions](https://eslint.org/docs/latest/extend/plugins#name-a-plugin) from eslint itself?
   - should `typescript` and `@typescript-eslint/***` packages be part of your (peer/dev-)dependencies?

This list is not intended as a literal proposal of questions that should all be addressed in the docs. Rather they're meant as examples of a topic that I think could use some clarification. Even referencing an example repo with a good setup would already help. Alternatively, there's interest in having a generator similar to [eslint/generator-eslint](https://github.com/eslint/generator-eslint). There's [an open issue](https://github.com/eslint/generator-eslint/issues/120) to create a TypeScript template, but at this moment it seems unclear if they want to move forward with that.

### Affected URL(s)

https://typescript-eslint.io/custom-rules

**Comment by bradzacher** [comment]
Answering quickly to help unblock you right now - these can be worked into proper docs after the fact.

> Do rules need to be compiled to JS before being usable?

It's generally best to pre-compile them, but you could also leverage `ts-node`/`tsx` to avoid that - just depends if you want the lint-time perf hit or not.

When I worked at Meta we used to use `@babel/node` to transpile our rules (written in flow) on the fly because there wasn't a good spot in the lint pipeline to do a build. We consumed it by adding `require('@babel/node')` to the plugin root `index.js`.
At Canva (where I work now) we build the rules to JS ahead of time because of the way the repo is organised.

> Can the rule from the [code snippet in the documentation](https://typescript-eslint.io/custom-rules/#rulecreator) be directly consumed in your eslint config, or does it need to be wrapped in a plugin?

Either - you can use the runtime rules setup if you would like because rules made with our tooling are just plain old lint rules (you'd probably want to pre-compile them unless you want users to run the lint like `ts-node ./node_modules/.bin/eslint --rulesdir eslint_rules`).
You can also create your own plugin package locally and consume that either as a local node module, or I believe you can also use the absolute path via `require.resolve`.

At both Meta and Canva we defined a separate plugin just because it allows better isolation of the codebases. At Meta we used a yarn `link:` dependency to install it and at Canva it installs the directory (`yarn add ../my-custom-plugin` IIRC?).

If you've got a multi-package monorepo style project you can also use yarn workspaces to do it - this is how we do it in this project - `yarn` creates the appropriate symlinks at install time and ESLint just sees our plugins as plain old node modules.

> What tsconfig is recommended when compiling a rule?

Whatever you need to support the node version your repo uses, plus `strict: true` would be all we recommend as a baseline.

> are there package naming recommendations on top of the [naming instructions](https://eslint.org/docs/latest/extend/plugins#name-a-plugin) from eslint itself?

Nope - just ensure you follow ESLint's requirements and that's all you need to do. ESLint's requirements must be adhered to in order for ESLint's "name shortening" to work.

> should typescript and @typescript-eslint/*** packages be part of your (peer/dev-)dependencies?

It depends what you use - if you use our utils, then you should add `@typescript-eslint/utils` as a dependency. Avoid peer deps - peer deps are something you should only really use if you're "plugging" in to the system or it's a hard requirement for the user but you don't want to control their version.

You'd want to have:
- a peer dep on TS (so that strict package managers won't error when you access TS)
- a peer dep on ESLint (to signal that you're "plugging in" to ESLint and also to signal what versions you support)
- and a full dep on our utils (if you use them)

**Comment by awilson9** [comment]
I'm trying to view the documentation for custom rules but the page seems to be broken. https://typescript-eslint.io/custom-rules

![Screenshot 2023-06-27 at 2 51 26 PM](https://github.com/typescript-eslint/typescript-eslint/assets/15809032/ca11934a-ca92-4c92-b72a-3a55d569e794)

**Comment by bradzacher** [comment]
The page has moved
https://typescript-eslint.io/developers/custom-rules
