### ISSUE TITLE
Bug: @typescript-eslint/no-unnecessary-condition removing required optional chaining

### ISSUE THREAD

**Issue by Xavier59** [typescript-eslint/typescript-eslint#7086]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.3&sourceType=module&code=MYewdgzgLgBAZiEAjAhgJwFwwEoFNRoAmAPNGgJZgDmANDAN4yqYxmVUwC+AfDALwN4iLI2ZYAREgCeuGAEJxXLgFgAUABtcsALZSAYon4xxCcQG41a0JBCaAdOpBUAFAmToA2roMgAugH47Zhh-f2MAC1x1R3lxAEoLVTVvQwBqAXEQc0tVawhbXAcnV0RmL31EAKD0ELDxSOiQWISgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1vwAtoOA7rUb5E0AIbx0UDgDNZkADThskTrWL98HIqVoAjWJXj5mqDJDkLl2KARLkqNeskYtW0FPipk6ogLbE8OKi9AAemijIlBxM5jLySio4iACOaWnSANrJqmL80Em2OJIC4oSoNsVYxThMCFIWlADmnJ6QuRAAvrkAulU49qTIFNR0DMxsZLHRyKIs3A60ACaIssyUpjPZnVD5HIUDqrqIHbb9uXgnI07jrpOs4tAShIukO7WQ+4e7NZ+rsnECHw0kgTxeRVqUE84mWsXghFB4PKZ2KPXORyuDhuYxcbjY6lgTCYiDIUSer2mTGWmxiTFB31RPS6QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTokBMADL5ABpwNSCTyZk0NpXEBXdEJpREmTlgBu6AMLExAUSKz4ZGZnmKRRWHvjJpYOQuG0SsWZmjoAsvUTsAZvSoJE5KkPCwACayGOwwCBFEAFZkFrQR0RgASpywqLIExHFWkeiCzhwkXlEx6ACSRHhYsH6m5hWiANbIiAAyyABGWgAW6NCd7I5pUP6wHtq6yGLojVr0JMhETA0AYmjoAHL08JyTZqEiS3n0TZHVmadt6MIAvhaQ6AAe0Pml7ADaHRK6AA+hlaqkOgAqKEAeihADommIkWRhABdEAvIA

### Repro Code

```typescript
const foobar: Record<string, { bar: string }> = { foo: { bar: "bye !" } }
let myFoo = "fo";

console.log(foobar[myFoo]?.bar ?? "hello !");

myFoo += "o";

console.log(foobar[myFoo]?.bar ?? "hello !");
```

### ESLint Config

```javascript
{
    env: {
        node: true,
        commonjs: true,
    },
    extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/strict",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
    ],
    root: true,
    overrides: [],
    parser: "@typescript-eslint/parser",
    parserOptions: {
        ecmaVersion: "latest",
        tsconfigRootDir: __dirname,
        project: ["./tsconfig.json"],
    },
    plugins: ["@typescript-eslint"],
    rules: {
        "@typescript-eslint/no-throw-literal": "off",
        "no-prototype-builtins": "off",
        "@typescript-eslint/restrict-template-expressions": "off",
        eqeqeq: ["error", "always", { null: "ignore" }],
        "@typescript-eslint/consistent-type-definitions": ["error", "type"],
        "@typescript-eslint/array-type": [
            "error",
            {
                default: "array",
                readonly: "array",
            },
        ],
    },
}
```

### tsconfig

```jsonc
{
    "compilerOptions": {
        "target": "es2020",
        "strict": true,
        "preserveConstEnums": true,
        "noEmit": true,
        "sourceMap": false,
        "module": "commonjs",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "isolatedModules": true,
    },
    "exclude": [
        "node_modules",
        "**/*.test.ts"
    ]
}
```

### Expected Result

When running `eslint --fix \"**/*.ts\" `, the code should not be changed and should output:

```
hello !
bye !
```

### Actual Result

The rule `@typescript-eslint/no-unnecessary-condition` removes the optional chaining and transform the code to:

```typescript
const foobar: Record<string, { bar: string }> = { foo: { bar: "bye !" } }
let myFoo = "fo";

console.log(foobar[myFoo].bar ?? "hello !");

myFoo += "o";

console.log(foobar[myFoo].bar ?? "hello !");
```

Which outputs the following:

```
Cannot read properties of undefined (reading 'bar') 
```

**Comment by bradzacher** [comment]
Could you please use our playground for the repro? Our playground supports linting so you can reproduce the problem.

https://typescript-eslint.io/play/

**Comment by Xavier59** [comment]
@bradzacher I have edited the issue with the correct playground link.

**Comment by Josh-Cena** [comment]
Please turn on `noUncheckedIndexAccess`. TypeScript tells us that the expression is never non-null, and we trust that type.

**Comment by bradzacher** [comment]
@Josh-Cena is correct.

The rule is powered exclusively by types.
Based on your types, `foobar[myFoo]` can never ever be `undefined` - hence the rule flags the optional chain as unnecessary.

This the reason you can remove the optional chain operator without causing a TS error - because TS thinks the type is not `undefined` - however at runtime it definitely can be!

Josh is correct - the [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) compiler option will make TS include `undefined` at read time to make sure your code is safe.

The other option is to manually union in `undefined` - eg `Record<string, { bar: string } | undefined>` - however this isn't as safe as the option. The option TS specifically applies at read time only, but the manual union will also apply at write time - allowing you to write `undefined` accidentally.

[playground with `noUncheckedIndexedAccess` turned on](https://typescript-eslint.io/play/#ts=5.1.3&sourceType=module&code=MYewdgzgLgBAZiEAjAhgJwFwwEoFNRoAmAPNGgJZgDmANDAN4yqYxmVUwC+AfDALwN4iLI2ZYAREgCeuGAEJxXLgFgAUABtcsALZSAYon4xxCcQG41ahMnQBtXQZABdAHTMzMAPSeYgUHIYACoAyjBgIADuMLhoaCBoEDDgMFAAFuQJALSsIMkpsmgArpow4eTq6jAEaPhQ6lIw5FRh1YkADlDk4CgVwCkolBBylqqgkCCaLuogVAAU1sz2+ohOAPxu6DArK8Z55TkKAJQWqmoOhgDUAuIg5sOjEOO4k9NziAtnzmvMm9viu1PycRHNRAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1vwAtoOA7rUb5E0AIbx0UDgDNZkADThskTrWL98HIqVoAjWJXj5mqDJDkLl2KARLkqNeskYtW0FPipk6ogLbE8OKi9AAemijIlBxM5jLySio4iACOaWnSANrJqmL80Em2OJIC4oSoNsVYxThMCFIWlADmnJ6QuRAAvrkAulU49qTIFNR0DMxsZLHRyKIs3A60ACaIssyUpjPZnVD5HIUDqrqIHbb9uXgnI07jrpOs4tAShIukO7WQ+4e7NZ+rsnECHw0kgTxeRVqUE84mWsXghFB4PKZ2KPXORyuDhuYxcbjY6lgTCYiDIUSer2mTGWmxiTFB31RPS6QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTokBMADL5ABpwNSCTyZk0NpXEBXdEJpREmTlgBu6AMLExAUSKz4ZGZnmKRRWHvjJpYOQuG0SsWZmjoAsvUTsAZvSoJE5KkPCwACayGOwwCBFEAFZkFrQR0RgASpywqLIExHFWkeiCzhwkXlEx6ACSRHhYsH6m5hWiANbIiAAyyABGWgAW6NCd7I5pUP6wHtq6yGLojVr0JMhETA0AYmjoAHL08JyTZqEiS3n0TZHVmadtF7RWAKpE0KPj6JENpQAePwAgtBPCQTA5zsIAL4WSDof7QfKldgAbQ6JXQAH0MrVUh0AFQEgD0BIAdE0xBSyMIALogaFAA)
[playground with `undefined` manually unioned in](https://typescript-eslint.io/play/#ts=5.1.3&sourceType=module&code=MYewdgzgLgBAZiEAjAhgJwFwwEoFNRoAmAPNGgJZgDmANDAN4yqYxmVUwC+MAPjAK5hCuOJVyEAfDAC8DeIiyNmWAERIAnrhgBCFVy4BYAFAAbXLAC26gGKIZMFQhUBuY8YTJ0AbSu2QAXQA6ZmcYAHowmEBQchgAFQBlGDAQAHcYXDQ0EDQIGHAYKAALclyAWlYQAsKtNH4zGBTyExMYAjR8KBN1GHIqZPa8gAcocnAUFuBClEoIbTcjUEgQM0CTECoACg9mHxtEfwB+YPQYA4OHaubK3QBKVyNjXzsAalkVEBd5xYhl3FX1raIHZPAJHZinc4qS5rHQqO7zCIwQAy5HFEo1mjBxms0kUSnQUsVJj0IGAAOSwcYpFDqXIUKiFWDZVrZdrAKDuIHeEH+eyCYSiMDie5AA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1vwAtoOA7rUb5E0AIbx0UDgDNZkADThskTrWL98HIqVoAjWJXj5mqDJDkLl2KARLkqNeskYtW0FPipk6ogLbE8OKi9AAemijIlBxM5jLySio4iACOaWnSANrJqmL80Em2OJIC4oSoNsVYxThMCFIWlADmnJ6QuRAAvrkAulU49qTIFNR0DMxsZLHRyKIs3A60ACaIssyUpjPZnVD5HIUDqrqIHbb9uXgnI07jrpOs4tAShIukO7WQ+4e7NZ+rsnECHw0kgTxeRVqUE84mWsXghFB4PKZ2KPXORyuDhuYxcbjY6lgTCYiDIUSer2mTGWmxiTFB31RPS6QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTokBMADL5ABpwNSCTyZk0NpXEBXdEJpREmTlgBu6AMLExAUSKz4ZGZnmKRRWHvjJpYOQuG0SsWZmjoAsvUTsAZvSoJE5KkPCwACayGOwwCBFEAFZkFrQR0RgASpywqLIExHFWkeiCzhwkXlEx6ACSRHhYsH6m5hWiANbIiAAyyABGWgAW6NCd7I5pUP6wHtq6yGLojVr0JMhETA0AYmjoAHL08JyTZqEiS3n0TZHVmadt6MIAvhaQ6AAe0Pml7ADaHRK6AA+hlaqkOgAqKEAeihADommIkWRhABdEAvIA)

**Comment by Xavier59** [comment]
Thanks. I've played a bit and unions seems a bit limited with typescript for now :(

```typescript
const foobar = {
  "foofoo": {"bar": "bye !"},
} as Record<string, { bar: string } | undefined>

const foofoo1 = "foofoo";
const foofoo2 = "foo" + "foo";

if (foobar[foofoo1] !== undefined) {
  foobar[foofoo1].bar;
}

if (foobar[foofoo2] !== undefined) {
  // Error out: Object is possibly 'undefined'
  foobar[foofoo2].bar; 
}
```

[Playground link with `undefined` unioned in](https://typescript-eslint.io/play/#ts=5.1.3&sourceType=module&code=MYewdgzgLgBAZiEAjAhgJxgXhgbwLABQMMARAiOSQFy4mprWlICeApjAIQkC+ANIdxgoIMAEqtQaACYAeaGgCWYAOa9cMejXlLlMQQB8YAVzBTWcJaykA+QoVCRY5cgEYspZ4hIBue+GjwiOQATO5kXjAA1B5evgSECnAwABTk9ADaniAuALqcmNgmZhZgVgCUuITEaeiZQYi5AHT0cdx2BIkpNWh1FIjBeRwFxqbmllIV+EQwAPQzMACiaGggGCBGUDQA8kgAVhKwCiIADiAQEApIADbMMADkRWOlUndVgci1WQPN6N4wAkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1vwAtoOA7rUb5E0AIbx0UDgDNZkADThskTrWL98HIqVoAjWJXj5mqDJDkLl2KARLkqNeskYtW0FPipk6ogLbE8OKi9AAemijIlBxM5jLySio4iACOaWnSANrJqmL80Em2OJIC4oSoNsVYxThMCFIWlADmnJ6QuRAAvrkAulU49qTIFNR0DMxsZLHRyKIs3A60ACaIssyUpjPZnVD5HIUDqrqIHbb9uXgnI07jrpOs4tAShIukO7WQ+4e7NZ+rsnECHw0kgTxeRVqUE84mWsXghFB4PKZ2KPXORyuDhuYxcbjY6lgTCYiDIUSer2mTGWmxiTFB31RPS6QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTokBMADL5ABpwNSCTyZk0NpXEBXdEJpREmTlgBu6AMLExAUSKz4ZGZnmKRRWHvjJpYOQuG0SsWZmjoAsvUTsAZvSoJE5KkPCwACayGOwwCBFEAFZkFrQR0RgASpywqLIExHFWkeiCzhwkXlEx6ACSRHhYsH6m5hWiANbIiAAyyABGWgAW6NCd7I5pUP6wHtq6yGLojVr0JMhETA0AYmjoAHL08JyTZqEiS3n0TZHVmadt6MIAvhaQ6AAe0Pml7ADaHRK6AA+hlaqkOgAqKEAeihADommIkWRhABdEAvIA)

Same result with `noUncheckedIndexAccess`.

[Playground link with `noUncheckedIndexAccess`][https://typescript-eslint.io/play/#ts=5.1.3&sourceType=module&code=MYewdgzgLgBAZiEAjAhgJxgXhgbwLABQMMARAiOSQFy4mprWlICeApjAIQkC+ANIdxgoIMAEqtQaACYAeaGgCWYAOa9cMejXlLlMbgD5ChUJFjlyARiylziEgG5j4aPETkATNbJ2YAaht2jgSECnAwABTk9ADatiAWALqcmNgArmBSrHBKrFIAlLiExFHosW6IiQB09EHcRgShESVoZRSI7kkcKTDpmdlguQX4RDAA9KMwAKJoaCAYIKlQNADySABWErAKIgAOIBAQCkgANswwAOS9WTlS50WuyKVxHdXo9jACQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1vwAtoOA7rUb5E0AIbx0UDgDNZkADThskTrWL98HIqVoAjWJXj5mqDJDkLl2KARLkqNeskYtW0FPipk6ogLbE8OKi9AAemijIlBxM5jLySio4iACOaWnSANrJqmL80Em2OJIC4oSoNsVYxThMCFIWlADmnJ6QuRAAvrkAulU49qTIFNR0DMxsZLHRyKIs3A60ACaIssyUpjPZnVD5HIUDqrqIHbb9uXgnI07jrpOs4tAShIukO7WQ+4e7NZ+rsnECHw0kgTxeRVqUE84mWsXghFB4PKZ2KPXORyuDhuYxcbjY6lgTCYiDIUSer2mTGWmxiTFB31RPS6QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTokBMADL5ABpwNSCTyZk0NpXEBXdEJpREmTlgBu6AMLExAUSKz4ZGZnmKRRWHvjJpYOQuG0SsWZmjoAsvUTsAZvSoJE5KkPCwACayGOwwCBFEAFZkFrQR0RgASpywqLIExHFWkeiCzhwkXlEx6ACSRHhYsH6m5hWiANbIiAAyyABGWgAW6NCd7I5pUP6wHtq6yGLojVr0JMhETA0AYmjoAHL08JyTZqEiS3n0TZHVmadtF7RWAKpE0KPj6JENpQAePwAgtBPCQTA5zsIAL4WSDof7QfKldgAbQ6JXQAH0MrVUh0AFQEgD0BIAdE0xBSyMIALogaFAA)

This issue doesn't really concern `no-unnecessary-condition` anymore but do you think it should be reported to typescript ?

**Comment by Josh-Cena** [comment]
@Xavier59 This is a very commonly reported limitation of TS: it doesn't track indexed access where the indexed expression is not a constant. Tracking that introduces too much performance penalty.
