### ISSUE TITLE
Docs: how to treat JS files as JS instead of TS?

### ISSUE THREAD

**Issue by kkmuffme** [typescript-eslint/typescript-eslint#7106]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

It seems JS files are treated as .ts files and I don't know how I can fix this.
I know it's possible, bc I found a playground link where it works exactly as I want it to:

What I have:
https://typescript-eslint.io/play/#ts=5.1.3&sourceType=script&code=LAKAxg9gdgzgLgAgGYQggvAg9AKhwgATgE8AHAUwQG8BXKAayggHcoBfBHLBACgCkAygHkAcgDpSAQwBOMcjwDkkmABNlKhQEpNAblCRYiAEYyMCQaIky5i9eq16QQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0URNGgdokcGAC+ITUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUgBDTrADuAKWFhREqbWh9BKimsxipAXxDGgA

What I want:
https://v6--typescript-eslint.netlify.app/play/#ts=5.1.3&fileType=.js&code=LAKAxg9gdgzgLgAgGYQggvAg9AKhwgATgE8AHAUwQG8BXKAayggHcoBfBHLBACgCkAygHkAcgDpSAQwBOMcjwDkkmABNlKhQEpNAblCRYiAEYyMCQaIky5i9eq16QQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tieQEMAZolp9kySgHMmAW0Qt0URNGgdokcGAC%2BITUA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDUgBDTrADuAKWFhREqbWh9BKimsxipAXxDGgA&tokens=false
(I found it similarly in https://github.com/typescript-eslint/typescript-eslint/issues/7029#issuecomment-1547805045)

My tsconfig file contains allowJs/checkJs true.
How do I get typescript-eslint to work like in the 2nd example from playground, to respect JS @type declarations?

Here's my testing tsconfig file

```
{
    "compilerOptions": {
        "typeRoots": ["/some/path/node_modules/@types"],
        "target": "es2021",
        "module": "commonjs",
        "allowJs": true,
        "checkJs": true,
        "noEmit": true,
        "strict": true,
        "useUnknownInCatchVariables": false,
        "noImplicitThis": false,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "strictNullChecks": true,
        "noUncheckedIndexedAccess": true,
        "allowUmdGlobalAccess": true,
        "skipLibCheck": true
    },
    "files": ["example.js"],
    "include": [
        "some.d.ts",
        "foo/*"
    ]
}
```

### Affected URL(s)

Depends on the answer where it would fit best.

**Comment by bradzacher** [comment]
Oh, sorry - I did misunderstand.
In that case you need to type all of your JS code explicitly using JSDoc - that's the only way to make it work. TS will type everything in JS as `any` by default and it will not warn you about untyped variables or untyped imports.

It's definitely doable - it's just not easy. There's a small movement of people who are doing this because it saves a build step - it just requires a lot more discipline!

You can use eslint overrides to turn type-aware linting on for JS files

**Comment by bradzacher** [comment]
> But for some reason typescript-eslint treats it as .ts file and ignores the @type comment.

Our tooling does not "treat it as a TS file" - it passes the extension through to TS and it does its own thing with it.

If you're seeing errors it's just because there's something missing in the setup and the file isn't being correctly checked with all types being resolved. It's hard to provide generic advice on this though as it depends entirely on the project setup.
