### ISSUE TITLE
Bug: no-unnecessary-condition and strict-boolean-expressions - 

### ISSUE THREAD

**Issue by FiniteLooper** [typescript-eslint/typescript-eslint#7118]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.1.3&sourceType=script&code=C4TwDgpgBA8gRgKwgY2AaQiKBeKBnYAJwEsA7AcygB8pSBXAWzgkOvxCYHsAbAbgFgAUEIgAPMJ0LAoyTqQJRyhTnTAAhLLgA8aKGOARSAEzyxEKdJgA0UACoBJAwz2iDx0wCUUkozpvwkVAwQAD4QgApiJzwALjtHCAYAbQBdGwBrTDi0AEo4r1lCXwCLYJsHJ1SQnBChKCgoxLwAOkIIIzpkCC0Cny0SoOt4ypSw8Lr6qHC2vDpuYHzvIv7zQZByhOTRm0aGOIrEnJqoAG8Jyag24DpCUlPzi6hm55m54CsHi6TdpMyQFJScSSz2a0wgs3m30qfwB1BoqRyOycaU+UAAvg80R9BBcThicVAcrwgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK+SpPRRE0aB2iQANOGx4ipZBWp0GzNsnxUydAEYcOSIU3oAPYtEHymqDJGWr12gC+IIFAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDAruuGAL4g9A

### Repro Code

```typescript
type ObjectKey = string | number | symbol;

export const groupBy = <K extends ObjectKey, TItem extends Record<K, ObjectKey>>(items: TItem[], key: K): Record<ObjectKey, TItem[]> =>
  items.reduce<Record<ObjectKey, TItem[]>>(
    (result: Record<ObjectKey, TItem[]>, item: TItem) => {
      return {
        ...result,
        [item[key]]: [...(result[item[key]] || []), item],
        //Lint Error Here ^^^^^^^^^^^^^^^^^
      }
    },
    {}
  );
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/no-unnecessary-condition": "error",
    "@typescript-eslint/strict-boolean-expressions": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strict": true
  }
}
```

### Expected Result

I expect no lint errors in this code.

### Actual Result

It reports errors for the `(result[item[key]] || [])` statement.  The "fix" it to remove the ` || []` so that the statement is: `(result[item[key]])`.  This will satisfy ESLint, but it causes the code to break.

### Additional Info

Here is [a TS Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgKwgY2AaQiKBeKBnYAJwEsA7AcygB8pSBXAWzgkOvxCYHsAbAbgCh+EAB5hOhYFGSdSBKOUKc6YAEJZcAHjRQRwCKQAmeWIhTpMAGigAVAJJ6GO4XsPGASinEGtV+ElQYIAB8QQAUxA54AFw29hAMANoAulYA1pgxaACUMR7ShN5+ZoFWdg7JQThB-FBQEfF4AHSEEAZ0yBAaeV4aRQGWseVJIaE1tVChLXh03MC5ngW9pv0gpXGJw1b1DDFl8VlVUADeY+NQLcB0hKTHp2dQjY9TM8AWd2cJ2wnpIElJMQlHo1JhBprNPuUfn9qDRklktg4Uu9xgB6FFQACiAGUADJkOb3QlE4kAPTJZPGAFooB4GJwAG7QYAAC2IxmAnHwAENgGyAGZYbj4lhWOB0SQs6DSAzQOAtLmpYxcpXnUEvACEyIAvnctW8zkcdbUsgJBKBIFAAAosPAyHDHfDAHkQGIEEgUKykLkMF2O93kKxc8i++hMFi8KA66SySQGHlcmLWwi20jJe0JMZHR3OmIAIgAcgBhXOe72+3MqThwEtQIO+gDMAHZI-qHQQc1BcwBxACCNa9PrzheZJDwNbrMXrAA4W5ns3o81ji6XB52AFKcCDj4OTgCcs9qWfbC87hb7K-La+I3G4299ABYAAwHttOk-d8+0Mt5tdc0hbwMdyge8AEYXyPN9yyLftv07LE6AA2sgPvAAmcD53LXsYNXXMe1vQCH3rdDj0wz8B3LABZLlhDvGJ73vYjILzaCLzzFRr3wpCHwAVlnJJTWjW1uAgRpuE4chQgUJRVBAUI4ydKwAHISMUrIsiAA) to see how that code functions and the data it produces.  Notably, you can go there and remove the ` || []`, which is what the lint rule wants me to do, and see how that breaks the code.  Compare the output before and after doing this

**Comment by bradzacher** [comment]
The rules are reporting as expected because they are solely driven by types.

Your types declare the type of `result` to be `Record<ObjectKey, TItem[]>`
So that means the type of `result[item[key]]` is `TItem[]`. This type is **never** a falsey value.
As the type is never falsey, based on the types `|| []` can never be hit and is dead code - hence the report from `no-unnecessary-condition`.
As the type is only ever an object-like type (an array here), your config specifies this case is disallowed in a boolean location - hence the report from `strict-boolean-expressions`.

At runtime though your values don't match your types - you have potential `undefined`! This is solved by the [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) TS compiler option, which unions `undefined` into the read types (but not the write types) for safety.

That being said - even with the flag there is an unfortunate side-effect of the generics you're using - TS doesn't know how to evaluate them properly and thus reports the wrong types to us.
`result[item[key]]` should be typed as `TItem[] | undefined` with the flag, but it's not - instead it's typed as `Record<ObjectKey, TItem[]>[TItem[K]]` - which is essentially saying "it's too much effort to resolve these types so I'm not going to bother" and it avoids evaluating them until it is forced to.
It does do this implicitly due to the assignment - but that's not something we're able to see/access from the lint rule code (a limitation of the TS APIs).

If we instead introduce an intermediate variable we can force TS to do the right thing:
```ts
const itemKey: ObjectKey = item[key];
result[itemKey];
```

[Here is the working playground](https://typescript-eslint.io/play/#ts=5.1.3&sourceType=script&code=C4TwDgpgBA8gRgKwgY2AaQiKBeKBnYAJwEsA7AcygB8pSBXAWzgkOvxCYHsAbAbgFgAUEIgAPMJ0LAoyTqQJRyhTnTAAhLLgA8aKGOARSAEzyxEKdJgA0UACoBJAwz2iDx0wCUUkozpvwkVAwQAD4QgApiJzwALjtHCAYAbQBdGwBrTDi0AEo4r1lCXwCLYJsHJ1SQnBChKCgoxLwAOkIIIzpkCC0Cny0SoOt4ypSw8Lr6qHC2vDpuYHzvIv7zQZByhOTRm0aGOIrEnJqoAG8JyZk5BV3guIHLTQbKzJAUgUEL+rbgOkJSU-On2awJmc2AVkBFySuySLxSKTiSWBzWmEFm82hTmCKWoNFSOR2TjSkKgAF9AaSIR9JidydScrwgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK+SpPRRE0aB2iQANOGx4ipZBWp0GzNsnxUydAEYcOSIU3oAPYtEHymqDJGWr12gC+IIFAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDArugDTg2RGwAqkWgALdNADW6ACYBJIjPQAPWQEFo0dCTKUO6XgF8QhoA)
