### ISSUE TITLE
Consider keeping parserServices.hasFullTypeInformation for another major version?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7124]
## Overview

Coming over from https://github.com/microsoft/TypeScript/pull/54693#discussion_r1235548917: in v6 we removed `parserServices.hasFullTypeInformation`. Consumers can now check if `parserServices.program` exists. But, there are a few existing external consumers that rely on it:

* [Sourcegraph search for `parserServices.hasFullTypeInformation`](https://sourcegraph.com/search?q=context:global+parserServices.hasFullTypeInformation+-file:.*node_modules.*+-repo:npm*&patternType=standard&sm=1&groupBy=repo): 23 results
* [Sourcegraph search for `parserServices?.hasFullTypeInformation`](https://sourcegraph.com/search?q=context:global+parserServices%3F.hasFullTypeInformation&patternType=standard&sm=1&groupBy=repo): 4 results

If we do nothing and keep it removed, the referenced plugins/etc. may not work out-of-the-box with v6. I'm happy to send PRs over to help them upgrade, but that might be kind of a pain. And we don't know what _internal_ code will break.

Proposal: how about we add it back in as a `/** @deprecated */` property, then remove it in v7? It's not much to add/change on our end. Thoughts @typescript-eslint/triage-team?

**Comment by JamesHenry** [comment]
Sounds like a good plan to me!

**Comment by bradzacher** [comment]
Our parser services weren't ever a documented feature - the only way we supported and documented using them was via our utility functions. It had types, but that's because TS doesn't have any way to define an opaque type.

Some of those are incorrect usages of the API and should instead have used our recommended and documented `getParserServices` function. Eg there's a lot of cases like `if (! hasFullTypeInfo) { silently don't even create a rule }` which is an anti-pattern.

I personally don't think we should keep it around. It doesn't represent any information that exists any more (it will always be true, or it won't exist)

**Comment by Josh-Cena** [comment]
I don't think we should push it back further, either. The migration effort sounds low and breaking changes are meant to be breaking changes (adding `@deprecated` is not). If you want to, you can start adding `@deprecated` now before v6 ships.

**Comment by JamesHenry** [comment]
Consider me convinced!

**Comment by JoshuaKGoldberg** [comment]
👍 I'll go ahead and file issues on downstream repos found by the OP's [Sourcegraph search for parserServices.hasFullTypeInformation](https://sourcegraph.com/search?q=context:global+parserServices.hasFullTypeInformation+-file:.*node_modules.*+-repo:npm*&patternType=standard&sm=1&groupBy=repo). It's a pretty straightforward fix so I feel comfortable contributing to them if needed.

**Comment by JoshuaKGoldberg** [comment]
Actually, wait - the backwards compatibility story here isn't great. Right now `parserServices.program` exists even if `parserOptions.project` wasn't configured in the ESLint config. So for the community configs, switching from checking `parserServices.hasFullTypeInformation` to `!!parserServices.program` isn't backwards compatible for v5. 

This is actually quite relevant for some community configs. For example, `eslint-plugin-sdl` behaves differently based on whether there is type information (e.g. see https://github.com/microsoft/eslint-plugin-sdl/blob/31d6d6802499c22f948e780ac573610d248b78a2/lib/ast-utils.js#L40 and other functions in that file).

I agree that if the migration effort were low then this would be a definite "break it and let them know". But since the configs will probably want to support v5 for a little while, and it's very little effort on our end to keep it, I suspect we should actually push back to v7 after all. Thoughts?

**Comment by Josh-Cena** [comment]
Is it possible for configs to detect the TS-ESLint version and branch logic?

I get the compatibility story of "config use the legacy API to support both v5 and v6, and then use the modern API in the next major to support both v6 and v7"—that also makes sense.

**Comment by bradzacher** [comment]
I guess the thing is we've always given the advice that you shouldn't do progressive enhancement of lint rules depending on if type information might be there.

Thats the same hard-and-fast rule that we have taken with every single one of our lint rules.

The reason we take this line is because config is hard and if you just silently enhance a rule with type information but the user misconfigures it how can you alert the user to the misconfiguration?

Either use type info or not - never "maybe use it if it's there".

Also as mentioned - this wasn't ever a documented usecase - so should we be so cognisant of breaking an undocumented, not recommended way of using our API?

I get your concern - for sure! But there's sadly no backwards compatible way to remove this. At some point we need to rip the bandaid and downstream consumers will need to figure out how to write their own backwards compatible code.

**Comment by JoshuaKGoldberg** [comment]
> we've always given the advice that you shouldn't do progressive enhancement of lint rules depending on if type information might be there ... this wasn't ever a documented usecase - so should we be so cognisant of breaking an undocumented, not recommended way of using our API?

On the flip side, I don't think the public docs website ever explicitly mentions the advice against progressive enhancement. Filing an issue: #7158

At any rate, 👍 I can close this out again and just post an informative message linking to this thread in the downstream repos. Thanks!
