### ISSUE TITLE
Enhancement: add type for `data` of report message

### ISSUE THREAD

**Issue by Max10240** [typescript-eslint/typescript-eslint#7141]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Suppose I am writing a rule that detects the number of lines in the current file, and if the file is more than 100 lines, reports an error to the user and tells him the exact number of lines in the current file: 
For now, I can't tell "createRule" about the type of "data", so type checking and autocompletion won't work. I can only constrain the type of "data" using something like "satisfies":

```typescript
interface IMessages {
  tooLargeFile: {
    lines: number;
  };
}

export default createRule<[], keyof IMessages>({
  name: '...',
  // ...,
  create(context) {
    return {
      Program(){
        if (context.sourceCode.lines.length > 100) {
          // ...
          context.report({
            messageId: 'tooLargeFile',
            data: { 
              lines: context.sourceCode.lines.length,
            } satisfies IMessages['tooLargeFile'], // with type checking and autocompletion
          })
        }
      }
    }
  }
})
```

It would be great if createRule could do this automatically, such as:
```typescript
export default createRule<[], IMessages /* interface */>({
  name: '...',
  // ...,
  create(context) {
    return {
      Program(){
        if (context.sourceCode.lines.length > 100) {
          // ...
          context.report({
            messageId: 'tooLargeFile',
            data: { 
              lines: context.sourceCode.lines.length,
            }, // no need to use `satisfies`
          })
        }
      }
    }
  }
})
```

### Fail

```typescript
export default createRule<[], IMessages /* interface */>({
  name: '...',
  // ...,
  create(context) {
    return {
      Program(){
        if (context.sourceCode.lines.length > 100) {
          // ...
          context.report({
            messageId: 'tooLargeFile',
            // type error(property 'lines' is missing)
            data: { 
              
            },
          })
        }
      }
    }
  }
})
```

### Pass

```typescript
see above.
```

**Comment by Max10240** [comment]
If this proposal is needed, I can try to create a PR for it

**Comment by Max10240** [comment]
as sample: https://github.com/typescript-eslint/typescript-eslint/pull/7142

**Comment by bradzacher** [comment]
We thought about this way back when we first implemented the types!
https://github.com/typescript-eslint/typescript-eslint/blob/f74862cbfb5c74ba958ba27d1ea2ca5046821818/packages/utils/src/eslint-utils/RuleCreator.ts#L51-L58
But we thought about it as an extra bit of safety that one could opt into (eg an additional generic parameter) rather than the default way to do things.

The issue was the types were already super complex with 4 generics and getting things to infer just right, well, didn't work well.

Additionally we didn't really like the idea of making users define another thing to keep in sync withthe real code. Defining the placeholders separately to the message strings AND keeping them in sync - it will be a cumbersome. I mean it's already kind of cumbersome already to have to add a message to the config AND add a message to the `TMessageIds` union - it'll be more annoying to have to remember to add the placeholder to the message string and then add a property to the message object for the message string.

We also don't want to get into a situation where people do things like
```ts
type TMessages = {
  myMessageId: {};
};

/// ...

messages: {
  myMessageId: 'hello {{placeholder}}',
}

/// ...

context.report({
  messageId: 'myMessageId',
  data: { placeholder: 'oops' },
});
```
[Which is valid code](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgshAzoghgcyVAvFA3gKCigFsQFl0IBJAEwC48BfAGn0YG598aIBjAGxQAnaADMArgDtewAJYB7SVBFh5Q4AB54SVBlpQIAD2ARJNRFADWEEPNGxyupAD4AFMLQMCRYjsq0GbQo9GlYiGhRgFEDHSkQAbSCnWgBdVkYASgYAN3lZGk58FTVgV28SPxCGAHJSWJDqsKgIqK9CIigwQV4IAAt5fh4hGsb2ljYMziA) because any object is assignable to the `{}` type thanks to structural typing!

It would make it *really* easy for people to slip up, add a placeholder to a message that *DIDN'T* have one, then have a false sense of security!
Though in testing we could work around this by doing some type wizardry like
`data: {} extends TMessages[TMessageId] ? Record<string, never> : TMessages[TMessageId]`
[playground](https://www.typescriptlang.org/play?ssl=10&ssc=3&pln=10&pc=89#code/C4TwDgpgBAKgshAzoghgcyVAvFA3gKCigFsQFl0IBJAEwC49CioAzAezYcWACcBLAHZoANEwC+ooqXKoMtAOp9gACzYBXYAAUANigDGEGqu00IPBrigT8YgNz58pvbp7QWagXuB82AqK7A2HmAAHngkWWoaKAgAD2AIARpEKABrCBA2FlgZSkQAPgAKFB40CyZiCMpaBnCKORpJKBoUYBQLMRj4xOScqoxEAG06yNoAXSgAfigAJQg9IJoQ7n4hYSgBCAA3M3yoWtyB4cOosdExAEoGLbY+Gnt8AKDgQoIpfqiGAHJpD9ovpotNrlZisDjfAFMIhgXQGYymcxQL6QojWS72J7BV4VP70JG-epRRQqdRaWGGeFmFHNVrtRig9icJHUtEXexAA)

Note: as soon as you add one placeholder, then it's fine forever because TS will do excess property checks for you.

Perhaps there's some wizardry we can do with template literal types to make this work? I'm not exactly sure if TS is going to be fully able to do what we want without some CRAZY complexity.

---

That's a lot of ramblings...
I guess what I'm trying to say is that we're definitely open to this idea, and always have been! We've just been waiting for TS to get to a point that we can do it without adding a heap of overhead to the user maintaining the rule.

**Overhead for the sake of a little bit of type safety isn't necessarily a good thing!**

The things stopping us from pushing forward with this:
1) we need a way to validate that the placeholders *all* appear in the message string
2) we need a way to validate that the string's placeholders are *all* defined in the types

If we have solutions for this - then let's go!! - we can look at adding this in for the next next major release (v7). But without those solved - the manual labor involved in the types makes them less useful overall.

I say that because there are lint rules which are able to do it with better precision than what we could do with types:
- [`eslint-plugin/no-missing-placeholders`](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/no-missing-placeholders.md)
- [`eslint-plugin/no-unused-placeholders`](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/no-unused-placeholders.md)

The one caveat to these rules is that they can't validate `data` within a test file, nor can they validate if you split the rule across files. But those are a minor points compared to the safety they do bring.

**Comment by Max10240** [comment]
> The things stopping us from pushing forward with this:
> we need a way to validate that the placeholders all appear in the message string
> we need a way to validate that the string's placeholders are all defined in the types

[TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsghsAxgCwKoDtgEsA2BhHAewGcIAeAZSggA9gJ0ATYqY4AJy3QHMAaKAEoRiAVxzBqdBsygBtUYkTDiALigAjQoRwQ46fgFsEKCIzVtOPfuwhGu5jl24BdKAF45AMzg5S-AOT+-BTOAHzuUFS09EwsAAYAvgkAJADeXJ4Q7IK2cFwJcVAAUFClUAD8chwiEPxCouKyAIzOdblcriVlalFSsVBxaRlZUABiKenomdlCdugFXWVllfBIaJi4BCTks3n6Xj5+A2n1YsDNzhPjcfzoEABuWWGLS1Bqst6+tVB3j+y3DyeAG4iqDQJAoABxCDAIQARxEWBsjAAIgg4GQACqSGIyCxOfho4BwADSEBAOOkLHxPAivyy-AACjZ7lhCCIWNEqaxHLSPIFwh5sVz+oNJtMxhNhjN2vM4i9KsyHmyOZTRWkadwEqlUvLXstYMZ1th8ERSFjwiKZNLBGqZLJNNpdPtNfxNc4XvrSpUBLIAAyuK0saoQT1epaVaGwiAIpGmIkY30AJlaUATZIpAB9BBd+GKlaz2cQJr6WkkCqEw+HSu90+TA317fT2K4fRBEIR2IwyMzCJB2KAMwC-uE1Kk5IyoFw0+iM841CJ0ABrdCEADu6CgCSrrzUzZ3aij8MRyITZF2XEJs-JebSBZVxbS10rS1r15ADdxLFkzdbOQ7XY9uwfZZION4-IC7CjlA46yJO051h+C7LquG5biCRRcPQ7DeEoORgJ2wAAJJTIQWJ2tSvLcOEqQvAYyhwNwEBqJiIJLIw6KHjCx5xqi6IWiC25FJ4i6INghCbjYBEDuRQY8pY1EABQZIQahCNJxGkRaACUMGgkJRQAPSGe4bhmeZFmWVZ1lmVAmIAKIUNiNkua5FlFOC0CYn6ESrCgGAmls5r+J4WhJDYcwALSav4oRAlAxlVOwNT8AARKFhCpWlEV7NFVGpR68q0UscDISu67oGxZREQAggYABCZWoZVRQJFAABk-6dt2vb9mBIDDlklbyp5dlNBER4xie8b8f4cBTqoMGpHAST8OoC1jqktUNUksUYVJhGKcVZT0cQxCMcxUBzUELwccSY4JLwrXaSCB0DkddEMUxaj+DqK0JDd7GcTBUClVA42Pc9+0QBpH1LKd53fVdcCA2UiUAALAMQkW0JAYk4+wwHZJFdngNA-joCIBjqFk-gLT8hASHAZ1YNw6BwOoOhQMAhDc2TV3Nv4AB0ilJgAzEmSbabdwPjmDENPQkL1FG9wBwydX2Xb9y27U9SwY1jOM0HjwAE0TUAkwA8uoABW7YSDgWDYT4UBGBSEk4BSxB41gngUuVaFgMBfVYMI-B6IwV3qHTjCEMIDMSLQWBsFOm6jb9oNNRV8UAzL90g-La1qArUNFEAA) Can this help？Or maybe, in the wrong direction?😄

**Comment by bradzacher** [comment]
That's a great start as it let's us infer the place holders from the generics!
I knew template literal strings would let us do it!

The complicated thing is doing it the other way around (validating defined placeholders exist in the string) because there's no pre-defined ordering and placeholders can appear multiple times in a string. I don't think it's possible to do!

The other thing we need to wait for is the partially inferred generics feature in TS. As mentioned - if you have a default generic then TS will use that instead of inference. Which causes a problem for rules with options! Those rules need to pass one generic - but if you pass one generic you need to also pass all non-default generics.
So without partially inferred generics the user needs to manually supply the message ids and the placeholders - which is why we need this inverse check too!

With partially inferred generics instead we can ignore the problem because people can just write code like: `createRule<Options, _>(...)` which tells TS "use this type for the first generic and infer the second generic" - which means no more explicit types to keep in sync!

**Comment by Max10240** [comment]
> The complicated thing is doing it the other way around (validating defined placeholders exist in the string) because there's no pre-defined ordering and placeholders can appear multiple times in a string. I don't think it's possible to do!

how about this?! [TS playgroud](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsghsAxgCwKoDtgEsA2BhHAewGcIAeAZSggA9gJ0ATYqY4AJy3QHMAaKAEoRiAVxzBqdBsygBtUYkTDiALigAjQoRwQ46fgFsEKCIzVtOPfuwhGu5jl24BdKAF45AMzg5S-AOT+-BTOAHzuUFS09EwsAAYAvgkAJADeXJ4Q7IK2cFwJcVAAUFClUAD8chwiEPxCouKyAIzOdblcriVlalFSsVBxaRlZUABiKenomdlCdugFXWVllfBIaJi4BCTks3n6Xj5+A2n1YsDNzhPjcfzoEABuWWGLS1Bqst6+tVB3j+y3DyeAG4iqDQJAoABxCDAIQARxEWBsjAAIgg4GQACqSGIyCxOfho4BwADSEBAOOkLHxPAivyy-AACjZ7lhCCIWNEqaxHLSPIFwh5sVz+oNJtMxhNhjN2vM4i9KsyHmyOZTRWkadwEqlUvLXstYMZ1th8ERSFjwiKZNLBGqZLJNNpdPtNfxNc4XvrSpUBLIAAyuK0saoQT1epaVaGwiAIpGmIkY30AJlaUATZIpAB9BBd+GKlaz2cQJr6WkkCqEw+HSmpUnJGVAuGn0RnnGoROgANboQgAd3QUASVdeanp7GHaij8MRyITZF2XEJLfJebSBZVxbS10rS1r9cbA-T5LbUA73b7A4SINBXHo7G8ShyYEI7GAAEkpoQsXbqby+GmfygVIEnCVIXgMZQ4G4CA1GxAAyKAADUfCwRgEFMGBIOg78EOA-hO3JQhPAAhDNVCEEljQ4k1BRKAEKnGMZ3jdEcKAkCQSHIpwWgZCcFQ9DGEw4hiCg8helxX9LH-ElALIiIAAoZKDU8ux7ftigjSJALFTVtVSNISXLDU-wWcNKhDCcoE+UgXlHQF2AASkAkMKi0uy-mvTwO0QbBCAHGxn1fb9lNdADlOA0J5IyQg1CEQL30-LFCVCJywKKTiigAeky9w3Dy-KCsKoriryqBMQAUQobESpq2qCq48BoExP0IlWFAMBNLZzX8TwtCSGw5gAWk1fxyKgbKqnYGp+AAIl6wgZtmga9mGv8Zo9eUwKWOB21Ui8KLKN8AEEDAAIV289+w4uickQF9GDIZlCEgV8QAzAE-kreVuLKpoIgY2NZxY-w4EbVQgNSOAkn4dQwdrVJjrOpJRpBH7MSTCJeP4+hBKw8gQbhiGoYSGHCZ1RHTuRgI4H8KBs38CmUdBAKX2AeStrKCDhNEtQQaCF4qJ2tjeHShyQRZ192fAvHeZ1Yn+co9E9yFv6SdF8WIHiqWli5kToN50GsHBuXoY0MmEZOymEgAOigKC9lJo34YpqmBaVoDhxVkXwwptQmm9r0XjVhIxaKCW2Y50pdZ5qACadonTdh+Pyct12lgmgABYBiEG2hIB83P2HYF8oEG0onpe0BY8ZsGoAMI3iCcA8oB+-w6yF9ARAMdQsiBQdafUEQJBsQHTGb1v24utT0D732VMumf++tt3qI98MvaDkWQ5BCa6r3kqkJQqjoCEvWmq0XL96v+rw+1spM+z3OaHz4BC+L7Iy8xRrY5G2uewkOAwksDcHQHAdQOgW6EBbt-fwY5-DLx1jLWONMA6lEFsrP2g4t6h1vpHcaOUs45zzhAAuWR35lRgb-I2PxCAAKASAsBEDgBQNbnAhBnMkFt0hmnMo6CgJ2z9jDTBwdQ5AA)
At the very least we can verify `{message: '... ’, data: {/*… */}}`(To verify `{messageId: '... ', /*... */}`, other efforts may be required), just like the two ESLint plugins do:
> [eslint-plugin/no-missing-placeholders](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/no-missing-placeholders.md)
[eslint-plugin/no-unused-placeholders](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/HEAD/docs/rules/no-unused-placeholders.md)

**Comment by Max10240** [comment]
> The other thing we need to wait for is the partially inferred generics feature in TS. 

If that's acceptable, we can use "currying" to get around it.  We can offer both ways, like:
```typescript
// use currying
createRule<TOptions>()({
  // ...
  create(context) {
    context.report(/*...*/);
  }
});

// or normal
createRule<TOptions, MessageIds>() {
  // ...
}
```
just like zustand did: [zustand](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md#:~:text=Why%20that%20curring)

**Comment by JoshuaKGoldberg** [comment]
Yeah that playground is ... a lot 😄. +1 that the rule types are already pretty complicated. I personally am not (yet?) of the opinion that the complexity is worth the added type safety. Especially given that folks often are verified by [`eslint-plugin/no-missing-placeholders`](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/f5f377f07991b7a587825c7b811d310c3ea048ad/docs/rules/no-missing-placeholders.md) + [`eslint-plugin/no-unused-placeholders`](https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/f5f377f07991b7a587825c7b811d310c3ea048ad/docs/rules/no-unused-placeholders.md) and/or rule tests.

Marking as `evaluating community engagement`, which for this specific context is our friendly way of saying _"we probably won't wnt this unless a bunch of people ask for it with strong reasons why it should be done"_.

**Comment by JoshuaKGoldberg** [comment]
It's been >6 months and this issue hasn't been positively mentioned in other contexts. Closing this out as a wontfix on our end.

If anybody comes across this later and wants it: if you can figure out a way to make the types great, please do post a new issue with it. But keep in mind the constraints mentioned in this thrad. If it's not better than the lint rules from https://github.com/typescript-eslint/typescript-eslint/issues/7141#issuecomment-1716263421 then there's not much use.

Thanks for the discussion, all!
