### ISSUE TITLE
Bug: @typescript-eslint/unbound-method doesn't work with object methods.

### ISSUE THREAD

**Issue by dvun0g** [typescript-eslint/typescript-eslint#7178]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://github.com/dvun0g/issue-eslint-typescript-unbound-method

### Repro Code

```typescript
const object = {
	val: 1,
	method: function () {
		console.log(this?.val);
	},
};

class Class {
	val = 1;
	method = function () {
		console.log(this?.val);
	};
}

object.method(); // 1 | Not Error

const testUnboundFunctions = function (func) {
	func();
};

const { method: method1 } = object;
testUnboundFunctions(method1); // undefined | Not Error
testUnboundFunctions(object.method); // undefined | Not Error

const { method: method2 } = new Class();
testUnboundFunctions(method2); // undefined | Error
testUnboundFunctions(new Class().method); // undefined | Error
```

### ESLint Config

```javascript
module.exports = {
	parser: '@typescript-eslint/parser',
	parserOptions: {
		ecmaVersion: 2020,
		sourceType: 'module',
		project: './tsconfig.json',
	},
	plugins: ['@typescript-eslint'],
	rules: {
		'@typescript-eslint/unbound-method': 'error',
	},
};
```

### tsconfig

```jsonc
{
	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"strict": true,
		"esModuleInterop": true,
		"skipLibCheck": true
	}
}
```

### Expected Result

I expected to get errors when passing a method from an object to the ```testUnboundFunctions``` function.

### Actual Result

I got errors only with classes but not with objects.

### Additional Info

The repository where the error was reproduced: https://github.com/dvun0g/issue-eslint-typescript-unbound-method.
To reproduce the error, execute: ```npm run lint```.

**Comment by bradzacher** [comment]
This is working as expected.
The rule is powered solely by types.

The type of `new Class()` looks like `{ method: () => void }` - which we interpret as a "bound function property". OTOH if you declared `method` as `method() { ... }`, then the signature would look like `{ method(): void }` - which we instead interpret as "an unbound method".

This does mean that we cannot tell the difference between `method = function() {}` and `method = () => {}` i.e. we cannot tell that a function property is not auto-bound.
This is an intentional hole in the rule though because there's no reason to use `method = function() {}` over just `method() {}` - so it's not something people do in modern JS.

An object type defined like you specified is typed in exactly the same style - if you define `{ method: function() {} }` - the signature becomes `{ method: () => void }`, but if you instead use the method syntax `{ method() {} }` then the signature would similarly become `{ method(): void }` - [and the rule works as expected](https://typescript-eslint.io/play/#ts=5.1.6&sourceType=module&showAST=es&code=MYewdgzgLgBCBGArApsWBeGBvAsAKAEgA3AQwBsAuGARgBp8CBbZKACxABMAKASmwYKhIIMsgB0ZEAHMubAJYQxpMjwDcDAL708G9XnzAyJCBBgBhIyf6FlMTNT1MW7DnZgAzAK5g0c8DF5rAkFwCBFxSRl5RWU1TT0NfHwEFDQxZjZOXlUYAHpcmhgAHxgAORBYAFEAJ2qQaqS8IWgYKGRoAFUweBBvDgAxb19Qty8fKD8wALHgPlxCGez8XUbm2CwYDJcqLc5qGA03FNQoPTbO7t6wAaGJ0K5djmo1PIK+5Hc5MGRXEvKq2r1fDnKBdHp9QbjSYQLjHNKPF75GDvT7fX5lCowGp1Br6JqhdabZycHbEjgAJgObm+AHdzJYYXE8CCwVcblD7o9yYi3tcPl8fsUsYDcSzLhDbtCuLT6cZGekyTzkXzUYKStj6kA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6WJgIwHsOATWgFtE+ABbc+6KImjRu0SODABfEMqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA).

---

However you should 100% be avoiding using `this` inside objects because TS types `this: any` in all object functions. So you are writing completely unsafe code!

In modern JS you should not write pseudo-classes, and should instead only write true classes.

**Comment by dvun0g** [comment]
Thanks for the explanation.
