### ISSUE TITLE
Docs: Clarification of configurations

### ISSUE THREAD

**Issue by marekdedic** [typescript-eslint/typescript-eslint#7195]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Reading https://typescript-eslint.io/blog/announcing-typescript-eslint-v6 and looking at https://typescript-eslint.io/rules/?supported-rules, I am confused about the new configurations, more precisely, which configurations are subsets of others

- is "recommended" a subset of "strict"? (I think yes?)
- is "recommended-type-checked" a subset of "strict-type-checked"? (I think yes?)
- is "recommended" a subset of "recommended-type-checked"? (I think no?)
- is "strict" a subset of "strict-type-checked"? (I think no?)

### Affected URL(s)

- https://typescript-eslint.io/blog/announcing-typescript-eslint-v6
- https://typescript-eslint.io/rules/?supported-rules

**Comment by bradzacher** [comment]
@marekdedic does this doc clarify your question?
https://typescript-eslint.io/linting/configs

**Comment by bradzacher** [comment]
![Screenshot_20230712-010102.png](https://github.com/typescript-eslint/typescript-eslint/assets/7462525/e0cd55c9-9942-4598-9a6e-244aaf3810f7)

![Screenshot_20230712-005927.png](https://github.com/typescript-eslint/typescript-eslint/assets/7462525/bd251da9-d194-45fb-a074-e346d0ae3840)

![Screenshot_20230712-005940.png](https://github.com/typescript-eslint/typescript-eslint/assets/7462525/4d463528-9a36-4d59-93d7-6df2bb248d53)

What about these two sections just below...?

In contrast the stylistic sections do not mention they include other configs because they do not - aside from the type checked variant

![Screenshot_20230712-010158.png](https://github.com/typescript-eslint/typescript-eslint/assets/7462525/081a1a49-ff97-47c5-9c19-2fb8880426ff)

**Comment by marekdedic** [comment]
Hi, these do help and maybe I'm just lazy that I didn't read far enough, but I suspect that I won't be the only one :D

How about something like:
- `strict`: Contains `recommended` + additional strict rules that can also catch bugs but are more opinionated than recommended rules.

**Comment by JoshuaKGoldberg** [comment]
> I suspect that I won't be the only one :D

Heh, agreed. Although I wish people always read the docs in full, you're right that many don't. Accepting a PR to add just a bit to the descriptions in those six list items.

**Comment by JoshuaKGoldberg** [comment]
I'll just take this, it's been bugging me that I want to see a PR 😄
