### ISSUE TITLE
Rule proposal: prefer-enum-as-string-union

### ISSUE THREAD

**Issue by prcodes** [typescript-eslint/typescript-eslint#7270]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Disallow enums consisting of all string literals - prefer string unions instead. String enums are verbose and usually contain duplicate code (name and value are usually the same or similar). A string enum can usually be replaced with a string union which is a more modern TypeScript concept compared to enums. Additionally, the TypeScript documentation somewhat cautions against enums in their documentation.

https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#enums
https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums

Ideally this rule would auto-fix code by converting string enums to string unions.

### Fail Cases

```typescript
// Error - can be replaced with
// type Pet = "cat" | "dog";
enum Pet {
  Cat = "cat",
  Dog = "dog",
}

// Const enums with all string values should fail
// May not be able to auto fix this though
const enum Pet {
  Cat = "Cat",
  Dog = "Dog",
  CatDog = Cat+Dog,
}

// This should fail but may not be able to be auto fixed.
const cat = "cat";
const dog = "dog";
enum Pet {
  Cat = cat,
  Dog = dog,
}
```

### Pass Cases

```typescript
// Non-string enums OK
enum Pet {
  Cat,
  Dog,
}

// Mixed value types OK
enum Pet {
  Cat = "cat",
  Dog = 0xd09,
}
```

### Additional Info

Out of scope for this rule would be to convert enums to `as const` objects. I think that could be a separate rule.

**Comment by bradzacher** [comment]
https://typescript-eslint.io/linting/troubleshooting#how-can-i-ban-specific-language-feature

We are not looking to add rules that ban language features. 

There's a lot of FUD that's spread about enums that is rooted in misunderstanding of the feature. They are a good option that work much better than simple string unions or const objects for some cases.
Similarly string unions and const objects are both good options that work better than enums for some cases.

Interestingly its number enums that you should avoid due to their very unsafe behaviour thanks to their "flags enum" usecase (any `number` can be assigned to a number enum).

Applying a hard rule against them is overall harmful to the broader ecosystem and is not something we would want to promote from our project.

**Comment by Josh-Cena** [comment]
> They are a good option that work much better than simple string unions or const objects for some cases.

Wondering what case it is? AFAIC, string enums are the only case where you can absolutely replace it with a union and achieve the same semantics, because number enums are usually (if not always) used as bit flags and default (without initializer) enums are meant to be opaque.

**Comment by bradzacher** [comment]
Some quick points off the top of my head:

TS is slowly moving to a place where string enums are truly nominal types - which provides some nice guarantees in the type system that you don't get with union types.

It can also be nice with a number of cases to avoid widening to `string` - as the type will only ever widen to the enum.

Having a quickly referenceable namespace can improve DevX in some cases where TS may not be able to autocomplete a string literal (eg when writing out an anonymous object).

Having an referenceable namespace is nice for certain type operations. Without it you need to do things like `typeof union['type']` which can cause some typecheck perf impact.

Prevents accidental misspellings in cases where you're not using strictly annotated types.

Disambiguates code so it's easier to use a find/grep tool to find references. Also concretely identifies untyped variables in the codebase (see prior point about widening).

Provides concrete targets for IDE tooling (eg refactor renames) where string unions may be missed due to being anonymously typed - leading to more manual effort.

Having a type+value together as the same name is quite a handy thing that you cannot fully replicate with a string union or a const object without a lot of verbose boilerplate.
