### ISSUE TITLE
Docs: improve description for `no-dynamic-delete`

### ISSUE THREAD

**Issue by jtbandes** [typescript-eslint/typescript-eslint#7290]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The `no-dynamic-delete` description is a bit sparse and lacks a convincing argument for why the rule is valuable.

On Discord, I mentioned:

> [the description] mentions hasOwnProperty but this seems to work:
> ```
> > obj = {}
> {}
> > obj['hasOwnProperty'] = 42
> 42
> > Object.hasOwnProperty.call(obj, 'hasOwnProperty')
> true
> > delete obj['hasOwnProperty']
> true
> > Object.hasOwnProperty.call(obj, 'hasOwnProperty')
> false
> ```
> 

In reply, @bradzacher offered:

> ```ts
> function delete(thing, key) {
>   delete thing[key];
> }
> 
> function test(arg) {}
> 
> console.log(test.name); // "test"
> delete(test, 'name');
> console.log(test.name); // "" !?!?!?
> 
> console.log(test.length); // 1
> delete(test, 'length');
> console.log(test.length); // 0 !?!?!?
> 
> ```
> 
> A truly dynamic delete is dangerous because you never know what is being deleted - which can cause unintentional side-effects.
> 
> Consider cases where classes "hide" behaviour on instances behind underscore-prefixed names (or they just mark them as private in TS) - a dynamic delete might accidentally delete the private prop and cause some weird behaviour!
> 
> There's also weird stuff with non-writable properties in that they don't get deleted.
> EG delete instance.constructor does nothing!
> 
> Dynamic deletes can be dangerous as they can lead to "undefined" behaviour if you're not careful!
> 

It would be great for this (or something like it / derived from it) to be added to the `no-dynamic-delete` rule description to help people understand the rationale for the rule.

### Affected URL(s)

https://typescript-eslint.io/rules/no-dynamic-delete/

**Comment by bradzacher** [comment]
There's a lot of weirdness with `delete` - for example as seen above you can "delete" a function's `.length` property and it'll get reset to 0 and the expression will return `true`. However if you try to delete an array's `.length` property - nothing will happen and the expression will return `false` in non-strict mode - or it will throw an excepiton in strict mode!!!

There's also weird behaviour for some properties like a function's `.call` or `.apply` if you try and delete them then the expression returns `true` (indicating the delete was successful) yet the properties do not get deleted!

So if you don't know exactly what you're deleting:
- the delete might do absolutely nothing (eg a function's `.call`/`.apply`)
- the delete might reset a value instead of remove it (eg a function's `.length` or `.name`)
- the delete might throw an exception (eg an array's `.length`)

In general you should just avoid `delete` altogether in most code and instead opt for different data structures (eg if you're deleting keys - a `Map` is probably the better data structure to use).

**Comment by Josh-Cena** [comment]
To be exact: `delete` only works for own configurable properties. This is why it doesn't work with methods (they are defined on the prototype) or array length (because it's nonconfigurable). There are lots of gotchas if you use delete on specific class instances, but deleting from plain objects (a la using it as a map) is usually safe—even safer if the object has `null` prototype :)
