### ISSUE TITLE
Docs: no-extra-semi doesn't have formatting warning

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#7307]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The documentation for the `@typescript-eslint/no-extra-parens` rule is here:
https://typescript-eslint.io/rules/no-extra-parens/

At the top of the page, we can clearly see the formatting warning:

> We strongly recommend you do not use this rule or any other formatting linter rules. Use a separate dedicated formatter instead. See [What About Formatting?](https://typescript-eslint.io/linting/troubleshooting/formatting) for more information.

The documentation for the `@typescript-eslint/no-extra-semi` rule is here:
https://typescript-eslint.io/rules/no-extra-semi/

However, it does have have the warning. This seems like it is a bug, because when we use [Prettier](https://prettier.io/), it automatically removes superfluous semicolons, making this rule unnecessary. Thus, I believe that the warning should be shown in the same way that it is for the `no-extra-parens` rule.

The reason that the warning is not showing is because the `meta.type` for the rule is equal to `suggestion` instead of `layout`. (`no-extra-parens` has a `meta.type` of layout, so the warning shows.)

Thus, I recommend that we change the `meta.type` for the rule to `layout`.

### Affected URL(s)

https://typescript-eslint.io/rules/no-extra-semi/

**Comment by bradzacher** [comment]
`no-extra-semi` isn't a formatting concern though - it's a syntactic one!

[as you can see from this playground](https://typescript-eslint.io/play#ts=5.1.6&showAST=es&fileType=.ts&code=MYewdgzgLgBAHjAvDAjAbg0A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaRADwBdoBDQ5RAWwEt0p8AzVyAGnG0gAEyATwAOKAMbQGwssWTwGuMgHoCxclRr0mGSImjR80SDwC%2BIE0A&tsconfig=&tokens=false) - the extra semicolons ***change the AST***!

Unlike with extra parentheses where one may stylistically choose to add parens to manually disambiguate code - extra semicolons are not a stylistic choice - they are a correctness issue.

On the other hand the presence or absence of semicolons is covered by the [`semi` rule](https://typescript-eslint.io/rules/semi/) which *does* have the block because it is a stylistic concern.

**Comment by Zamiell** [comment]
can we update the docs to say that the rule is unnecessary if you are using Prettier?
i feel like that is useful information that should be documented

**Comment by bradzacher** [comment]
We don't like to document such a think as every formatter is different and so a rule may or may not be unnecessary.

Instead we just recommend that users use 3rd party configs like [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) and reference that as the source of truth for what rules are unnecessary.
