### ISSUE TITLE
Repo: Set up a system to give contributors roles on Discord

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7323]
## Overview

Following up on https://github.com/typescript-eslint/typescript-eslint/discussions/7103: we want to give nice friendly roles on Discord to folks who've contributed in some way, such as filing issues and sending PRs.

I don't know how to do this. But surely someone somewhere has set up such a thing. Or failing that, there's got to be a good way to keep track of it.

Assigning myself for tracking and public visibility.

**Comment by Zamiell** [comment]
Unfortunately you can't automatically do it in a safe way because a GitHub username won't necessarily correspond to a Discord username and/or a Discord nickname.

If you want to sacrifice safety, you could make the assumption that the names correspond, and then write a bot to automatically assign the role upon a new user joining the Discord server. (And you could use the bot to do a 1-time search through the existing users in the Discord to assign the "Contributor" role using the same GitHub search function.)

Obviously, this would make the server vulnerable to spoofing attacks where someone just takes the Discord username/nickname of an existing contributor.

**Comment by auvred** [comment]
What if there will be special issue/discussion where everyone who wants to join this program will be able to write their Discord nickname? This will allow to iterate through issue comments with to detemine contributor's Discord account

---

By the way, this may be useful somehow: there is a similar program in [aws-cdk](https://github.com/aws/aws-cdk) - they assign different merit badges to each pull requests,  depending on how many contributions the PR author has made

Reference: https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#badges-pilot-program

It's done with using this gh action: https://github.com/aws-github-ops/github-merit-badger

**Comment by Josh-Cena** [comment]
The question is whether this gives them any extra privilege, or if it's just access to an extra channel, etc. If the latter, then we can simply use typical role assignment systems, like reactions, or the recent onboarding feature.

**Comment by Zamiell** [comment]
> What if there will be special issue/discussion where everyone who wants to join this program will be able to write their Discord nickname? This will allow to iterate through issue comments to detemine contributor's Discord account

Fantastic idea!

**Comment by JoshuaKGoldberg** [comment]
Well, nobody ever requested roles - so I'm going to go ahead and close this out. Ah well :)
