### ISSUE TITLE
Configs: shouldn't `explicit-function-return-type` be part of `disable-type-checked`?

### ISSUE THREAD

**Issue by stephanedr** [typescript-eslint/typescript-eslint#7326]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

I've switched to a configuration structure as presented in https://typescript-eslint.io/linting/configs/#disable-type-checked (top config \*.ts, overrides \*.js).
`explicit-function-return-type` is enabled at top, but I also need to explicitly disable it for the \*.js override, whereas I expected it to be excluded by `disable-type-checked`.
I understand that `explicit-function-return-type` doesn't use type checking, but to me it should be part of `disable-type-checked` as I suppose its main goal is to modify a TS configuration to get it compatible with JS files.
Or maybe add a new config file, e.g. `disable-all-ts` (including `disable-type-checked`)?
I've identified 2 other rules with the same concern: https://typescript-eslint.io/search?q=mixed+JS%2FTS

### Impacted Configurations

`disable-type-checked`, or maybe add a new one.

**Comment by bradzacher** [comment]
> as I suppose its main goal is to modify a TS configuration to get it compatible with JS files

No - that's not the point of `disable-type-checked`.
The point of it is to make it easier to configure things and turn off type information on parts of your codebase that aren't able to be type-aware.

This might be JS files - this might be some fixtures or test files or similar.

The reason we added this config was because it allows users to build configs in a "type-aware first" fashion, rather than trying to work them as a "non-type-aware first" then slap the type-aware config in an override so they don't have crashes.
With the type-aware rules being added regularly, recommended sets changing every major, and 3rd party configs changing regularly - it is really hard to try and do a "type-aware first" config manually because it is a constantly moving target.

This is all different to "rules that 100% do not work on files that don't allow TS syntax". That set of rules is small and well-defined (just 3 rules - 2 of which you wouldn't use at the same time -- so really just 2 rules). Additionally this set is not a moving target - it's static (the last time a rule was added was over 3 years ago!). So it's entirely possible to disable that set on JS files. In fact most codebases don't even need to do anything because the 3 rules aren't part of our recommended sets and a lot of people don't use them as they feel they're too heavy!

I also want to be clear that type-aware rules fully work on JS files - there's no need to disable them at all for JS files! JSDoc comments allow you to annotate all your types so you can take full advantage of type-aware rules. The reason people often turn off type-aware rules on JS files is instead because JS files are an anomaly within their codebase and thus aren't covered by a tsconfig and aren't well typed - they're usually config files and the like that you don't really want to lint.

This is a lot of words - the TL;DR is that whilst I like where your head is at - I don't know if there's really enough benefit to generating a new config that is going to remain static and unchanging (probably forever?).

**Comment by stephanedr** [comment]
I hadn't understood the goal of  `disable-type-checked`. Thanks for the clarification.
A new configuration file for 2/3 rules doesn't seem indeed necessary.
