### ISSUE TITLE
Docs: Document Superfluous Rules with TypeScript

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#7328]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

#### @typescript-eslint/no-dupe-class-members

The [ESLint documentation for the rule](https://eslint.org/docs/latest/rules/no-dupe-class-members#when-not-to-use-it) says that the rule is superfluous if you use TypeScript.

According to Brad, the only reason that `typescript-eslint` bothers to maintain an updated version of the rule is because some people prefer the ESLint errors over the TypeScript compiler errors. However, this reasoning is not documented anywhere, so I propose the following warning be added to [the top of the page for `no-dupe-class-members`](https://typescript-eslint.io/rules/no-dupe-class-members):

> Danger
The code problem checked by this ESLint rule is automatically checked by the TypeScript compiler. Thus, it is not recommended to turn on this rule in new TypeScript projects. You only need to enable this rule if you prefer the ESLint error messages over the TypeScript compiler error messages. (When this rule was originally written, the TypeScript compiler checks did not exist.)

#### @typescript-eslint/no-invalid-this

The [ESLint documentation for the rule](https://eslint.org/docs/latest/rules/no-invalid-this#when-not-to-use-it) does not explicitly mention it, but this rule is superfluous if you use TypeScript with the `strict` or `noImplicitThis` compiler flags enabled. (The `strict` flag automatically includes `noImplicitThis`.)

According to Brad, the only reason that `typescript-eslint` bothers to maintain an updated version of the rule is because some people prefer the ESLint errors over the TypeScript compiler errors. However, this reasoning is not documented anywhere, so I propose the following warning be added to [the top of the page for `no-invalid-this`](https://typescript-eslint.io/rules/no-invalid-this/) (which is a slightly modified version of the warning from the previous section):

> Danger
The code problem checked by this ESLint rule is automatically checked by the TypeScript compiler (as long as you have the `strict` or `noImplicitThis` compiler flags enabled). Thus, it is not recommended to turn on this rule in new TypeScript projects. You only need to enable this rule if you prefer the ESLint error messages over the TypeScript compiler error messages. (When this rule was originally written, the TypeScript compiler checks did not exist.)

**Comment by JoshuaKGoldberg** [comment]
This seems reasonable to me at first glance, but I'll defer to @bradzacher.

> Danger

This isn't really a "danger" level note (things won't disastrously break if you don't read them). Maybe a note, or info?

**Comment by Zamiell** [comment]
> things won't disastrously break if you don't read them
I agree, but I chose danger because that is what is used already for Prettier-style rules.

In other words, `@typescript-eslint/member-delimiter-style` has a danger warning because you should disable it if you use Prettier.

Subsequently, `@typescript-eslint/no-dupe-class-members` should have a danger warning because you should disable it if you use TypeScript. And we should expect that virtually everyone reading this page is using TypeScript, so a big red error message seems appropriate.

**Comment by bradzacher** [comment]
Note that there is a BIG difference between the formatting thing and this case.

If you have prettier AND `member-delimited-style` then you're at risk of infinite and unresolvable formatting as prettier and the lint rule conflict with each other and their fixes never align. This is a big DANGER and users **NEED** to be aware of it or else they can create a broken devx and probably a CI that can never succeed.

OTOH rules that are "superfluous" are just that - they don't do anything that TS doesn't already do, but having them turned on only adds some noise in the form of double reporting. Some users actually like to have the duplicate reporting because ESLint is faster than TS in many cases - i.e. doing `yarn eslint specific/file.ts` is infinitely faster than doing a full typecheck cycle on any non-trivial codebase.

It's also worth noting that we have our `eslint-recommended` set which disables the base `no-dupe-class-members` rule. So if someone is using our recommended set then they won't see that rule ever! So they will only seek the rule out if they specifically want it.
`no-invalid-this` is also not in eslint's recommended set - so the user again has to seek the rule out to turn it on. `this` parameters are also on the rarer side - so it's less likely that a user will see the case of "using this inside a function with a this parameter" error that we fixed with our extension rule..

---

That's a lot of text - what am I getting at? Just highlighting that IMO this very much falls into the realm of bikeshedding. It's a very niche and begnign problem we're documenting and warding people away from.

Though to be clear - if we really want to add this - more than happy to accept a PR!
