### ISSUE TITLE
Docs: Formatting / Deprecated Rules are not clearly delineated in the rule list

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#7329]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The [rules reference](https://eslint.org/docs/latest/rules/) lists all of the rules. It's the first place that someone goes to when they want to start looking through all of the rules that `typescript-eslint` offers.

Right now, they are separated into 2 categories: Supported Rules & Extension Rules.

However, this layout does not capture which rules are formatting rules (which are greatly discouraged from being used) and it does not capture which rules are deprecated (which obviously shouldn't be used). In other words, the "bad" rules are lumped in together with everything else, which makes the experience painful as an end-user who is going through the list to find out which ones they want to enable for their codebase.

On the left sidebar, there is a "Formatting Rules" and "Deprecated Rules" section, but this is pretty obscure and hard to miss, especially because they are all the way at the bottom behind a huge list of rules. Furthermore, the fact that these sidebars exist isn't represented on the main rules page. So I motion that these sidebar categories are completely deleted and the categorization is merged into the main rules page in some way.

First, I'd mention that we might want to take inspiration from [the ESLint rules page](https://eslint.org/docs/latest/rules/), which delineates rules into four categories:
- Possible Problems
- Suggestions
- Layout & Formatting
- Deprecated

(I'm not counting the "Removed" category here.)

So, we could fix this problem in a few different ways. I think one way is to replicate the ESLint rule layout, such that the ordering of rules on the page would look something like this:

- Possible Problems
  - Possible Problems (Main Rules)
  - Possible Problems (ESLint Extension Rules)
- Suggestions
  - Suggestions (Main Rules)
  - Suggestions (ESLint Extension Rules)
- Layout & Formatting
  - Layout & Formatting (Main Rules)
  - Layout & Formatting (ESLint Extension Rules)
- Deprecated
  - Deprecated (Main Rules)
  - Deprecated (ESLint Extension Rules)

At the end of the day, the problem we are looking to solve is that users can go through the menu of rules without tripping over "bad" rules. Or, they can easily see from a glance which rules are formatting rules when browsing the master rule list.

### Affected URL(s)

https://eslint.org/docs/latest/rules/

**Comment by bradzacher** [comment]
*personally* I don't like ESLint's rule page layout because it makes it harder to find things.
Instead of having a big list of rules in alphabetical order - instead I have 4 smaller lists in alphabetical order.

If you're ever looking for a rule and was like "it had a name like XXX" - scanning 4 separate lists is much harder.

It also creates an explicit "tiering" of rules - which can ward some people away from certain rules. "OH I only use 'possible problems' rules and ignore all the others" which is not great as there are many great rules across all the categories (yes, even the formatting category has some ***okay*** ones!)

Instead of sectioning off things into separate tables - IMO it would be better to just add the information to the table itself as a column that the user can filter on.

Note that the big reason we keep the extension rules separate is to clearly delineate them and make them discoverable to avoid people filing duplicate issues. Though this isn't as important as much as it used to be - back in the day we had static markdown only so a separate table was the only way to "filter" them. TBH we could similarly consider merging them in to the main table now as a filter instead.

**Comment by Zamiell** [comment]
> Instead of sectioning off things into separate tables - IMO it would be better to just add the information to the table itself as a column that the user can filter on.

I like that idea!

> TBH we could similarly consider merging them in to the main table now as a filter instead.

Or as an extra column for "extension", so that all rules are alphabetical.

**Comment by Zamiell** [comment]
Ok, so it has been a month, should I do a PR for this?

**Comment by JoshuaKGoldberg** [comment]
> TBH we could similarly consider merging them in to the main table now as a filter instead.

Yeah it'd be nice to simplify everything together. Sorry for the delay - let's say this is accepting PRs!

**Comment by Zamiell** [comment]
I'll try working on this once #7285 and #7372 are accepted.
