### ISSUE TITLE
Docs: Two pages describe package versions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7341]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Both https://typescript-eslint.io/users/dependency-versions and https://typescript-eslint.io/users/versioning exist say what versions we support right now. I haven't looked deeply, but I'm guessing there was a merge conflict that resulted in the pages repeating each other.

### Affected URL(s)

https://typescript-eslint.io/users/dependency-versions
https://typescript-eslint.io/users/versioning

**Comment by auvred** [comment]
Yea, it seems to be caused by this commit https://github.com/typescript-eslint/typescript-eslint/commit/c23365292631b1c3db7c439c9d962234084f66b7

It combined two versions of `Versioning.mdx`

1) https://github.com/typescript-eslint/typescript-eslint/blob/e35c5c1c39f3d76b916ad1c1ac2c7bf05b379193/docs/maintenance/Versioning.mdx
2) https://github.com/typescript-eslint/typescript-eslint/blob/3e18a319236776798e7b068a27b3d5fab8184230/docs/users/Versioning.mdx

I assume the second version is correct  (it was introduced here https://github.com/typescript-eslint/typescript-eslint/pull/7033)

Should we revert this change to match the second variant?

**Comment by JoshuaKGoldberg** [comment]
<img alt="The Star Wars evil Sith emperor saying 'execute order 66'" src="https://media4.giphy.com/media/xTiIzrRyvrFijaEtY4/giphy.gif"/>
