### ISSUE TITLE
Repo: Version 6 of @typescript-eslint/eslint-plugin is not on yarn yet

### ISSUE THREAD

**Issue by FabianWarnecke** [typescript-eslint/typescript-eslint#7398]
### Suggestion

https://www.npmjs.com/package/@typescript-eslint/eslint-plugin shows 6.2.1 as the current version of @typescript-eslint/eslint-plugin, whereas https://yarnpkg.com/package/@typescript-eslint/eslint-plugin still shows 5.56.0.
Is this intended?

**Comment by JoshuaKGoldberg** [comment]
Look slightly up on that page 😜 

<img width="1227" alt="Screenshot of the yarn package page saying [New packages and versions may not show up in this interface due to an ongoing npm incident. Only search is affected, installs work as usual.](https://github.com/npm/feedback/discussions/937)" src="https://github.com/typescript-eslint/typescript-eslint/assets/3335181/045f6ba9-ce82-4f2b-8e17-9281e23e32cc">

> [New packages and versions may not show up in this interface due to an ongoing npm incident. Only search is affected, installs work as usual.](https://github.com/npm/feedback/discussions/937)

It's not a problem on our end.

**Comment by FabianWarnecke** [comment]
Maybe I should get new glasses... 🤦‍♂️
Thanks for pointing out the obvious and sorry for bothering you about it. 😅
