### ISSUE TITLE
Docs: `explicit-function-return-type` should have benchmark link to show performance-convenience-trade-off

### ISSUE THREAD

**Issue by loynoir** [typescript-eslint/typescript-eslint#7414]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

https://typescript-eslint.io/rules/explicit-function-return-type/

> However, explicit return types do make it visually more clear what type is returned by a function. They can also speed up TypeScript type checking performance in large codebases with many large functions.

It is not clear that how much faster will be, if use `explicit-function-return-type`.

Is there a benchmark link?

### Affected URL(s)

https://typescript-eslint.io/rules/explicit-function-return-type/

**Comment by bradzacher** [comment]
There is no benchmark.

There are certain cases where return types can turn anonymous object types into named types - allowing the checker to run faster because it can short-circuit downstream checks.

It can also help generate better type declarations for the same reason. This is a good way to reduce the size of generated types by naming and reusing types.

It can also help incremental updates as it allows TS to short-circuit checks (eg if you change the function internals without changing the return type TS can concretely know it needn't check dependents.

But setting up a test for this would be a pretty convoluted test case and not representative of the real world. Chances are most codebases wouldn't see any noticeable improvement.
