### ISSUE TITLE
Turnkey TSLint-like developer experience

### ISSUE THREAD

**Issue by flowstate247** [typescript-eslint/typescript-eslint#7432]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

I miss the way we just had to install TSLint and everything was working as intended.
Now we have to wrestle with the eslint ecosystem and that's painful frankly.
It's all a giant puzzle to solve with eslint, typescript-eslint, various other eslint plugins, + prettier on top of that...

Why can't we just have a whole nice turnkey experience to enable Typescript linting and formatting like they have in other languages?

**Comment by JoshuaKGoldberg** [comment]
I can't tell if you're venting or legitimately asking. But either way, starting this discussion isn't the way to accomplish what you probably want to accomplish.

If you're venting, then know that GitHub Issues is not the appropriate place to start a broad _"the system is bad"_ discussion. Please read our [contributing guide](https://typescript-eslint.io/contributing), as all folks are asked to before filing issues. We recommend you try more social communities such as Discord or Twitter for venting. Issues are meant to be single-purpose _"I'm proposing a specific change"_.

If you're legitimately asking then I'd suggest reading up on at least our documentation first. Even if it doesn't make you happy about the current state of things, it'll at least help you make a more informed case for why things need to change.

* https://typescript-eslint.io/linting/troubleshooting/formatting: why we believe using any linter -ESLint, TSLint, or otherwise- for formatting was never a good idea in the first place
* https://typescript-eslint.io/linting/troubleshooting/tslint: why TSLint was deprecated

Closing and locking because I don't want this issue to turn into a whole discussion. But I'm happy to chat more in another forum if you have more questions.

**Comment by JoshuaKGoldberg** [comment]
...all that being said, yeah, the current system is kind of a pain :smile:. I don't think anybody's thrilled at how many tools it takes to get set up in typical projects. A lot of builders/frameworks do it for you now -[`npm create astro`](https://astro.build), [`create-next-app`](https://nextjs.org/docs/pages/api-reference/create-next-app), [`npx create-remix`](https://remix.run/docs/en/1.19.2/tutorials/blog#creating-the-project), [template-typescript-node-package](https://github.com/JoshuaKGoldberg/template-typescript-node-package), etc.- but you'll still need to tinker with the system if you want to customize anything.

ESLint is investing in two larger initiatives to simplify things:

* [Flat configs](https://eslint.org/docs/latest/use/configure/configuration-files-new) _(sooner)_: a newer, simpler configuration file format that simplifies the concepts around plugins & rule settings. I'm hopeful that that config simplification at least helps people understand how they're configuring their linter.
* [Complete rewrite](https://github.com/eslint/eslint/discussions/16557) _(later)_: rethinking ESLint as an extensible core that allows for much more powerful, straightforward integrations for common user needs. I'm particularly hopeful that this rewrite will simplify these two TypeScript-related points in particular (listed under _Maybes_, alas):
  * "Make ESLint type-aware": building in a pluggable concept of "types" that can be extended by plugins. Doing so would mean a _ton_ of rules from typescript-eslint can be moved to ESLint core. For context, many of our rules really aren't TypeScript-specific - they're just only practical if you use a type checker.
  * "Make ESLint project-aware": typescript-eslint experience a lot of performance issues in setting up type checking because of a result of how ESLint is structured today. We'd sent an RFC to ESLint with more information: https://github.com/eslint/rfcs/pull/102. Sadly, it was rejected.

But! Much of this complexity is inherent to having a thriving, vibrant ecosystem like JavaScript's. The community is constantly exploring and iterating on new ways of doing things. That means there isn't ever one standard preset that fits for everyone. Even if one tool took care of both formatting and TypeScript syntax+types natively, you'd still want the ability to add plugins for every flavor you've added into your project. Those plugins would need to at least support third party npm packages so that individual projects, teams, companies, etc. could write their own.

There have been a few notable efforts recently to make more of an all-in-one tool. The top three that come to my mind are:

* https://github.com/xojs/xo: wrapper around ESLint that simplifies much of the configuration
* https://github.com/rome/tools: bundler, formatter, linter, etc. - all in one, in Rust
* https://github.com/web-infra-dev/oxc: bundler, formatter, linter, etc. - all in one, in Rust

Having a more unified tool is a nice idea but hasn't hit mainstream adoption yet for two reasons:

* The ecosystem is still evolving relatively quickly. Any one tool that establishes a preference will become out of date within a few years at most. These tools need to iterate as quickly as the world around them - which is a disadvantage given how many different efforts are happening all at once (formatters, linters, type checkers, etc.).
* Most of these new tools are written in Rust or other lower-level languages than JavaScript for their performance. While Rust & co. are incredibly fast and can interop with JavaScript thanks to WebAssembly & wrapper projects, their _practical_ interop is not great:
  * Most JavaScript/TypeScript developers don't also work in Rust/etc., so the contributor pool is much smaller
  * Nobody has successfully gotten enough of the TypeScript type checker (re-)implemented in Rust (not even [stc](https://github.com/dudykr/stc)) to compete on a feature level with typescript-eslint's typed rules. Nor has any native speed linter been willing to sacrifice performance to run TypeScript's APIs directly

I personally am hesistant to bundle TypeScript syntax & types directly into tools. Although it's convenient, it does make it a little harder for competitors to TypeScript to enter the game. That's not an issue today but I hope it eventually will be. TypeScript is over a decade old and I'd love to see a new competitor that improves on TypeScript's model (e.g. deduplicating the concepts of interfaces vs types, adding in dependent types, etc.).

We should also note that there's a [TC39 Types as Comments proposal](https://tc39.es/proposal-type-annotations). It's contentious but I hope that it passes within the next decade. If it does, I hope it'll at least standardize some types syntax, so parsers such as typescript-eslint's will have to do less work to add in support for types syntax.
