### ISSUE TITLE
Fix peer dependency

### ISSUE THREAD

**Issue by deser** [typescript-eslint/typescript-eslint#747]
@typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by kulinar310** [comment]
You can try to delete folder node modules. And install again " npm i"

**Comment by bradzacher** [comment]
we do not have a dependency on the package, we have a peer dependency on the package. This is on purpose.

You are expected to install and manage your own installation of eslint, because we are a plugin of eslint. If every eslint plugin had a hard dependency on eslint at a different version, your node_modules folder would get polluted with extra conflicting installs of eslint.

More reading: https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by deser** [comment]
ok thx

**Comment by crhistianramirez** [comment]
@bradzacher  does typescript-eslint not support version 6+ of eslint? Just wondering if the peer dependency should be `>=5.0.0` instead of  `^5.0.0`

**Comment by bradzacher** [comment]
#735
