### ISSUE TITLE
Configs: Don't disable no-import-assign & no-redeclare

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#7547]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

The [`eslint-recommended` config](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts) says that:

```ts
/**
 * This is a compatibility ruleset that:
 * - disables rules from eslint:recommended which are already handled by TypeScript.
 */
```

In [July of 2022, we removed `valid-typeof` from the `eslint-recommended` config](https://github.com/typescript-eslint/typescript-eslint/pull/5381) because we discovered that the rule was not completely handled by TypeScript.

Currently, the `eslint-recommended` config turns off [`no-import-assign`](https://eslint.org/docs/latest/rules/no-import-assign) and  [`no-redeclare`](https://eslint.org/docs/latest/rules/no-redeclare). However, I think that similar to [`valid-typeof`](https://eslint.org/docs/latest/rules/valid-typeof), this is a bug, because these two rules are not (completely) handled by TypeScript.

<br>

### `no-import-assign`

[For `no-import-assign`, the ESLint official documentation](https://eslint.org/docs/latest/rules/no-import-assign) lists these as the "bad" cases that it catches:

```js
import mod, { named } from "./mod.mjs"
import * as mod_ns from "./mod.mjs"

mod = 1          // ERROR: 'mod' is readonly.
named = 2        // ERROR: 'named' is readonly.
mod_ns.named = 3 // ERROR: The members of 'mod_ns' are readonly.
mod_ns = {}      // ERROR: 'mod_ns' is readonly.
// Can't extend 'mod_ns'
Object.assign(mod_ns, { foo: "foo" }) // ERROR: The members of 'mod_ns' are readonly.
```

However, if we [paste this into a TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBCCATANHA3nAdgQxAUyTgF84AzKCEOAIgDoB6RJOkAKwGcaAoUSWOACo4ODgmQB9LGIpVajZq049uzOAF44ARji69+hgzgBRAEqmA8qYBccAOTM7cYGKj4cSCFgA2ATzrcuAREmgBM+gZGZpY29kGETi5wbh5efgHMUhx08SFwAMxwhibmVrYAKgAW+Aj4IABG+FBiEGT2mdJOOG7J7p4+-qqS0hoYpBHF0WXtwxyJrn1pg8UAwjhYdvD4AB4w+FhEDrN23Bb1bPgAxjB0ohzAAOZYABQdHGiYZBAQtjRfEDQSABKIpRUqxKo1AgNJotNpHJBZLo9FL9dLcIA), we can see that TypeScript does not actually prevent the `Object.assign` case.

Thus, the ESLint rule still has some value and I propose that `eslint-recommended` should not disable it.

<br>

### `no-redeclare`

[For `no-import-assign`, the ESLint official documentation](https://eslint.org/docs/latest/rules/no-redeclare) lists these as the "bad" cases that it catches:

```js
var a = 3;
var a = 10;
```

If we [paste this into a TS playground](https://www.typescriptlang.org/play?#code/G4QwTgBCELwQzAbgFCktOBGADCoA), we can see that TypeScript does not actually catch the bug.

However, there is a wrinkle here that makes this case more complicated than the previous one. The `eslint-recommended` config also enables the [`no-var`](https://eslint.org/docs/latest/rules/no-var) rule. This means that while this error case would not be flagged by the TypeScript compiler, it would still (probably) be flagged by ESLint.

With that said, I don't like this, for two reasons:

1) The documentation on the config is wrong. It says that it explicitly "disables rules which are handled by TypeScript", and this is not handled by TypeScript.
2) End-users may decide to disable the `no-var` rule. In this case, they would assume that `no-redeclare` is handled by TypeScript, which is false, so they would be vulnerable to bad redeclares due to `typescript-eslint` misleading them.

Thus, for these reasons, I propose that the `eslint-recommended` should not disable `no-redeclare`. (This would cause code with two `var` statements to trigger _both_ the `no-var` rule and the `no-redeclare` rule, which I think is completely fine.)

### Impacted Configurations

eslint-recommended

**Comment by bradzacher** [comment]
Thanks for the thoughtful discussion.

On the second request - hard no.
`var` is barely used in modern TS because the scoped let/const are much better for almost all usecases. The only case where I've seen var intentionally used is in the TS codebase where they had module global variables that were accessed millions of times, so using var to avoid the TDZ checks was the smart option.

All other cases use let/const and we haven't heard of anyone manually disabling `no-var` and then running into code smells of multiple declaration `var`s.
It's also worth clarifying that using `var` to "redeclare" a variable is actually completely safe and fine. It's "bad code" - but it's just a stylistic thing for the most part.

Additionally people hate the `no-redeclare` rule in TS because in a lot of codebases using the [type/value redeclaration](https://typescript-eslint.io/play/#ts=5.2.1-rc&fileType=.tsx&code=C4TwDgpgBAKlC8UCMBuAUAYwPYDsDOwsCy6aQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaaRAE0QGN4BDE9KRaafaSAGnG0gAEAXATwAOKCtACWg3oRTwxuXgHoCxMpRp0MkRs1acAviD1A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false) is a really really common pattern. Some people use it instead of enums and some libraries (like zod) use it as idiomatic code.

So turning on the rule to catch code that isn't ever written in modern TS AND actively errors on correct, valid TS code is not something we'll be doing.

**Comment by bradzacher** [comment]
```ts
Object.assign(mod_ns, { foo: "foo" })
```

The cases that I see people use `Object.assign` are already pretty rare - they're very targeted and people often use it with a new object in the first param (I.e. As a spread alternative) because people generally hate side-effectful code like that.
I reckon I could count on one hand the cases where I have seen someone has use it to mutate an object.

I can say for certain that I've honestly never seen someone use `Object.assign` to mutate an imported value. Even in the commonjs days where "imports" were fully mutable and it was an uncommon practice to assign to the "imports" I didn't see that pattern.

---

The reason we turned `valid-typeof` back on was because [TS doesn't catch the common typo `typeof foo === undefined`](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPJjAJYoDmA3AFAYCeADiEtjnvALxfwCuKo2MiGDUgA). This is a typo we have seen a heck of a lot ourselves (IIRC there was even some in our codebase) - so it was a no brainer to turn this rule on!

But for the other two talking about intersections of really, really rare patterns that cause runtime errors. Like for sure they are examples of valid code - but it's just not something that actually is done.

Duplicating TS errors at large to help catch errors that most people would highly likely never ever see isn't a great DevX - it's one of the things that turns people off of linters as a whole as they feel like they become noisy.

**Comment by Zamiell** [comment]
Sounds good to me, thanks for the discussion!
