### ISSUE TITLE
Consider removing dependency on `natural-compare`

### ISSUE THREAD

**Issue by alfaproject** [typescript-eslint/typescript-eslint#7556]
Consider using the native Intl API for natural string comparison:
```js
const natOrdCmp = new Intl.Collator(undefined, { numeric: true }).compare;
['a1', 'a2', 'a10'].sort(natOrdCmp);
```

I believe this achieves the same as what the `natural-compare` package does but without that extra dependency.

**Comment by bradzacher** [comment]
We use `natural-compare` because it is what ESLint uses.

https://github.com/eslint/eslint/blob/10c4f85dca978b42d37619f50565a06b9a28c9ac/package.json#L96

So there's no extra dependency is required.

There's probably differences between the two approaches. Someone would need to do the investigation and make the change to eslint, and we would follow suit from that - not before though.
