### ISSUE TITLE
Bug: [no-extra-parens] Some unnecessary parens in simple assignment statement  can't be remove.

### ISSUE THREAD

**Issue by finscn** [typescript-eslint/typescript-eslint#7573]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.ts&code=MYewdgzgLgBAhgLnmAnjAvDA3gXwNwBQoksARknKhjAOQDWApijYUeNDMNQBSnwQxoAJwCWYAOYBKQsQ4ATHqUn8Y3YWKkz2sBtQDavFeomSAuq1mwAZtTgG%2BcAcanmCQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaRADwBdoBDQgB0ukV1QwG1JFpp9pIAaKSvHiQAur3DZIAATIBPGigDG0AJY0yxZPBW4yAegLFyVWvUbMwbDlx79Ig4SIkBfEM6A&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
const a: any = {};
const b: any = 'key';

const c = (b as string);
const d = (b) as (string);
const e = [(b as string)];

const f = a[(b as string)];

```

### ESLint Config

```jsonc
{
  "rules": {
    "no-extra-parens": ["error", "all"],
    "@typescript-eslint/no-extra-parens": ["error", "all"]
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true
  }
}
```

### Expected Result

format the code like this: 
```ts
const a: any = {};
const b: any = 'key';

const c = b as string;
const d = b as string;
const e = [b as string];

const f = a[b as string];

```

### Actual Result

```ts
const a: any = {};
const b: any = 'key';

const c = (b as string);
const d = (b) as (string);
const e = [(b as string)];

const f = a[b as string];

```

### Additional Info

Unnecessary parens in Line 3/4/5 can NOT be removed.

Only the last line is correct.

**Comment by bradzacher** [comment]
Hi there 👋!

As you may have heard [ESLint core is deprecating its formatting rules](https://eslint.org/blog/2023/10/deprecating-formatting-rules/). We are likewise moving in the same direction and deprecating our formatting rules.

Deprecated rules will be removed in the next major version as their new home is the [eslint-stylistic](https://github.com/eslint-stylistic/eslint-stylistic) project.

If this issue is important to you please consider filling an issue over at eslint-stylistic which will be the new home for stylistic/formatting rules.

Thanks!
