### ISSUE TITLE
Configs: @typescript-eslint/typescript-estree needs typescript 5.2.2 support

### ISSUE THREAD

**Issue by daniilgri** [typescript-eslint/typescript-eslint#7599]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Typescript has latest version 5.2.2. After upgrading it I have this:

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.2.2

Please only submit bug reports when using the officially supported version.

=============

**Comment by auvred** [comment]
Which version of the `@typescript-eslint/typescript-estree` are you using? The TypeScript 5.2 is supported since v6.5.0: https://github.com/typescript-eslint/typescript-eslint/pull/7535
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v6.5.0

**Comment by JoshuaKGoldberg** [comment]
> Configs

The Configs issue template isn't the right one to use for what looks like either a bug report or feature request around TypeScript versions. Please file again with the right template. Since this looks like it's a version-specific issue, it's likely [🐛 Report a Complex Bug With a Reproduction Repository](https://github.com/typescript-eslint/typescript-eslint/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=08-bug-report-complex.yaml&title=Bug%3A+%3Cshort+description+of+the+issue%3E).

We have those templates for good reason 🙂. They ask for necessary information such as what versions of packages you're using. They also include relevant suggestions such as _I have updated to the latest version of the packages_. Which I'm guessing is the issue here, as @auvred indicated.
