### ISSUE TITLE
Rule proposal: @typescript-eslint/no-var

### ISSUE THREAD

**Issue by oliveryasuna** [typescript-eslint/typescript-eslint#7613]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

ESLint comes with the [no-var](https://eslint.org/docs/latest/rules/no-var) rule. I see it used on many projects to enforce `let` or `const`. TypeScript docs says use `declare var` in declaration files (https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#global-variables), so there is a conflict.

I propose we introduce a new rule that excludes declaration files from check (or by configuration).

### Fail Cases

```typescript
N/A
```

### Pass Cases

```typescript
N/A
```

**Comment by bradzacher** [comment]
Global variables are a rare case to be declaring in projects specifically - they generally represent a code smell because encapsulating variables within modules to be explicitly imported is the much preferred version

If for some reason you still do want to use `var` inside `.d.ts` files, you can disable the rule on those files using overrides config.

https://eslint.org/docs/latest/use/configure/configuration-files#configuration-based-on-glob-patterns
