### ISSUE TITLE
Enhancement: [consistent-type-imports] New fixStyle for top level if possible, inline otherwise

### ISSUE THREAD

**Issue by joshkel** [typescript-eslint/typescript-eslint#7621]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/consistent-type-imports

### Description

With `{prefer: 'type-imports', fixStyle: 'inline-type-imports'}`, the consistent-type-import rule can combine types and runtime identifiers into a single `import`, which many find desirable (see #2769). However, if only types are imported, the fixer does per-identifier `type` instead of a top-level `import type`. This has disadvantages: TS's [`verbatimModuleSyntax`](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) doesn't elide the import; Jest + Babel may unnecessarily detect the file as potentially modified and needing to have it tests rerun; the [no-import-side-effects](https://typescript-eslint.io/rules/no-import-type-side-effects/) rule (if configured) immediately triggers.

I propose adding some sort of `fixStyle: 'combined-type-imports'` (intelligently combine however possible) option to address this.

### Fail

```typescript
import { Foo, Bar } from 'Foo';
import { Baz, Qux } from 'Baz';
type T = Foo;
const x: Bar = 1;
type T2 = Baz;
Quz();
```

### Pass

```typescript
import type { Foo, Bar } from 'Foo';
import { type Baz, Qux } from 'Baz';
type T = Foo;
const x: Bar = 1;
type T2 = Baz;
Quz();
```

### Additional Info

[This comment](https://github.com/typescript-eslint/typescript-eslint/issues/2769#issuecomment-1425253169) suggests using eslint-plugin-import to provide missing desired functionality, but it does not appear to be able to do this (combining imports using type specifiers, but enforcing top-level if top-level would work).

As mentioned, no-import-side-effects can enforce this, although it feels strange (and feels like not ideal DX) to have one typescript-eslint rule's fixer create code that has to be immediately fixed again by another related rule in the same package. (I may be wrong here - I see that ESLint may [encourage this sort of thing](https://eslint.org/docs/latest/extend/custom-rules#applying-fixes), although the fix-and-repeated behavior that it describes does not appear to be triggered with VS Code's "Fix this @typescript-eslint/consistent-type-imports problem" and "Fix all @typescript-eslint/consistent-type-imports problems in this file" quick fixes, so it still may be worth addressing.)

**Comment by bradzacher** [comment]
Thanks for the request.
We won't be looking to add such stylistic semantics to the rule.

The rule purposely does not enforce the specific positioning of the qualifier - it purely enforces that imported symbols are properly qualified. The fix style option is only provided to help align the fix with what your codebase may do, but is not there to enforce anything.

There are other rules that may help you such as [`import/consistent-type-specifier-style`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/consistent-type-specifier-style.md), [`import/no-duplicates`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md#inline-type-imports) or [`@typescript-eslint/no-import-type-side-effects`](https://typescript-eslint.io/rules/no-import-type-side-effects/) - which are all rules that specifically enforce code styles you may want.

---

ESLint rules are supposed to be single-minded and focus on addressing one specific problem so that things are kept simpler for users and maintainers - it's much easier for everyone to reason about a rule if it focuses on one thing.

Having one rule fix a problem with code that violates another rule is fully intentional within the ecosystem as you've noted because it's impossible for a rule to handle every variation of style. For example our fixer currently always adds a semicolon to the end of the new import it inserts - but this may violate a codebase's style! But we won't be adding an option for this given that the `semi` lint rule exists to enforce exactly this style!
