### ISSUE TITLE
Reopen #1391

### ISSUE THREAD

**Issue by jimmywarting** [typescript-eslint/typescript-eslint#7635]
I would like to wish for #1391 to be reopen.

**Comment by bradzacher** [comment]
I'm not quite sure why we would reopen #1391 when [there was already a completely working solution provided](https://github.com/typescript-eslint/typescript-eslint/issues/1391#issuecomment-1124154589).

You haven't provided any information at all about why we should.

Copy pasting it here for posterity as it also includes examples:

---

As per our [FAQ article](https://typescript-eslint.io/docs/linting/troubleshooting#how-can-i-ban-specific-language-feature) - this can easily be achieved using `no-restricted-syntax`:
```json5
{
  no-restricted-syntax: [
    'error',
    {
      selector: ':matches(PropertyDefinition, MethodDefinition)[accessibility="private"]',
      message: 'Use #private instead',
    },
  ],
}
```
[playground](https://typescript-eslint.io/play/#ts=4.6.4&sourceType=module&showAST=es&code=PQKgBApgzgNglgOwC5gQewLQCdpK3AYyQgBMMoBPZAQwA8AuMAbQCgx2wByCLLNLTgBo2HAN4iOHKBBgQi-Rp3oBbakgIALaAAoACnwAOPJBQAiEAGaI4SOGgSCwAWQhINaEuasIbdhAEomagICaCg4ACM4eBMAXgAiA3wANzUIeIBdIQlJMGUw6gBzCEUAVWkwAGIkuFTiMEQoYmoSbMkAX2EMsBBgFhYCGGooKDAAMTQ0MHFJJLQDAEZGagQKAG4cgwBXCPgCMDmDACZl1Y3ZvmIiUgPDAGZT9c2UtNv5gBZH845qwwBWL79ST5NweBbafzTdqbHZ7PKudwkI4QqHPNBXYgkeGgkh3FGiaEXWqvEGI974wk-UkeP4UoEcYooYKhEb8cGQ0RgHBILZYBBgBZgNaU9jbXaEMCMsDMsL8ZEcrmuXn8wXCtEYm5SmWsrB4hXc5UCoUi27E+pakKyrDk-VKvlGtWSKWVbVQfi0208+2q6HQoA&rules=N4XyA&tsConfig=N4XyA)

similarly the inverse can easily be enforced as well:
```json5
{
  no-restricted-syntax: [
    'error',
    {
     selector: ':matches(PropertyDefinition, MethodDefinition) > PrivateIdentifier.key',
      message: 'Use `private` instead',
    },
  ]
}
```
[playground](https://typescript-eslint.io/play/#ts=4.6.4&sourceType=module&showAST=es&code=PQKgBApgzgNglgOwC5gQewLQCdpK3AYyQgBMMoBPZAQwA8AuMAbQCgx2wByCLLNLTgBo2HAN4iOHKBBgQi-Rp3oBbakgIALaAAoACnwAOPJBQAiEAGaI4SOGgSCwAWQhINaEuasIbdhAEowAD4wfTgANzUIAEkSCGQ4Kx4AOgBrCAohCUkwZWgoagBzCEUAVWkwAAMDfEjiSrBEKGJqEizJAF9hAF0wEGAWFgIYaigoMAAxNDQwcUkatAMARkZqBAoAbmyDAFcAI3gCMAWDACZV9a35vmIiUmPDAGYLze3aqIfFgBYXq44AYhOAFZfoNJHk3B4ltpAqIOtt9odcq53CRTjDZvDrmhbsQSMjISRHhi4W8Ih8IaiviSsQDKR4gTSwRxiihqAQCPl+NDYWAcEgdlgEGAlmANrT2LsDoQwKywOzOWN+OjefzBcLReK3ji5HjZa55RyuVhiarXOqRWKJQ9ycR9WyjUqsNSzQKhZatZI5f8FcbGa6LZr4fCgA&rules=N4XyA&tsConfig=N4XyA)

I don't believe that a lint rule makes sense here. We want to avoid adding rules which just ban a specific language features unless we can add some real additional value. Given that there's no fixer we can provide (because it's unsafe), and there's no options to configure or tweak - I don't see any additional value we can provide.

For this reason, we shall reject this rule proposal.
