### ISSUE TITLE
Bug: prefer-optional-chain suggests optional chaining during strict null equality check

### ISSUE THREAD

**Issue by justinbhopper** [typescript-eslint/typescript-eslint#7654]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=LAKAlgdgLgpgTgMwIYGMYAIAiSpPQb1HXQHoT0BJAWwAcB7OXaALnQAZ0wBndPANyQAbMABN0AwQFcYRcUOmsIkqgCN46AD7olgwQG5QAX1CgUdCFyjoROJK2y5N2ybvQBedAHMYUB0gAUAJQGIKBk6ADCABYwKADWkJ7oKnRQUehpOOgABja42Zw8UHCSaQCe6ACCAHKYGVFZubYAdBLSBdzaqc6u-mooSJJcGBydEqKBoGAI6P55eABkC9YtbRgAhG4eOoKBBLJmFnSCMM2CdJ7%2BAETVympwrFfoANQruK3yMMFG6DCCw-sQMRDlxjqdzpcrhQIOMxPNmldviBjKEQAhJBAUFAwOYvD4-EF7LYnDtAcQ4D5JHAIAQ5FIYKwAMzoQwhFGgIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6RAM0WloHsalfkwCG8WmQAWo5uii9o-aJHBgAviHVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
const data: Data | null = getData();

// Checking both that `data` is truthy AND that `data.value` is not null (because 0 is valid)
if (data && data.value !== null) {
  console.log("Number: " + data.value);
} else {
  console.log("Invalid data.");
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  "rules": {
    "@typescript-eslint/prefer-optional-chain": "error"
  }
};
```

### Expected Result

I expect in this case the rule would not suggest using optional chaining, because there is no way to check that `data` is truthy and that `value` is not null in a single condition.

### Actual Result

The rule suggests a fix of `data?.value !== null` as the condition, but this condition means we are no longer checking if `data` is null.  Applying the fix changes the logic and causes downstream errors (see playground).

**Comment by Josh-Cena** [comment]
The rule's report is correct: `data && data.value !== null` is true if and only if `data` is non-null and `data.value` is non-null. `data?.value !== null` is true if and only if `data` is non-null and `data.value` is non-null. If `data` is `null`, then `data?.value` would be `undefined`, and the condition is still false. If you change `data.value !== null` to `data.value !== undefined`, you will see that the report is gone.

**Comment by Josh-Cena** [comment]
Oops, I completely brain-farted. You are right—it should not report when the exact value of the optional chain is relied on.

**Comment by adamsmasher** [comment]
Given that, with this rule on, the auto-fixer will (very subtly!) break users' code, should anyone be using this rule right now?

`prefer-optional-chain` is included in `stylistic-type-checked`, which means that the default "max settings" for eslint are arguably broken.

Unfortunately, fixing this is probably a little too far out of my wheelhouse, but in the interim should this rule be disabled and/or removed from `stylistic-type-checked`? At least a warning about it added to the documentation?

**Comment by bradzacher** [comment]
@adamsmasher the issue has 3 non-maintainer interactions with you being the 4th.
It's just not a common problem amongst the community to have this exact state - so nobody else has stepped up to champion it.
If this is a problem for your codebase - then it might be a dealbreaker for you right now and it's up to you as to whether or not you turn it off.

Personally this is one of the reasons that I think using strict-equality for `null` is bad. I don't believe you should ever consider `null` and `undefined` as distinct values and instead you should use loose-equality for `null` so you always treat them the same.
I.e. if you were to adjust the above code to use `!=` instead of `!==` - then the fix works just fine.

---

We are a community run project. The **volunteer** maintainers spend most of their time triaging issues and reviewing PRs. This means that most issues *will not progress* unless a member of the community steps up and **champions** it.
If this issue is important to you — consider being that champion.

**Comment by jsfm01** [comment]
Hello! I've submitted a pull request to address this issue. While I've implemented a solution, I'm open to suggestions on how to improve it further. Your feedback would be greatly appreciated!
