### ISSUE TITLE
Bug: [lines-between-class-members] not working with new "enforce" option from base rule

### ISSUE THREAD

**Issue by Friendsen** [typescript-eslint/typescript-eslint#7716]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

Note: Playground doesn't let me specify eslint version, so version is wrong currently (needs to be > 8.49).

https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=KYDwDg9gTgLgBAYwDYEMDOa4FEQoLZhLBwDeAUHHKPocALLAwAWEAJgBQD6AXHCgHYBPAJS8AbhACWrANwUquAkQbM2XXgJHiprUvMoB6A3DQsArkl38I8JijHF%2BwAO5JJTvgCMID%2BQF95ARsmYCgcGmVGFg5ROAlpPUpDY1MIC107BzgnV3diFG9fSgCAoA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKXgSwDsUBaAI0QBcB3RRA4gY3gENlliBbRD86VDSAHsAZsMgAacNkgABCgE8ADigbQ8iisRT4CFAPQ6S5arXpNW7Lj0R90YANpTsUG9EHQJT7FmfS6w9wZEO0dfXx8w50hSFgIAawAZQmCBZngqZnlUSUjfSEVoRAA3O0guCgALQQATT1yoogAPClLyqtqvMIBfTuwAXV6unPDenERGoI0AQWEKGwB5Ipt4QWZajAo4REGvAYgerqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```typescript
export class Example {
  exampleMethodWithOverride(_: any): void;
  exampleMethodWithOverride(_: any): void {
    // should not have newline above
  }
  anotherExampleMethod(): void {
    // should have newline above
  }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "lines-between-class-members": "off",
    "@typescript-eslint/lines-between-class-members": [
      "error",
      {
        "enforce": [
          {
            "blankLine": "always",
            "prev": "method",
            "next": "method"
          }
        ]
      },
      {
        "exceptAfterOverload": true
      }
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Error on missing newline above `anotherExampleMethod`:

### Actual Result

Error on missing newline above `exampleMethodWithOverride`:
Error on missing newline above `anotherExampleMethod`:

### Additional Info

Introduced in [v8.49.0](https://github.com/eslint/eslint/releases/tag/v8.49.0) of eslint. 
Link to commit introducing the "enforce" option in the base rule:  https://github.com/eslint/eslint/commit/acb7df35b9a7485f26bc6b3e1f9083d1c585dce9
Link to base rule: https://eslint.org/docs/latest/rules/lines-between-class-members

**Comment by bradzacher** [comment]
There's no bug here - the formatting rules are just community maintained - they live in this project but us maintainers do not watch upstream for changes, nor do we fix bugs or add features. (We're actually in the process of deprecating them all)

This is missing because nobody in the community has felt motivated to add it - you're the first one.

**Comment by bradzacher** [comment]
Hi there 👋!

As you may have heard [ESLint core is deprecating its formatting rules](https://eslint.org/blog/2023/10/deprecating-formatting-rules/). We are likewise moving in the same direction and deprecating our formatting rules.

Deprecated rules will be removed in the next major version as their new home is the [eslint-stylistic](https://github.com/eslint-stylistic/eslint-stylistic) project.

If this issue is important to you please consider filling an issue over at eslint-stylistic which will be the new home for stylistic/formatting rules.

Thanks!
