### ISSUE TITLE
Enhancement: [no-unnecessary-condition] Add an option to disable autofix

### ISSUE THREAD

**Issue by bjb568** [typescript-eslint/typescript-eslint#7848]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unnecessary-condition/

### Description

The `no-unnecessary-condition` rule currently autofixes `?.` to `.`, but this is a dangerous change for projects which were developed without this rule turned on because it can cause runtime errors. I propose adding a `disableAutofix` config option so that the rule can be used for warnings without providing autofixes.

This is where the autofix is in the code: https://github.com/typescript-eslint/typescript-eslint/blob/7ad86eead76fa9e96573ac011376c1cb8c009cee/packages/eslint-plugin/src/rules/no-unnecessary-condition.ts#L639

### Fail

```typescript
const myArray: string[] = [];
const firstElementIncludesFoo = myArray[0]?.includes('foo'); // warning
```

### Pass

```typescript
const myArray: string[] = [];
const firstElementIncludesFoo = myArray[0].includes('foo'); // after autofix this throws a runtime error
```

**Comment by bradzacher** [comment]
Your example code does not error ([playground](https://typescript-eslint.io/play/#ts=5.2.2&fileType=.tsx&code=FAYw9gdgzgLgBAWwJ4EEBOaCGSBcdZoCWEA5gNoC6cAvHJQNyiSxwBmhasAogDYCmCPhBgBJCCB4BXACZ8oAMTBgaiVBmxkADBQD8AOmISZcgBQByVkrMBKRsCA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)).

The rule has handling for the case of chaining off an index signature and so the fixes it provides should be safe given the types and the code structure.

For additional safety you can turn on the `noUncheckedIndexedAccess` compiler option so that the possible `undefined` is properly represented.

If you have an example that errors and erroneously fixes in the playground, please dump it in and we can reopen and take a look.

**Comment by bjb568** [comment]
This one does error:

```js
const myArray: string[] = [];
const myElement = myArray[0];
const firstElementIncludesFoo = myElement?.includes('foo');
```

**Comment by bradzacher** [comment]
That is a known problem that's pretty-well impossible for us to track.

The layer of indirection means that we cannot add logic to check "if the thing being chained has an index signature" - that information is lost as soon as you assign it to a variable.

The incorrect types (without `noUncheckedIndexAccess`) mean that we think it must not be nullish.

> noUncheckedIndexedAccess might work well for a new project, but turning it on in an existing codebase would break existing typing.

This rule will also be painful throughout an existing codebase that doesn't have `noUncheckedIndexedAccess` turned on (as you've discovered).

All of our rules are only as good as the types you provide.
