### ISSUE TITLE
Enhancement: [no-unused-vars] Allow autofixing when it’s safe

### ISSUE THREAD

**Issue by flying-sheep** [typescript-eslint/typescript-eslint#7877]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unused-vars/

### Description

As described in #3456, autofixing this rule is disabled because things like attribute access can have side effects.

There are, however, safe instances, e.g.
- removing a unused symbol that isn’t the last symbol from an import
- turning a `import from` that only imports unused symbols into a side-effect-only `import`

### Fail

```typescript
import { Used, Unused } from 'module'

export default Used

// or

import { Unused } from 'module'
```

### Pass

```typescript
import { Used } from 'module'

export default Used

// or

import 'module'
```

**Comment by bradzacher** [comment]
The reason there isn't an autofixer for the rule isn't because it's hard to tell when it's safe - there are many easy to detect cases that are safe to remove!

Instead there's no fixer because it massively gets in the way of developer workflows!

For example imagine you have autofix on save turned on.
You write the above "fail" code with the intention of adding a usage of `Unused` in a few moments.
You hit save because you're a religious saver and ... your variable disappears.
Now you have to hit undo and hope it undoes the autofix - or retype the variable again and use it before you hit save.

It's a frustrating developer experience thing.

Another reason it's bad is because often times unused variables can be a signal that you have incomplete code - i.e. the developer has forgotten to finish something, or incorrectly written code.
If you were to silently delete unused variables (which is what would happen from CLI with the `--fix` flag) then instead of getting notified that you've got incomplete code - it'd just disappear!
Hopefully it'd get caught in tests but who knows!

For these and many other reasons - we won't be adding an autofixer.

**Comment by bradzacher** [comment]
For the specific workflow you described it would be beneficial to automatically delete the variable, for sure. However for every workflow where it's correct to delete an unused variable - there are countless others where it is not correct to.

Unfortunately there is no way for a rule to know anything about a workflow, however. A rule is dumb and simplistic - the only input it has is the current AST - so you cannot know past states and understand when it's "correct" to remove a variable. The rule sees an unused variable, it deletes an unused variable, that would be it - no exceptions.

> and habits can be changed

You're suggesting users change their habits and workflows for the sake of the occasional and small convenience of automatically deleting an identifier or two from code.

This is obviously not a good developer experience. By forcing a majority of people to change their workflows to account for a fixer - the fixer has clearly gotten in the way of the developer and is thus a bad fixer.

---

A long time ago this lint rule did have a fixer. The authors originally thought as you did "we can detect safe cases and remove them automatically" - the fixer did not last long and it was removed by popular demand because it got in the way of the majority of user's workflows.

We shan't be adding this fixer to the rule, ever.

---

If you have specific workows for which you want to add a fixer for - we encourage people to build on our tooling and release a 3rd party plugin with features we've rejected from our project.

We reject things because we don't believe they'll have broad applicability - but that doesn't mean you won't find a userbase.

**Comment by flying-sheep** [comment]
> You're suggesting users change their habits and workflows for the sake of the occasional and small convenience of automatically deleting an identifier or two from code.

I didn’t imply that all would, that’s why I’m talking about choice. I don’t understand why you’re talking about “forcing” anyone to do anything when I made that clear.

Many users chose to adopt that habit, as evidenced by the fact that many Python projects e.g. enable Ruff rule `F841` without marking it as `unfixable`. (you [can find examples here](https://github.com/search?q=%5Btool.ruff%5D+select+%28%22%5C%22F%5C%22%22+OR+%22%27F%27%22%29+path%3Apyproject.toml&type=code))

> We shan't be adding this fixer to the rule, ever.

You made a case for never adding an automatically-on one, but not a case for an opt-in one. That would be compatible with both our wishes: Nobody gets forced (again, no idea why you thought I wanted to do that), and I can choose to enable it.

If opt-in autofixing for individual rules isn’t something that ESLint supports, that’s a technical blocker, but not a reason to not strive for it.

Is there anything I missed?
