### ISSUE TITLE
Docs: Auto-add a performance warning to typed rules' "When Not To Use It"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#7918]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

Several typed rules have a similar kind of _"performance is slower with typed rules"_ notice in their _`## When Not To Use It`_. Examples:

https://github.com/typescript-eslint/typescript-eslint/blob/3cc3d0eff8e9d574d35c05c97b607a8a6ba59d9b/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md?plain=1#L98

https://github.com/typescript-eslint/typescript-eslint/blob/3cc3d0eff8e9d574d35c05c97b607a8a6ba59d9b/packages/eslint-plugin/docs/rules/prefer-reduce-type-parameter.md?plain=1#L58

How about we standardize this by adding that automatically in rule docs generation (https://github.com/typescript-eslint/typescript-eslint/blob/3cc3d0eff8e9d574d35c05c97b607a8a6ba59d9b/packages/website/plugins/generated-rule-docs.ts)?

### Affected URL(s)

https://typescript-eslint.io/rules/*

**Comment by bradzacher** [comment]
I don't know if we really want to be slapping this on every page it seems like it'd push people away because they're scared of slowness?

Really the advice is "try it and see if it's acceptable perf for your usecase" but if you aren't careful about the wording you could end up cutting people off before they even try it.

One alternative might be to instead link to the docs about type-aware linting so they have a clear docs page that explains the setup and the caveats so they can better understand things?

**Comment by JoshuaKGoldberg** [comment]
> link to the docs about type-aware linting

Yeah that's more in the direction of where I was thinking. As in, we can inform gently that type-aware linting has some concerns, but also that it's likely worth it in many codebases.
