### ISSUE TITLE
Bug: (ast-spec) `ChainExpression` is not in the callee type for `CallExpression`

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8008]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

ast-spec

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

I propose to include `ChainExpression` here:
https://github.com/typescript-eslint/typescript-eslint/blob/37f34f4eb47940762769f6fdcd1902f52870cf81/packages/ast-spec/src/unions/LeftHandSideExpression.ts#L23-L44

### Additional Info

As far as I know it's a valid ESTree syntax (e.g [playground](https://typescript-eslint.io/play/#ts=5.3.2&showAST=es&fileType=.tsx&code=CYUwxgNghgTiAEYD2A7AzgF3mpBbEGAFgJYoDmAXPAN7wAOMSdVUKAngL4BQXkUaaeAEEaXePAACAChz4ipMgH4AdAyYBKMdgxQMxMPUZ0ATAG4u3LjLwES5FWrrqpmq7NsKHR9QAMdZMhBgeAwQXDpoUPgQAA8GEAFiVB8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false))

It's just a bit strange to see this error, although I know that `CallExpression` can have `ChainExpression` as a `callee`: 

![Screen of ts error](https://github.com/typescript-eslint/typescript-eslint/assets/61150013/ef3cd6e8-73bc-441a-adc3-2d0cf72de34e)

AST snapshot:
https://github.com/typescript-eslint/typescript-eslint/blob/37f34f4eb47940762769f6fdcd1902f52870cf81/packages/ast-spec/src/legacy-fixtures/basics/fixtures/optional-chain-call-with-parens/snapshots/1-TSESTree-AST.shot#L514-L519

**Comment by bradzacher** [comment]
We wouldn't add it to `LeftHandSideExpression` because it's not a valid LHS expression.
The origin of LHSE was for the left-hand-side of an assignment: `left = right`.
This then got reused around the place because the syntax rules were the same for a number of places.

Over time however things have diverged and now LHSE is not the correct type for the entire AST.

For example - chain expressions are not a valid LHSE (`(x?.y) = 1` is syntactically invalid code) however they are a valid callee (`(x?.y)()` is syntactically valid, but semantically invalid due to optional chain short-circuiting causing the expression to be possibly undefined).

**Comment by fisker** [comment]
[`someone?.is = coming`](https://github.com/tc39/proposal-optional-chaining-assignment)

**Comment by bradzacher** [comment]
@fisker stage 1 - so not coming any time soon haha

**Comment by Josh-Cena** [comment]
FYI: [`LeftHandSideExpression`](https://tc39.es/ecma262/#sec-left-hand-side-expressions) in the ES spec includes many things that are not valid assignment LHS, such as `new Foo()`, template literals, `new.target`, etc. It's just a blanket nonterminal for anything with higher precedence than the `++` operator. `LeftHandSideExpression` has never meant "valid assignment target" because it requires algorithmic steps anyway ([AssignmentTargetType](https://tc39.es/ecma262/#sec-static-semantics-assignmenttargettype)) in order to forbid `eval` but allow `((foo.bar))`. Therefore we should make our `LeftHandSideExpression` definition in line with the spec.

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/typescript-eslint/typescript-eslint/pull/9231
