### ISSUE TITLE
Enhancement: [naming-convention] Add a selector for `typeof` types

### ISSUE THREAD

**Issue by reduckted** [typescript-eslint/typescript-eslint#8076]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/naming-convention

### Description

When writing an Angular component, sometimes you need to use an enum in a template. To access the enum, you add a property to the component that exposes the enum type. For example, if we have this enum:

```ts
export enum Size {
    Small,
    Medium,
    Large
}
```

And we want to access it in a template like this:

```html
<ng-container [ngSwitch]="selectedSize">
    <div *ngSwitchCase="Size.Small">Tiny</div>
    <div *ngSwitchCase="Size.Medium">Just right</div>
    <div *ngSwitchCase="Size.Large">Huge</div>
</ng-container>
```

Then we can put this in the component:

```ts
export class WidgetComponent {

    public selectedSize: Size = Size.Medium; // This is the property used in the `ngSwitch` directive.

    public Size: typeof Size = Size; // This allows `Size.Small`, etc to be used in the `ngSwitchCase` directive.

}
```

Ideally, the property that exposes the enum type should have the same name as the enum. I don't expect the `naming-convention` rule to enforce that, but it would be nice if I could at least require these kinds of properties to be PascalCase.

If I have this rule, then the suggested property name is `size` rather than `Size`: 
```json
{
    "selector": "classProperty",
    "format": ["camelCase"],
}
```

I could use this rule, but then the `selectedSize` property could also be called `SelectedSize`, which I don't want:
```json
{
    "selector": "classProperty",
    "format": ["camelCase", "PascalCase"],
}
```

Ideally I would want something like this:
```json5
[
    {
        "selector": "classProperty",
        "format": ["camelCase"],
    },
    {
        "selector": "classProperty",
        "types": ["typeof"], // <- Restrict to `typeof X` types.
        "format": ["PamelCase"]
    }
]
```

### Fail

```TypeScript
export class WidgetComponent {

     public size: typeof Size = Size;

}
```

### Pass

```TypeScript
export class WidgetComponent {

     public Size: typeof Size = Size;

}
```

**Comment by bradzacher** [comment]
I don't think this is a good idea because there are going to be many, many cases where this isn't what you want.

`typeof` just extracts the type of some expression - yes it can be used to reference the enum as a whole - but it can also be used for anything else.

For example:

```ts
function foo(): string {...}

const bar: typeof foo =...;
```

In this instance you wouldn't want `bar` to be named `Bar` - it's not a capitalisation that makes sense given that it is just a function.

The only cases you would want this naming convention would be `typeof` a class or an enum.

I think overall such cases are very rare and thus not broadly applicable to the community. As such its not something we shall add to the lint rule. Thanks for filing!

**Comment by reduckted** [comment]
Your example implies that I would apply the naming convention to _everything_. I would only apply it to class properties, and even then, I could restrict it to `*. component.ts` files in the unlikely event that it was still too broad.

Alternatively, couldn't I use the rule to allow _any_ naming convention (camelCase, PascalCase, UPPER_CASE, etc) and then write my own custom rule to handle these cases?

**Comment by bradzacher** [comment]
My example exists to illustrate that "typeof" is much wider reaching than you might have originally intended.

Yes, you may restrict such a selector specifically to class properties to reduce the blast radius but that just further reinforces how niche this request is.

**Comment by reduckted** [comment]
Fair enough. 

I'm happy to write a custom rule for this particular scenario, but I'd still have to add `eslint-disable` comments to suppress the `naming-convention` rule. Do you have any suggestions on other ways this problem could be solved?

I guess a different way you could look at this feature request is that I want to automatically ignore naming rule violations in specific scenarios.

In [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/advanced.md#ast-and-selectors), you can use selectors to specify where the rules should apply. Would something like that ever be considered in this plugin (I'm happy to create a new issue to discuss that further, but don't want to waste everyone's time if there's no chance of it happening 😄)

**Comment by bradzacher** [comment]
My suggestion would be to allow both camel and Pascal case for class properties and then you could use a custom limit rule to restrict the latter to just those properties annotated with a `typeof` type. Could do it syntactically and avoid type info to keep things simple.

> you can use selectors to specify where the rules should apply

The rule already has that - that's what `selectors` is for in this rule.
In the general case - no. It makes sense for the JSDoc plugin because JSDoc is comments - so adding selectors to choose what comments to consider makes sense because the rules otherwise function without selectors.
But all of our rules already use selectors because they are powered based on AST structure etc and often times it's a concert of multiple selectors that make the rule work at all - so trying to turn off specific selectors would be complicated if it's even possible.

Again though we aren't looking to create super flexible rules that satisfy every usecase - we are looking to satisfy the majority of cases and people can fork our rules or augment them with their own if they have their edge cases that they need to support.
