### ISSUE TITLE
Repo: Move eslint-plugin-tslint to a separate repo

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8118]
### Suggestion

[`@typescript-eslint/eslint-plugin-tslint`](https://typescript-eslint.io/packages/eslint-plugin-tslint) is an ESLint plugin that allows running TSLint rules within ESLint. It's made to help folks migrate off TSLint towards ESLint.

`eslint-plugin-tslint` has existed in this monorepo for many years because that was a convenient way to keep it maintained alongside our other packages.

But, we keep synced package versions (for good reason - see #7521). So `eslint-plugin-tslint` has been getting version bumps steadily for years ... despite no new issues being filed on it for quite some time. [A query for relevant issues with label `package:eslint-plugin-tslint`](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin-tslint%22+-label%3Aexternal+-label%3Atriage+-label%3A%22working+as+intended%22+) shows that we haven't had anything come up since 2020.

Keeping the package around is also a maintenance burden. For example, in #7752, its unit tests are failing with `EXPERIMENTAL_useProjectService` enabled. I really don't think we need to test the case of someone running with `eslint-plugin-tslint` _and_ the new project service.

Proposal: let's make a new repository for `eslint-plugin-tslint`.
* It won't need to automatically publish new releases weekly with the rest of our packages.
* Its only `dependencies` entry is `@typescript-eslint/utils`, which we can switch to a `^` version matcher.
* We'll still be able to actively maintain the repository if anything comes up

_(originally pointed out by @bradzacher in a private triage team chat)_

**Comment by bradzacher** [comment]
We re released over three thousand versions of that plugin due to automated version syncing - but the code hasn't changed in a very long time.

TSLint is long dead and buried by this point so most people have migrated off of it. The stragglers also aren't likely keeping up-to-date with their eslint versions (or else they'd kill tslint!)

So yeah moving it to a new repo for it to sit and no longer be auto released would be the best option for everyone, I think. Also further distances our main repo from TSLint to help people not mix up the names.

**Comment by JoshuaKGoldberg** [comment]
Moved to: https://github.com/typescript-eslint/eslint-plugin-tslint
