### ISSUE TITLE
Enhancement: Add defaults for TSESLint.RuleContext type parameters

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8147]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#supported-rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Relevant Package

utils

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Right now, `RuleContext` doesn't provide defaults for its type parameters:

https://github.com/typescript-eslint/typescript-eslint/blob/99a026fe41b4b169914352fe66e7d5d687b300bf/packages/utils/src/ts-eslint/Rule.ts#L175-L178

That means if you want to describe any arbitrary rule context the way e.g. #8146 does, you have to explicitly type out `RuleContext<string, unknown[]>`. It's a little inconvenient.

Proposal: let's add defaults to make referring to an "unknown" rule context a little easier?

```ts
interface RuleContext<
  TMessageIds extends string = string,
  TOptions extends readonly unknown[] = unknown[],
> {
```

### Additional Info

#8148 is a draft PR showing the changes internally.

**Comment by bradzacher** [comment]
I think it's fine to not provide defaults because it means that you have to specifically opt-in to the unbounded, unsafe behaviour.

This is good because it means that if someone is writing a rule and wants to pass the context around they have to pass the parameters - preventing unsafe code.

For example this is a very common pattern I've seen:

```ts
const someUtil = (context: RuleContext<MessageIds, Options>) => { ... };

const rule = createRule<MessageIds, Options>({
  // ...
  create(context) {
    someUtil(context);
  },
});
```

You might say "but if they move the function into the `create` body they could remove the param entirely!" and you're not wrong - but who are we to dictate others preferred style?

If we default the type params then it's valid for the user to define `ctx: RuleContext` for said function - which means that when that function calls eg `contex.report` it will have zero safety around the message ids!

I'd much rather export an obviously unsafe version of the type like we do for the `RuleModule`

https://github.com/typescript-eslint/typescript-eslint/blob/99a026fe41b4b169914352fe66e7d5d687b300bf/packages/utils/src/ts-eslint/Rule.ts#L636

**Comment by JoshuaKGoldberg** [comment]
Makes sense to me! Closing as wontfix. Thanks!
