### ISSUE TITLE
Configs: Remove no-unsafe-enum-comparison from recommended

### ISSUE THREAD

**Issue by pgsandstrom** [typescript-eslint/typescript-eslint#8168]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

The suggestions from [no-unsafe-enum-comparison] are of two types:

1. Nice to have: I wrote `myEnum === 'foo'` when I should have written `myEnum === MyEnum.FOO`.
2. Annoying: I wrote `myEnum === someStringFromExternalService`.

While the first type is decent, the second type is frustrating and requires workarounds or disabling of the rule that often does not improve the code.

This makes me feel like the rule is not up to par with the other rules in the recommended set. The recommended set should be reserved for rules that either catches actual bugs, or do not annoy the user. This rule does neither.

Since the pruning of the recommended rules in the v5 release, this is the only recommeded rule that regularly causes confusion at my company. I undestand that this change should only be made at the next major release.

Other discussions related to this rule:
https://github.com/typescript-eslint/typescript-eslint/issues/7219

**Comment by Josh-Cena** [comment]
Could you give a more self-contained example of how you can both end up with an enum-typed variable and a string-literal-typed variable? Are you hand-writing types for some external service?

**Comment by pgsandstrom** [comment]
Often it comes down to us receiving a value from an external service that needs to be compared to a value that we have hand-written an enum type for, yeah. And sometimes we have enum-types that has been auto-generated by different types of services.

To be clear, I know there are workarounds for this, such as type assertions. I just don't think that using type assertions in these situations actually improve the code, so the suggestion produced by the no-unsafe-enum-comparison rule is more a hinderance than a help.

**Comment by bradzacher** [comment]
I don't think that your specific usecase of "an external service with types that are `string` compared against our local types which are an enum" is a good motivation for us to remove this from the entire recommended set.

Avoiding such comparisons is a best practice because it means that you can safely refactor code - for example if you define your local enum as `enum Foo { A = 'a' }` but the "external service variable" is just typed as `string` - then there's zero safety there! If the external service changes its value there's no way to validate that you've also changed your local value - and the opposite applies too.

Instead of this being a weakness in the rule - instead I'd counter and say that this is a weakness in your codebase's types. Ideally the "external service variables" should be typed with your enum, or the external service types should define an enum which it uses as the types of the variables.
I don't know anything about your project's setup - but in most TS codebases I've seen there are ways to control the external type boundary - either via a patch of the `node_modules` folder, or by changing the code generator, or some other mechanism depending on your stack.

---

v6 has been out for 7 months now with this rule being added to the recommended set and this is the first feedback we've heard of this type. This leads me to believe that it may be a more isolated case.

It's also worth noting that it's okay if a recommended rule doesn't apply to every single codebase. There's a lot of different styles out there, and every codebase requires different safety guarantees. As an example we include both `no-explicit-any` and `ban-ts-comment` in our recommended set because using `any` or ts comments is almost always a code smell - but I know of some codebases that turn these rules off because they feel that they get in the way of their style and workflows, and they're okay with sacrificing some safety for those.
That doesn't mean we should remove them from the recommended set - they're still the best practices to achieve the safest codebases!

I think this is the same situation - in the vast, vast majority of cases one should not compare an enum against a non-enum value because it introduces a point of unsafety and a source of pain during refactors. However in some codebases it may be acceptable to have this unsafety for various reasons such as your codebase. That's a completely valid outcome!

**Comment by pgsandstrom** [comment]
Well, I did link to another discussion raising very similar concerns, and I created this issue after the third instance of this rule confusing someone in my company. Sure, they were junior developers, but it was a hinderance to them.

I guess we have a different view of what a recommended set should contain, and that is of course valid :) Perhaps I'll check if someone else has raised similar issues when the time comes for the next major release.
