### ISSUE TITLE
Bug: [no-floating-promises] ignoring references makes this rule ineffective

### ISSUE THREAD

**Issue by erquhart** [typescript-eslint/typescript-eslint#8170]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=IYZwngdgxgBAZgV2gFwJYHsIwOYFNkCC40AasADYK4AUAlDAN4BQMMATvgmxEwL5NNQkWIhQYseZGUo16zVgHoFMZAAtUIGBpjB45dMDQRsMAA5t0AWw24ANDACSMAFYIQyGKuCnTuCLgATFXQdEBBUbCxUD2QQ3QA3YDZUYAAjclwWGChMdxhEmRgAXhx8ImFpKjosjmQuLAYYAMNgAC58iioYfn4gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oDN4OBDfMwDmtYtA4BbSshTooiaBOiRwYAL4h1QA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
async function getAsyncValue() {
  return
}

async function getValue() {
  // this is a floating promise, I just happened to assign it to a variable
  const value = getAsyncValue()
  return { data: value }
}
```

### ESLint Config

```javascript
module.exports = {
  parser: "@typescript-eslint/parser",
  rules: {
    "@typescript-eslint/no-floating-promises": ["error"],
  },
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    // ...
  }
}
```

### Expected Result

Expected an error because the promise is never awaited within the function body.

### Actual Result

No error, and the function returns an unawaited promise.

### Additional Info

I've seen the other issues about this, and I'd like to ask if at all possible that it not be comment-closed (totally get it if you need to, though). This rule has been mostly ineffective for me, and I'd really like to understand it better.

As I read it, the point of this rule is to help me catch promises that I've accidentally forgotten to await, which for me happens often.

**I would guess that about 80% of the time I'm assigning the result to a variable, and 80% of those times I'm not expecting that variable to contain a promise.**

I've read #3359, #5749, and #6766, where it's simply stated that this is how the rule is designed, and that it's assumed the promise is referenced to be awaited later. It is also suggested to round out this behavior with other rules (no-unused-vars is mentioned, plus a couple others), but these rules don't actually address the issue at hand - I have them active on my project.

If this is a limitation on how far we can take linting our typescript, I totally understand that! I don't know much about how eslint actually works, and I suspect this is the case. But if it's just down to differing ideas on what makes this rule useful, I'd again like to posit that, I expect, it's only useful for the average person in a fraction of relevant cases, as promises are very often awaited for their values, which are generally assigned to variables. I expect that the majority of use cases aim to await every promise at some point within a given function body.

The basis being offered is that this rule is delineating between floating promises and referenced promises, but in practice it's delineating between promises that purely produce a side effect and promises that return a value, and only handles side effect promises.

Any help in understanding or corrections on approach are  greatly appreciated!

**Comment by bradzacher** [comment]
The reason that we don't handle this case is because, as you stated

> it's assumed the promise is referenced to be awaited later

For example imagine this code:

```ts
function foo() {
  const prom = getPromise();
  return { prom };
}
```

By your reasoning this is an error. However this is completely reasonable code because one can imagine the usage of the function like this:

```ts
await foo().prom
```

Now that promise has been awaited as expected.

There's no possible way for us to track promises across function / module boundaries so we can't know if a promise is awaited or not.

So we have two options - assume promises assigned to a variable are handled correctly - or assume that they're not.

If we assume that they're not you can imagine how problematic this would be for many completely valid patterns. It would cause a large number of false positives on code like the above and force people to write different code to work around it.

So it's more reasonable to assume stored promises will be awaited because, in general, this is the case.

---

There is a big limitation for linting in that we only have two ways to check code - syntactically (via the AST) and via types. Neither check gives us a way to track values at all - we can't flag the fact that `getValue()` returns an un-awaited promise and thus its return value must be used and the `.data` property must be awaited.

It is possible to build rules that do this or parts of this - but there is absolutely massive complexity in doing so - it would be a monumental effort but it would also be for very small returns because these sorts of bug vectors are rare.

It's hard to tell exactly what your bug vector is here - but I assume that you meant to do something like

```ts
async function getValue() {
  // this is a floating promise, I just happened to assign it to a variable
  const value = await getAsyncValue()
  return { data: value }
} 
```

This is one of the reasons that I personally like `explicit-function-return-type` - because your bug would have been caught by annotating `Promise<{ data: T }>`, as `Promise<{ data: Promise<T> }>` is not assignable to it.

**Comment by erquhart** [comment]
Thanks so much for the breakdown on this, linting limitations are about what I expected. And yeah, going the other way and assuming assigned promises are not handled correctly would produce a ton of false positives. Explicit function return type is a good backup for this, agreed.
