### ISSUE TITLE
Rule proposal: Prefer a named interface or type over inline object literals

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8320]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Sometimes folks write inline object type literals to represent objects in type annotations. For example, function parameters; return types; variable declarations. Two problems I see with these inline object literals:

* They aren't named: so TypeScript errors and refactorings aren't as good
* They clutter the syntax space around the function

Proposal: let's have a rule that bans object type literals in type annotations, with a configurable minimum number of object properties to report on? Let's say, banning types with >= 2 properties by default?

### Fail Cases

```TypeScript
let myValue: { apple: boolean; banana: boolean };
```

### Pass Cases

```TypeScript
interface Values {
  apple: boolean;
  banana: boolean;
}

let myValues: Values;
```

### Additional Info

I'm not sure what the exact list of syntax locations should be. But _"all type annotations"_ feels like a good start to me.

For auto-fixing, I can imagine this being useful in JSX-oriented libraries such as React if the auto-fixer creates a type with a name like `{Component}Props` when the type annotation is the first argument of a function that can be a JSX component.

**Comment by bradzacher** [comment]
The issue I have with this is that it is a really, really heavy style to enforce.
Sometimes you do just want a one-off, local, anonymous type for something.
sometimes it doesn't really matter if you have an inline type or not.

EG with react components it's often "fine" to define the prop type inline because nobody wants the type directly unless you're wrapping the component - and TS can do the rename just fine for the component callsites.

Personally I'm a -1 to this living in our project - I think something like https://github.com/typescript-eslint/typescript-eslint/issues/7670 is much more valuable and would be less "opinionated" than this style.

**Comment by JoshuaKGoldberg** [comment]
Right! It didn't occur to me that #7670 would cover this as well. I'll mark that one in the v7 milestone to make sure we get to it. That rule proposal feels more and more valuable as time goes on. Thanks!
