### ISSUE TITLE
Bug: [prefer-optional-chain] Issue with check on `null` and `undefined`

### ISSUE THREAD

**Issue by capsuleman** [typescript-eslint/typescript-eslint#8380]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

[link](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=MYewdgzgLgBAhjAvDADAbgLAChSVgIyVUy2wUQpgFcwATAUwDMBLMe2mAH05kIuTBUANkK48%2BlGgxZtaJcpLpNW7MbySLpKjt3X8YgkSQkDho3QuRTlstSepKZ7YxtMi7rh1tlogA&eslintrc=N4KABGBECmAeAu0B2ATAzpAXGA2uCUADgDYCuA5gJZKYAC8AnodGgMYBOlh8AtC8dXgB6dtFYB7ALaTkKaCkj4AugBp8kQgEN2aaOyxR6TFhy69%2BgoVp17IaiBu272AeW6VxSDNlAEi7cQArMXgDSHg2TwAzSnIAOkC0T0UIAF97KHZSYhYDXwJII2Y2Tm4%2BNAEkYUJRKL0ecXdPTWIeVgALTWowvQD9fFSQVKA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTokBskANODUgk8mZNDaURAV3T8aUeLAAmUjO0ici6AB5sBAXxD6gA&tokens=false)

### Repro Code

```TypeScript
const a = 0;
const b = 0;

a === undefined || b === null || b === undefined; ❌
a === undefined || b === undefined || b === null; ❌
b === null || a === undefined || b === undefined; ✅
b === null || b === undefined;                    ✅
```

### ESLint Config

```javascript
{
  "extends": [
    "plugin:@typescript-eslint/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json"
  },
  "rules": {
    "@typescript-eslint/prefer-optional-chain": "error"
  }
};
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "es6",
    "strict": true,
    "module": "esnext"
  }
}
```

### Expected Result

All these lines should be ok and I should not have to switch 2nd and 3rd statement to pass the rule check.

### Actual Result

Error on first 2 lines

**Comment by peanutenthusiast** [comment]
Hi, @bradzacher I've been looking into the issue, and could use pointers on where/which code to modify. Wondering if the line below

https://github.com/typescript-eslint/typescript-eslint/blob/28b94625e58d137144475ff72d39e0536d236ba3/packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts#L133

might be good to look into.

**Comment by kirkwaiblinger** [comment]
This is a very confusing stuff. I think I've refined the conditions for the false positive a bit, though.

It looks like you need to meet the following conditions:

Within an arbitrary length `||` chain, have 3 consecutive components:
1. any kind of positive nullish literal comparison (i.e. `expr === null` or `expr == undefined`, but NOT `expr != null`) against an expression that will be narrowed to a non-nullish type after the `||`. (i.e. `document.querySelector('') === null` but NOT `document.querySelector('') === undefined`)
2. a _strict_ positive comparison between a nullish literal and a variable (or, member expressions also appear to work)
3. a _strict_ positive comparison between the _other_ nullish literal not used in 2. and the variable used in 2. (or, if doing so with a member expression, the same member expression, where optional chaining does not appear to be compared strictly)

So, for example, the following will flag
```typescript
window == 3 || window > 25 || window === undefined || undeclaredVariable === null || undefined === undeclaredVariable || undeclaredVariable === 42
```
due to the subexpression `window === undefined || undeclaredVariable === null || undefined === undeclaredVariable` (where the fact that `window` is not typed to include `null` is significant).

I plan to keep poking at this to try and fix it, but just leaving this information here in writing in case I give up/forget and it's helpful to someone else, or jogs one of the previous authors' memories

**Comment by kirkwaiblinger** [comment]
Note that we also trigger an analogous false positive with the logical inverse of the expression (after applying DeMorgan)
`window !== null && b !== null && b !== undefined`
