### ISSUE TITLE
Docs: describe the process of closing invalid issues in more detail in the Issue Flow docs

### ISSUE THREAD

**Issue by auvred** [typescript-eslint/typescript-eslint#8435]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

The current documentation doesn't clearly say when invalid issues should and should not be closed. As I understand it, an issue can either be closed or labeled as "awaiting response". Therefore, if a "duplicate" or "working as intended" label was added to the issue, and that issue doesn't have "awaiting response" label, the issue should be closed.

There is also no mention of "wontfix" and "evaluating community engagement" labels. IMO it would be nice to mention them there.

### Affected URL(s)

https://typescript-eslint.io/maintenance/issues#issue-flow

**Comment by bradzacher** [comment]
"wontfix" is really just a convenient way of signalling to people why we closed an issue.
If we just close an issue without a tag sometimes people can see it as opportunity to continue commenting or open a new issue and convince us.
The wontfix tag is really us saying "we've made our decision and that decision is no".

Generally only used to close enhancement requests.
Rarely also might be used to close a bug as in "this bug requires some really convoluted state to trigger so we're okay not fixing it - wontfix"

----

`evaluating community engagement` is a newer part of the workflow that josh introduced.
it serves as a way for us to "put a pin" in an issue re-evaluation in a few months.

the idea is that we as maintainers *_generally_* have a pretty good idea about how people write code and what styles / standards people want.

However there are some cases where we can't necessarily leverage our "gut", for example:
- if we don't have experience in the area (eg there's a library/framework that people use that we've never touched) then we don't know the idiomatic patterns associated with that thing.
- there is some new syntax or a new feature then we're not sure of how people may the feature.
- a user makes a compelling argument on something we otherwise would have closed.

The ECE tag allows us to leave an issue open in a state where we're clearly saying "if this is important to you please react / comment". The idea being that in a few months we can come back and see if there has been any community engagement on the issue. If there has been a decent chunk then we take it as good signal that this is something that has value to the community and we can mark it as "accepting PRs". If there hasn't been then the opposite is true and we can reject and close the issue as a "wontfix".

In a way it also allows us as maintainers to step back from a discussion and take some time off - allowing us to come back later with fresh eyes and a clear mind. There have been a few times that I personally have found I've gotten "tunnel-vision" in an issue and missed the point -- sometimes you're talking past one another, sometimes you just miss the point entirely, sometimes you don't have the experience to understand the value, sometimes you had a bad day, sometimes the requestor is coming across as a 💩 and it rubs you the wrong way -- whatever the reason sometimes taking a step back can help you see a different perspective and not reject a useful request.
