### ISSUE TITLE
Docs: [unbound-method] Mention restrictions around this params such as in `Reflect.apply`

### ISSUE THREAD

**Issue by andreww2012** [typescript-eslint/typescript-eslint#8452]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.tsx&code=MYGwhgzhAEAqCmEAu0DeBYAUNaBbeSAFgPYAmAFAJRpY44BK8AZiPMEgHRgAO3IAnuSIBLCBwBGwgHal4pALIESpADTQRENWABOAcwCu%2BKUgiUA3LWgBfLJcky5iomSo1sdAPQfoHX5ZuYAUA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6WJgIwHsOATWgFtE%2BABbc%2B6KImjRu0SODABfEMqA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Repro Code

```TypeScript
class Test {
  method() {
    Reflect.apply(this.bindedMethod, this, arguments);
  }

  bindedMethod() {
    // ...
  }
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/unbound-method": ["error", {
      "ignoreStatic": false | true
    }]
  }
}
```

### tsconfig

```jsonc
Not relevant
```

### Expected Result

I think cases like `Reflect.apply(this.bindedMethod, this, arguments)` should not make this rule report. 

### Actual Result

It reports an error.

**Comment by Josh-Cena** [comment]
The rule is never aware that a method is able to bind the `this` value, because it never knows. Otherwise, you have to special-case a lot of array methods too.

**Comment by bradzacher** [comment]
Josh is correct - the rule is purposely shallow in how it reports on usage. It does not understand the inner workings of function calls - even those in the stdlib. Mostly because the complexity of building out support for all of the various forms that are safe is large and expensive and ultimately not worth the cost - both maintenance cost and runtime cost - given that such usecases are super rare in the general case.

Eg most people don't use the `Reflect` API because is relatively new and in particular `Reflect.apply` is really no better than the more direct `method.apply`.

I'm okay with the rule not handling these cases. If we want to document the edge case, we can?

**Comment by andreww2012** [comment]
Thanks for the response - I largely agree with you, I wasn't even sure if it's worth reporting.

Still want to leave here my implementation idea just in case there's any demand for covering such use case:
- Only check static method usages, for example `Reflect.apply`, `Array.prototype.map.call(...)` and not `someVar.map(...)` (but perhaps `<array literal>.map(...)`?
- Make this check opt-in if it runtime costly.

**Comment by Josh-Cena** [comment]
This rule already relies on type information, so checking `Reflect.apply` is not any harder than `someVar.map`, because we can use type information to know that `someVar` is an `Array`. The only problem is whether it's worthwhile to do so because we tend to not like carving special cases for built-in functions.

**Comment by JoshuaKGoldberg** [comment]
Retargeting the issue to indicate it's a docs one. We can mention the restriction in the docs. 👍
