### ISSUE TITLE
Repo: Enable alphabetical (natural) sorting of fields

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8479]
### Suggestion

Spinning out of https://github.com/typescript-eslint/typescript-eslint/issues/8477#issuecomment-1946131383: we're interested in maybe enabling https://eslint-plugin-perfectionist.azat.io/configs/recommended-natural or similar to enforce alphabetical sorting of fields. That likely includes methods and properties on classes, interfaces, objects, type aliases, and so on.

For reference I've used that rule in my http://github.com/JoshuaKGoldberg/create-typescript-app for quite a while now and have been very happy with it.

**Comment by JoshuaKGoldberg** [comment]
Blocked on https://github.com/azat-io/eslint-plugin-perfectionist/issues/111. We sometimes use comments to delineate specific members of enums.

**Comment by abrahamguo** [comment]
@JoshuaKGoldberg Here is some info that I discovered while working on #8726, that you might find helpful when you begin working on this!

- In `eslint.config.mjs`, it seems like the pattern is to `// register all of the plugins up-front`. However, because of an interesting coincidence, this _breaks_ for `eslint-plugin-perfectionist`:
For the six existing ESLint plugins where we are using a preset (`@typescript-eslint`, `eslint-plugin-eslint-plugin`, `jsdoc`, `jsx-a11y`, `react-hooks` and `react`), it is unnecessary to register them up front, since those plugins are registered again in the preset. However, it does not break anything either.
For `eslint-plugin-perfectionist`, it _does_ break to register it up front in addition to using a preset. The reason is because `eslint-plugin-perfectionist` has two completely separate JS files — an ESM build and a CJS build. When we `import` `eslint-plugin-perfectionist` into `eslint.config.mjs`, we pull in the ESM build, but inside `compat.config()` when ESLint pulls in the plugin, it `require`s it, thus pulling in the CJS build. This causes ESLint to complain that two distinct object references are both trying to register themselves under the name `eslint-plugin-perfectionist`. By coincidence, none of the six existing double-registered ESLint plugins have this issue.

- As mentioned in #8733, `yarn lint-fix` does not work on `packages/eslint-plugin`. I was unable to determine the root cause of this issue.
- Several files in the root of the repo were either not linted (`.github`, `tools`), or not properly ignored from linting (`.nx/cache`, `.yarn/releases`)
- `yarn lint` was very slow due to the build step, which seemed unnecessary for this task. Therefore, I ran eslint directly with caching and progress (`DEBUG=eslint:flat-eslint eslint . --cache`) which seemed much more performant for this task. At times, when autofixing, I had to increase Node's memory with `--max-old-space-size`.
- Pretty obvious, but I autofixed one rule at a time in order to easily review changes.
- At times, when autofixing, some unrelated things were removed, such as optional chaining or `=== true/false` checks. This appeared to be related to something with typed linting, and potentially how I was running ESLint. In any case, I was able to manually revert those bad autofixes with no issues.

**Comment by JoshuaKGoldberg** [comment]
Marking as blocked on the v8 launch because the `main` <> `v8` branch merge conflicts from doing this would be _infuriating_. 😂

**Comment by abrahamguo** [comment]
@JoshuaKGoldberg, just curious — what did you end up doing with `.git-blame-ignore-revs` (https://github.com/typescript-eslint/typescript-eslint/pull/8726#issuecomment-2012225194)?

**Comment by JoshuaKGoldberg** [comment]
I figured we could add that in after the PRs are merged. We won't know the full list of commit hashes until then. 🤷

**Comment by JoshuaKGoldberg** [comment]
Note from https://github.com/typescript-eslint/typescript-eslint/pull/9842#discussion_r1724978173: we'd like to customize the [`perfectionist/sort-imports` `groups` option](https://perfectionist.dev/rules/sort-imports#groups) at some point.

**Comment by JoshuaKGoldberg** [comment]
Notes, too, on incorrect comment placements:

* https://github.com/typescript-eslint/typescript-eslint/pull/9848#discussion_r1725014602

**Comment by bradzacher** [comment]
Suggestion @JoshuaKGoldberg - lets disable sorting on enums.
So much of our codebase is setup with enums sorted by value and sorting by label breaks that really nice value ordering.
EG:

```ts
enum BagOfValues {
  Foo = 1,
  Bar = 2,
  Baz = 3,
  Bang = 4,
}
```

Is much better than

```ts
enum BagOfValues {
  Bang = 4,
  Bar = 2,
  Baz = 3,
  Foo = 1,
}
```

Or for a real example:

https://github.com/typescript-eslint/typescript-eslint/blob/90cebbba5a3648f997c3009919266715103f3370/packages/type-utils/src/isTypeReadonly.ts#L13-L20

Is much better than

https://github.com/typescript-eslint/typescript-eslint/blob/e04faa59c77a5a4889d30623216f2acdd5ad9a3e/packages/type-utils/src/isTypeReadonly.ts#L15-L22
