### ISSUE TITLE
Bug: consistent-return issues with some function signatures

### ISSUE THREAD

**Issue by ST-DDT** [typescript-eslint/typescript-eslint#8576]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=GYVwdgxgLglg9mABAgwggznANgUwDJwDmAFFAJ4AOOAXIulAE4xiECUtwAhlujogD6IAbnBgATRAG8AsAChEiGMESlKfALybEAcnpicDBttZS5ChQxxQQDJFx44A3GcQBfOa6A&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6MgeyeUuX0Ra1oifLGhN0URNGgdokcGAC%2BAGkWRkI-MwDmqDFmyQAVsgAmHMpMPYoAWw5nEkyEVLIK1fAttLFfpSA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkeAhpgObp4VTolHoAebANOBqR4sACYBXDACVOsVBILF2kIuPSRBNKKMkYVnbn01DaJPJmTQ2lCxPRbhagKLxkNsHYemoY9NFRGeiUidi9HMwtkRABJIjwsInpUMMx7CLAAekywABUAC050MEZiuCIAM2QmEjASRH9kKuhk1ABPMArYTDAAQgAjCTQxEqIR-PoAN2K8WDB%2B4sx0acwEkeQiT0LPEnKqpgA6QeGDgCsSYh9IEgBraIAZZH6AYULoG9T0q9bYAHcAZTa8UKBGgABF0BV6FI8DEkN08GRbGlvNpIEsLqhpgApC5EACy4ikGmR9iEAF9HJBeAEJH52ABtK5qPwAfV0xLIGUgYmQ5hM2myYCWAEchksRl0enhtng2g0xLBoML0IE1p5OIiwMQwPB6NBsP8wABiABMpoAHAAGK4JcyZXaWfAkTL0FCK6CZBJISBCAC6IHJQA&tokens=false

### Repro Code

```TypeScript
function onConsoleLog(type: string): false | void {
  if (type === 'stderr') {
    return false;
  }
}
```

### ESLint Config

```javascript
{
  "rules": {
    "@typescript-eslint/consistent-return": "error"
  },
  "settings": {
    "jsdoc": {
      "mode": "typescript"
    }
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "target": "esnext",
    "moduleResolution": "node",
    "module": "esnext",
    "strict": true,
    "noEmit": true,
    "declaration": true,
    "stripInternal": true,
    // These are configs specifically for !build and have to be reverted in the tsconfig.build.json
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true
  }
}
```

### Expected Result

No error.

### Actual Result

Expected to return a value at the end of function 'onConsoleLog'. 1:10 - 1:22

### Additional Info

The onConsoleLog is used/specified by vitest: 

- https://vitest.dev/config/#onconsolelog

Or would you rather consider the function type on vitest side to be flawed?

**Comment by bradzacher** [comment]
This is working as intended.
The rule is telling you that all code paths should return a value as that is the style you've chosen to enforce by using the rule.

You can't opt-out of the style by annotating the return type with `| void`.

> Or would you rather consider the function type on vitest side to be flawed?

Definitely yes. For the above reason and additionally because using `void` in a union is generally considered as a code smell.

`void` is a special type in TS and it means many things depending on where it's used. To a consumer `void` means "you can ignore the return type". Eg it informs the user that storing the return type is incorrect.

From this you can see that it's kind of nonsensical to use `void` in a union that means you have "the function returns a boolean or you can ignore the return type". Huh??? Which is it? Am I inspecting the return or not? If I call this what should I do?

If you instead use `| undefined` then you're saying to the user "it returns false or undefined". Okay that makes sense now - I should always care about the return type.

To be honest I'd consider this API even more flawed because what it essentially defines is a weird boolean - it defines a function which returns two possible values. Sounds a lot like the return type could just be `boolean`.

**Comment by ST-DDT** [comment]
It looks like I misunderstood the rule and that it is not intended for users of TypeScript.
I think this issue can be closed.
Could you please report the flawedness to vitest, so that they can address that?
I'm only confident in expressing the what but not really the why.
