### ISSUE TITLE
Bug: @typescript-eslint/no-unsafe-assignment doesn't work with multiple casts

### ISSUE THREAD

**Issue by toasted-nutbread** [typescript-eslint/typescript-eslint#8594]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&fileType=.js&code=PQKhAIAEBcE8AcCm4DeBXAdgawwewO4YC%2B4IwAsAFADGuGAztOAB4CM4AvOAFIDKA8gDkAdPACGAJ3qIAFAHJWcgJQBuKrQZNmAJk7hQEGAmQoMaALYAjRBJJlwMtqqrq6jcLHZcDUOElSYOATEpMAOfEKiktLyikrONG5MsLreYL7GqGZWNnZhMp4JrprgAF5e%2BulG-qYW1rahDj7VJoF4hHnhAiLiUrIKyvFqiSXNfibZ9Z2lqZWG4wHY7SH2MhE90f1xRSP0uAA2iML7uADmMgDabAA0LNq3ng-3Zay3MwC6CUA&eslintrc=N4KABGBEBOD2sBdIC4wOgVwKYBpxSwA8EsA7AEwGcUwBtfAXTwkgAcBDaSraGyAAQQBPVlkoBjaAEtWCALRiANlNIIA9By49IzKJu7QA8rKmxS1VKAgss4gLbsAaj0qnSNAEwAGDx90tKWAxocSwAFREsPjtYcgxFKP8Ce3YAMSx2BGCxGitrFgBzRVgAI3ZFACUsLOh3VAAzcu4klik7VmUscgBldClxJFR0bHwIAF8ktjgAK1tBulHrSAA6NWmJM3qpAuX1s0hFhnwJ-EgyADdcxcgSuAB3Axph3Guxb18nzBf8yDusEqIJHMbgsaC%2Bx10bEUGAKKlB9B%2BgkiEmksgUlGUqgOECYp22pFg0CwAAVMiRavDrgAqXaBdyTGkIaiMSGYBKgvIsJGiFEyeRKFTqAlyDDmdj1LBydiUVwFUh2MjzM7QOC8Y4gMZAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEk8sAJgK4YVQCiAygEwAM33SABpwNSHgCGmAObo8bSFz4Dho2tAAW6aAGsAUmUp5MTdCJpR6zDACV0JWKiYFiCoo3SqLkEseTR5IxMzNShfTH88ADkWVABhLV1DMGNTczF3AEkkVH9kPABBIgBPNlSQ73DIgAVMWEQsPGLMonzkCVyALwkXIjLg9NoSJkRETHsSbMRc6Hyi5qIGdAAPdkw6zGSAMw6SCrESHWREABlkACME7R02HdQ9wahziT2AVUxUBQA6LzFEHo0yWAAF9HuJig1kgBtAC6olBokgyCI0CcSzYUNCkAAVF8AFZkUQw9KQFaopjoyiY7zuJYAfSsLHskCJIGBQA&tokens=false

### Repro Code

```TypeScript
/** @type {unknown} */
const x1 = JSON.parse('1');
const x2 = /** @type {number} */ (x1);

const y1 = /** @type {unknown} */ (JSON.parse('1'));
const y2 = /** @type {number} */ (y1);

const z1 = /** @type {number} */ (/** @type {unknown} */ (JSON.parse('1')));
const /** @type {number} */ z2 = /** @type {unknown} */ (JSON.parse('1'));

console.log([x1, x2, y1, y2, z1, z2]);
```

### ESLint Config

```javascript
{
  "root": true,
  "extends": [
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2022,
    "sourceType": "module",
    "ecmaFeatures": {
      "globalReturn": false,
      "impliedStrict": true
    },
    "project": [
      "./jsconfig.json"
    ]
  },
  "env": {
    "browser": true,
    "es2022": true,
    "webextensions": true
  },
  "plugins": [
    "@typescript-eslint"
  ],
  "ignorePatterns": [
    "*.json",
    "*.ts"
  ],
  "rules": {
    "@typescript-eslint/no-unsafe-assignment": "error"
  }
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "module": "ES2022",
    "target": "ES2022",
    "checkJs": true,
    "moduleResolution": "node",
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "strictPropertyInitialization": true,
    "suppressImplicitAnyIndexErrors": false,
    "skipLibCheck": false,
    "baseUrl": ".",
    "paths": {},
    "types": []
  },
  "include": [
    "*.js"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

### Expected Result

Expected that it doesn't take two assignments to cast an `any` to a different type after first casting to `unknown`.

### Actual Result

Requires two assignments or else the rule fails.

**Comment by bradzacher** [comment]
[playground with TS instead of JSDoc](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=MYewdgzgLgBAHgRgFwwK5gNZhAdzDAXhgCkBlAeQDkA6ABwEMAnCAUwAoByBDgSgG4AsAChQkWHABMhGG0Q8Y9CDDCoAtgCMWjQUOGjoMAJ4JpbMlTpNWnbj3mK0mbHh37YhqUTbH7SlRq0dPXADAC8TLzMKGgZmdi5eOwUldCxcfAd-TW1gsRhQiRQsrVNzGKt4219HNJdhXIgQABsWaiaQAHM2AG1EABp4CQHjYaH8hAGCgF1%2BYSA&eslintrc=N4KABGBEBOD2sBdIC4wOgVwKYBpxSwA8EsA7AEwGcUwBtfAXTwkgAcBDaSraGyAAQQBPVlkoBjaAEtWCALRiANlNIIA9By49IzKJu7QA8rKmxS1VKAgss4gLbsAaj0qnSNAEwAGDx90tKWAxocSwAFREsPjtYcgxFKP8Ce3YAMSx2BGCxGitrFgBzRVgAI3ZFACUsLOh3VAAzcu4klik7VmUscgBldClxJFR0bHwIAF8ktjgAK1tBulHrSAA6NWmJM3qpAuX1s0hFhnwJ-EgyADdcxcgSuAB3Axph3Guxb18nzBf8yDusEqIJHMbgsaC%2Bx10bEUGAKKlB9B%2BgkiEmksgUlGUqgOECYp22pFg0CwAAVMiRavDrgAqXaBdyTGkIaiMSGYBKgvIsJGiFEyeRKFTqAlyDDmdj1LBydiUVwFUh2MjzM7QOC8Y4gMZAA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEk8sAJgK4YVQCiAygEwAM33SABpwNSHgCGmAObo8bSFz4Dho2tAAW6aAGsAUmUp5MTdCJpR6zDACV0JWKiYFiCoo3SqLkEseTR5IxMzNShfTH88ADkWVABhLV1DMGNTczF3AEkkVH9kPABBIgBPNlSQ73DIgAVMWEQsPGLMonzkCVyALwkXIjLg9NoSJkRETHsSbMRc6Hyi5qIGdAAPdkw6zGSAMw6SCrESHWREABlkACME7R02HdQ9wahziT2AVUxUBQA6LzFEHo0yWAAF9HuJig1kgBtAC6olBokgyCI0CcSzYUNCkAAVF8AFZkUQw9KQFaopjoyiY7zuJYAfSsLHskCJIGBQA&tokens=false)

We do not support JSDoc assertions in any rules because syntactically they don't exist. Syntactically they are just an expression wrapped with a pair of unnecessary parentheses.

This isn't a new thing - no type-aware rules have ever supported them. It's not something we're looking to support because it's a special case that requires custom, special case handling all over the place.

The same goes for any JSDoc comments actually. None of our rules support checking the comments and thus the only support we have for them is incidental - eg we can't check a variable's type annotations, only the resulting type.
