### ISSUE TITLE
Accepting of TS specific React rules?

### ISSUE THREAD

**Issue by milesj** [typescript-eslint/typescript-eslint#865]
I have written a handful of TS specific React rules that I internally use (not public at the moment). I would like to make them public but don't really want to manage something like `eslint-plugin-react-typescript`.

Would you be open to accepting them here? I noticed tslint has a few React rules, so it may be viable.

**Comment by bradzacher** [comment]
Do you know if `eslint-plugin-react` would be receptive to them?
Though I doubt you personally would want to contribute them there because it's a pure JS codebase.

Maybe we should create a separate `@typescript-eslint/eslint-plugin-react` within this repo, so that we can keep the ruleset separate?

I'm not sure what the best solution is tbh.
Part of me feels like putting them into our base `eslint-plugin` might "open the floodgates" so-to-say, so maybe separating them is a good idea?

Hmm... I need to think on this some more.

I'd be interested to hear @JamesHenry's opinion on this.

**Comment by glen-84** [comment]
They should be separate IMO, not everyone is using React. The Angular rules are separate, for example.

**Comment by milesj** [comment]
@glen-84 Is that a no for `@typescript-eslint/eslint-plugin` or `@typescript-eslint/eslint-plugin-react` or both?

**Comment by glen-84** [comment]
That's a decision for the maintainers, I just don't think that it should be in the generic configuration (`@typescript-eslint/eslint-plugin`).

Regarding `@typescript-eslint/eslint-plugin-react`, that's again up to the maintainers, and whether or not they want these rules to be mixed in with the others WRT issues, PRs, etc.

Would it not make sense to have a separate repository within the `typescript-eslint` organization?

**Comment by bradzacher** [comment]
> Would it not make sense to have a separate repository within the typescript-eslint organization?

The problem we've found with having a separate repo per package when they're all related and interdependent is that it's then hard to coordinate releases, as there's the dependencies create an implicit ordering in how you do things.

The more repos you have, the more PRs you potentially have to raise when you add a feature.

Also, it can create some confusion for users when they find bugs or need enhancements. "Does this feature belong in `@typescript-eslint/eslint-plugin-react`, or `@typescript-eslint/utils`, or `@typescript-eslint/parser`. Then you waste time transferring/duplicating issues between repositories...

This is why a lot of big projects converge on a monorepo (i.e. babel did it, react does it, .NET is doing it right now).

---

Maybe to start with it makes sense to not have a new package? I.e. if we eagerly create a new package, and then only ever have 1 or 2 react rules, then it's a bit of a waste of time creating a whole package for them.

We can always breaking change split them into a new package if we get past a certain threshold?

Unsure. I think both solutions work.

**Comment by glen-84** [comment]
> The problem we've found with having a separate repo per package when they're all related and interdependent is that it's then hard to coordinate releases, as there's the dependencies create an implicit ordering in how you do things.

There are hundreds of ESLint configuration packages (if not more). I don't understand the need to coordinate TS-ESLint releases with configurations that could be maintained individually.

> The more repos you have, the more PRs you potentially have to raise when you add a feature.

Configurations don't have to be updated with every release of TS-ESLint, unless I'm missing something.

> Also, it can create some confusion for users when they find bugs or need enhancements.

That's true for closely-related packages like the parser and plugin, but not so much for library-specific configurations.

> Maybe to start with it makes sense to not have a new package?

We should differentiate between packages and repositories here – bringing it into the monorepo is one thing, but including it in the same (npm) package would be rather unfortunate. It may be 1 or 2 rules now, but that will quickly grow, and what about Angular, or Vue.js, or Svelte? Should they also be brought in? Are you and James going to handle all the maintenance?

> We can always breaking change split them into a new package if we get past a certain threshold?

That threshold will be vague, and before you know it, developers will be downloading 25 extra files, that in many cases they have absolutely no use for.

Anyway, that's just my opinion. 🙂

**Comment by milesj** [comment]
Looping in @yannickcr (owner of https://github.com/yannickcr/eslint-plugin-react), who might have some input here.

**Comment by adidahiya** [comment]
I agree with @glen-84 here, 👍 for a new `@typescript-eslint/eslint-plugin-react` package in this monorepo. Non-React TS projects shouldn't need to pull in those rule implementations, and it is nice to author those rules in this monorepo given all the TS build tooling & release infra.

**Comment by JamesHenry** [comment]
I would definitely say that it does not make sense to have them in the `@typescript-eslint/eslint-plugin` and my initial reaction is to also not be in favour of creating `@typescript-eslint/eslint-plugin-react` within this monorepo, specifically.

I understand the idea around synergies, but I am not a React user, and I am 50% of active maintainers at this point :) it's hard enough already keeping on top of the stuff which is generally applicable to goals of the project without layering on new context and expectations.

I am an Angular user, and also had a need for Angular-specific ESLint stuff in the same way that folks on this thread have a need for React stuff.

Instead of suggesting it be added to this monorepo, I worked with other folks who care about static analysis within the Angular ecosystem to create the (WIP) https://github.com/angular-eslint/angular-eslint project. We make use of the utils provided by this monorepo.

I am not saying that that's exactly what should happen for each frontend framework, but hopefully it's clear by that action that I am not somehow being biased towards my own stack when I say this. I don't think we should be biased towards _any_ stack (beyond the obvious TypeScript + ESLint 😛).

What I would love to see as an ideal solution to this:

Folks from the React community who care about these rules maintain a new repo under the `typescript-eslint` organization. Just in the same way that @JoshuaKGoldberg is not part of the core team on this repo but is happily (and with full autonomy) maintaining https://github.com/typescript-eslint/tslint-to-eslint-config under the organization already.

That way we can easily have _some_ synergy - e.g. we can easily wire up webhooks to trigger builds across repos, but also have some logical separation.

I'll keep thinking about this, but would love to know what you think about what I've said in the meantime!

**Comment by adidahiya** [comment]
@JamesHenry that also sounds quite reasonable. Happy to contribute to a new react-specific repo in the typescript-eslint org in the coming weeks/months.
