### ISSUE TITLE
Gitter?

### ISSUE THREAD

**Issue by glen-84** [typescript-eslint/typescript-eslint#872]
Have you considered having a [Gitter](https://gitter.im/) room?

**Comment by bradzacher** [comment]
We haven't really had a use case for it yet. Github issues work fine enough for people asking questions - as we don't really have many people (2 maybe?) asking questions.

I'd personally prefer to keep conversations in issues for now.

Because it's a heavy-ish process to open an issue, it creates a bit of a barrier which means people think twice about their problem, and are willing to do more to unblock themselves first.  
With gitter being an instant message, you're more likely to have people ping simple questions instead of reading docs, because it's easier.

Finally, as we're volunteers, I don't really want to introduce another notifications stream into the maintainer's pipeline. A chat room has a different expectation of response times, which we can't really meet.

**Comment by glen-84** [comment]
Fair enough. 🙂

Thank you for all the work that you and the other contributors do.
