### ISSUE TITLE
Repo: deprecate no-magic-numbers

### ISSUE THREAD

**Issue by Martinspire** [typescript-eslint/typescript-eslint#8790]
### Suggestion

In a previous issue it was stated that this is a stylistic rule that will not be maintained. Therefore it should be marked as deprecated so the stylistic team can take over

Issue about numbers in array not being ignored:
https://github.com/typescript-eslint/typescript-eslint/issues/8102

Issue on stylistic about it not being deprecated:
https://github.com/eslint-stylistic/eslint-stylistic/issues/238

**Comment by bradzacher** [comment]
> it was stated that this is a stylistic rule that will not be maintained

That's not what I said at all. I said

> we aren't looking to deviate from the base rules enforced style. Instead the goal is to augment the existing style with support for TS features that align with the style.

I also said

> [The rule is] considered feature complete and thus feature frozen by both us an eslint core.

Being feature frozen and unmaintained are very, very different things.
We will continue to enhance it with new TS features that align with the existing style and we will fix bugs as reported. We will also keep it in sync with the base rule as it changes.

We are just not accepting any new features.

If the base rule is deprecated we'll follow suit. But otherwise there's no reason to deprecate it.

If another plugin would like to fork it to add new features - they're free to do so at any time.
