### ISSUE TITLE
eslint-plugin: Feature freeze naming and sorting stylistic rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#8792]
## Overview

Following #8091: we'd like to feature freeze our stylistic rules that work for naming and sorting. Copying much of its description here...

Right now, [our _Formatting_ docs](https://typescript-eslint.io/linting/troubleshooting/formatting) reference ESLint's policy on preferring to avoid stylistic rules:

> Per [ESLint's 2020 Changes to Rule Policies blog post](https://eslint.org/blog/2020/05/changes-to-rules-policies#what-are-the-changes), ESLint itself has moved away from _stylistic_ rules, including _formatting_ rules:
>
> > Stylistic rules are frozen - we won't be adding any more options to stylistic rules. We've learned that there's no way to satisfy everyone's personal preferences, and most of the rules already have a lot of difficult-to-understand options. Stylistic rules are those related to spacing, conventions, and generally anything that does not highlight an error or a better way to do something.

Yet we actively maintain a few rules that arguably fall purely within the prefer-to-avoid area:

* **[`@typescript-eslint/member-ordering`](https://typescript-eslint.io/rules/member-ordering)**: the options are excessively complex, requiring many examples and nested descriptions of options in the docs
* **[`@typescript-eslint/naming-convention`](https://typescript-eslint.io/rules/naming-convention)**: same as member-ordering, and even has FAQs
* **[`@typescript-eslint/sort-type-constituents`](https://typescript-eslint.io/rules/sort-type-constituents)**: supports basic group ordering but is not generally as comprehensive as [`eslint-plugin-perfectionist`](https://eslint-plugin-perfectionist.azat.io)

We're going to:

* Feature freeze the aforementioned naming and sorting stylistic rules
  * This would only be a _feature_ freeze - we'd continue to fix bugs in them and update them for new TypeScript versions.
* Explicitly indicate in their docs that further features should be built by the community, with links to any equivalents

---

Note that this issue does _not_ suggest we want to remove the existing [_`stylistic`_](https://typescript-eslint.io/linting/configs#stylistic) or [_`stylistic-type-checked`_ ](https://typescript-eslint.io/linting/configs#stylistic-type-checked) presets.
* Rules such as [`@typescript-eslint/prefer-nullish-coalescing`](https://typescript-eslint.io/rules/prefer-nullish-coalescing) and [`@typescript-eslint/prefer-string-starts-ends-with`](https://typescript-eslint.io/rules/prefer-string-starts-ends-with) are great at helping folks find better ways to write code.
* Even "consistency" rules in there such as [`@typescript-eslint/array-type`](https://typescript-eslint.io/rules/array-type) that enforce adhering to one of <=3 common syntax forms have a strong benefit in aligning a codebase to a single style. This discussion is about rules that are highly unbounded in complexity and don't have definitive _"pick one and practically always use that"_ solutions within a project.

**Comment by karlhorky** [comment]
> Yet we actively maintain a few rules that arguably fall purely within the prefer-to-avoid area:
> 
> * **[`@typescript-eslint/member-ordering`](https://typescript-eslint.io/rules/member-ordering)**: the options are excessively complex, requiring many examples and nested descriptions of options in the docs
> * **[`@typescript-eslint/naming-convention`](https://typescript-eslint.io/rules/naming-convention)**: same as member-ordering, and even has FAQs
> * **[`@typescript-eslint/sort-type-constituents`](https://typescript-eslint.io/rules/sort-type-constituents)**: supports basic group ordering but is not generally as comprehensive as [`eslint-plugin-perfectionist`](https://eslint-plugin-perfectionist.azat.io)

> We're going to:
> 
> * Feature freeze the aforementioned naming and sorting stylistic rules
>   
>   * This would only be a _feature_ freeze - we'd continue to fix bugs in them and update them for new TypeScript versions.
> * Explicitly indicate in their docs that further features should be built by the community, with links to any equivalents

cc @antfu from [ESLint Stylistic](https://github.com/eslint-stylistic/eslint-stylistic), in case these rules would be good candidates to be migrated from `@typescript-eslint` to ESLint Stylistic (eg. in [`@stylistic/eslint-plugin-ts`](https://eslint.style/packages/ts))

**Comment by antfu** [comment]
I am ok to take `naming-convention` to eslint.style even tho it's a bit beyond our scope, but if taking them could help the community, then I am happy to host it.

For `member-ordering` `sort-type-constituents` I am not so sure. If the ts-eslint team decided not to maintain them, I'd suggest directly deprecating them to some extent and redirecting users to `eslint-plugin-perfectionist`, which is better scoped.

**Comment by JoshuaKGoldberg** [comment]
> `naming-convention`

Another alternative could be to have a dedicated ESLint plugin for it, like `eslint-plugin-naming`. I personally think that would be a very good result for users _*if*_ there's enough maintenance effort put into it to justify it. I'd be up for that as long as at least one other dev who's done ESLint work in the past is too.

> `member-ordering` `sort-type-constituents`

cc @azat-io - I believe our two main blockers on pointing those over to `eslint-plugin-perfectionist` are:

* Confirming with you're that you're ok with that 😄 
* Making sure the existing rules have feature parity with their equivalents

**Comment by bradzacher** [comment]
These rules are already massive and handle so many usecases. We as maintainers have no bandwidth to add support for things and so we were relying on the community to build these features.

All of those issues have been open for multiple years (some 5y) and have gathered very few reactions - most less than 10 - and only one or two more than that. Most haven't had a comment in several years as well.

This is the reason we're closing and feature freezing things - because it's clear to us that these things won't be actioned by the community. Either because they're not of broad enough appeal or because they are too complex for new contributors to approach.

I'm a strong -1 on moving things. I don't think it changes anything or improves the situation at all. If anything it worsens the situation and adds friction because we will force users to migrate to a new plugin for the sake of it.

**Comment by bradzacher** [comment]
I guess put another way.

If we're looking to migrate the rules purely because we don't like that they're considered "feature frozen" then that is a bad idea.

If we're looking to migrate the rules purely because we want to build these new features - then why not do that in our repo?
Was there a blocker to allowing you to work and make these changes in our repo?

**Comment by azat-io** [comment]
> Another alternative could be to have a dedicated ESLint plugin for it, like eslint-plugin-naming. 

It's a good idea to implement it in [eslint-plugin-eslint-plugin](https://github.com/eslint-community/eslint-plugin-eslint-plugin).

> Confirming with you're that you're ok with that 😄

Of course it's great.

**Comment by JoshuaKGoldberg** [comment]
> If we're looking to migrate the rules purely because we want to build these new features - then why not do that in our repo?
Was there a blocker to allowing you to work and make these changes in our repo?

Oh, heh, I might have come away from #8091 with a different conclusion on where the discussion landed...

My impression is that we in this project don't have the bandwidth to support a family of rules with rich options the way, say `eslint-plugin-perfectionist` has. There's a lot more overhead to working on the rules in our repository -where you're blocked on a review from one of us and have to adhere to our versioning- compared to doing it standalone.

For the _sorting_ stylistic rules, since `eslint-plugin-perfectionist` already exists & is more comprehensive than our rules, I think once it's fully at feature parity then it'd be a straightforward win to point people to it, yeah?

For the _naming_ rules, it's certainly more muddied. Given that nobody has made a community plugin and the eslint-stylistic project doesn't currently have it in its scope, I'm up for just backing away from it and not pointing folks to them. So, what you're saying I think: _not_ moving `naming-convention` and instead leaving it as-is. If some enterprising community member eventually makes their own `eslint-plugin-naming` or that does to it what `eslint-plugin-perfectionist` does to our _sorting_ rules, then we could revisit.

**Comment by bradzacher** [comment]
The perfectionist plugin is a unique example of a community member just "doing their own thing" - they chose to build their own completely separate implementations of some of our rules (in conjunction with some brand new rules).

To my knowledge there wasn't requests in our repo for these rules or the features that were built - it was just a community member choosing to start a separate, parallel workstream with the intent to be different.

In this particular case we're happy with the result because
(a) we don't like maintaining such stylistic rules ourselves (complexity is high so fixes and features aren't super easy and opinionatedness is high so people request more options).
(b) without the weight of backwards compat they were able to redesign and simplify the options for some rules.

TBF (b) we could have achieved ourselves in a major, but likely wouldn't have cos (a) heh.

In the case of the perfectionist plugin yeah, I'm happy to declare our rules deprecated on favour of those ones as they have created a better outcome.

**Comment by bradzacher** [comment]
In the case of `naming-convention` it really was that rewrite. It was a divergence from the existing state of `n` different naming rules into a unified form. It supports 99% of use cases right now and there is scope to get it to 99.99% - but it's definitely diminishing returns and ultimately not worth the effort as often that 1% case is someone trying to be too tricky with their naming conventions.

So freezing it makes sense because we feel we've covered enough usecases to be very broadly useful.

**Comment by bradzacher** [comment]
The question to ask for each rule really would be "what do we/users gain from deprecating and moving the rule to a separate, 3rd party plugin?"

---

In the case of the sorting rules, as I mentioned, we shed maintenance burden of rules we don't want to maintain and users get better maintained rules with a cleaner, better thought-out design.
In that case it's a clear win and a no-brainer for us to declare our sorting rules as deprecated and funnel people over to the perfectionist plugin.

---

In the case of `naming-convention` I don't see any win. There's no existing plugin to move to - so there's no "better" solution that's been redesigned or is actively maintained with new features. Just moving the rule to an existing 3rd party doesn't really net any benefits either, IMO.

Whilst I agree there is overhead in working within our project - that overhead isn't likely going to stop someone building things if they think they're valuable. If that was the case then there'd be no contributors to our project (or any major project for that matter!). EG Josh didn't you have a PR for TypeScript itself that took so long to merge that you bought a cake on its birthday as a meme? That hasn't stopped you or others building new things for TS!

As an example https://github.com/typescript-eslint/typescript-eslint/issues/816 has been open for almost **_5 years_** with just 11 reactions (and 33 on a similar old tslint issue). It wouldn't be a super complicated implementation - yet nobody has tried. I doubt that the reason nobody has tried is due to review overhead in our project! Instead I would say that the reason it hasn't been worked on is because it's not a trivial problem to solve so it's not "brand new new contributor friendly" - so the barrier to entry is higher than the perceived value.
Moving to a new plugin/repo/etc wouldn't solve that -- the problems don't get simpler just because the rule changes repos!

---

This is why I want us to make the distinction and be careful and conscious about what we're doing.

If there is an existing alternative and it's close to parity and or better - then there's no question - it's a win for everyone to make the change.

If there is no alternative then forcing the creation of one is going to lead to a net-negative result.
