### ISSUE TITLE
Bug: [no-unnecessary-type-assertion] assumes better type narrowing than typescript offers

### ISSUE THREAD

**Issue by paradoxloop** [typescript-eslint/typescript-eslint#8827]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.4.3&fileType=.ts&code=MYewdgzgLgBAHjAvDA3gKBjA5ATywLmwAsBTAGzJCwBoNs4CYBGABjQF800AzAVzGBQAluBgQQAWxIAxfoJFgAPABUYJOFBJgAJhBgBrEjhDcYUHAAcSJ%2BAD4AFBYBOIC-mUBKVHQgB3IVDARDCOLhZe6JiYwACGECTYePh0UTAA9GkwMbBQREJ6FiBCYLDOrjD5YsIUMABEOLUwAD51cI3avAlQIGaWJBDATkIWsGAgsABGJMUA5lkTZF09YDFOLr4pURlqEGTFsE68i3VjALT8JMD9EKs4p%2BZWp3HxTsLgjc4kAG5aUHoraxA-jAcxAvCc8TIPwgm2i4GgMCcSBgZQsWT0uCwsJgEycJBi%2BgA3HROBw0EA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=&tokens=false

### Repro Code

```TypeScript
const x = {
  'y': 'hello',
  'x': 10
}

function someFunction<T extends keyof typeof x>(prop:T) {
  switch (prop) {
    case 'y':
      // at this point prop is still "y" | "x" due to typescript not being able to narrow
      // eslint rule "no-unecessary-type-assertion" prevents narrowing ourselves
      const r = prop as 'y'
      break;
  }

}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {
    "@typescript-eslint/no-unnecessary-type-assertion": "error"
  }
}
```

### Expected Result

Eslint would allow me to narrow the type manually given typescript is not able to do it.

### Actual Result

Receiev an error that this assertion is unnecessary since it does not change the type of the expression.eslint[@typescript-eslint/no-unnecessary-type-assertion](https://typescript-eslint.io/rules/no-unnecessary-type-assertion)

**Comment by bradzacher** [comment]
Your evaluation is incorrect - we don't report here because we assume TS is better than it is.
The rule is powered purely by the types that TS reports.

If you [inspect the types of `prop` with and without the assertion](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAHjAvDA3gWAFAxgcgJ44BcuAFgKYA2FIOANJtjnETAIwAMmAvppgGYBXMMCgBLcDAggAtmQBiQkeLAAeACowycKGTAATCDADWZPCD4woeAA5lz8AHwAKawCcQ1wmoCUqBpIB3UShgEhgXd2tfdCxsGGAAQwgyXAJCfziYAHosmATYKBJRQ2sQUTBYNw8YYskxKhgAIjxGmAAfJrhWvQEUqBBLGzIIYFdRa1gwEFgAIzJygHM8mYo+gbAE13cAjLiczQgKcthXAVWmqYBaITJgYYhNvEurW0uk5NcxcFa3MgA3XRQQwbLYgIJgJYgASuZIUAEQXbYUCQE6sJAwKrWADciOyuUymQAegB+XHI6AwVwAJnRmLyhnwOBxsUy+wJcRJuJmrjICSMzOwPAw3EwQA) you can see that without the assertion TS reports the type of `prop` to be `T  extends "y" | "x"` but with the assertion instead TS reports the type of `prop` as `"y"`.

![screenshot of the previous paragraph](https://github.com/typescript-eslint/typescript-eslint/assets/7462525/0c8aa09b-aa44-42d7-802d-cd1ef5dbf08a)

I think that this is a bug with TS itself - a behaviour that changed in (from the looks of it based on testing) in TS v4.3. In v4.2 TS correctly reports both locations as the generic - in v4.3+ it exhibits the above behaviour.
The assertion should not be changing the type of the original variable.

**Comment by paradoxloop** [comment]
thanks @bradzacher yup I can see the behaviour change in TS v4.3. I will lodge a bug report with them.

**Comment by Josh-Cena** [comment]
There's no bug here. `prop` has type `T extends "y" | "x"` but in fact it's assignable to `"y"`. You don't need the assertion:

```ts
function onlyY(arg: "y") {}

function someFunction<T extends "x" | "y">(prop: T) {
  switch (prop) {
    case "y":
      onlyY(prop);
      break;
  }
}
```
