### ISSUE TITLE
Configs: Remove one of the nullable assertion rules from `strict-type-checked`

### ISSUE THREAD

**Issue by 6XGate** [typescript-eslint/typescript-eslint#8884]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

Either `non-nullable-type-assertion-style` or `no-non-null-assertion` from `strict-type-checked`

### Impacted Configurations

Any configuration that includes `strict-type-checked`. This prevents either style from being used in an appropriate situation without disabling the rule. Seem they are both designed to force using the other style, so therefore clash/collide.

**Comment by bradzacher** [comment]
This is working as expected.

`no-non-null-assertion` is there to prevent using non-null assertions because they're unsafe.
```ts
const map = new Map<string, string>();

const value = map.get('lol does not exist')!; // obviously unsafe
```

`non-nullable-type-assertion-style` is there to stop cases like this:
```ts
declare const nullable: string | null;
const y = nullable as string;
```
These cases look "fine" to many people during code review because you assume that it's not eliding the `null` type. You need to trace the type of `nullable` to understand that it is the same as `nullable!`.

The latter enforces that you prefer using a `!` so that the unsafety of the assertion is clear and consistently annotated, and the former is there to warn against using it at all because it's generally an unsafe type operation.
