### ISSUE TITLE
Rule proposal: prefer `satisfies` over `as`

### ISSUE THREAD

**Issue by hypeJunction** [typescript-eslint/typescript-eslint#8900]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

We were just dealing with a bug that could have easily been prevented with some lint checks. Not sure what other implications adding such rule would be, but here is what happened.

Given a type:

```ts
export interface AggregateRequest {
  type: AggregationType;
  moduleIDs: string[];
}
```

A dev wrote and the code review missed:

```ts
const aggregateRequest = { type: config.aggregationType } as AggregateRequest;
```

TypeScript was happy, but this eventually led to a runtime error because `moduleIDs[]` were undefined.

Enforcing `satisfies` would have caught an error earlier on.

### Fail Cases

```TypeScript
const a = 'abc' as number;
const foo = {} as { a: string }
```

### Pass Cases

```TypeScript
const a = { a: 'foo' } satisfies { a: string }
```

**Comment by bradzacher** [comment]
This suggestion isn't actually correct because `satisfies` doesn't change the type like `as` does. [example](https://www.typescriptlang.org/play?#code/DYUwLgBAHhC8EEYIGcCGYCWyBmGTMQG4AoAelIggD0B+Y4gYwHsA7ZSATwC5E5oSgA)

This means that you can't always switch to `satisfies`. I definitely agree that `as` is generally unsafe and harmful - but it's not possible to switch everything to `satisfies` either.

Additionally all `satisfies` usages can be made `as` usages, but all `as` usages cannot be made `satisfies`.

All in all it means a rule that can be very hard to resolve depending on what your code looks like.

The best course of action here is to use this rule to enforce no `as` and people can figure out the best resolution  https://typescript-eslint.io/rules/consistent-type-assertions/
