### ISSUE TITLE
Configs: Better resolution for `tsconfigRootDir` in monorepo with flat config

### ISSUE THREAD

**Issue by ashtonsix** [typescript-eslint/typescript-eslint#8910]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22preset+config+change%22+) and found none that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Description

**Context**

My monorepo has one `tsconfig.json` at the root, and other child configs at `*/tsconfig.json`. Here is my `eslint.config.js` folder located at the root:

```js
import { readdirSync } from "node:fs";
import js from "@eslint/js";
import typescript from "typescript-eslint";

/** @type {import('eslint').Linter.FlatConfig[]} */
export default [
  js.configs.recommended,
  ...typescript.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        project: ["./tsconfig.json", "./*/tsconfig.json"],
      },
    },
  },
  ...readdirSync(import.meta.dirname)
    .filter((dir) => existsSync(`${import.meta.dirname}/${dir}/tsconfig.json`))
    .map((p) => {
      return {
        files: [`${p}/**/*.{ts,tsx}`],
        languageOptions: {
          parserOptions: {
            tsconfigRootDir: `${import.meta.dirname}/${p}`,
          },
        },
      };
    }),
];
```

This config works perfectly, but we observe `tsconfigRootDir` has been defined using an idiosyncratic method. It is my expectation that `typescript-eslint` should work out-of-the-box in monorepos without manually having to set `tsconfigRootDir` this way.

When defining `tsconfigRootDir` as `import.meta.dir`, `typescript-eslint` resolves library imports as `any` even when I can clearly see the correctly resolved types in the VSCode tooltips. It seems to be unaware of the types available for child projects.

<img width="999" alt="image" src="https://github.com/typescript-eslint/typescript-eslint/assets/6740947/c1dc92da-4664-4012-8890-52a5bd96bf73">

### Additional Info

Search terms used for related issues: tsconfigRootDir, monorepo, flat

**Comment by bradzacher** [comment]
It's impossible to provide too much advice without a reproduction.
Also our configs do not turn on `parserOptions.project` - intentionally so - so this is unrelated to configs.

**Comment by bradzacher** [comment]
When you define a relative path like `./tsconfig.json` - we need something against which to resolve that relative path. Without `tsconfigRootDir` we have exactly one physical path available to us - the CWD. ESLint does not provide us any additional information.

The issue is that the CWD is dynamic - if you run ESLint from a different folder than the root then the CWD is different and so your relative paths are different.

`tsconfigRootDir` is the way for you to to provide us with a constant disk path to resolve relative paths against. As long as you use `__dirname`/`import.meta.dirname` then it doesn't matted what CWD you're in cos the path is static.

---

When you define an array of tsconfigs we will traverse them in order when we provide type info for a file. This can be small if you have dozens of tsconfigs.

Your config above works around this by using your internal repo implementation details to circumvent this iteration - you're overriding the base glob config and configuring the projects to say "the files within the `./foo/` directory must use `./foo/tsconfig.json`. Which is a nice little perf enhancement - but is not a generalisation that we can make.

For example you might have a setup where all `src` files in `foo` use `./foo/tsconfig.json` but all `test` files in foo use `./tsconfig.json`. We don't know - and we can't make generalisations as we need to support everyone!

We do have support for something you might like - https://typescript-eslint.io/packages/parser#project try the value of `true` for your `parserOptions.project` then we'll find the nearest tsconfig on disk for each file and try to use that. Which means your config setup becomes:
```js
export default tseslint.confg({
  languageOptions: {
    parserOptions: {
      project: true,
      tsconfigRootDir: import.meta.dirname,
    },
  },
})
```

**Comment by ashtonsix** [comment]
@bradzacher, thank you for the response — I like the behaviour when `parserOptions.project === true` very much! It feels intuitive.

My suggestion then, would be to more clearly explain the implications of moving away from that in the [Monorepo Configuration](https://typescript-eslint.io/getting-started/typed-linting/monorepos/#one-tsconfigjson-per-package-and-an-optional-one-in-the-root) docs.

I had some trouble understanding what was meant by "For each file being linted, the first matching project path will be used as its backing TSConfig."... Does this mean flipping the order for `.project` from `["./tsconfig.json", "./*/tsconfig.json"]` to `["./*/tsconfig.json", "./tsconfig.json"]` is necessary for the child configs to make priority over the root config?

By the way, all the `tsconfig.json` files in my child projects look like this: `{ "extends": "../tsconfig.json" }`. I've only defined them so ESLint is able to find the type packages installed in those projects.

**Comment by bradzacher** [comment]
> I wonder whether ['./tsconfig.eslint.json', './packages/*/tsconfig.json'] should be reversed to more closely match the behaviour of project === true?

We consume the array in the order you define it. If you want a different order then it's up to you to change it.

We can't tell what you meant by the array ordering so we can't infer any specific ordering.

> Reading "For each file being linted, the first matching project path will be used as its backing TSConfig" carefully, it's my belief that if ./tsconfig.eslint.json exists then it will always be matched first, and ./packages/*/tsconfig.json shall never be used.

Matching is the key word there.

If the first tsconfig includes the file being linted then, yes, it is considered "matching" and thus the other ones are never loaded or checked.

If the first tsconfig does not include the file being linted then it is not matching and the parser continues iterating.

**Comment by ashtonsix** [comment]
Thank you for all the explanations, everything is resolved from my perspective. Should I close this issue now?
