### ISSUE TITLE
Rule proposal: break up consistent-type-assertions into consistent-type-assertion-syntax and no-unsafe-object-literal-type-assertion

### ISSUE THREAD

**Issue by kirkwaiblinger** [typescript-eslint/typescript-eslint#8921]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Currently, consistent-type-assertions does two _completely_ different things. 
1. When type assertions are used, enforces the use of `<T>x` or `x as T` syntax on any kind of expression. This is a purely stylistic concern that enforces consistency over two exactly equivalent syntaxes and has no correctness implications (notwithstanding syntax conflicts with JSX)
2. Correctness validation around type assertions used on object literals where the `satisfies` operator or assignment to a variable might be more correct, since the type assertion may disguise preventable errors from the compiler (namely, missing properties).

These are _utterly orthogonal_ concerns, whose only common thread is that they relate to type assertions. But that also means that `no-unnecessary-type-assertion` is just as related to the checking of `<T>x` vs `x as T` as the object literal validation is. 

### Fail Cases

```TypeScript
// consistent-type-assertion-syntax: ['error', 'angle-bracket']
x as T;
  ^^^^
// consistent-type-assertion-syntax: ['error', 'as']
<T>x;
^^^
// no-unsafe-object-literal-type-assertion: ['error']
<T>{};
^^^^^
{} as <T>;
^^^^^^^^^
```
^^ Note that I would also refine the report loc of the type assertion _syntax_ to be on the type assertion only, whereas the object literal report loc should include the object literal and the assertion. Related: https://github.com/typescript-eslint/typescript-eslint/issues/8543

### Pass Cases

```TypeScript
// consistent-type-assertion-syntax: ['error', 'angle-bracket']
x as T;
// consistent-type-assertion-syntax: ['error', 'as']
<T>x;

// no-unsafe-object-literal-type-assertion: ['error', 'allow-as-parameter']
f({} as T, <T>{});
// ^^ currently impossible for this line to pass the existing rule with any configuration.
```

### Additional Info

Note that I am proposing no logic or options changes compared to the existing consistent-type-assertions rule. I am just proposing that the assertionStyle and objectLiteralTypeAssertions be their own separate rules.

FWIW, the assertionStyle stuff probably belongs in the stylistic config, and the objectLiteralTypeAssertions stuff probably belongs in the strict config

**Comment by bradzacher** [comment]
Funnily there used to be two separate rules.
- no-angle-bracket-type-assertion and
- no-object-literal-type-assertion

In v2 we merged them into one rule
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0 // https://github.com/typescript-eslint/typescript-eslint/pull/731 

The reason we merged them was because people were asking for a way to completely ban assertion syntax.
Configuring multiple rules around assertions would have been tricky - so we merged them to reduce surface area and confusion.

From my experience in modern TS people don't ever even think of using angle-bracket assertions. So really by-and-large the rule only really enforces the object literal assertions.

---

All that being said - I don't think splitting the rules makes sense.

If someone wants to ban all assertions but also really strongly ban the angle bracket style them this FAQ explains how they can do that - https://typescript-eslint.io/troubleshooting#how-can-i-ban-specific-language-feature

**Comment by kirkwaiblinger** [comment]
> The reason we merged them was because people were asking for a way to completely ban assertion syntax. Configuring multiple rules around assertions would have been tricky - so we merged them to reduce surface area and confusion.

Maybe so... But I, personally, feel very confused by the current setup. Normally when rules have multiple areas that they flag in, it's because they're different instances of the same kind of issue. So I spent a(n) (embarassingly) _long_ time when I was first setting up this rule trying to figure out how object literal type assertions differ based on the syntax used, i.e. why `<T>{}` might be different from `{} as T`, in the same way that there _is_ a real difference between, for example, the syntaxes in method-signature-style. But nope! complete red herring. They're just unrelated concerns.

> From my experience in modern TS people don't ever even think of using angle-bracket assertions. So really by-and-large the rule only really enforces the object literal assertions.

So far every codebase at my company uses `assertionStyle: 'angle-bracket'`. Not really sure why but I'm guessing some/all have existed since before `as`, and/or the devs learned TS back then and never changed habits, so they set that up for consistency and no one has championed getting rid of that kinda-but-not-overtly-deprecated syntax (well, no one but me lol). 

> If someone wants to ban all assertions but also really strongly ban the angle bracket style them this FAQ explains how they can do that - https://typescript-eslint.io/troubleshooting#how-can-i-ban-specific-language-feature

Sure... but that's a team-member/super-user build-your-own lint rule approach that I could do today, but did not and would not have remotely considered as a user. Plus it obviously doesn't have an autofix, which is a huge appeal in using `consistent-type-assertions` (i.e. as a codemod tool to migrate to `as`). 

The use case I had/still have is I want to configure different severities for the different parts of this rule. type assertion syntax? error! _autofix_ em! done! object literal type assertions? this is a program logic error, so warn, and people can gradually address them over time if they happen to be looking at the code anyway, but it's nothing to get too stressed about going out of your way to fix.

When I first configured typescript-eslint for my team, I gave up on trying to achieve that, since, at the time, I did not have the knowledge of the existence of no-restricted-syntax or of how to use it. I would hate for other people in the wild to have the same experience and give up 🤷‍♂️

**Comment by bradzacher** [comment]
> So far every codebase at my company uses assertionStyle: 'angle-bracket' 

That is definitely the outlier - most people stopped using angle brackets when `as` was added because the syntax is much better.

Eg there's [barely two dozen hits on sourcegraph](https://sourcegraph.com/search?q=context:global+/assertionStyle:+%5B%27%22%5Dangle-bracket%5B%27%22%5D/&patternType=keyword&sm=0) for angle bracket vs [10x that for as](https://sourcegraph.com/search?q=context:global+/assertionStyle:+%5B%27%22%5Das%5B%27%22%5D/+OR+/consistent-type-specifier-style%5B%22%27%5D:+%5B%22%27%5D/&patternType=keyword&sm=0). 

---

> Plus it obviously doesn't have an autofix, which is a huge appeal in using consistent-type-assertions (i.e. as a codemod tool to migrate to as). 

The rule specifically has an autofixer just for the angle bracket to as case - so you can turn the rule on either as error or warning and you still get the migration power.

I.e. You turn the rule on as a warning (with the setting in `as`) and `no-restricted-syntax` on as an error - and you get the best of both worlds.

Though it's worth noting that migrations are not a usecase we consider a priority. Migrations are short-term - usually once-off but linting is forever.
