### ISSUE TITLE
Enhancement: [no-duplicate-type-constituents] Prevent unnecessary `| undefined` for optional parameters

### ISSUE THREAD

**Issue by binoche9** [typescript-eslint/typescript-eslint#9203]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

When a function parameter (or a class property) is marked as optional with `?`, it implicitly includes `undefined` in the type definition, so there is no need to explicitly add an `| undefined` to the type definition. I'd like to detect these cases and also autofix away the `| undefined`.

I don't think I see an existing rule to do this and it seems too complicated to do with `no-restricted-syntax` (though it wouldn't be able to autofix anyways).

### Fail Cases

```TypeScript
function foo(bar?: number | undefined) {
    return bar
}
```

### Pass Cases

```TypeScript
function foo(bar?: number) {
    return bar
}
```

**Comment by higherorderfunctor** [comment]
Note that [exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes) removes the implicit undefined.

If this rule is implemented, it is just a nuance to be aware of.

**Comment by Josh-Cena** [comment]
@higherorderfunctor: this proposal talks about optional _parameters_, not _properties_.

**Comment by bradzacher** [comment]
> it seems too complicated to do with no-restricted-syntax

It's quite a simple query, actually.
Here is a working example that would catch most cases just fine - [playground](https://typescript-eslint.io/play/#ts=5.4.5&fileType=.tsx&esQuery=N4IgZglgNgLgpgJxALhQWwIYwMYAs4DOAFAGICuAdtjBAPYUAic2UGCWdFANAATlU16AUQAeABwSECnXgEEECWgHd%2B1TqIlTOASh4A%2BHgEkAJnAo1IiANq0xgihig8AvDxgIycALoA6MWww0An0eABUAZVCATzE4WQoKWhgOehCIgFUKTmjYtPDM00gKOGMAaTgopVoEYxAuEAI4KGYYapRQGBi4FBA8aFr65rAYdpBO2J6%2BqAGQIZHkDq7J3H662bhh0fHu1CmZua2l1EwcfAI1xubqavPkK0WJ1AhTcwhLJHqAN0dPHtV7JgsAL2EAAXy4Dx2IGeZgsEEQa2%2BUF%2BqH%2B6nEkgI0noYIhYyO0JecIRXx%2BUPkihUlDUwgxWhxoK84JACAgAHNcPNIZNaGgxLRKDNLi0bih7vjHoTYW94R8QEiUSATNL3rjuagsO4IAAjMjwNYONBQ2z2RxrWyILBtVDORFkw6SqAQeDsKB25FQ9y-UHg9XgeHTA2BKH%2BdhBMFM5msjlciVQmGvVWkj09CI5OIJJIpChgqPszkO%2BNEmUk%2BX21AZLL0dO5%2BrRgsLOM9BPEuUKqGVwoQYplCpVGq50FAA&code=GYVwdgxgLglg9mABMOcAUAoRiCGAuRMEAWwCMBTAJ0QB9FwATc4GMchgGi0VIH4CiZKrXpgmLNpwwBKRAG9ulclBCUkpDAF8MQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQHYHsBaaFAF2gEsBjUxAE0OQE9dSBDAD3TAG1xsciaNHzRIAGn4CsA7JGSIkNUd3QBbNqSoALFAAoAYrFw0K%2BXABFEVeG2iazucWCMnSjgKIcADiWTJHZwBBYXwAd1dTcy9fFADzAEowAD4wAEk6RFYKADMKIR58b3dzNngwAF4wclhEAF0AOm87NjVkFLAAFQBlTqZvRCDcAnYS3A6egFVcRz6Bie7pzLzcegBpRCYw0ToJKVlINTi2AHNEVWnVqmPoJjBjZYpVujBzV%2BLHMrBm%2B1XaMX2EAAvvs6vwQSCgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

I don't know if this case is really wide enough for us to consider building an entire rule for. It is ultimately a minor stylistic concern that does some very minor code cleanup.

This could potentially live as part of [`no-duplicate-type-constituents`](https://typescript-eslint.io/rules/no-duplicate-type-constituents/).

**Comment by binoche9** [comment]
> Here is a working example that would catch most cases just fine

Hm `no-restricted-syntax` is a lot more expressive than I realized

**Comment by JoshuaKGoldberg** [comment]
+1 from me to existing in [no-duplicate-type-constituents](https://typescript-eslint.io/rules/no-duplicate-type-constituents). I can't think of a case where folks using that rule wouldn't want this enabled.

**Comment by abrahamguo** [comment]
I am all for this!

However, one consideration is that this will cause a problem for people who have `exactOptionalPropertyTypes: true` in their tsconfig. [(docs)](https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes)

Any ideas on the best way to handle this? 

- Since this rule already requires type information, can we/should we auto-detect this setting from the tsconfig? Is there any precedent for this in typescript-eslint?
- Should we (instead/in addition) add an option for this? What should it be called?
    - `allowExactOptionalPropertyTypes` to match the relevant tsconfig option?
    - `ignoreOptionalUndefined` to follow the convention of `ignoreIntersections`/`Unions`?

**Comment by JoshuaKGoldberg** [comment]
My understanding is that `exactOptionalPropertyTypes` only impacts _property_ types, not _parameters. https://www.typescriptlang.org/play/?exactOptionalPropertyTypes=true#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHcsMALAeQAds8oIAKAN1uRAH4AueAZwxi1QDmASk4McWYAG4AUNKKlK1VLTppQifiGBCZQA

```ts
declare function withOptional(value?: string): void;

withOptional(undefined); // Ok
```

**Comment by abrahamguo** [comment]
🤦🏻‍♂️ I did not read carefully enough and was thinking properties, even though the exact same confusion was made earlier in the conversation haha...

Do you think it'd be beneficial to implement this for properties, though, in addition to parameters?

**Comment by JoshuaKGoldberg** [comment]
Hmm, maybe. I can see benefits but it would be tricky with `exactOptionalPropertyTypes`.

> can we/should we auto-detect this setting from the tsconfig

We can! 

https://github.com/typescript-eslint/typescript-eslint/blob/21375f65c734afc4545c0c3e7a15f72d3959c660/packages/eslint-plugin/src/rules/strict-boolean-expressions.ts#L162-L167

My hunch is that that might be better a separate issue. I think it'd be a lot tricker because of needing to handle `exactOptionalPropertyTypes`.

**Comment by cyberixae** [comment]
I was looking for a similar rule for properties. Note that in case of `exactOptionalPropertyTypes` you might actually wish for the auto-fixer to add the missing `| undefined` to all optional properties, so you could conveniently pass `undefined` to them. Also, leaving the unnecessary `| undefined` out would be less scary if there was a convenient way to add them everywhere in a situation where turning on `exactOptionalPropertyTypes` would later turn out to be necessary.

**Comment by auvred** [comment]
Maybe I came here too late, but don't you think this check is better suited to the [`no-redundant-type-constituents`](https://typescript-eslint.io/rules/no-redundant-type-constituents) rule? Since `| undefined` is not really a duplicate, but a verbose version of TS's implicit behavior.

**Comment by abrahamguo** [comment]
@auvred I considered this. However, I feel like this belongs better in `no-duplicate-type-constituents` for a couple reasons:

From the docs for `no-duplicate-type-constituents`:
> This rule disallows duplicate union or intersection constituents. We consider types to be duplicate if they evaluate to the same result in the type system.

Since marking a parameter optional, and using an explicit `undefined` do evaluate to the same result in the type system, I would argue that they are indeed duplicates of each other.
On the other hand, `no-redundant-type-constituents` works with (1) top and bottom types (`any`, `unknown`, `never`), and (2) literal-vs-primitive types (i.e. `''` vs `string`), so I'd argue that is less related to this PR.

Additionally, I want to use the autofixing logic of removing `undefined` from the union, and `no-duplicate-type-constituents` already has the autofixing logic I want, whereas `no-redundant-type-constituents` is not autofixable.

**Comment by kirkwaiblinger** [comment]
Seems reasonable to let ease of implementation guide the decision here, granted the distinction between "duplicate" and "redundant" is... suspicious (duplicate being a strict subset of redundant in my book). Especially if we start using isTypeAssignableTo to power the redundancy check at some point, now that v8 has dropped.

> whereas `no-redundant-type-constituents` is not autofixable.

Should someone file an issue for that?
