### ISSUE TITLE
Incorrectly listed dependencies in `@typescript-eslint/typescript-estree`

### ISSUE THREAD

**Issue by hacknug** [typescript-eslint/typescript-eslint#926]
_Got here because I use pnpm and Eleventy uses `@typescript-eslint/typescript-estree` for some things._

pnpm is super cool but it sometimes breaks when dependencies aren't listed correctly. In your case `typescript` is listed in `devDependencies` but I think it should actually be in `dependencies` since it ends up being a requirement in your `dist` files.

Relevant lines:
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/package.json#L63
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/parser.ts#L3

**Comment by hacknug** [comment]
Looks like a duplicate of #828 although that was closed and has a proposed solution at the end of it.

**Comment by bradzacher** [comment]
We won't ever put it as a `dependency`, as this will mean npm will install an additional copy within the tree if our version doesn't match the user's.

We _used_ to have it as a peerDep, but as mentioned in #828, we removed it from that to aid with adoption in mixed code tools like `create-react-app`.

We are planning on adding it back as a peerDep, and marking it as an optional peer dependency via the peerDependenciesMeta, but that mechanism has only just been released in `npm`, so we cannot adopt them just yet, as people do not instantly update npm.

It'll probably be a few months before npm 6.11.0 reaches a decent enough adoption that we can consider adding it back in without disrupting users.

---

I know it's a bit of an abuse of the dependency system, but it's an expectation that the user will have typescript installed as a dependency of their root package when using our tooling, because they themselves are using it to compile their typescript code.
