### ISSUE TITLE
Bug: [promise-function-async] Incompatibility with new async React types

### ISSUE THREAD

**Issue by jtbandes** [typescript-eslint/typescript-eslint#9341]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Abug) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Issue Description

(See prior discussion at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68918#issuecomment-2155732510 / cc @eps1lon as contributor to `@types/react` to discuss next steps.)

`@types/react` has recently been updated to include `Promise<...>` in the `ReactNode` union type. (While this is still "experimental", it is already being picked up automatically by `next`, so if a user adds `import "next"` to their React project they will start experiencing these new types.) Having a `Promise` as a possible `ReactNode` variant triggers new errors from `@typescript-eslint/promise-function-async` (and possibly other rules) in some places, for example:

```ts
import * as React from "react";
import {} from "next";
class extends React.Component<React.PropsWithChildren> {
  override render() {
    return this.props.children;  // error: Functions that return promises must be async
  }
}
```

<img width="766" alt="code snippet showing lint error" src="https://github.com/typescript-eslint/typescript-eslint/assets/14237/f63a384d-1607-4592-9c6c-a8b346c3f2d3">

Example repro: https://github.com/jtbandes/react-async-lint-repro/actions/runs/9492059438/job/26158570236

While this is technically correct behavior of the rule, the suggested fix (adding `async` to `render()`) would be incorrect in React, and overall it seems like this class of error has the potential to be disruptive to React users. At the [request of a `@types/react` maintainer](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68918#issuecomment-2161664355), I'm filing an issue here to discuss any possible next steps.

### Reproduction Repository Link

https://github.com/jtbandes/react-async-lint-repro

### Repro Steps

1) clone the repo
2) `npm install`
3) `npm run lint`

### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin`     | `7.13.0` |
| `@typescript-eslint/parser`            | `7.13.0` |
| `TypeScript`                           | `5.4.5` |
| `ESLint`                               | `8.57.0` |
| `node`                                 | `20.12.2` |

**Comment by bradzacher** [comment]
I assume that what's happening is that the new react types have updated `this.props.children` to include `Promise<T>` in the union - hence the rule is reporting.

This occurs because of **INTENTIONAL** design in the rule to flag un-annotated functions that return a union of promises. [This playground is a distillation of the intentional behaviour](https://typescript-eslint.io/play/#ts=5.4.5&fileType=.ts&code=CYUwxgNghgTiAEYD2A7AzgF3gDwFz0xgEsUBzeAH3gAUYkBbItEAHkJNID4BuAKF4BmAVxRgMRVPBFQUKJBigYQwABQBKeAG9e8eHAxCYKHHwC%2BgkWInGZchUuABGdfgwBPAA4gkAnFp16IAZGJrzmwqLikrbyisoATC4EGMRklDR0jMxsKRyc-rr6hsbYZrxAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Y6AewFtLlFaAM1hMy%2BSpya0AhskKj0URNC7RI4MAF8QmoA&tsconfig=&tokens=false).

The reason the rule reports on this is because 99.99999% of the time writing a function that returns `T | Promise<T>` or `T | Promise<U>` is incorrect and unintended and instead just returning `Promise<T>` or `Promise<T | U>` is the intention.

[This behaviour is documented in the rule's docs](https://typescript-eslint.io/rules/promise-function-async/#:~:text=When%20functions%20return%20unions%20of%20Promise%20and%20non%2DPromise%20types%20implicitly%2C%20it%20is%20usually%20a%20mistake%E2%80%94this%20rule%20flags%20those%20cases.%20If%20it%20is%20intentional%2C%20make%20the%20return%20type%20explicitly%20to%20allow%20the%20rule%20to%20pass.).

As mentioned in the docs - there is an escape hatch built into the rule - annotate the return type for the function. Why do it this way? (a) it's easy to check for syntactically (b) it's explicit documentation for future readers - "I have annotated this return type because I have intentionally returned a promise and a non promise".

Solutions:
1) annotate `render` return type for cases where you want to return `this.props.children` but don't want the render to be `async`
2) turn off method checking with [`checkMethodDeclarations`](https://typescript-eslint.io/rules/promise-function-async/#checkmethoddeclarations)

**Comment by eps1lon** [comment]
annotating the `render()` is better anyway because [TypeScript is really bad at inferring a good return type for render functions](https://github.com/microsoft/TypeScript/issues/57779).

**Comment by jtbandes** [comment]
OK, I checked all the places where this error had come up for me during the upgrade and I'm satisfied that annotating the return type is a reasonable solution in all cases. Thank you! 🙏 

@eps1lon I suspect this will become a more common question as more and more people upgrade `@types/react`. Might be something worth mentioning in release notes somewhere. :)
