### ISSUE TITLE
Repo: Consider having Renovate only update major and minor versions, not patch versions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9372]
### Suggestion

I'm sick and tired of getting so many Dependabot/Renovate PRs. In this package alone it's over a dozen a week [[example dependencies search: first week of June 2024](https://github.com/typescript-eslint/typescript-eslint/pulls?q=label%3Adependencies+created%3A2024-06-01..2024-06-08+)]. And across a few dozen repositories... I had to make https://github.com/JoshuaKGoldberg/prune-github-notifications just to have a usable GitHub inbox.

One potential way to trim down on these updates could be to no longer take in patch updates automatically. The default could be to take in only major and minor versions.

Is this ... a good idea? Bad idea? Input needed!

⁉️

**Comment by mcmxcdev** [comment]
Something that worked really well for freelance client projects I worked on: one monthly non-major (patch, minor) deps upgrade PR and one PR per major dep upgrade delayed by a month to ensure its more stable. I understand that a consumer lib like this might have different requirements though.

**Comment by bradzacher** [comment]
That generally doesn't work well because things change and break even in non majors. Behaviours change in subtle ways. Lint rules add new errors. Prettier tweaks its formatting.

It can be really hard to remediate things when you upgrade 15+ packages and a bunch of tests and CI jobs start to fail.

There are a few PRs we've got open right now from renovate with errors that we need to investigate and fix from just one package change. It would be horrid if we had those errors buried along with many other upgrades. We'd probably end up blocking all dep upgrades until someone has a bandwidth to manually pull the branch to investigate.

**Comment by mcmxcdev** [comment]
It's subjective, you have to make sure everything still works for the minor/patch upgrades of course, but at the same time you ensure that 3rd party deps are compatible with major dep upgrades that you do afterwards.

Probably most time efficient, instead of doing minor/patch one by one where one dep could just be incompatible with another one until you upgrade that one too.

**Comment by bradzacher** [comment]
You'd be surprised how often minor bumps can fail CI when done en masse.

Here's an example renovate config that does a grouping of updates on a schedule though
https://github.com/camunda/infraex-common-config/blob/main/default.json5

The thing I'm worried about is that if a PR fails CI it'll likely sit there in perpetuity waiting for someone to investigate and fix it.

But maybe I'm worrying about nothing and It would be worth us exploring this.

**Comment by JoshuaKGoldberg** [comment]
<img width="883" alt="Screenshot of many various patch-level dependency update PRs" src="https://github.com/typescript-eslint/typescript-eslint/assets/3335181/5a7cdb51-b25b-44d5-9118-2610cbf8d8f6">

I'm going to mark this as `team assigned`. 🫠
