### ISSUE TITLE
Rule proposal: Preferring type assertions over ts-expect-error / ts-ignore

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/typescript-eslint#9448]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Users sometimes use `// @ts-expect-error` or `// @ts-ignore` comment directives to suppress assignability errors instead of a type assertion. I think there are two cases to consider:

* 🍎 an `as any ...` / `as unknown as ...` are needed: I think it's worth it preferring an assertion, as comment directives hide other issues
* 🍌 an `as ...` or `!` is sufficient: definitely preferable to use an assertion

The problem here is, we don't have a way to determine what errors, if any, are being suppressed by a comment directive (https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/issues/65 -> https://github.com/microsoft/TypeScript/issues/51749). So it might be hard to work around edge cases with multiple TS errors. My _hunch_ is we can if:

* We limit it to simple cases, like assignments to `let`s and parameters to functions
* We ignore cases with any errors in retrieving types
* We use the type assignability API (#7936) to inform a suggestion fixer whether it's 🍎 or 🍌 

...but I haven't investigated deeply. 🙂 

### Fail Cases

```TypeScript
declare const valuesRaw: string[] | undefined;

// @ts-expect-error -- we know this is fine etc.
const values: string[] = valuesRaw;
```

### Pass Cases

```TypeScript
declare const valuesRaw: string[] | undefined;

// eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- we know this is fine etc.
const values = valuesRaw!;
```

### Additional Info

💖

**Comment by kirkwaiblinger** [comment]
> comment directives hide other issues

Is it possible to get the list of suppressed errors from TS? A related idea that might also be worth looking into could be to require that ts-expect-error/ts-ignore only suppress one error.

**Comment by kirkwaiblinger** [comment]
I think I'm mostly positive towards this proposal provided it's feasible to implement robustly

**Comment by Josh-Cena** [comment]
IMO `ts-expect-error` and assertions are very different. `ts-expect-error` means you expect the error to be automatically fixed one day, usually because of language limitations or wrong lib defs. Assertions mean you never expect it to work, for example because the API returns `string | string[]` but in this context it can only be a string.

**Comment by silverwind** [comment]
I see, https://github.com/microsoft/TypeScript/issues/19139 it the related request.

**Comment by bradzacher** [comment]
I'm a -1 here.

From my experience at scale - `@ts-expect-error` will error when you fix the problem, but `as any` will never, ever, ever error and is a permanent safety hole in your codebase.

I've seen incidents in production due to `as any` assertions that had been forgotten about.

Yes, there is a chance that a `@ts-expect-error` can permanently remain because the error it suppresses turns into a different error - but in practice that's a rare occasion, IME.

The best solution I've found is doing something like
```ts
// @ts-expect-error
const thing: CorrectType = brokenThing;
```
To truly isolate the unsafe conversion to limit the chance of other errors sneaking in.

---

The other thing to talk about is what you want to culturally normalise in a codebase.

Ideally you want to trend towards
- zero `any`s and zero `as unknown as T`s (or rather just zero `as`s in general),
- zero non-null assertions,
- as zero suppression comments

Culturally you want people to think of _all_ of these things as being taboo so they strive for better types and runtime checks instead of being lazy.

But in reality ofc you will need some form of unsafety - it is just the nature of the push-and-pull between TS and JS.

So what would you rather normalise culturally?
- suppression comments
- A non-null-assertion or an `as any` inline in the code
- all of the above

Personally I think that normalising suppression comments is the least-bad - for the reasons I stated above. With the TS comment lint rule you can enforce a description as well so people have to explain themselves.
I like it because it works similar to what clippy enforces in rust when you write code behind the `unsafe` keyword. Clippy enforces you write a comment next to it explaining why your `unsafe` code is actually safe. And I see a supprwcomment with a description as the same thing.

Technically you could have `no-explicit-any` on and so someone needs a suppression comment for the `as any` - but requiring a description on eslint suppressions is a rarer thing to do.

**Comment by Josh-Cena** [comment]
> I see, [microsoft/TypeScript#19139](https://github.com/microsoft/TypeScript/issues/19139) it the related request.

For the context: they don't want to do this because they don't want to expose the error numbers as a public API. The error numbers are not meant to be stable and often come and go. Instead, they want to have text-based error codes like Flow, but it's a huge effort and it's unclear whether they would ever do it.

**Comment by JoshuaKGoldberg** [comment]
@bradzacher it sounds like you're -1 on the 🍎 `as any as ...` disallowance, and I can understand & empathize with the reasoning. No strong pushback from me on that one.

But for 🍌 `as ...` / `!`, is that still something you think isn't worth it?

**Comment by bradzacher** [comment]
I don't think 🍌 is worth an enitre lint rule - no.

For many of the same reasons above a non-null-assertion can be worse. For example it's just one character and is easily missed in reviews. A suppression comment is not.

```ts
potentiallyNullish!.property();

//vs

// @ts-expect-error -- todo this is not supposed to be null
potentiallyNullish.property();
```

An `as` assertion is really bad too as it's a super unsafe operator. It's the chatgpt of operators and can hallucinate properties into your code (`{} as {a:string}`) without an error - which can be way worse for safety than just having a suppressed error.

```ts
// convoluted example
declare const apiResult: { a:string } | null;

const fixedApiResult = apiResult as { a:string, b: string };

fixedApiResult.a.length; // good now

fixedApiResult.b.length;
// oopsie woopsie crash
```
