### ISSUE TITLE
Docs: How to setup vs code to debug website

### ISSUE THREAD

**Issue by instantgis** [typescript-eslint/typescript-eslint#9511]
### Before You File a Documentation Request Please Confirm You Have Done The Following...

- [X] I have looked for existing [open or closed documentation requests](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3Adocumentation) that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Suggested Changes

I am learning how typescript-eslint works because I want to use the TypeScript AST in a node app later.
I want to debug through the execution of Playground.tsx to understand the structure of the AST displayed under the Typescript tab.
My interest is mostly in the TypeScript AST parts which I want to understand how to use on its own.
There is a lot going on here. Docusorus etc. React etc.
I cloned this repo built it and got it running. I'd like to be able to debug into all the parts.

**How do I setup a VS code launch setting and package.json script that allows me to debug through the website starting with Playground.tsx?**

Surely when contributors work on those parts they need to debug, right?
How is this done?

### Affected URL(s)

https://typescript-eslint.io/play

**Comment by Josh-Cena** [comment]
If you just want to use the TS AST, you should use the TypeScript compiler API, not our infra. In any case, you don't want to run the debugger on our website, because all code there has been bundled and adapted so it runs in the browser. If you are going to use it in Node, read our docs for `@typescript-eslint/typescript-estree` instead, and use our programmatic API.

**Comment by bradzacher** [comment]
If you want to debug the website - Chrome devtools has all the tooling you need to debug. There are console logs with line numbers that will get you a line number close enough to dig in to what's running.

But I'd agree with Josh - learning how it works via the website is going to be one of the worse ways because it's all transpiled and bundled.

Instead debugging node directly would be better - which you can do easily - just google "vscode node debug" and you'll find an article telling you how to attach vscode to node.
