### ISSUE TITLE
Bug: [switch-exhaustiveness-check] <Single object type with const property cannot be exhausted>

### ISSUE THREAD

**Issue by maodun11** [typescript-eslint/typescript-eslint#9642]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.5.2&fileType=.tsx&code=GYVwdgxgLglg9mABADwIwAoCeAuRBvRAL1wHJUAmAZhMQF9EAffI0qgFhtoEp8BYAKESIAzgHcYUCAAtEWAHSEeeAUKEQAhsICmiMlRLYVqoQCMATlvUBrANxG1mnSXYH7q85dtuAJluDqQABsoQ0FjWXQAfVwwLQA3LTMeAF4APmZuLC47MOMPaxyhWgFi-gFQSFgEFHIsXAJiXQpqOiUjMQlpWUwFNtzEDW0m-VDwxHyvft9-IJC3IXQomPjElPSCTMxs%2BfGLAqNS0vLwaHgkZEo64eo%2BoQ7JGSy%2BfsGnZtd%2B0z3J42mA4NG4UW0UQsQSSUQaQyXCyhXCEzhhyAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3QAacDToMmeCmFHopAXxAqgA&tokens=false

### Repro Code

```TypeScript
function x1(y: { z: '123' } | { z: '234' }) {
  switch (y.z) {
    case '123':
      break;
    case '234':
      break;
    default:
      ((_: never) => { })(y);
      break;
  }
}

function x2(y: { z: '123' }) {
  switch (y.z) {
    case '123':
      break;
    default:
      ((_: never) => { })(y);
      break;
  }
}

function x3(y: '123') {
  switch (y) {
    case '123':
      break;
    default:
      ((_: never) => { })(y);
      break;
  }
}
```

### ESLint Config

```javascript
module.exports = {
  "rules": {}
}
```

### tsconfig

```jsonc
{
  "compilerOptions": {
    "strictNullChecks": true,
    "strict": true
  }
}
```

### Expected Result

No error message.

### Actual Result

Error in func x2: 2345: Argument of type '{ z: "123"; }' is not assignable to parameter of type 'never'. 18:27 - 18:28

**Comment by bradzacher** [comment]
I'm not quite sure I understand - how is this a bug in the rule? It looks like you're commenting on how TS doesn't correctly refine the parent type to `never` if there isn't a union type.

**Comment by maodun11** [comment]
> I'm not quite sure I understand - how is this a bug in the rule? It looks like you're commenting on how TS doesn't correctly refine the parent type to `never` if there isn't a union type.
Yep.  'x1'shows that Ts correctly refine the parent type to never and  'x3' shows that Ts can deal with non-union type

**Comment by maodun11** [comment]
> how is this a bug in the rule?

Sorry I probably didn't write the correct formmating of the title, I just think that according to 'x1' and 'x3', 'x2' should be correct.

**Comment by bradzacher** [comment]
The rule doesn't use the context about what the parent may or may not be.
it just looks at the type of the switch value.

Put another way - to the rule there's no difference between `{ z: '123' } | { z: '234' }` and `{ z: '123' | '234' }` when you pass `y.z` - it sees them as exactly the same case.

Realistically this problem is quite a bit more complicated.

---

TS _should_ refine this case - there's probably a reason that it doesn't though. WOuld be worth searching their issues to see if you can find something relevant or file something if there's not.

**Comment by kirkwaiblinger** [comment]
Hi @maodun11! 

I'm going to close this issue...

The issue report does not mention behavior of any typescript-eslint rule, nor is one included in the config/playground link. Although the title mentions switch-exhaustiveness-check, all discussion pertains to TS itself. 

Feel free to file an issue with relevant examples if there is behavior regarding switch-exhaustiveness-check itself that needs to be examined. 🙂 Otherwise, I think this is purely an external TS issue. 

Thanks for understanding!
