### ISSUE TITLE
Enhancement: no-unused-vars Reopen auto-fix discussion

### ISSUE THREAD

**Issue by theo-walton** [typescript-eslint/typescript-eslint#9681]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+plugin+rule+option%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Link to the rule's documentation

https://typescript-eslint.io/rules/no-unused-vars/

### Description

I have followed this issue: https://github.com/typescript-eslint/typescript-eslint/issues/2689 and the closing thoughts are: 

> Many people configure their ides with autofix on save. If no-unused-vars had a fixer, then it would continually delete your in-progress variables. This has significant chance to irreparably break code (eg if there is a function call with a side-effect that's assigned to an unused variable, deleting it means you lose the side-effect).

>There will never be a fixer added for this reason.

and this does not feel satisfying for a couple of reasons:
* if there was a fixer, people could just *not* configure their IDEs in such a way. Im sure people can adapt
* if a variable in unused I think the proposal is to remove the declaration of that variable, not the expression that ends up being assigned to the variable
* people can disable the fixer if they really don't want the functionality

Also one of the benefits of fixers is the ability to 1 time migrate codebases to a new rule easily.

### Fail

```TypeScript
const unusedVar = myFunctionWithSideEffects();
```

### Pass

```TypeScript
myFunctionWithSideEffects();
```

**Comment by Josh-Cena** [comment]
Hi! This is an extension rule from ESLint. We don't add behavior beyond what's necessary to power TS-aware linting. If you want to see it implemented you would first have to propose it to ESLint core.

**Comment by bradzacher** [comment]
> if a variable in unused I think the proposal is to remove the declaration of that variable, not the expression that ends up being assigned to the variable

Say we do this.
Now you have a bunch of potentially useless function calls sitting around in the codebase.

For example:
```ts
export function pureFunction(value: string): string {
  return value;
}

const unused = pureFunction('yolo');
```
If you fix the last line to
```ts
pureFunction('yolo');
```

That's **_OBVIOUSLY_** not correct because now you're doing work that has no side-effects and thus is useless work.
There's no lint rule to detect such useless function calls so you've made the code appreciably **_WORSE_** by doing this fix.

> people can disable the fixer if they really don't want the functionality

That's assuming it's gated behind an option, which fixes are not; more often than not.

> if there was a fixer, people could just not configure their IDEs in such a way. Im sure people can adapt

This is an incredibly user-hostile way of thinking.
"You're using an IDE feature that has existed for decades but too bad stop using it because we added a fixer"
That is just not a valid thing to do - you can't just force tens of millions people to stop using an IDE feature because you've deemed it irrelevant.

---

In addition as Josh mentioned - this is an extension rule and we align with upstream.
Upstream has no fixer - so we shall not have a fixer.
