### ISSUE TITLE
Bug: [no-deprecated] fails on declared instances

### ISSUE THREAD

**Issue by Zamiell** [typescript-eslint/typescript-eslint#9970]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.
- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22package%3A+eslint-plugin%22) and found none that matched my issue.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### Playground Link

https://typescript-eslint.io/play/#ts=5.3.3&showAST=es&fileType=.tsx&code=PTAEFpK6du4LAChnAFRtAAQCYFMAHAJzwGMBDAFzx1DWGQDMBXAO1MoEsB7V0AZ24BbPADE2HHqwAUASlABvAL7JBI8ey685AblAhQAdW5EA1vwA0ocv1B4AHgTLUcAOmSow8bz-gek%2BKQANuQkoJys1ESM5KR4oADKwngAkpF40bHxCsig%2BhjY%2BMRkVDR0DEh5SSIAsniUABbcOABcoHKgALwAfKAAbtycODrIKigBZCFhpLz8lALJaVExcW3VqemZcSPjahvLWa7rdY3NuvpgouRB-PGseADmVJx9eACEyEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oBNFjpEZAIb5E3dFETRoHaJHBgAviGVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

See the playground link above.

**Comment by Zamiell** [comment]
This is something that the `deprecated/deprecated` handled fine, but the new rule does not. So it is kind of like a regression. Maybe we should look through the `deprecated/deprecated` tests to make sure that nothing else was missed? (Not sure if that was already done, if it was then ignore me.)

**Comment by bradzacher** [comment]
Note that this isn't due to `declare` -- it just seems like we don't handle this particular call expression case?

```ts
declare const someInterface: SomeInterface;
someInterface.SomeMethod; // ✅ errors
someInterface.SomeMethod(); // ❌ missing error

const someInterface2: SomeInterface = {} as any;
someInterface2.SomeMethod; // ✅ errors
someInterface2.SomeMethod(); // ❌ missing error
```
[playground](https://typescript-eslint.io/play/#ts=5.3.3&showAST=es&fileType=.tsx&code=PTAEFpK6du4LAChnAFRtAAQCYFMAHAJzwGMBDAFzx1DWGQDMBXAO1MoEsB7V0AZ24BbPADE2HHqwAUASlABvAL7JBI8ey685AblAhQAdW5EA1vwA0ocv1B4AHgTLUcAOmSow8bz-gek%2BKQANuQkoJys1ESM5KR4oADKwngAkpF40bHxCsig%2BhjY%2BMRkVDR0DEh5SSIAsniUABbcOABcoHKgALwAfKAAbtycODrIKigBZCFhpLz8lALJaVExcW3VqemZcSNIahvLWa7rdY3NegaAoOR2REQm-KqLmyt4R8knTTi6%2BmCAMuSgQpx%2BPwIgBza63Ij%2BGasOYLERLDLPABMa0eBziXUUSmstnIrAAnjs9gitngka9avUPucwFcMhD7rs0YisuTjlTml8DH8AUDQeCTMggA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oBNFjpEZAIb5E3dFETRoHaJHBgAviGVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)
