### ISSUE TITLE
Rule proposal: prefer discriminator

### ISSUE THREAD

**Issue by FloEdelmann** [typescript-eslint/typescript-eslint#9984]
### Before You File a Proposal Please Confirm You Have Done The Following...

- [X] I have [searched for related issues](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+label%3A%22enhancement%3A+new+plugin+rule%22) and found none that match my proposal.
- [X] I have searched the [current rule list](https://typescript-eslint.io/rules/#rules) and found no rules that match my proposal.
- [X] I have [read the FAQ](https://typescript-eslint.io/linting/troubleshooting) and my problem is not listed.

### My proposal is suitable for this project

- [X] My proposal specifically checks TypeScript syntax, or it proposes a check that requires type information to be accurate.
- [X] My proposal is not a "formatting rule"; meaning it does not just enforce how code is formatted (whitespace, brace placement, etc).
- [X] I believe my proposal would be useful to the broader TypeScript community (meaning it is not a niche proposal).

### Description

Note that I'm not sure whether this is feasible or suitable for a wider audience, but I wanted to put it out here anyway.

Given:

```ts
interface Foo {
  type: 'Foo'
  value: number
  foo: string
}
interface Bar {
  type: 'Bar'
  value: string
  bar: string
}
declare const baz: Foo | Bar
```

We can narrow the type using different comparisons:

1. Using the discriminator property: `baz.type === 'Foo'` or `baz.type === 'Bar'`
2. Using the `typeof` operator: `typeof baz.value === 'number'` or `typeof baz.value === 'string'`
3. Using the `in` operator: `'foo' in baz` or `'bar' in baz`

For consistency and [greppability](https://morizbuesing.com/blog/greppability-code-metric/), using the discriminator property approach might be preferable.

### Fail Cases

```TypeScript
if (typeof baz.value === 'number') {}
else if (typeof baz.value === 'string') {}

if ('foo' in baz) {}
else if ('bar' in baz) {}

switch (typeof baz.value) {
  case 'number': {}
  case 'string': {}
}
```

### Pass Cases

```TypeScript
if (baz.type === 'Foo') {}
else if (baz.value === 'Bar') {}

switch (baz.type) {
  case 'Foo': {}
  case 'Bar': {}
}
```

**Comment by kirkwaiblinger** [comment]
Hi @FloEdelmann!

I understand the principle behind what you're asking for, but I wonder if you could flesh out some details to help figure out whether it's feasible to implement. This may venture close or into territory that the TS API doesn't really let us answer, namely asking speculative questions around what types would be we made changes to the code being linted.

Some of the questions on my mind:
1. What kinds of expression should we inspect to check as type narrowing locations?
2. Are there widespread patterns that would be "coincidentally narrowing", in that they result in a narrowing, but that's not the point of the condition?
3. What heuristics can we look for to determine whether a discriminant would have been available? What if there are multiple discriminants?
4. Do we need to do complex analysis of a discriminant is available in order to achieve the objective of this rule? Or can can similarly good results be achieved by just banning the `in` operator? `in` narrowings are always notoriously unsound.

Thoughts?

**Comment by bradzacher** [comment]
It has been three weeks without response from OP.
Closing out.
